### ISSUE TITLE
Authenticate password

### ISSUE THREAD

**Issue by mario0582** [jc21/nginx-proxy-manager#1]
Hello, I loved this tool makes it much easier to use domains in docker. It is better than any other existing option.

But I'd like to give the idea of ​​putting user authentication to make it secure, and also allow administrators to be able to free access for certain users.

It would also be interesting to choose an external SSL certificate besides lets encrypt.

Congratulations on the project, I hope to see these implementations one day. : D

**Comment by jc21** [comment]
Thanks for the suggestions :) I definitely do want to improve this to add some features like that in future.

**Comment by mario0582** [comment]
I am a founder of a hosting company in Brazil, if possible please contact me by email, I would like to possibly hire your services if you are available to improve this your tool so that I can use it in my company. My email is office@battlecloud.club.

If you can and want to send me an email to talk hehe, thanks for responding.

**Comment by jc21** [comment]
I've tried to send you an email but it bounced so I'll ask here..

I'm in the process of rewriting the entire project and I wanted to ask you a few things about what you want to accomplish in regard to the user permissions. Keep in mind that I might not be able to implement all of your requests :)

1. What user permission levels do you want, currently I've got Administrators and non-administrators but do you want more granularity and why?
3. Would you want hosts to be only visible to the user who created them? with Admins being able to see everything of course
3. Do you want to see any restrictions placed on users, such as only being able to create certain types of hosts (ie, proxy hosts but not streams), or only being able to create hosts that are subdomains of whitelisted domains?

**Comment by mario0582** [comment]
Hi, Thanks for getting in touch. All the points you mentioned are correct.
These changes would be sensational.
My intention is to use this commercially because all the proxy solutions in
docker that I tried to use did not work.
The following points would be interesting:

1 # an administrative sector where a super admin can manage other users,
create new users and delete.

2 # An authentication and login page.

3 # user can use lets encrypt or add a custom SSL. (Comodo, NameCheap, Etc).

In the rest everything you mentioned would be interesting to have, but the
most urgent would be just a basic authentication for a single user so you
can leave the door open and have security. and a place where the password
could be changed of course.

A very important thing would also be not to use the standard bootstrap
template, to use something more sophisticated, I'll leave a link from a
bootstrap admin template gratís in github, if it is not too complicated you
could use it instead of the standard interface.

https://github.com/puikinsh/Adminator-admin-dashboard

Thanks for replying, my professional email is support@battlecloud.club but
you can speak to me directly by this same personal email.

**Comment by jc21** [comment]
I've actually based the new design on Tabler: https://tabler.github.io/

Here's some current screenshots
![screen shot 2018-06-28 at 8 33 15 am](https://user-images.githubusercontent.com/1518257/42003313-3da82b36-7aae-11e8-8894-a90f5edf877b.png)
![screen shot 2018-06-28 at 8 33 39 am](https://user-images.githubusercontent.com/1518257/42003314-433ec500-7aae-11e8-9f54-8523c95d04f0.png)
![screen shot 2018-06-28 at 8 34 12 am](https://user-images.githubusercontent.com/1518257/42003323-497f37c4-7aae-11e8-886c-e9288193c6fe.png)

**Comment by mario0582** [comment]
Oh my God, this is incredible. This interface is sensational, perfect.
Please keep in touch with me always, please let me know when this new
version is available. I sure as hell want you working with me in my
company. My company is new but growing and having this panel will be a
success. I will be happy to send PayPal commissions on any recurring sale
of our infrastructure.

I would also like to talk about the possibility of discussing new functions
exclusively for my company in the future, I'll sort if you are in
agreement, when you want we can talk about values ​​or about your direct
participation in the company. It would be an honor .

Thanks, Have a nice Day :D

**Comment by idlerus** [comment]
Any expected release date? or pre-release?

**Comment by jc21** [comment]
I have been steadily doing work on this in my spare time but I don't want to commit to any dates yet.

At this stage, the UI is about 70% done but the nginx backend work hasn't been started yet.

Other features you'll be interested in:
- custom ssl certs
- multiple domain names (aliases) in hosts
- wildcard hostnames

A stable release would be at least a month away

**Comment by idlerus** [comment]
Thank you for response, can you add simplier way to debug logs. I've added alias to my manager with /logs to display plain nginx file browser. So I have temporary fix but some file browser in app would be awesome time saver.

**Comment by jc21** [comment]
Log viewing is planned however it might not make the initial v2 release.

**Comment by jc21** [comment]
Ok people, version 2 is ready for someone to test besides me. Have a read of [the documentation](https://github.com/jc21/nginx-proxy-manager/blob/v2/README.md) including the [installation instructions](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/INSTALL.md) and [importing guide](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/IMPORTING.md).

The app has only a few minor bugs I want to change but I'm using it in production myself on 4 instances. 

Testing of the custom certificates in particular needs to be done, I haven't purchased a cert in forever so I don't have one to play with and they can be fairly different.

If you have issues, probably be to report them as new issues and mention that they affect version 2 in the description.

Thanks
