### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by razzam21** [jc21/nginx-proxy-manager#10]
I have tried installing this on Mysql 5.7 and Mysql 8.0 (both support JSON columns).  When the container first loads it is in a 'starting' state.  When I look at the logs it is filled with this error:

migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null default '{}', `is_deleted` int unsigned not null default '0') - ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'meta' can't have a default value,
migration file "20180618015850_initial.js" failed

How can I get this to work?  I have tried relaxing the sql_mode of Mysql in the hopes of letting it go in and then put that back but that doesn't seem to have an effect.

**Comment by jc21** [comment]
To be honest I've done most of my testing with the latest Maria database engine which I looks like supports default blob values of any string whereas mysql JSON data types only accept default values written as expressions. The KnexJS library doesn't know how to handle the different between them yet so I've updates the migration to remove these and handle defaults in a different way.

Pull the docker image again to get it working.
