### ISSUE TITLE
Hosts Offline (Commaind failed: /usr/sbin/nginx -t -g "error_log off;"....)

### ISSUE THREAD

**Issue by domiey** [jc21/nginx-proxy-manager#103]
Hope anybody can help. Get "Status Offline" on all proxy/redirect hosts. Tooltip says: 

```
Commaind failed: /usr/sbin/nginx -t -g "error_log off;"
nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Config (Rasperry 3): 
```
{
  "database": {
    "engine": "mysql",
    "host": "192.168.1.37",
    "name": "nginxproxy",
    "user": "user",
    "password": "password",
    "port": 3306
  }
}

docker run -d \
    --name nginx-proxy-manager-app \
    -p 80:80 \
    -p 81:81 \
    -p 443:443 \
    -e TZ=Europe/Berlin \
    -v /opt/nginxproxy/config.json:/app/config/production.json \
    -v /opt/nginxproxy/data:/data \
    -v /opt/nginxproxy/letsencrypt:/etc/letsencrypt \
    jc21/nginx-proxy-manager:latest-armhf
```

Already set "server_names_hash_bucket_size" to 32 manually in /etc/nginx/nginx.conf. 
![Bildschirmfoto 2019-03-13 um 14 42 18](https://user-images.githubusercontent.com/26581844/54285626-a19dc280-45a2-11e9-86f7-adc9e537abb4.png)

**Comment by jc21** [comment]
Interesting.. seems that the pi has a default lower than 32, which seems to be the lowest default for other archs. Should be trivial to increase this for everyone.
