### ISSUE TITLE
SSL Options are not visible with a long Domain-List

### ISSUE THREAD

**Issue by ITbyHF** [jc21/nginx-proxy-manager#1033]
I have one Certificate, that contains nearly all of my Domains, which was issued with the Cloudflare DNS-Challenge.
The upper 2 Options (Force SSL & HTTP/2 Support) in the SSL Menu are not visible when using a Certificate with a long domain list/name (see screenshot)
Version 2.8.0

Expected behavior
All Options visible or even an Option to give Certificates custom Names

![image](https://user-images.githubusercontent.com/61453797/115899069-9b0af600-a45e-11eb-8b9e-5dc79b6608d0.png)

Operating System
Docker-Compose / Ubuntu 20 (KVM VM)

**Comment by jc21** [comment]
PR has been merged. Will be part of the next release.
