### ISSUE TITLE
Future request (MFA)

### ISSUE THREAD

**Issue by justfor-it** [jc21/nginx-proxy-manager#1035]
Hi,

Is there an option to add MFA to Nginx Proxy manager?

- So maybe Duo Mobile

Thanks in advanced

**Comment by psharma04** [comment]
Even if it's normal TOTP (e.g. Google Authenticator/Authy), it massively improves the security for everyone.

**Comment by kennylajara** [comment]
+1

**Comment by chaptergy** [comment]
Feature request: https://github.com/jc21/nginx-proxy-manager/issues/313
