### ISSUE TITLE
Rpi4 proxy MYSQL db date error

### ISSUE THREAD

**Issue by zaquert** [jc21/nginx-proxy-manager#1037]
Hello everyone I have a strange error on my nginx-proxsy menager on docker. I work on rpi 4 on newest version of the server raspbian.
 My configuration looks like this: 
![IMG_20210424_205503](https://user-images.githubusercontent.com/70597626/115969849-6ae75400-a53f-11eb-92d1-b38452be5150.jpg)
After running this stack I get a nginx_app status unhealthy and which log 
![IMG_20210424_135105](https://user-images.githubusercontent.com/70597626/115969951-d3cecc00-a53f-11eb-8784-9d796080862d.jpg)
And after looking on the data base I got this strange error: this MYSQL server doesn't support dates late then 2038 
![IMG_20210424_134929](https://user-images.githubusercontent.com/70597626/115969984-05479780-a540-11eb-8f85-bc4e8a4ba167.jpg)
Can someone please help me whith that ?

**Comment by deboy69** [comment]
Same issue here.....

**Comment by zaquert** [comment]
I found a solution to my problem on this issue page https://github.com/yobasystems/alpine-mariadb/issues/47.
Just change in db image from :latest to :10.4.17
