### ISSUE TITLE
Errors when using seperate MYSQL server

### ISSUE THREAD

**Issue by danmed** [jc21/nginx-proxy-manager#105]
`migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1`

This occurs when it first tries to create the database.. only 2 tables are created : 

migrations
migrations_lock

**Comment by danmed** [comment]
fixed by updating MySQL to MariaDB and using MySQL as the engine in the config.json

**Comment by jc21** [comment]
For anyone coming across this in future, only MySQL server v5.7.8 and above, and MariaDB databases are supported with this project.

**Comment by dgancedo** [comment]
I'm having the same issue with a fresh install but I'm using MariaDB 10 on other container
Server version: 10.1.38-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

the error is:
writing new private key to '/data/nginx/dummykey.pem'
-----
Complete
[4/26/2019] [11:41:01 PM] [Migrate  ] › ℹ  info      Current database version: none
[4/26/2019] [11:41:01 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...
migration file "20190227065017_settings.js" failed
migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1

and the last part keep repeating, any idea?

**Comment by jc21** [comment]
With Mariadb, the JSON field type [was introduced in 10.2.7](https://mariadb.com/kb/en/library/json-data-type/).
