### ISSUE TITLE
After restarting container getting "getaddrinfo ENOTFOUND db" and "bad gateway" preventing logins.

### ISSUE THREAD

**Issue by ilovepancakes95** [jc21/nginx-proxy-manager#1057]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? YES
- Are you sure you're not using someone else's docker image? YES
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? N/A

**Describe the bug**
- A clear and concise description of what the bug is. 

I know other people have posted this same error before and resolved it by using the latest mariadb-aria image, which I am already on. I still get the same error. Everything worked fine with nginx proxy manager for MONTHS until I happened to restart the docker compose stack today. I get "Bad Gateway" on login page when trying to login, and get the following error constantly in the container log for the NPM container (maria DB container shows running okay). And the NPM container status shows "Unhealthy parse error: Invalid numeric literal at line 1, column 7 NOT OK ".

```
[5/3/2021] [7:10:10 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
[5/3/2021] [7:10:20 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
[5/3/2021] [7:10:30 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
[5/3/2021] [7:10:40 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
```

I am still able to access services through NPM that were setup before the container restart... so clearly something is working, just isn't working fully for whatever part involves logging in to web interface I guess.

- What version of Nginx Proxy Manager is reported on the login page? 2.8.0

**Expected behavior**
Healthy status for health check on Docker and admin page allows login and shows no "bad gateway" error.

**Operating System**
- Docker on Alpine Linux x64

**My Docker Compose File Being Used**
```
version: '2'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.8.0'
    network_mode: network01
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - /var/lib/docker/volumes/nginx-proxy-manager/_data/config.json:/app/config/production.json
      - /var/lib/docker/volumes/nginx-proxy-manager/_data/data:/data
      - /var/lib/docker/volumes/nginx-proxy-manager/_data/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4.15'
    network_mode: network01
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /var/lib/docker/volumes/nginx-proxy-manager/_data/data/mysql:/var/lib/mysql
```

**Comment by Callum-W** [comment]
I'm getting the same issue.  Even when changing "db" to the host IP address it showing the same error.

I can access the database with "IP:PORT" but am getting the error
`✖  error     connect EHOSTUNREACH {_MY_IP_}:{_PORT_}`

I've tried multiple different maria db images as some people have suggested, but haven't had any luck resolving this issue.

**Comment by chaptergy** [comment]
Sounds like a docker misconfiguration. Are the two docker containers still in the same docker network? Are you able to ping one container from inside the other one? Did you change something in docker so container names as hostnames are no longer resolved?

**Comment by ilovepancakes95** [comment]
> Sounds like a docker misconfiguration. Are the two docker containers still in the same docker network? Are you able to ping one container from inside the other one? Did you change something in docker so container names as hostnames are no longer resolved?

Didn't change anything in docker/portainer and yes the two containers are confirmed on same docker network. They are also part of the same compose file I have been using for a while. The only thing I did before it stopped working was update the containers to latest version, then noticed it not working, and even after changing the images back to previous versions it still exhibits same issue.

I can ping from the app container to the db container fine. Pinging from db to the app container I can't try because it won't open a console to the db container. It just quits out of the shell right away after clicking connect in portainer.

**Comment by chaptergy** [comment]
Sounds like the database is having issues. You said the db image shows "running ok", but have you checked the logs of the db container to see if they contain any errors?

**Comment by ilovepancakes95** [comment]
> Sounds like the database is having issues. You said the db image shows "running ok", but have you checked the logs of the db container to see if they contain any errors?

Yes, db container shows "running" and the logs are below:

```
[i] pre-init.d - processing /scripts/pre-init.d/01_secret-init.sh


[i] mysqld not found, creating....


[i] MySQL directory already present, skipping creation


2021-05-03 18:30:20 0 [Note] /usr/bin/mysqld (mysqld 10.4.15-MariaDB) starting as process 1 ...


2021-05-03 18:30:20 0 [Note] Plugin 'InnoDB' is disabled.


2021-05-03 18:30:20 0 [Note] Plugin 'FEEDBACK' is disabled.


2021-05-03 18:30:20 0 [Note] Server socket created on IP: '::'.


2021-05-03 18:30:20 0 [Warning] 'user' entry '@3e3ea634ad48' ignored in --skip-name-resolve mode.


2021-05-03 18:30:20 0 [Warning] 'proxies_priv' entry '@% root@3e3ea634ad48' ignored in --skip-name-resolve mode.


2021-05-03 18:30:20 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1286: Unknown storage engine 'InnoDB'


2021-05-03 18:30:20 0 [Note] Reading of all Master_info entries succeeded


2021-05-03 18:30:20 0 [Note] Added new Master_info '' to hash table


2021-05-03 18:30:20 0 [Note] /usr/bin/mysqld: ready for connections.


Version: '10.4.15-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server


[i] pre-init.d - processing /scripts/pre-init.d/01_secret-init.sh


[i] mysqld already present, skipping creation


[i] MySQL directory already present, skipping creation


2021-05-30 15:45:00 0 [Note] /usr/bin/mysqld (mysqld 10.4.15-MariaDB) starting as process 1 ...


2021-05-30 15:45:00 0 [Note] Plugin 'InnoDB' is disabled.


2021-05-30 15:45:00 0 [Note] Plugin 'FEEDBACK' is disabled.


2021-05-30 15:45:00 0 [Note] Server socket created on IP: '::'.


2021-05-30 15:45:00 0 [Warning] 'user' entry '@3e3ea634ad48' ignored in --skip-name-resolve mode.


2021-05-30 15:45:00 0 [Warning] 'proxies_priv' entry '@% root@3e3ea634ad48' ignored in --skip-name-resolve mode.


2021-05-30 15:45:00 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1286: Unknown storage engine 'InnoDB'


2021-05-30 15:45:00 0 [Note] Reading of all Master_info entries succeeded


2021-05-30 15:45:00 0 [Note] Added new Master_info '' to hash table


2021-05-30 15:45:00 0 [Note] /usr/bin/mysqld: ready for connections.


Version: '10.4.15-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
```

**Comment by chaptergy** [comment]
Hm, then I'm really not sure what it could be, maybe updating could fix the issue?

**Comment by ilovepancakes95** [comment]
To anyone seeing this in future.... The issue appears to have something to do with Docker Compose v2 and the latest versions of nginx proxy manager and mariadb-aria with the "network_mode" option which lets one assign the containers to an existing docker network. When I removed that line from each container, it all worked normally, but then the containers wouldn't be in the network I needed them to be in. I switched over to Docker Compose v3 and used the new method of defining existing networks and all works now. See below compose file for reference.

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.9.3'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4.15'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
networks:
  default:
    external: true
    name: proxy_network2
```
