### ISSUE TITLE
add support for desec dns in Lets encrypt dns challange

### ISSUE THREAD

**Issue by fareszr** [jc21/nginx-proxy-manager#1059]
hi 
when generating LE certs desec is not an option when selecting a dns provider

they support LE api 

documentation: https://desec.readthedocs.io/en/latest/dyndns/lets-encrypt.html

**Comment by chaptergy** [comment]
Unfortunately the DNS challenge within nginx proxy manager is only available for [certbot dns plugins](https://certbot.eff.org/docs/using.html#dns-plugins). deSEC does not have a plugin for this, they have opted for the manual certbot challenge with hooks, which would require a significant rewrite of the integration. So I don't think this will be implemented for now, unless a certbot plugin for deSEC is published.
