### ISSUE TITLE
Invalid letsencrypt (Fake LE Intermediate X1)

### ISSUE THREAD

**Issue by jenschurchill** [jc21/nginx-proxy-manager#106]
I've manually configured an NPM Docker image to support ppc64le, and gotten it to a working'ish state.
But when I create a letsencrypt cert. for a given proxy, and access the site, I get an "invalid cert." warning, and when inspecting the certificate, it states: CN: Fake LE Intermediate X1

What could I be missing?

**Comment by jc21** [comment]
Sounds like you're using the development environment which uses the LE testing servers for certificates.

The `NODE_ENV` environment variable should either be unset or set to `production` in your docker stack.

**Comment by jenschurchill** [comment]
Bingo, thank you.
