### ISSUE TITLE
Does not work with docker

### ISSUE THREAD

**Issue by jayjupdhig** [jc21/nginx-proxy-manager#1060]
When i save that content to a file:

´´´
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
´´´

Then save it in an file called ´docker-compose´ then run ´docker docker-compose up -d´ it does not work: Get that errors:

´´´
root@nginx-proxy-manager-debian10:~# docker ./docker-compose up -d
unknown shorthand flag: 'd' in -d
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  app*        Docker App (Docker Inc., v0.9.1-beta3)
  builder     Manage builds
  buildx*     Build with BuildKit (Docker Inc., v0.5.1-docker)
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  scan*       Docker Scan (Docker Inc., v0.7.0)
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes
unknown shorthand flag: 'd' in -d
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  app*        Docker App (Docker Inc., v0.9.1-beta3)
  builder     Manage builds
  buildx*     Build with BuildKit (Docker Inc., v0.5.1-docker)
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  scan*       Docker Scan (Docker Inc., v0.7.0)
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/
´´´

When i execute it (firstly flagged with chmod +x) directly with ´./docker-compose up -d´, i get that messages:

´´´
root@nginx-proxy-manager-debian10:~# ./docker-compose up -d
./docker-compose: Zeile 1: version:: Kommando nicht gefunden.
./docker-compose: Zeile 2: services:: Kommando nicht gefunden.
./docker-compose: Zeile 3: app:: Kommando nicht gefunden.
./docker-compose: Zeile 4: image:: Kommando nicht gefunden.
./docker-compose: Zeile 5: restart:: Kommando nicht gefunden.
./docker-compose: Zeile 6: ports:: Kommando nicht gefunden.
./docker-compose: Zeile 8: -: Kommando nicht gefunden.
./docker-compose: Zeile 10: -: Kommando nicht gefunden.
./docker-compose: Zeile 12: -: Kommando nicht gefunden.
./docker-compose: Zeile 13: environment:: Kommando nicht gefunden.
./docker-compose: Zeile 15: DB_MYSQL_HOST:: Kommando nicht gefunden.
./docker-compose: Zeile 16: DB_MYSQL_PORT:: Kommando nicht gefunden.
./docker-compose: Zeile 17: DB_MYSQL_USER:: Kommando nicht gefunden.
./docker-compose: Zeile 18: DB_MYSQL_PASSWORD:: Kommando nicht gefunden.
./docker-compose: Zeile 19: DB_MYSQL_NAME:: Kommando nicht gefunden.
./docker-compose: Zeile 25: volumes:: Kommando nicht gefunden.
./docker-compose: Zeile 26: -: Kommando nicht gefunden.
./docker-compose: Zeile 27: -: Kommando nicht gefunden.
./docker-compose: Zeile 28: depends_on:: Kommando nicht gefunden.
./docker-compose: Zeile 29: -: Kommando nicht gefunden.
./docker-compose: Zeile 30: db:: Kommando nicht gefunden.
./docker-compose: Zeile 31: image:: Kommando nicht gefunden.
./docker-compose: Zeile 32: restart:: Kommando nicht gefunden.
./docker-compose: Zeile 33: environment:: Kommando nicht gefunden.
./docker-compose: Zeile 34: MYSQL_ROOT_PASSWORD:: Kommando nicht gefunden.
./docker-compose: Zeile 35: MYSQL_DATABASE:: Kommando nicht gefunden.
./docker-compose: Zeile 36: MYSQL_USER:: Kommando nicht gefunden.
./docker-compose: Zeile 37: MYSQL_PASSWORD:: Kommando nicht gefunden.
./docker-compose: Zeile 38: volumes:: Kommando nicht gefunden.
./docker-compose: Zeile 39: -: Kommando nicht gefunden.
´´´

**Comment by rezzorix** [comment]
Did you install docker-compose?

If yes, file should be "docker-compose.yml", the command then is "docker-compose up -d"

**Comment by jayjupdhig** [comment]
Thank you very much. I installed it as described here: https://docs.docker.com/engine/install/debian/

Cite: ´apt-get install docker-ce docker-ce-cli containerd.io´

Do i also have to add the ´docker-compose´ package to the APT command.

Like that?
-> ´apt-get install docker-ce docker-ce-cli containerd.io docker-compose´

**Comment by jayjupdhig** [comment]
OK, now i insalled the package "docker-compose"...

Then, i have to save that lines in a file called e.g. "MY_DOCKER_FILE":

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```


Then i have to execute that?
-> `docker-compose up -d ./MY_DOCKER_FILE`

Is that correctly?

Thank you very very much for your feedback.

**Comment by rezzorix** [comment]
well.. easiest is to make a folder in your home-folder, put the yml file in and then run it from there:

```
cd ~
mkdir npm
cd npm
nano docker-compose.yml -> fill the content as needed, save the file, exit nano
docker-compose up -d
```

**Comment by jayjupdhig** [comment]
Thank you very much, works very well!! :-)

Maybe you can add that info to https://nginxproxymanager.com/setup/ , for people they want to install your proxy manager (looks very interesting, will see it when the installation is done) but without docker knownledge (yet).

**Comment by jayjupdhig** [comment]
Another question HERE: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1736
