### ISSUE TITLE
Loading takes 10 seconds, extra config needed?

### ISSUE THREAD

**Issue by sanderdatema** [jc21/nginx-proxy-manager#107]
When using Caddy my sites load pretty fast, but with NginxPM it takes about 10 seconds for each first load. After that it's ok. But when I wait a few minutes, it'll take a few seconds again.

Am I missing something?

**Comment by jc21** [comment]
The admin site isn't 100% optimised and it might be that it's JS assets aren't cached. Or it might be that the database isn't warm. Open your web browser's dev tools and see which parts (js or xhr) are taking the longest to respond.

**Comment by sanderdatema** [comment]
The weird thing is that the first 10 seconds absolutely nothing happens. Only after that the browser is able to request anything. Like a dns request that takes ages. Except that it can't be that, because Caddy works fine.

It's not just your admin site, it's any site.

Is there a debug setting I could use?

**Comment by jc21** [comment]
If it is a DNS issue you can test by opening a console and trying to lookup a record and see how long it takes:

```
nslookup www.google.com.au
```

Try different domains you've probably never visited, to make sure you're not using your local dns cache.

**Comment by sanderdatema** [comment]
But that's what I said: it's not a dns issue, Caddy would have trouble too, then.
