### ISSUE TITLE
DB Connection Issues - Upgrade - 2.9.0/2.9.1

### ISSUE THREAD

**Issue by Jiriteach** [jc21/nginx-proxy-manager#1077]
I've updated to 2.9.0 and since the update, the app is reporting is unhealthy with connection issues to the db. Existing rules are working but I cannot login to NPM.

App logs are showing - error connect ECONNREFUSED

Looks like way connection approach to the db has changed. I am using yobasystems/alpine-mariadb:latest. I will try and revert the db but I am trying to do this without loosing my existing rules.

Anyone else seeing similar issues? Have removed existing containers and re-pulled without success.

My Docker compose - 
  _version: '3'
  services:
    app:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: always
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      environment:
        DB_MYSQL_HOST: "db"
        DB_MYSQL_PORT: 3306
        DB_MYSQL_USER: "DBUSERNAME"
        DB_MYSQL_PASSWORD: "DBPASSWORD"
        DB_MYSQL_NAME: "DBNAME"
      volumes:
        - /home/pi/Docker/npm/data:/data
        - /home/pi/Docker/npm/letsencrypt:/etc/letsencrypt
    db:
      image: 'yobasystems/alpine-mariadb:latest'
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ROOTPASSWORD
        MYSQL_DATABASE: DBNAME
        MYSQL_USER: DBUSERNAME
        MYSQL_PASSWORD: DBPASSWORD
      volumes:
        - /home/pi/Docker/npm/data/mysql:/var/lib/mysql_

**Comment by jc21** [comment]
This _shouldn't_ be related to the 2.9.0 release, as the node packages are the same as previous releases. Though I have been wrong before.

The CI test suite also brings up a MySQL database and tests connectivity. This _might_ be an issue with arm (I'm guessing, since you're using yobasytems?)

v.2.9.1 is out. Test with that as well?

**Comment by Jiriteach** [comment]
Found the issue - Its an issue with 2.9.0 and 2.9.1 and alpine-mariadb 10.5.9.
I reverted to 10.4.17 and no problem. Everything is working as expected again with 2.9.1. All my existing rules etc. in place.

**Comment by henkisdabro** [comment]
Thanks for this solution, however when I downgraded I ended up with errors on my side, such as:

`InnoDB: Unsupported redo log format. The redo log was created with MariaDB 10.5.8.`

That said, I only had one host in my setup, so I rebuilt the entire stack using the new "quick setup" format anyways to get rid of the issues and start fresh.

**Comment by Jiriteach** [comment]
@henkisdabro  - I didnt see this but I cleared my logs before which its probably why so it created new logs.

**Comment by Jiriteach** [comment]
Closing as not required anymore.
