### ISSUE TITLE
Porkbun as DNS provider

### ISSUE THREAD

**Issue by jakern** [jc21/nginx-proxy-manager#1079]
**Are you in the right place?**
- If you are looking for support on how to get your upstream server forwarding, please consider asking the community on Reddit.
- If you are writing code changes to contribute and need to ask about the internals of the software, Gitter is the best place to ask.
- If you have a feature request for NPM then you are in the *right place.*
I might be in the right place but this might be a certbot issue

**Is your feature request related to a problem? Please describe.**
My request is about the providers available in let's encrypt DNS challenges

**Describe the solution you'd like**
Porkbun offers and API to edit DNS https://porkbun.com/api/json/v3/documentation

**Describe alternatives you've considered**
I am currently running certbot manually and uploading the certs under the custom option but I am also try to get cloudflare to work

**Additional context**
I saw the comment here that I should create this request #613 https://github.com/jc21/nginx-proxy-manager/issues/613#issuecomment-723036527

**Comment by chaptergy** [comment]
A [certbot plugin for porkbun](https://pypi.org/project/certbot-dns-porkbun/) does exist, so this seems possible. Maybe I will get around to adding this next week.

**Comment by chaptergy** [comment]
Unfortunately the certbot porkbun dns plugin is not compatible out of the box, but would require changes on their side, to be able to fetch credentials from a file. I could open an issue over there, maybe even suggest some code, but I am not able to test it

**Comment by chaptergy** [comment]
The [pull request](https://github.com/jc21/nginx-proxy-manager/pull/1099) is open. You can already try it out if you use the docker image `jc21/nginx-proxy-manager:github-pr-1099`
