### ISSUE TITLE
Creating proxy for nginx-proxy-manager admin interface

### ISSUE THREAD

**Issue by cboulanger** [jc21/nginx-proxy-manager#108]
Hi,
Awesome piece of software, very useful, thank you very much for publishing it. 

I am trying to create a proxy for the admin interface on port ~91~ 81. Here is what I have:
Domain name: proxy.mydomain.de (real domain name here)
scheme: https
Forward host/port: 127.0.0.1:81
SSL certificate: proxy.mydomain.de
Force SSL

It shows status "Online", but when I access proxy.mydomain.de, I get a 502 Bad Gateway.

What am I doing wrong?

**Comment by kolbii** [comment]
Can you make sure the service on port 81 is running?

**Comment by cboulanger** [comment]
Yes, it is, I am trying to use it to proxy itself...

**Comment by cboulanger** [comment]
My bad. nginx-proxy-manager serves http traffic only. when I switched to http, it worked. Closing.

**Comment by RosaEinhorn** [comment]
Can we put the admin interface behind a path? Like: domain.com/npm ? I'm trying it but it won't work. Can't find any info about it.

**Comment by miguelwill** [comment]
nope, npm run only un root of URL host

**Comment by GAS85** [comment]
> nope, npm run only un root of URL host

This kind of an old issue, but actually it is possible to hide admin panel behind the sub path: https://wiki.sitnikov.ga/doku.php?id=howto:npm#final_npm_configuration
Add 2 locations:
![изображение](https://user-images.githubusercontent.com/6813635/210221280-8c497607-fd80-4d0b-9cbf-eada5bbb39ff.png)

And add Advanced rule:

```nginx
location ~ ^/(css|js|images|login|assets|nginx|users|audit-log|settings) {
  return 307 https://$http_host/npm$request_uri?$args;
}
```
Replace `npm` with whatever you need in Custom Location **and** Advanced config.
Now you can control TLS configuration for NPM Admin Panel as for #481, #182
