### ISSUE TITLE
Azure DNS challenge fails

### ISSUE THREAD

**Issue by vbap** [jc21/nginx-proxy-manager#1087]
I am attempting to create SSL certificates using Azure DNS challenge just released in v2.9.2.

I fill the Credentials file when selecting Azure, replacing the template values with my actual values (I am using service principal).

When I press "save", I get internal error.

The logs show:

```
[5/11/2021] [9:53:10 AM] [Express  ] › ⚠  warning   Command failed: /opt/certbot/bin/certbot certonly --non-interactive --cert-name "npm-21" --agree-tos --email "admin@EXAMPLE1.net" --domains "SUB1.EXAMPLE1.net,www.EXAMPLE2.com.au" --authenticator dns-azure --dns-azure-credentials "/etc/letsencrypt/credentials/credentials-21"
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-azure-credentials /etc/letsencrypt/credentials/credentials-21
```

When I check the contents of directory /etc/letsencrypt/credentials/, there are no files present. So it seems the credentials file is not created?
Each time I attempt a "save", the suffix is increased (log file above shows cert-name "npm-21" and files "credentials-21" where previous iterations would show npm-2-/credentials-20, npm-19/credentials-19

I have tested my azure DNS credentials via otehr methods (Acme SSL) and they work fine.

**Comment by vbap** [comment]
I checked further. seems npm is using the wrong certbot argument to supply azure dns credentials.

Instead of 
`--dns-azure-credentials`

It should be
`--dns-azure-config`

(according to https://certbot-dns-azure.readthedocs.io/en/latest/index.html)

**Comment by chaptergy** [comment]
Ah, unfortunately this is non-standard behavior of this plugin. I have opened an issue over there (see link just above this comment) if they would consider supporting the credentials flag. Otherwise I would have to remove this DNS provider, since supporting non-standard flags would require a significant rewrite of the DNS challenge implementation.

**Comment by chaptergy** [comment]
Pull request to use the new version is open, in about an hour you can use docker image `jc21/nginx-proxy-manager:github-pr-1099` to get to test / use these changes before the next actual release.

**Comment by vbap** [comment]
> Pull request to use the new version is open, in about an hour you can use docker image `jc21/nginx-proxy-manager:github-pr-1099` to get to test / use these changes before the next actual release.

Tested and seems working well - many thanks for this!
