### ISSUE TITLE
Proxying to container with self signed https access

### ISSUE THREAD

**Issue by tiagombrito** [jc21/nginx-proxy-manager#110]
Hello,

I'm trying to create a docker-compose stack in portainer, with nginx-proxy-manager and keycloak, among other apps.

When accessing keycloak via https://hostname:8443 I'm able to access the application, since the container has a self signed cert in it.

Yet i'm not able to do it via npm, I create a proxy host with domain "keycloak.domain", https scheme, pointing to container:8443, and when accessing https://keycloak.domain i get an error (This site can’t provide a secure connection), yet i'm still able to access it via http.

The configuration file shows nginx is listening on port 80 instead of 443, probably because i didn't use letsencrypt (I'm just experimenting with https, and don't want the domain visible outside the local network), nor did i give npm the cert files, since i was expecting to use the ones in the keycloak container.

Is this not possible, or am i doing it wrong?

EDIT: Creating a custom certificate and adding it to npm and the proxy host seems to work just fine.

Thank you, and i hope that was coherent.

**Comment by jc21** [comment]
What you're experiencing is expected behaviour. The edge server (NPM) is not configured for SSL termination so you have to use `http` - no matter what the upstream server uses. It's functioning as a proxy, just not a secure one until you create or add certificates.

**Comment by tiagombrito** [comment]
Thank you.

Since I have my solution, I'll close the issue.

**Comment by goodvandro** [comment]
@tiagombrito How did you solve your problem? Can you share the steps with me?
