### ISSUE TITLE
Integrate SPNEGO for Kerberos authentication

### ISSUE THREAD

**Issue by stibra** [jc21/nginx-proxy-manager#1102]
Please integrate NPM with spnego for Kerberos integration.

https://github.com/stnoonan/spnego-http-auth-nginx-module

**Comment by chaptergy** [comment]
Closing as a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/437. Please comment your wish for Kerberos over there. If that issue is resolved and closed but not with kerberos, we can reopen this one.
