### ISSUE TITLE
"proxy_pass" directive is not allowed

### ISSUE THREAD

**Issue by vawaver** [jc21/nginx-proxy-manager#1112]
I wanted to make a proxy host for calibre-web docker - https://docs.linuxserver.io/images/docker-calibre-web
Based on their documentation for NGINX there I added code to the proxy host config file (of course I replaced my IP)

```
        location /calibre-web {
                proxy_pass              http://<your-ip>:8083;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                proxy_set_header        X-Script-Name   /calibre-web;
        }
```
After that, I am not able to run the NGINX app correctly.
I found the error message in the log.

nginx: [emerg] "proxy_pass" directive is not allowed here in /etc/nginx/conf.d/include/proxy.conf:7

How can I fix it?
Thank you

NGINX docker is updated to the latest version today.

**Comment by chaptergy** [comment]
How exactly did you set this up? Did you paste the entire code block
```nginx
location /calibre-web {
    proxy_pass              http://<your-ip>:8083;
    proxy_set_header        Host            $http_host;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Scheme        $scheme;
    proxy_set_header        X-Script-Name   /calibre-web;
}
```

Into the advanced tab? Or did you create a custom location `/calibre-web` location and paste just the contained code:
```nginx
proxy_pass              http://<your-ip>:8083;
proxy_set_header        Host            $http_host;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Scheme        $scheme;
proxy_set_header        X-Script-Name   /calibre-web;
```

Both of which should theoretically work. However if you used the second code snipped and added it to the advanced tab this error would be expected, since the content there is injected into the server block. And `proxy_pass` is not allowed inside the server block.

**Comment by vawaver** [comment]
Thank you for your reply.
I have created persistent volume on 
/home/tony/nginxproxy/data/nginx/proxy_host
and there is file 9.conf (for the particular subdomain)
I put this code inside of 9.conf - there is a "location" part so I replaced it with the code mentioned above.

**Comment by chaptergy** [comment]
You can try adding it though the UI. Edit the proxy host and add what you wrote to the advanced tab:
```nginx
location /calibre-web {
    proxy_pass              http://<your-ip>:8083;
    proxy_set_header        Host            $http_host;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Scheme        $scheme;
    proxy_set_header        X-Script-Name   /calibre-web;
}
```
If you post your entire `.conf` file I might also be able to answer you what was wrong with it

**Comment by vawaver** [comment]
Thank you for your answer.
I left my config here.
https://pastebin.com/jb7irf0b
Please be so kind and check it.

**Comment by chaptergy** [comment]
Unfortunately I am unable to reproduce your issue, your config looks fine and when I try it on my machine, no error is thrown. But setting it though the UI did work for you?

**Comment by vawaver** [comment]
I don't know exactly how to do it.
What should I do?
Thank you for your answer.

**Comment by chaptergy** [comment]
Try this
![image](https://user-images.githubusercontent.com/26956711/119653510-f2620480-be16-11eb-98cc-2cb179391a85.png)

**Comment by vawaver** [comment]
Thank you very much.
I will try it and let you know.

**Comment by vawaver** [comment]
I tried to do exactly as you suggested to me.
It did not help. 
It still moves me on the login screen after few mouse clicks.
Hmm...
Any other idea?
Thank you.

**Comment by chaptergy** [comment]
Unfortunately I have no other ideas. But I found this issue which is exactly your problem: https://github.com/jc21/nginx-proxy-manager/issues/854. Not sure what to make of it, it seems that it might be an issue with the authentication mechanism of calibre web? I also found [this page](https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx-proxy-manager), maybe this will help you? But I don't think I can provide any further help, sorry.

**Comment by vawaver** [comment]
Thank you for your help.
Finally, I have found a working solution for myself.

1. Set Cloudflare to "DNS Only" for my subdomain (losing Cloudflare protection)
2. Get a new certificate for my subdomain in NGINX proxy
3. Put the code to Advanced -> Custom config configuration

```
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
```
Now it seems to work fine without pushing me to the login screen.
Maybe it will help the others.
