### ISSUE TITLE
Many ACL Login attempts

### ISSUE THREAD

**Issue by Sigri44** [jc21/nginx-proxy-manager#113]
Hello,

I have v 2.0.11 on Docker, and I just activated the ACL.

On my "classic" domains (Proxy Host), it works very well, but I also put some on NPM and now he asks me for the ACL, then the NPM login (so far, everything is normal), but after the login, he asks again for the ACL. Despite the many attempts, the answer is "timeout" for the NPM login.

And if I'm going to "cancel" in this new ACL request, then "Unauthorized".

![aaaa](https://user-images.githubusercontent.com/9304947/55384901-36ee0000-552c-11e9-8bf8-6f38a24efbe8.png)

Thanks.

**Comment by chaptergy** [comment]
A lot has changed since this issue was opened. If this issue reappears let me know or open a new issue.
