### ISSUE TITLE
More than one port by domain

### ISSUE THREAD

**Issue by sigmagf** [jc21/nginx-proxy-manager#1147]
**Is your feature request related to a problem? Please describe.**
Maybe. I created a gitlab container, the same on the site releases ports 80, 443 and 22, in the proxy dashboard I informed to redirect the domain "gitlab.mydomain.com" to port 80 of the gitlab container, however when trying to use ssh for push it didn't work, only with http that works, then I thought it's because port 22 isn't listening to the domain and therefore never receives requests.

**Describe the solution you'd like**
The possibility of a domain redirecting to more than one port would probably solve the problem.

**Comment by apainter2** [comment]
DNS does not work that way, domain names are simply a phone-book of IP addresses :)

So as long as the SSH instance you're trying to connect to, is hosted on the same server that the webserver instance is listening on it should be fine.

Example:
example.domain.tld points to 1.2.3.4
Your host NPM on the server server that also has the SSH and webservers (on a different port) example:
https://example.domain.tld points to 1.2.3.4 which then proxies you to the actual web-server 1.2.3.4:80 AND the SSH server is hosted on the same server it would work, as the SSH instance would also be listening on IP 1.2.3.4.

If your using NPM as a front-door (public-facing) instance then forwards the HTTP(s) requests to another back-end instance via a different IP address, then use the streams option to forward SSH connections to that same backend server instance.

Example:
example.domain.tld points to 1.2.3.4
Your server on 1.2.3.4 only has NPM deployed to it, and is acting as a front-door/gatekeeper/proxy host only.
NPM is configured to forward example.domain.tld to IP 6.7.8.9 then when you try to connect to SSH at example.domain.tld it is trying to connect to the SSH instance on 1.2.3.4. To forward SSH (normally port 22) to 6.7.8.9 reconfigure the SSH instance on server 1.2.3.4 to use a different port, then configure a stream on the NPM server to stream port 22 to server 6.7.8.9.

Does this make sense? Hopefully, it does.

Thanks,

**Comment by sigmagf** [comment]
But I'm using one machine only, only one machine is with the gitlab and proxy container, I know it's probably not the most correct way and that the proxy should be in a separate instance.

The best way in this case would be for me to create another VM, I use lightsail, just for the proxy and then use the internal ips to redirect to the right container on the right port, eg:

1.2.3.4:81 - http gitlab
1.2.3.4:811 - ssh gitlab

and so on the vm of the proxy I add in "proxy hosts" the domain "gitlab.mydomain.com" pointing to 1.2.3.4:81 and create a "stream" of "80" and "443" to 1.2.3.4:811 TCP . That?

**Comment by apainter2** [comment]
Does AWS Lightsail only allow ssh connections via a web browser?

source: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/understanding-ssh-in-amazon-lightsail

You need to find away to use a SSH client such as Putty to work and connect directly to the SSH server instance, rather than a web-browser, but if you do, then try the following:
I am making the following presumtions here:

1. Your gitlab is not a docker container
2. The following is true:
   - NPM (running as a docker container) and is configured to listen to requests on ports 80 and 443
   - GitLab is hosted on a seperate VM/host to NPM (IP 1.2.3.4)
   - SSH is enabled on the server hosting the gitlab instance (IP 1.2.3.4)


I would redirect all http traffic to https on the front end, unencrypted http traffic's days are now numbered).

So I recommend trying this:

Your web-instance:
Create a proxy host using the following options:

[Details]
Domain Name: example.domain.tld (your FQDN)
Scheme: http (this presumes your running http on the backend instance only)
Forward Hostname / IP: 1.2.3.4
Forward Port: 81
Cache Assets: Enable

[SSL]
SSL Certificate: Select the relevant LE certificate
ForceSSL: Enable
HSTS Enabled: Enable
HTTP/2 Support: Enable


Stream option:
Incoming Port: 22 (standard SSH port - ensure that the hosting provider is not blocking this port)
Forward IP: 1.2.3.4
Forward Port: 811
TCP Forwarding: Enable
UDP Forwarding: Disable

**Comment by apainter2** [comment]
@sigmagf any news?

**Comment by sigmagf** [comment]
Sorry, hadn't seen it yet.

In my case now I use gitlab and NPM on the same machine and both in the docker, and in case the docker doesn't let me activate port 22 of the gitlab container.

I'm still opting for a way to do it using the same instance as lightsail.

This alternative you gave me is using two instances and installing, as you said, gitlab directly on the instance, right?

**Comment by neatgz** [comment]
Hello,
I want to reverse proxy some service on my QNAP nas.

For example:
https://nas.domain.com:1111   <--->   http://127.0.0.1:5678    
https://nas.domain.com:2222   <--->   http://127.0.0.1:1234
https://nas.domain.com:3333   <--->   http://127.0.0.1:4321

I really can't find how to configure using  Nginx Proxy Manager.

For some personal reason, I donnot want to do like this:
https://a.domain.com   <--->   http://127.0.0.1:5678    
https://b.domain.com   <--->   http://127.0.0.1:1234
https://c.domain.com   <--->   http://127.0.0.1:4321

Can you help me?
thanks a lot

**Comment by apainter2** [comment]
@neatgz This would not be possible by using a reverse proxy, what you are looking at is using an internal DNS solution to do this.

I would recommend Pi-Hole, as it now allows as well as network level ad-blocking, also local DNS resolution options.

**Comment by apainter2** [comment]
> 
> 
> Sorry, hadn't seen it yet.
> 
> In my case now I use gitlab and NPM on the same machine and both in the docker, and in case the docker doesn't let me activate port 22 of the gitlab container.
> 
> I'm still opting for a way to do it using the same instance as lightsail.
> 
> This alternative you gave me is using two instances and installing, as you said, gitlab directly on the instance, right?

@sigmagf , yes my solution uses two instances, you generally can not access the SSH instance within a docker container, as generally it does not exist. You can however SSH onto the VM instance, and use `docker exec -it NAMEOFCONTAINER COMMAND` commands.

**Comment by sigmagf** [comment]
I tried to do the same as you said, I created another vm, propio lightsail has bitnami's gitlab, and directed it to its ip, went to streans and configured it to redirect "22 ->2222" which is the port I defined, but it still doesn't works, my user is still not authorized

**Comment by apainter2** [comment]
@sigmagf I'll have to spin up a test environment on my VM Host to see whats the issue. Can you provide links to the application stacks your using. Thanks.

**Comment by sigmagf** [comment]
my gitlab real url?

**Comment by sigmagf** [comment]
Apparently even configuring to redirect 22 to 1.2.3.4:2222 or 22 to 1.2.3.4:22 doesn't work, I used the ip of the vm directly that is in gitlab and it worked

**Comment by mgutt** [comment]
NPM Proxy Hosts listen by default only on Port 80 and 443. Through the advanced settings you can add additional ports:
```
listen 22;
```

But this does not work for every type of traffic. I don't know if it works with SSH. Please test it and return feedback.
