### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by vibratim** [jc21/nginx-proxy-manager#117]
Hey folks,

I am encountering an issiue with my docker instance. The server is getting an error which I can't explain :)

`[4/8/2019] [6:40:13 PM] [Global ] › ✖ error ER_ACCESS_DENIED_ERROR: Access denied for user 'proxman'@'nginx-proxy-manager.br0' (using password: YES)`

I am running the container on an UNRAID host on a separate IP (macvlan).

Thanks in advance

**Comment by jc21** [comment]
That looks like a Database error :/

**Comment by vibratim** [comment]
Yeah it was a problem with my DB-Server :/
Nevermind :D 

But thank you anyway

**Comment by CrashyBang** [comment]
Hey @vibratim,

Did you get this working? I am trying something very similar at home.

Cheers.

**Comment by nnmalex** [comment]
I've also came across this error and the solution for me was to use a password different from what I've used initially.
