### ISSUE TITLE
Reset user password

### ISSUE THREAD

**Issue by onevision** [jc21/nginx-proxy-manager#1172]
I have picked up support for a website uses nginx-proxy-manager.  The guy who setup the website is long gone and I do not know his password.

I have access to the backend docker containers and have connected to MariaDB in hope of manually changing the password to something I know, however I cannot see where the users' passwords are stored.

Any help would be much appreciated.

**Comment by chaptergy** [comment]
If you have access to the database, you can go into the table named `auth` and update the `secret` column where the `user_id` is the user id you want. (You can see the users in the `users` table, and see the id associated with an email address.

To keep the user intact, change the secret to 
```
$2b$13$C9mJYK7Gf7sVgCCYw84HhOvOIpnyhkdGqwIp0PPj/s9.q0bxkoMZe
```
This will result in the password being `changeme`.

To just create a new admin user, see https://github.com/jc21/nginx-proxy-manager/issues/230#issuecomment-550565639
