### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by waterfallm** [jc21/nginx-proxy-manager#1176]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
trying to redirect to site on same docker server.
1. I've tried various diffent destimation sites nextcloud, grafana, portainer.
2. I've tried addressing by public IP and also private docker IP

**Nginx Proxy Manager Version**
2.9.3

**To Reproduce**
1. setup simple http host(no SSL cert yet)
2. url to direct to http host on docker host using external Ip or docker IP.

**Expected behavior**
docker website (grafana, portainer or nextcloud) should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9378879/122185435-008aca00-ce85-11eb-85c3-2680c65731a2.png)

**Operating System**
VPS Ubuntu version 18.04

**Additional context**
Also tried to setup on seperate Docker server with same error, so something i've doing consistantly wrong.

**Comment by waterfallm** [comment]
Ok i've followed my setup on yet another VPS but it's running Debian via OpenmediaVault.. All works as expected..

I suspect my Docker/Iptables setup on these other 2 VPS running Ubuntu.

**Comment by waterfallm** [comment]
So it looks like the "userland-proxy" setting i had used in my docker setup  
![image](https://user-images.githubusercontent.com/9378879/122219879-c5e65900-cea7-11eb-874c-4a748d6bf907.png)

**Comment by ccBrainKang** [comment]
same problem with you...
