### ISSUE TITLE
Add url path for custom location 

### ISSUE THREAD

**Issue by jancoow** [jc21/nginx-proxy-manager#118]
Hi there.

I'm trying to add a few custom locations for a specific proxy host. However, I'm unable to get this working with the web interface. It's not possible to add an URL path for the forward host name.

For example: This is the generated proxy pass:
proxy_pass http://192.168.1.2:9005;

However, I need to add a trailing slash:
proxy_pass http://192.168.1.2:9005/;

It works fine when I manually edit the nginx config. But it would be more useful if this can be done from the web UI.

**Comment by jlesage** [comment]
It should work. In the `Forward Hostname / IP` field, set the following value (see the ending slash):

```
192.168.1.2/
```

**Comment by jancoow** [comment]
@jlesage 

That only works when no port is given. Otherwise it will be set to 192.168.1.2/:9005

**Comment by jlesage** [comment]
Make sure to use the latest image version.  This has been fixed.

**Comment by jancoow** [comment]
That solved the issue. I pulled the latest version a weeks ago, and was running the image created on 2019-03-05. 
It works as expecting in the 2019-04-11 version.
