### ISSUE TITLE
https://nginxproxymanager.com/ is down

### ISSUE THREAD

**Issue by gempain** [jc21/nginx-proxy-manager#1188]
Hi,

Your website https://nginxproxymanager.com/ is down.

![Kapture 2021-06-18 at 21 44 52](https://user-images.githubusercontent.com/13135149/122609587-8887f400-d07e-11eb-81f2-6e9ad536b88b.gif)

Keep up the great work !

**Comment by jc21** [comment]
Looks like it's up and working now thx
