### ISSUE TITLE
Ngix fail to start

### ISSUE THREAD

**Issue by frozenstitches** [jc21/nginx-proxy-manager#119]
My log is being filled up with:
[nginx] starting...
nginx: [emerg] unknown directive "null" in /data/nginx/proxy_host/7.conf:30
I’m on a docker in unraid

**Comment by jc21** [comment]
can you tell me what's on that line in that file? It will be in your mounted data folder

**Comment by frozenstitches** [comment]
location / {# Access List

**Comment by jc21** [comment]
That's the entire file contents? seems to be a lot missing.

Any letsencrypt certs will not be able to renew when nginx is down altogether. If they expire and you're not using them, no big deal, they can renew later when nginx is back up.

**Comment by frozenstitches** [comment]
# ------------------------------------------------$# Lidarr.example.net
# ------------------------------------------------$

server {
set $forward_scheme https;
set $server"192.168.1.87";
set $port8686;

listen 8080;

server_name Lidarr.example.net;







[ Read 45 lines ]
I edited out my domain with example.net

**Comment by frozenstitches** [comment]
I ended up deleting the entry in the proxy host webui and every thing is back up and running.

**Comment by jc21** [comment]
Definitely seems weird. Re-open this if it happens again.
