### ISSUE TITLE
Add Infomaniak as DNS challenge plase

### ISSUE THREAD

**Issue by DarkAdibou** [jc21/nginx-proxy-manager#1190]
**What provider would you like to see added to NPM?**

Infomaniak

**Have you checked if a certbot plugin exists?**

**Comment by chaptergy** [comment]
It seems possible to integrate it: https://pypi.org/project/certbot-dns-infomaniak.  
Not sure when I will have the time to do it though.

**Comment by Fuechslein** [comment]
My pullrequest for this was already approved and got merged in v2.9.4

**Comment by chaptergy** [comment]
Ah, even better, thanks!
