### ISSUE TITLE
DB Connection Issues - Upgrade - 2.9.4

### ISSUE THREAD

**Issue by Jiriteach** [jc21/nginx-proxy-manager#1198]
Seem to have db connection issues with every upgrade and they are probably unrelated to NPM but always best to check.

I've updated to 2.9.4 and since the update, the app is reporting is unhealthy with connection issues to the db. Existing rules are working but I cannot login to NPM.

App logs are showing - error     select * from `migrations_lock` - ER_UNKNOWN_STORAGE_ENGINE: Unknown storage engine 'InnoDB'

Every second or so.
Anyone else seeing similar issues? Have removed existing containers and re-pulled without success.

This is on an RPI4.

My Docker compose -

> version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "DBUSERNAME"
      DB_MYSQL_PASSWORD: "DBPASSWORD"
      DB_MYSQL_NAME: "DBNAME"
    volumes:
      - /home/pi/Docker/npm/data:/data
      - /home/pi/Docker/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPASSWORD
      MYSQL_DATABASE: DBNAME
      MYSQL_USER: DBUSERNAME
      MYSQL_PASSWORD: DBPASSWORD
    volumes:
      - /home/pi/Docker/npm/data/mysql:/var/lib/mysql

**Comment by Jiriteach** [comment]
So the jc21/mariadb-aria:latest image does not come with InnoDB which explains the error message. Will change db's and try a few other things.

**Comment by Jiriteach** [comment]
Have had to revert back to 2.9.3 as too many things are breaking. If I change to yobasystems/alpine-mariadb:10.4.17-arm32v7 db then the original error is gone and I can log into the GUI but no rules appear with a raft of new errors.

Looks like it will be easier to just re-create all of the rules under a new setup.

**Comment by jc21** [comment]
Yes this is definitely not something that is controlled with each release.

After the db been setup once, it should not change. Whatever docker image you were using for it should not change either, or you will corrupt your data.

The jc21/maria-aria has not been updated in forever either.

You say this happens each release, so it's a very strange one.

**Comment by Jiriteach** [comment]
Thanks @jc21 - I've been using yobasystems/alpine-mariadb:latest for several releases now but last release I had to change to yobasystems/alpine-mariadb:10.4.17-arm32v7 due to their latest version causing connectivity issues.

Whats the recommend db to use if I had to setup things again? on an RPI4 so ARM based.

Thanks

**Comment by Jiriteach** [comment]
Or anyway to migrate content to another db?

**Comment by jc21** [comment]
Honestly I'd go with the SQLite option - uses less resources and requires no maintenance.

**Comment by Jiriteach** [comment]
Awesome - Thanks. Will do some research. I assume its a simple change the image to use a SQL lite image?

**Comment by jc21** [comment]
Negative. It's a change to the NPM [configuration](https://nginxproxymanager.com/setup/#mysql-database):

docker-compose.yml needs to have
```yml
environment:
  DB_SQLITE_FILE: "/data/database.sqlite"
```
and then changes to the [data configuration file](https://nginxproxymanager.com/setup/#configuration-file) are required.

**Comment by Jiriteach** [comment]
Thanks

**Comment by Jiriteach** [comment]
Ended up running a mysql dump then converting this to a sqlite3 db and using that. Works well against 2.9.4. This can be closed now. Thanks for the assistance.

**Comment by best-74** [comment]
> Ended up running a mysql dump then converting this to a sqlite3 db and using that. Works well against 2.9.4. This can be closed now. Thanks for the assistance.

Hmm, can you be helpfull and point on how to achieve this. I tried making a dump of my mariadb and convert it with at script, but when i tried to start with sqlite3 file it just deleted the file and startet from scratch.

**Comment by Jiriteach** [comment]
Sure - 

Backup your configuration first!

1. Use mysqldump to dump out the structure as a .sql file.
> mysqldump -h DBHOSTNAME -u DBUSERNAME -pDBPASSWORD DBNAME > npm_mariadb_backup.sql

2. Use mysql2sqlite (https://github.com/dumblob/mysql2sqlite) to convert the parse the content in the .sql file through to a Sqlite3 database.
> ./mysql2sqlite npm_mariadb_backup.sql | sqlite3 npm_database.db

3.  Move the new Sqlite3 database file into the correct location.
/npm/data/npm_database.db

4. Create a database configuration file for NPM to use a Sqlite3 database and save this as something like db_config.json.
> {
>   "database": {
>     "engine": "knex-native",
>     "knex": {
>       "client": "sqlite3",
>       "connection": {
>         "filename": "/data/npm_database.sqlite"
>       },
>       "useNullAsDefault": true
>     }
>   }
> }

5. Update the docker-compose.yml to use the Sqlite3 database.
> version: '3'
> services:
>   app:
>     image: 'jc21/nginx-proxy-manager:latest'
>     restart: always
>     ports:
>       - '80:80'
>       - '81:81'
>       - '443:443'
>     environment:
>       DB_SQLITE_FILE: "/data/npm_database.sqlite"
>     volumes:
>       - /home/pi/Docker/npm/data:/data
>       - /home/pi/Docker/npm/letsencrypt:/etc/letsencrypt
>       - /home/pi/Docker/npm/config/db_configuration.json:/app/config/production.json

Should be all that is required. Keep an eye on the log - best way to do this is via Portainer and then you can clear up the other mysql directories inside /npm/data/ as they are no longer required.

**Comment by best-74** [comment]
Great, -that worked. I forgot to correct the filename/location in configuration.json file. 

But i'm wondering why it's needed to create config.json when we write the "environment: DB_SQLITE_FILE: "/data/npm_database.sqlite" in compose.

One note on your guide (for others trying to follow). You change the extension on the db file from .db -> .sqlite. It is the same file, it's just the extension that has changed. :-)

For a quick way to dump database from mariadb container, to a directory on docker host, - use this command:
docker exec mariadb mysqldump --user database_username --password=database_password npmdb > ./npmdb.sql

**Comment by davidpesce** [comment]
For anyone stumbling on this in the future...
The configuration.json file is not needed as long as you name the sqlite file the same as when it is auto-generated. As long as you name it "database.sqlite" and store it in the data volume, it works perfectly.
