### ISSUE TITLE
Enable Discussions on this Repo Please

### ISSUE THREAD

**Issue by Jiriteach** [jc21/nginx-proxy-manager#1200]
Can discussions be enabled on this repo please? This will provide a better approach for many to ask questions/seek help as opposed to these being opened as issues and then being closed. Since it will be attached to the repo - information will remain for others to search etc.

Very simple to enable under Settings and categories etc. can be setup with Discussions.

Am aware of the Reddit community but there its barely active!

Thanks

**Comment by jc21** [comment]
Thanks for the idea, will do :)
