### ISSUE TITLE
re: Dark theme

### ISSUE THREAD

**Issue by f3bandit** [jc21/nginx-proxy-manager#1205]
**Is your feature request related to a problem? Please describe.**

Yes me and golem here don't like the bright lights

**Describe the solution you'd like**

If you could add a dark theme for us dungeon trolls that despise all that is bright
please and thank you! 

**Additional context**
yes you are awesome as well as you app! :) thx

**Comment by root9191** [comment]
Totally Agree with that!

**Comment by frisodubach** [comment]
Might be cool if we got the option to upload custom css instead.

**Comment by JesseyWhite** [comment]
duplicate of https://github.com/jc21/nginx-proxy-manager/issues/707

**Comment by geekedtv** [comment]
I second this. I am in this panel everyday and a dark theme would be an absolute game changer!

**Comment by chaptergy** [comment]
Closing in favor of https://github.com/jc21/nginx-proxy-manager/issues/707
