### ISSUE TITLE
How to uninstall NPM?

### ISSUE THREAD

**Issue by adoboligh1** [jc21/nginx-proxy-manager#1207]
How do I remove NPM from my server?

**Comment by danner26** [comment]
If you are using docker you can run `docker stop jc21/nginx-proxy-manager` or `docker stop CONTAINER_ID` which you can acquire from `docker ps`

**To remove the container/image/volumes:**
To remove the associated images, run `docker rmi jc21/nginx-proxy-manager jc21/mariadb-aria`
If you have other versions saved, you can find them by using`docker images -a` 

To remove the associated containers, run `docker rm jc21/mariadb-aria:latest jc21/nginx-proxy-manager:latest`
If you have other versions saved, you can find them by using `docker ps -a`

To remove the associated volumes, you can run `docker volume rm jc21/nginx-proxy-manager:latest jc21/mariadb-aria:latest`
If you have other versions saved, you can find them by using `docker volume ls`
