### ISSUE TITLE
No dashboard and _e is not a function issue

### ISSUE THREAD

**Issue by maciejs1982** [jc21/nginx-proxy-manager#1231]
Hi,
I'm currently getting no dashboard after login and half of the links don't work. Also when changing the user details from default to chosen I received error stating: _e is not a function, as well as anytime I try to browse through gui.

My system: Linux Ubuntu Server Focal 5.4.0-77-generic  x86_64 x86_64 x86_64 GNU/Linux running Docker-ce 5:20.10.7~3-0~ubuntu-focal, Google Chrome as browser

![Screenshot_2021-07-11_12-47-02](https://user-images.githubusercontent.com/77460878/125194204-3171db00-e248-11eb-996b-ea3c572eda8c.png)

**Comment by chaptergy** [comment]
Closed in favor of https://github.com/jc21/nginx-proxy-manager/issues/1219
