### ISSUE TITLE
I can't revert back to the normal http

### ISSUE THREAD

**Issue by RRPRIME** [jc21/nginx-proxy-manager#1232]
Version 2.9.4 
I enabled all options under SSL and generated a SSL certificate for a Proxy Host.
I can't revert back to the normal http
I removed the certificate, disabled all under ssl, changed the scheme to http, it still redirects to https, certificate is still there

**Comment by the1ts** [comment]
One of the options under SSL is HSTS (HTTP Strict Transport Security), this tells a browser to never allow non-https to that host, so the browser, in future requests, never hits http:// but the browser itself rewrites your request to https://. This HSTS request from the server side (NPM) is cached by the browser, in the case of NPM for 2 years. 

In short both the browser and NPM are doing exactly what you requested it to do by ticking that HSTS box and visiting the page.

To fix take a look at how to remove HSTS for your particular web browser and follow the instructions for this problem host. Or move to a different hostname.

**Comment by chaptergy** [comment]
Just to add here are some direct links on how to [remove HSTS in Firefox, Chrome and Safari](https://community.spiceworks.com/how_to/158595-how-to-clear-hsts-settings-for-safari-firefox-and-chrome)
