### ISSUE TITLE
v2.9.4

### ISSUE THREAD

**Issue by wolfy01** [jc21/nginx-proxy-manager#1237]
v2.9.4 Broke the UI. Downgrading to v2.9.3 fixes it. 
The issue: #1231 #1219

**Comment by zeroone82** [comment]
I've notice this too. For me login out and login back again seems to let me see and configure proxy hosts. All other dashboards are broken.

**Comment by chaptergy** [comment]
Closed in favor of https://github.com/jc21/nginx-proxy-manager/issues/1219
