### ISSUE TITLE
[Feature Request] Add hosts to Cloudflare automatically

### ISSUE THREAD

**Issue by MrSuttonmann** [jc21/nginx-proxy-manager#1238]
**Is your feature request related to a problem? Please describe.**
When I add a new host to NPM, I must also manually add the subdomain to my Cloudflare DNS settings. I have previously used Traefik as a reverse proxy which had an extension to automatically add the subdomain to Cloudflare.

**Describe the solution you'd like**
I would like the option to add a host to my Cloudflare DNS Zone automatically from NPM.

**Describe alternatives you've considered**
There are none, currently.

**Comment by dgeordgy21** [comment]
Yes, would be nice, like in https://www.cloudron.io
Thank's in advance

**Comment by chaptergy** [comment]
Closing in favor of more general https://github.com/jc21/nginx-proxy-manager/issues/1238

**Comment by MrSuttonmann** [comment]
@chaptergy You linked to, and closed, this issue. Could you please correct the link to the other issue?

**Comment by chaptergy** [comment]
Sorry, updated!
