### ISSUE TITLE
Limit TLS 1.2+

### ISSUE THREAD

**Issue by rudyberkvens** [jc21/nginx-proxy-manager#125]
Is there a way to support disabling TLS 1.0 and TLS 1.1 etc. 
Thanks,

**Comment by jc21** [comment]
Take a look at [this file(https://github.com/jc21/nginx-proxy-manager/blob/master/rootfs/etc/nginx/conf.d/include/ssl-ciphers.conf). You can copy it, modify it to your liking and mount it to the docker container to override the built in one.

`$(pwd)/ssl-ciphers.conf:/etc/nginx/conf.d/include/ssl-ciphers.conf`

Also I'll keep this open for the ability to specify ciphers using the UI.

**Comment by rudyberkvens** [comment]
That’s perfect. Thanks
