### ISSUE TITLE
[FR] Ability to clear logs?

### ISSUE THREAD

**Issue by Hukuma1** [jc21/nginx-proxy-manager#1254]
**Is your feature request related to a problem? Please describe.**
Was setting up a backup solution when I noticed that my `nginxproxymanager` config folder was giant. The `log` and `logs` folders are a whopping 2.2 GB. 

**Describe the solution you'd like**
Would love for some ability to a) clear logs on the spot from within the interface and b) perhaps implement an automatic method to clear logs after X amount of time has passed? e.g. retain logs for 1 month only

**Describe alternatives you've considered**
Not backing up my `nginxproxymanager` config folder. :P

**Comment by chaptergy** [comment]
b) was added in v2.9.5 two days ago via https://github.com/jc21/nginx-proxy-manager/pull/1140. 4 weeks of access logs and 10 weeks of error logs are kept and removed after.
