### ISSUE TITLE
How to collect access logs？

### ISSUE THREAD

**Issue by ck003** [jc21/nginx-proxy-manager#126]
Hello , Thanks for your sharing . How can I collect access logs because I want to know who have accessed my server , and I want to know their IP address, please help

**Comment by ck003** [comment]
@jc21

**Comment by kolbii** [comment]
Not sure, but I think you can mount a host directory to /var/log/nginx. For instance:
docker run -d \
    --name nginx-proxy-manager-app \
    -p 80:80 \
    -p 81:81 \
    -p 443:443 \
    -v /path/to/config.json:/app/config/production.json \
    -v /path/to/logs:/var/log/ninx \
    -v /path/to/data:/data \
    -v /path/to/letsencrypt:/etc/letsencrypt \
    jc21/nginx-proxy-manager:latest-armhf

**Comment by jc21** [comment]
The access logs for each host created by NPM is available in the `data` directory you should be mounting. eg `data/logs/proxy_host-10.log`

**Comment by ncm-lfc** [comment]
Any idea where I can find these log files in Hassio addon?

**Comment by b2az** [comment]
@ncm-lfc searching for the same. Have you found the logs?

**Comment by jonrub** [comment]
@ncm-lfc @b2az Did you find them?

**Comment by lordfiSh** [comment]
@jonrub @ncm-lfc @b2az you most likely don't need the info anymore, but logs are mapped to Supervisor Nginx Proxy Manager
 Log Tab: (https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/rootfs/etc/cont-init.d/npm.sh)

**Comment by graig123** [comment]
Any one looking to use **ngxtop** for access log monitoring and not having any luck.

I changes the conf file genarated by NPM for my host ( location: /data/nginx/proxy_host filename will be 1.conf  | or similar)
Inside it there is a line:
`access_log /data/logs/proxy-host-1_access.log proxy;`
changed it to:
`access_log /data/logs/proxy-host-1_access.log;`

ngxtop can procces log after this change.
