### ISSUE TITLE
Where is the / configuration?

### ISSUE THREAD

**Issue by joachimvadseth** [jc21/nginx-proxy-manager#129]
Hi, and great work! 

Set this up and working no problem with my plex.domain.com on mu UnRaid, but I want to have a Wordpress installation on my domain.com, but what folder do I put it in..? domain.com only shows me "Congratulations!" You have successfully installed..."

Thanks.

**Comment by jc21** [comment]
So I assume you want to run a wordpress site directly with this project, and it doesn't do that. It's only a passthrough to your next webserver, which would run wordpress.

Not to fear though, you'll be able to run [another docker container](https://hub.docker.com/_/wordpress) specifically for your wordpress installation.

Once that's up and running, just create a new Proxy Host for `domain.com` that forwards to the wordpress docker container.

**Comment by joachimvadseth** [comment]
I thought that was the case! No problem. Thanks for the conformation and keep up the good work! 

       Med vennlig hilsen
        Joachim Vadseth
         Fagerbakken 10
         6390 VESTNES
         NORWAY
 
              LinkedIn: http://lnkd.in/7CRff3 
              #: 41173660
              @: joachim@vadseth.net
              w: http://vadseth.net
