### ISSUE TITLE
Hi guys

### ISSUE THREAD

**Issue by yankieddl** [jc21/nginx-proxy-manager#1291]
hi  
i keep getting below error for JC21

[Global   ] › ✖  error     connect ECONNREFUSED 172.18.0.3:3306

 whichever DB variant I try, I'm getting the same result:

connect ECONNREFUSED 172.18.0.2:3306

i am using raspberry pi 4

pls advise

**Comment by jc21** [comment]
Your mysql server is not running so you'll need to inspect the logs for that container.

Alternatively, use the sqlite database option.

**Comment by yankieddl** [comment]
Thanks. Can you pls guid how to install sqlite db on the existing installation for raspberry pi 4. 

I am new to linux and trying to learn. Sorry if i hav askd a weird question. FYI maria db works fine on raspberry pi 4. Just the jc21 proxy manager giving trouble.

**Comment by chaptergy** [comment]
The docker-compose files in the [setup instructions](https://nginxproxymanager.com/setup/) contain all information you need. You just need to remove the `DB_MYSQL_...` environment variables and add the `DB_SQLITE_FILE` variable.

**Comment by yankieddl** [comment]
thanks.

the suggestions you gave me to use sql-lite worked and is working well.

🙏🙏

**Comment by yankieddl** [comment]
Good Day again

after setting username and password on nginx i logged out and tried to
login using new email and password but couldnt login.

is there a way to reset password.

pls advise.

thanks

**Comment by chaptergy** [comment]
See https://github.com/jc21/nginx-proxy-manager/issues/230. Maybe your password contained a hash (`#`), don't add a hash to the password (https://github.com/jc21/nginx-proxy-manager/issues/1120).

**Comment by yankieddl** [comment]
thanks for prompt response.

apologize again. i am not used to the terminology. how do i connect to
database and run the script UPDATE user SET is_deleted=1;?

thanks

**Comment by chaptergy** [comment]
I have changed my comment to include a link to a specific comment which explains step by step what to do.

**Comment by yankieddl** [comment]
thanks.

after first command it asked me enter root password. i tried all but none
works. it keeps giving me following error. pls note i am using sqlite and
not MYSQL

*$ sudo  docker exec -it nginx_db_1 sh*
*/ # mysql -u root -p*
*Enter password:*
*ERROR 2002 (HY000): Can't connect to local MySQL server through socket
'/run/mysqld/mysqld.sock' (2)*
*/ #*

**Comment by chaptergy** [comment]
I forgot that you are using the sqlite file, not the mysql database. You don't even need the mysql container anymore, you can remove it from the docker-compose.
You will have to edit the database file you specified in the docker-compose using a tool like [SQLite Browser](https://sqlitebrowser.org/). Change to the `user` table, and set `is_deleted` to `1`. Then follow step 2 and 3, and at the end, set it to `0` again.
If you haven't done much yet it might be easier to just delete the containers and the volumes and just start again.

**Comment by jc21** [comment]
I can also recommend using [litecli](https://github.com/dbcli/litecli) for connecting to sqlite db's.
