### ISSUE TITLE
Better DYNU support

### ISSUE THREAD

**Issue by systempal** [jc21/nginx-proxy-manager#1292]
**What provider would you like to see added to NPM?**
DYNU

**Have you checked if a certbot plugin exists?**
YES

Please consider update to latest acme.sh and add support for dynu_dns (old DYNU plugin will be removed soon) and add support in the GUI or elsewere for challenge-alias and domain-alias.

actually i need a way to call amce script as this:

export Dynu_ClientId="xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx"
export Dynu_Secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

acme.sh --issue -d *.contoso.com --challenge-alias contoso.dynu.net --dns dns_dynu

tya,
Simone.

**Comment by chaptergy** [comment]
v2 will not switch to acme.sh since it would be a huge undertaking. So unless someone from the community wants to implement acme.sh, this version will not have it.  
v3 will replace certbot with acme.sh anyways, but there is no timeline on when v3 will be in a usable state.

**Comment by chaptergy** [comment]
Since this issue is mainly about acme.sh support I will close this in favor of https://github.com/jc21/nginx-proxy-manager/issues/836.
