### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jpombas** [jc21/nginx-proxy-manager#1296]
Hi,

I apologize for opening an issue, but I thought it was the best way to report the following problem:

I followed the steps for a quick setup, but apparently it wasn't successful, could you helpme to understand what's wrong?

Thanks for your help ;)

![image](https://user-images.githubusercontent.com/9874020/128607921-bf114d82-4915-4b97-aeb3-3224f624423a.png)

![image](https://user-images.githubusercontent.com/9874020/128607802-d0fd9f64-9358-4e66-9198-341f7b7ab37c.png)

![image](https://user-images.githubusercontent.com/9874020/128607891-67eb7796-91f6-4c88-8581-bf298ccd6c71.png)

![image](https://user-images.githubusercontent.com/9874020/128607954-db137282-89f9-4990-acd3-a311e650b2f8.png)

![image](https://user-images.githubusercontent.com/9874020/128607826-8e7f715e-d0c0-4bdc-bd9b-fb115c91bc7d.png)

**Comment by jc21** [comment]
perhaps the nginx instance doesn't know what `hassio` is in the dns. Try curling it directly from within the running container:

```
docker exec -ti name_of_npm_container curl http://hassio:8123
```

you may have to use an ip address if the dns server on your network doesn't have an entry for `hassio`

**Comment by jpombas** [comment]
Using local IP address, i got que following results:

![image](https://user-images.githubusercontent.com/9874020/128627447-40ad4a08-e713-4b5e-8d27-ac4751e37825.png)

![image](https://user-images.githubusercontent.com/9874020/128627455-cd5848eb-bb99-4eec-b959-512e4bdec3c5.png)

![image](https://user-images.githubusercontent.com/9874020/128627481-af35cb18-bf9e-4809-8949-adaec85fe17f.png)

I also added the following configuration in Hassio:

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1

**Comment by phantomski77** [comment]
Try NPM’s container IP address for your `trusted_proxies` setting in `http` integration, instead of localhost. Localhost within your Home Assistant instance is just the container’s own localhost, not host’s localhost, if it makes sense. It needs immediate upstream reverse proxy IP, which would be your NPM container IP.

**Comment by jpombas** [comment]
Problem solved, thank you guys.

Sorry, but It was my lack of experience 😉
