### ISSUE TITLE
 Some serious qestions about project!

### ISSUE THREAD

**Issue by johny-mnemonik** [jc21/nginx-proxy-manager#131]
Hi i want try youre project on my lab. Early i use ngnix-admin parent project of nginx-proxy-manager. Have some qestions:
1.  How to install without docker or in LXC?
2.  Does this software support autostart after reboot? In nginx-admin you need to start server manualy from web ui if server was rebooted?
3. Have it options as cache, logs, loadbalancing, ssl and other functions  of parent project?

**Comment by jc21** [comment]
1. Don't have lxc version yet
2. Yes, with docker restart always option
3. yes asset cache, yes logs, no load balancing, yes ssl

**Comment by ccasalicchio** [comment]
Can load balancing be set in the advanced options? Because load balancing is not very hard to do
http://nginx.org/en/docs/http/load_balancing.html
but it would require access to the config file.
