### ISSUE TITLE
Use proxy without publishing ports

### ISSUE THREAD

**Issue by Aerya** [jc21/nginx-proxy-manager#132]
Hi,

I can't get your proxy work without publishing the ports. I mean some services dont provide us with build in auth so they can be accessed using IP:port. That is way not safe.
I looked at issues and readme but couldn't find the way to use it (as for Traefik) without "open ports". What did I miss?

thanks!

**Comment by PixiBixi** [comment]
Hi Aerya

You must linking backend containers and reverse-proxy container in order to use container name instead of publish the ports

It can be done with **--link** container:container or **depends_on** with compose

**Comment by Aerya** [comment]
Merci ;)
