### ISSUE TITLE
Changes in Access List are not applied immidiatly

### ISSUE THREAD

**Issue by LiohMoeller** [jc21/nginx-proxy-manager#1328]
If I change an access list (e.g. add or delete a value) the settings are not applied on the relevant host definitions unless I open the definition in e.g. proxy hosts and click save there.

**Comment by Salvora** [comment]
this happens to me all the time

**Comment by jc21** [comment]
This is easy to fix; reload nginx after modifying the access list file.

I didn't know this was a problem I guess I don't use access lists very often.
