### ISSUE TITLE
Downgrade vom github-develop to 2.9.7

### ISSUE THREAD

**Issue by root9191** [jc21/nginx-proxy-manager#1333]
**Describe the bug**

I made an Upgrade to the developer Edition because i wanted to test something. Then i wanted to use my 2.9.7 Docker again, but when i start the Container, it instantly goes to Status "unhealthy" and in the logs i found an Entry which contains, that the Database could not be migrated. Is ther a possibility to make an Downgrade of the Database?

**Nginx Proxy Manager Version**

2.9.7

Everything works so far, but i think it's better for me to use the stable Version ^^

**Comment by jc21** [comment]
Well I could give you some manual steps to revert an added database migration, but I think at this point you're fine to use the develop version. I'm planning to release that code very soon anyway, so wait until then before switching to the main branches.

If you're not already doing it, click the `Watch` button on this project and specifically watch `Custom` -> `Releases`. You'll get an email about it.

**Comment by root9191** [comment]
OK, Thank you very much.
I Need to donate now, because i really like your Work and your Support!
