### ISSUE TITLE
Real IP not working

### ISSUE THREAD

**Issue by offgrind** [jc21/nginx-proxy-manager#1336]
Hi,

the real IP is not working in 2.9,7. Did someone has a hint for me ?

-->

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Real External IP not showing in Synology as example.

**Nginx Proxy Manager Version**
2.9.7

**Expected behavior**

**Screenshots**

**Operating System**
Ubuntu 20.04, Docker latest

**Comment by kellcomnet2** [comment]
Same issue, I am running in docker bridge networking mode since it fails to start if I use host networking. I am unable to use ACLs because it never sees the real ip

**Comment by offgrind** [comment]
Hi, worked with a rebuild container and with "proxy_set_header X-Forwarded-Proto $scheme;" in advanced Custom Nginx Configuration.

**Comment by caesartcs** [comment]
@offgrind  did you add that in `/data/nginx/custom/server_proxy.conf`?

**Comment by openaspace** [comment]
> Hi, worked with a rebuild container and with "proxy_set_header X-Forwarded-Proto $scheme;" in advanced Custom Nginx Configuration.

Hi. 
wich is the correct sintax to add in the advanced config? 

I use alphine linux under proxmox, and ngninx proxy manager behind pfsense firewall
