### ISSUE TITLE
IPv6: Default Site setting not being respected 

### ISSUE THREAD

**Issue by Spiritreader** [jc21/nginx-proxy-manager#1347]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

When using ipv6, the default site setting is not being respected. Instead, the congratulations page is always shown
![image](https://user-images.githubusercontent.com/18438899/130544244-750905ba-6064-4a58-889d-d2d0a976da66.png)

**Nginx Proxy Manager Version**

2.9.7

**To Reproduce**
1. Configure docker with ipv6
2. Set NPM Default site to anything other than "Congratulations Page"
3. Observe setting not being respected for ipv6 addresses

**Expected behavior**

The desired page should be shown

**Additional context**

What I did to fix it:
Since you can edit the default_host site.conf file, I went ahead and changed it to:
```
server {
  listen 80 default;
  listen [::]:80 default; # added default here

  server_name default-host.localhost;
  access_log /data/logs/default-host_access.log combined;
  error_log /data/logs/default-host_error.log warn;


  include conf.d/include/letsencrypt-acme-challenge.conf;
  root /data/nginx/default_www;
  location / {
    try_files $uri /index.html;
  }
}
```

Specifically this line
https://github.com/jc21/nginx-proxy-manager/blob/5c679084605a79d98661a65eb272a06fc8cb5669/backend/templates/default.conf#L10
Adding a `default` seems to do the trick, although I don't know if specifying multiple `default` in the nginx site conf is good practice.

**Comment by TobiasKneidl** [comment]
@Spiritreader  Thanks for that!
