### ISSUE TITLE
Problem setting up stream

### ISSUE THREAD

**Issue by DejonckheereWard** [jc21/nginx-proxy-manager#1354]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

While setting up a stream, an error shows up saying "data.forwarding_host should match exactly one schema in oneOf"

**Nginx Proxy Manager Version**

Verstion 2.9.8

**To Reproduce**
1. Create a new stream
2. Fill in all values
3. Get error on saving

**Expected behavior**

Creating a new stream

**Screenshots**

![image](https://user-images.githubusercontent.com/32327026/131125986-378232d7-d82c-48dd-86c5-a2f18a9d370f.png)
![image](https://user-images.githubusercontent.com/32327026/131126426-0a51971d-4686-44dc-ba87-aef2d6bb0267.png)

**Operating System**

Photon Os 3.0, build 11dd065

**Additional context**

This issue didn't happen before in a previous install, we upgraded and re-setup nginx proxymanager today because of issues upgrading.

I don't seem to find any logs about this issue on the server either.

Docker version used: 19.03.15, build 99e3ed8

**Comment by MichelBaie** [comment]
is a fix planned ?

**Comment by BjoernAkAManf** [comment]
Might want to try the fix in the aforementioned PR.
