### ISSUE TITLE
Missing manifest Mariadb?

### ISSUE THREAD

**Issue by aroundmyroom** [jc21/nginx-proxy-manager#1357]
Pulled the new version (and this new version is also running) but it gave an error on the db part

manifest for jc21/mariadb-aria:10.4 not found: manifest unknown
Previously this was working ok.

what could I do possibly wrong or did I miss a change in a previous version?

**Comment by aroundmyroom** [comment]
ah . version 10.4 must become :latest

solved

**Comment by aroundmyroom** [comment]
when changing 10.4 to latest, I get again an issue on the logon, so probably the change from db goes wrong .. wierd.

**Comment by nielsvf** [comment]
> when changing 10.4 to latest, I get again an issue on the logon, so probably the change from db goes wrong .. wierd. in combination with username/pwd

I've got this as well.

**Comment by aroundmyroom** [comment]
> > when changing 10.4 to latest, I get again an issue on the logon, so probably the change from db goes wrong .. wierd. in combination with username/pwd
> 
> I've got this as well.

wonder what has changed betwee 2.9.3 and 2.9.8 so I rolled back an backup.

**Comment by aroundmyroom** [comment]
the problem is an already reported issue (but that user moved to sqllite) 
the storage engine InnoDB is not present when you move from 10.4 to Latest
So where I initially started with 10.4 (and that one worked before when pulling) now it tells us that the manifest is not there and changing the db to : latest gives a problem that it cannot migrate correctly.

So in this situation I do not care about the upgrade of the db and will let the error be the error and do not care about it.

**Comment by tuxmeister** [comment]
Same issue here, just tried a pull, updated to :latest tag and pulled again, now getting the following error:

`[8/30/2021] [2:03:20 PM] [Global   ] › ✖  error     select * from `migrations_lock` - ER_UNKNOWN_STORAGE_ENGINE: Unknown storage engine 'InnoDB'`

**Comment by fdr76** [comment]
it looks I have the same issue when I change 10.4 to latest.

@tuxmeister can you tell in which log-file you get the error?

**Comment by aroundmyroom** [comment]
@fdr76  you can see this when you do not run it in daemon mode (so do not run with -d) from commandline / shell

so the version :latest is a new mysql database without InnoDB .. no clue what has changed ..

**Comment by jc21** [comment]
See https://github.com/jc21/docker-mariadb-aria/issues/8

use `jc21/mariadb-aria:10.4.15-innodb`

**Comment by nielsvf** [comment]
> See [jc21/docker-mariadb-aria#8](https://github.com/jc21/docker-mariadb-aria/issues/8)
> 
> use `jc21/mariadb-aria:10.4.15-innodb`

It works now! Thanks for your reply. The README.md still contains ` image: 'jc21/mariadb-aria:latest'` though. Or is that for new installs only?

**Comment by aroundmyroom** [comment]
That fixed it. Thanks !

**Comment by jc21** [comment]
> It works now! Thanks for your reply. The README.md still contains ` image: 'jc21/mariadb-aria:latest'` though. Or is that for new installs only?

Yep this is fine for new installs. It's those whom had the previous image with innodb enabled that experience problems.
