### ISSUE TITLE
cannot set streams on Version 2.9.8

### ISSUE THREAD

**Issue by towatai** [jc21/nginx-proxy-manager#1382]
I always get an error message when creating streams as shown in the screenshot. Even a complete reinstallation of the machine has not helped. Tested under Ubuntu Server 20.04.3 and Unraid.

Installed according to the following instructions (of course with adjustment to the current version number).

https://apfelcast.com/nginx-proxy-manager-reverse-proxy-mit-grafischer-oberflaeche-gui/

![proxymanager_2-9-8](https://user-images.githubusercontent.com/31258373/132335347-15135e4f-181a-4080-80fc-75ee27850e8e.PNG)

**Comment by capemaxchile** [comment]
I have the same problem now! :(

**Comment by Strombach** [comment]
Same problem, installed with unraid Community Applications.

**Comment by jc21** [comment]
What about v2.9.9?

**Comment by capemaxchile** [comment]
Thanks JC21, its solved in 2.9.9!! Great!
