### ISSUE TITLE
I always get a 502 Bad Gateway error when I navigate to the root of a logged drupal site

### ISSUE THREAD

**Issue by cjamcu** [jc21/nginx-proxy-manager#1386]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
I have a proxy host pointing to a site made with drupal 9. When I log into the site and navigate to the root I always get a **502 Bad Gateway error**. I have tried to set custom settings but I am not successful.

**PD : If I do the same flow but by the ip of the service I have no problem.**

**Comment by jc21** [comment]
Sounds like the docker container for NPM can't communicate with your drupal site. You'll have to ensure that the scheme/ip/hostname/port of the drupal site is correct in the proxy config. You can confirm it's connectivity on the command line by running something like:

```bash
docker run --rm -ti name_of_npm_container curl http://hostname_of_drupal:80
```

**Comment by cjamcu** [comment]
The proxy is well configured because when I have not logged in the site works fine. This is verified by the curl that tells me to run, it is responding correctly. The curl works because it is being done without a user session. Thank you

**Comment by cjamcu** [comment]
@jc21 The real problem was `upstream sent too big header while reading response header from upstream` . I solved this by adding this advanced configuration

```
  location / {
   proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;

    # Proxy!
    include conf.d/include/proxy.conf;
  }
```
