### ISSUE TITLE
Adding oidc and/or header authenticatiom

### ISSUE THREAD

**Issue by erikthegamer1242** [jc21/nginx-proxy-manager#1387]
**Is your feature request related to a problem? Please describe.**

I have Authelia setup as my SSO, and I authenticate there and then I am forwarded to NPM login page and if I am not at my computer can't log in considering I have a strong password,

**Describe the solution you'd like**

Adding support for oidc to authenticate and/or header auth considering NPM is already proxied by itself.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jc21** [comment]
See #1388

Closing this, please continue discussions on the PR.

**Comment by erikthegamer1242** [comment]
I didn't think of authenticating proxy hosts using oidc, but the UI itself. Can this PR be used for that?

**Comment by jc21** [comment]
I'll say no. However you could create a proxy host for the admin interface and put it behind oidc but then you'll also need to log in to the ui after oidc.. also I think the `Authentication` header would clash so yeah scrap that idea.

Alternative UI authentication options won't be added to v2. They can be considered for v3, though the list of features to add for that is already huge.

**Comment by erikthegamer1242** [comment]
Could you please add it in v3 or point me to how to contribute and make it happen?

**Comment by Tuphal** [comment]
I also use Authelia and would love a Proxy/Header Authentication.

Could we set some kind of a bounty for this feature. I would be willing to pay for this.
