### ISSUE TITLE
SSL on admin web page

### ISSUE THREAD

**Issue by dbrosy** [jc21/nginx-proxy-manager#139]
This is not an issue more a how do I do this.

is it possible to secure the admin page on nginx proxy server. I have port 81 working fine but have a SAN cert which I want to use to access admin page and ideally port 443 but I guess that is already in use.

**Comment by OhHeyAlan** [comment]
@dbrosy setup a subdomain `admin.example.com` or in my case `nginx.mydomain.com` for your domain and port forward your domain/ip to port 81. Then you can use a custom cert to secure the subdomain. 

TLS traffic will enter port `:443` ----> `Nginx Proxy` -----> `:81`


<img width="1293" alt="Screen Shot 2019-05-10 at 12 20 09 PM" src="https://user-images.githubusercontent.com/11955126/57544975-8c34e280-731e-11e9-9b6d-d95828756d28.png">
<img width="616" alt="Screen Shot 2019-05-10 at 12 19 22 PM" src="https://user-images.githubusercontent.com/11955126/57544977-8ccd7900-731e-11e9-8e3b-12d2b4338f14.png">


Example:

**Comment by dbrosy** [comment]
Thanks @OhHeyAlan I now have it working. I had the scheme set to https.

**Comment by 123dev** [comment]
> Then you can use a custom cert to secure the subdomain.

How do you use a custom cert, the only available option is LetsEncrypt
I don't want to publish the admin publicly and want to use company self signed certificate, how can I do that?

Thanks

**Comment by 123dev** [comment]
> 
> 
> > Then you can use a custom cert to secure the subdomain.
> 
> How do you use a custom cert, the only available option is LetsEncrypt
> I don't want to publish the admin publicly and want to use company self signed certificate, how can I do that?
> 
> Thanks
Nevermind,

Figured it out, thanks for the instructions.

**Comment by securehosting1** [comment]
Thanks fixed.

**Comment by juanmafont** [comment]
> @dbrosy setup a subdomain `admin.example.com` or in my case `nginx.mydomain.com` for your domain and port forward your domain/ip to port 81. Then you can use a custom cert to secure the subdomain.
> 
> TLS traffic will enter port `:443` ----> `Nginx Proxy` -----> `:81`

 Remenber after you has access with SSL, then you can close port 81 at docker-compose.yaml or compose.yaml at opened only to internal docker network, so you need to remove  the '81:81'  from 'port' section and add section 'expose' with port 81 like down
 
![Screenshot_2024-05-09_17-53-51](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/6154911/f2724c64-6327-43bb-b13b-70383c8c557b)
