### ISSUE TITLE
Error 111: Connection refused at upstream: "http://127.0.0.1:81/health

### ISSUE THREAD

**Issue by NoName805** [jc21/nginx-proxy-manager#14]
Health check page is not available?

2018/09/04 19:06:12 [error] 223#223: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /health HTTP/1.1", upstream: "http://127.0.0.1:81/health", host: "localhost:9876"

2018/09/04 19:06:27 [error] 223#223: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /health HTTP/1.1", upstream: "http://127.0.0.1:81/health", host: "localhost:9876"

**Comment by jc21** [comment]
Are you running the container in host network mode by any chance?

**Comment by NoName805** [comment]
Yes, using bridge with static ip.

**Comment by jc21** [comment]
Hmm you say "bridge" but that's the default docker network mode, which is different from "host" mode.

https://docs.docker.com/network/#network-drivers

I've updated the docker images to expose the port which may fix your problem. The image works fine in both modes for me.

Pull one of these images to get the fix: `latest`, `2`, `2.0.2` - armhf builds will be updated later

Reopen if things aren't resolved for you.
