### ISSUE TITLE
Having issues getting admin panel to load

### ISSUE THREAD

**Issue by emarschang** [jc21/nginx-proxy-manager#140]
Just installed this tool using docker compose.  Container created just fine.  I can reach localhost/80 and localhost/443 just fine.  When looking at the docker container health it claims unhealthy.  An I see and a snip from the docker logs are below.

Last output	% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 
 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (22) The requested URL returned error: 502 Bad Gateway

 [5/10/2019] [3:20:43 PM] [Global   ] › ✖  error     Config file /app/config/production.json cannot be read Error: Config file /app/config/production.json cannot be read,

**Comment by jc21** [comment]
Have you [read this](https://github.com/jc21/nginx-proxy-manager/blob/master/doc/INSTALL.md#configuration-file)?

**Comment by lishine** [comment]
Same here.
Why it just not runs as described - docker-compose ...
The config is there, so what is the problem?

**Comment by george-viaud** [comment]
Similar problem here - things look fine but I am not certain how to dig deeper unfortunately.  I suspect there are some pre-flight things I've done wrong (creating DB, User, etc) - not sure where to look for logs to see what's failing.  Any direction on what to check would be greatly appreciated.

I use this tool via HASSIO regularly and would love to get it working stand-alone for use on AWS

**Comment by doughnet** [comment]
Same issue.  Funny thing is it works fine on a KVM virtual machine but on a OpenVZ 7 virtual machine it does not.  Not sure if that coincidence or not ...

**Comment by chaptergy** [comment]
Since this issue is fairly old I will close this. I anyone encounters this problem again, please open a new issue with as much information as possible, so logs, docker-compose files, etc
