### ISSUE TITLE
privkey changed in size from v2.9.4 and it is not recognized anymore as a valid privkey on QNAP NAS

### ISSUE THREAD

**Issue by hjhm35** [jc21/nginx-proxy-manager#1406]
Is it possible that the privkey file is not valid anymore? V2.9.4 generates privkey filesize about 1,66 kb. Higher versions (also 2.9.9) create privkeys with a size of 306 bytes. My QNAP NAS says that the file is not valid. When I create certificates with v2.9.4 then it works well.

**Comment by chaptergy** [comment]
The default config has been changed to use ecdsa instead of rsa. Maybe your system does not support this cryptographic method? You can overwrite `/etc/letsencrypt.ini` by mounting your own file into the docker container to remove these lines if you want to go back to rsa.
