### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by fa-ve** [jc21/nginx-proxy-manager#143]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?

Yes

- Are you sure you're not using someone else's docker image?

Yes

- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

No

**Describe the bug**
- A clear and concise description of what the bug is.

If I create a https proxy host I get a 504 Gateway Time-out if I request the site. 

- What version of Nginx Proxy Manager is reported on the login page?
v2.0.13 

**To Reproduce**
1. Go to Dashboard
2. Click on Hosts
3. Click on Add proxy host
4. Fill in subdomain name
5. Select https scheme
6. fill in ip and port
7. select SSL
8. request SSL cert
9. select force ssl or deselect will result same 504 Gateway Timeout
10. open new created site and wait for error

**Expected behavior**

display the site I requested.

**Screenshots**
N/A

**Operating System**
- running on QNAP container station.

**Additional context**
Add any other context about the problem here, docker version, browser version if applicable to the problem. Too much info is better than too little.

**Comment by OhHeyAlan** [comment]
Step #5, try setting it to `http` for the scheme.

**Comment by fa-ve** [comment]
same for HTTP, HTTP to HTTP is working perfect.. HTTPS to HTTPS is giving this timeout..

**Comment by fa-ve** [comment]
it's a weird issue, if I connect the server through an internal IP I get the error message. If I expose the same through my public IP it works as expected. a other internal https site is working.. so something is wrong with the destination site I expect

**Comment by jc21** [comment]
The error suggests that Nginx cannot talk to your upstream server. Without knowing your network stack, this is hard to diagnose.

**Comment by murraydb** [comment]
Just in case anyone find this.  I had this trouble with Heimdall and Tautulli.
if my server address was 192.168.3.69 - I had been using that for most items. (Sonarr, PiHole, Radarr, Plex, JellyFin etc.) 

When I used that same address for either Tautulli or Heimdall I would get the 504 Gateway timeout.

My solution was to check the docker items ip in portainer  ex 172.17.0.2 for Heimdall and http://172.17.0.5 for Tautulli.  Also to note, use the docker internal port 80 for Heimdall in my case, though I have 740 exposed via docker.

I know this wasn't a bug in  the nginx-proxy-manager project, but I figured, I would share my solution in case others find this thread via google as I did.

**Comment by luminousmg** [comment]
I had a similar issue with Digital Ocean, when using the assigned IP address of the droplet.  I corrected the issue by setting up a "Floating IP" in Digital Ocean and assigned that to the droplet.  Everything worked once I started using the floating IP address.  (I imagine this would also occur on AWS and you would need to assign an elastic IP address to the instance.)  Hope this helps as well!

**Comment by Sigri44** [comment]
Hi all !
I have the same error, but redirect domain to domain, it's the problem ?!

![image](https://user-images.githubusercontent.com/9304947/90668951-20dffd00-e251-11ea-9e01-02995555ad51.png)

**Comment by b4oshany** [comment]
@luminousmg, thanks for ur comment. I landed in the same problem

**Comment by kimtiago** [comment]
Thanks! This topic saved me.

**Comment by dongido001** [comment]
OMG @luminousmg Thanks a lot! was about to give up already. Saved me on Digital ocean (It's now called reserved IP)
