### ISSUE TITLE
worker_connections increase

### ISSUE THREAD

**Issue by PavelkaDavid** [jc21/nginx-proxy-manager#1435]
Hi, I have nginx proxy manager running in docker container and it hosts wordpress. In peak time web sometimes throw "500 Internal Server Error".
![image](https://user-images.githubusercontent.com/42189607/134940498-3f713eda-5a2d-4eda-9ef6-285283c3121c.png)

When searching through the error logs I always found this:
```
[alert] 2190841#2190841: 1024 worker_connections are not enough
[warn] 2190841#2190841: 1024 worker_connections are not enough, reusing connections
```

I've wanted to increase worker_connections, but I was unlucky as the only possible way is to add it to "/data/nginx/custom/root.conf":
```
events {
    worker_connections  10024;
}
```
That resulted into this error: "events" directive is duplicate in /data/nginx/custom/root.conf:1

So I'm out of ideas and replacing /etc/nginx/nginx.conf directly seems sketchy to me. Is there another way?

Thank you.

**Comment by chaptergy** [comment]
Unfortunately there is no other way than either to edit the file inside the container each time you update or to mount a different nginx.conf into the container.

**Comment by jearton** [comment]
+1

**Comment by e3ndr** [comment]
Don't want to necro, but I came here from Google and solved the issue (cleanly). 

In your Docker volume for NPM, there's now a `/nginx/custom` folder (documented [here](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations)). I made a file at `/nginx/custom/events.conf` and put the following contents:
```
worker_connections  40960;
```

Hope this helps someone else! ❤️
