### ISSUE TITLE
"Best Practice: Use a Docker network" not working : 502 error

### ISSUE THREAD

**Issue by maximeMD** [jc21/nginx-proxy-manager#1441]
Thank you for your amazing tool 😄 

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Nginx cannot proxy another service running in a Docker container using its hostname, even if they are in the same network.

**Nginx Proxy Manager Version**

v2.9.9

**To Reproduce**
1. Run npm with the exact docker-compose.yml defined here : https://nginxproxymanager.com/setup
2. Add an external network in the file, like here : https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network
3. Create another docker compose file defining a portainer instance, like here : https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network
4. Configure a new proxy host in npm : 
![image](https://user-images.githubusercontent.com/25101871/135193328-3b1b4b76-27f5-4bb2-bb70-369c2830fe26.png)

**Expected behavior**
Portainer should be accessible via portainer.xxxx.io, but it returns a 502 Bad Gateway error

**Operating System**
Ubuntu 20.04
Docker CE v20.10.8
docker-compose v.29.2

**Additional context**

I can `curl  http://portainer:9000` from the npm container

I don't know if it is from my side, or if the documentation doesn't give all information to make it work.
Anways, thank you again for your work !

**Comment by jc21** [comment]
If you can curl from the npm container then there must be some weirdness with nginx dns lookups or something.

That said, I'm using this method for my home network and haven't had any problems.

You haven't mentioned if you've ran `docker network create xxxxx` before bringing up the containers?

**Comment by maximeMD** [comment]
Hello @jc21 , thank you a lot for your quick answer 👍 

I ran `docker network create xxxxx` before, because docker-compose returns an error if you are trying to use an external volume which is not created yet !

I'll try to find a solution related to nginx dns lookups. If you have any more hint it would be awesome !
I won't close the issue atm, I would like to find a solution and maybe make a PR to improve the doc about this.

**Comment by maximeMD** [comment]
Ok that was unrelated to NPM ... i just messed up my DNS configuration when i was migrating my VPS...
Sorry for the time you spent, and thank you again for you work :)

**Comment by MallemIsmail** [comment]
> If you can curl from the npm container then there must be some weirdness with nginx dns lookups or something.
> 
> That said, I'm using this method for my home network and haven't had any problems.
> 
> You haven't mentioned if you've ran `docker network create xxxxx` before bringing up the containers?

I got the same exact setup as the OP but can't curl from the npm container it give me
> curl: (7) Failed to connect to 172.21.0.3 port 8787: Connection refused

What might be this problem? sorry for intrusion here.
