### ISSUE TITLE
entries in access_log not found in docker logs

### ISSUE THREAD

**Issue by niek1992** [jc21/nginx-proxy-manager#145]
**Checklist**
- **Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?**
yes i have.
- **Are you sure you're not using someone else's docker image?**
I've modified one of the ENV variables to match my timezone, but that shouldn't break logging. Currently it's the latest image pulled from DockerHub.

- **A clear and concise description of what the bug is.**
I'm trying to view the access_log and error_log in Docker Logs. but it only contains the messages about Lets Encrypt certificates and their renewal timers.

- **What version of Nginx Proxy Manager is reported on the login page?**
V2.0.13

**Expected behavior**
i'd espect to see the error.log and access.log of Nginx in order to see who/which have accessed my Nginx Proxy. If i navigate to the locations Nginx uses to store logs (/data/logs) i see several 
logfiles containing the information i need. 

**Operating System**
I'm running Docker on a Ubuntu 18.04 LTS VM on a ESXi hypervisor. 

**Additional context**
I've initially used the docker_compose.yaml file to setup the container. Today i've pulled the latest image, and configured the container from within Portainer UI. Same results.

**Comment by jc21** [comment]
> i'd espect to see the error.log and access.log of Nginx in order to see who/which have accessed my Nginx Proxy

Where do you *expect* them though? The title suggests you also expect them in the output of `docker logs`

You've said you've found them on disk already and they are in the location that the application is designed to use.

**Comment by niek1992** [comment]
Sorry, i should've been clearer. I've expected the output of both of those logs to be send to `docker logs` Since `stderr` and `stdout` gets picked up by that. But instead the logs get directed to /data/logs/error.log and access.log instead of /var/log/error.log and access.log that have a symlink to stderr and stdout. 

Is this by design? I would like to view the access and error logs in the `docker logs` instead of logging in via SSH and tailing the file manually.

**Comment by jc21** [comment]
Yes it's by design. I built this app for myself and I currently have 50 services running on one instance. I don't want to see all those access logs in my docker logs output, it's too much and irrelevant to the running of the docker container itself.

The separation also makes it easy to import the access logs in to an aggregator, such as logstash etc.

**Comment by niek1992** [comment]
Fair enough. I initially wanted to stay away from aggregrators to collect logs since i only have 6 containers running from which 2 are producing logs i'd like to read. I'll read up on a fitting one for me and how to implement it. Thanks anyway for replying to the issue i opened.
