### ISSUE TITLE
Slow Download Connection through Reverse Proxy

### ISSUE THREAD

**Issue by root9191** [jc21/nginx-proxy-manager#1453]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
I use the docker-compose File from this repo to start the Container. In my Local Network everything works fine and fast, but i am using a WikiJS and a Nextcloud Container too and made them public. If i want to download a Video for example, i only get about 200kb/s Download, the upload is a bit faster. In WikiJS i embedded a PDF with 20Mb and it takes about 3-5 Minutes to load this file. 

In the advanced Settings i have this Configuration:
```
add_header X-Frame-Options SAMEORIGIN;
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options  nosniff;
add_header Referrer-Policy "no-referrer-when-downgrade" always;
add_header Strict-Transport-Security "max-age=63072000" always;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;
location = /.well-known/carddav {  return 301 $scheme://$host/remote.php/dav; }
location = /.well-known/caldav {  return 301 $scheme://$host/remote.php/dav; }
location ^~ /.well-known { return 301 $scheme://$host/index.php$uri; }
```

**Nginx Proxy Manager Version**

2.9.9

**Operating System**
I am using a Raspberry Pi4 with 4GB of RAM and the new Debian Bullseye dietpi Image.
Everything is up to date (Docker, Docker-Compose, etc..)

Is anyone else having this issue or even found a solution for that?

**Comment by chaptergy** [comment]
Please see https://github.com/jc21/nginx-proxy-manager/issues/1180#issuecomment-863184299

**Comment by chaptergy** [comment]
Your Internet connection could also be the issue. If you are running this in your home network you most likely only have a consumer-grade internet connection. Which means the upload speeds are very significantly worse than your download speeds. And slow upload speeds from your home network to the www means slow download speeds when accessing it from the www. When the traffic stays inside your local network, there is no bottleneck of course.
