### ISSUE TITLE
Can't access configurations on Web UI

### ISSUE THREAD

**Issue by Neifab** [jc21/nginx-proxy-manager#1471]
Hello,

It's impossible to access the configuration menu when NPM is in web UI mode, only Proxys, Redirections etc... Tested on the last version, on iOS. 

Thanks

**Comment by chaptergy** [comment]
I really don't understand what you mean... What is the web UI mode? and what do you mean by configurations? How are they not accessible? Are you talking about issue https://github.com/jc21/nginx-proxy-manager/issues/702?

**Comment by Neifab** [comment]
Yes it is, sorry for the duplicate, didn't find it at first.
