### ISSUE TITLE
移动端页面选项缺失

### ISSUE THREAD

**Issue by wu202325** [jc21/nginx-proxy-manager#1475]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes / No
- Are you sure you're not using someone else's docker image?
  - Yes / No
- Have you searched for similar issues (both open and closed)?
  - Yes / No

**Describe the bug**

**Nginx Proxy Manager Version**

**To Reproduce**

**Expected behavior**
<!-- A clear and concise descr
**Operating System**
<!-- Please specify if using a Rpi, Mac, orchestration tool or any other setups that might affect the reproduction

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/702
