### ISSUE TITLE
Streams not working.

### ISSUE THREAD

**Issue by FreshImmuc** [jc21/nginx-proxy-manager#1506]
Hey, I tried to use streams with minecraft but it doesnt work.
![image](https://user-images.githubusercontent.com/65733898/138190372-4ee805f7-9c23-426b-a81a-e1cab21bf2d0.png)
What did I do wrong? it says online

**Comment by technoluc** [comment]
I'm trying to acces my RDP via Nginx Proxy Manager but i can't get it to work. I've forwarded 3389 to NPM via my router, added 3389:3389 as ports in the docker-compose.yml file and set up a stream incoming 3389 to ${PC_IP}:3389. Am i missing something?

**Comment by Kambaa** [comment]
Hello, like @chaptergy have mentioned, first i did add the ports, did a docker-compose down / up, and lastly, adding stream entries (with same ports for in and out, and added related computer local ip), i can access from outside successfully. Things to consider:

- From internet to your machine -> your router/firewall/modem should direct port to the machine that NPM is working
- Docker / docker-compose setup on adding port numbers as instructed
- and lastly, adding stream entries correctly( outside port, inside machine ip, inside port)

Have a good one!

**Comment by tbb98** [comment]
Hello!

I came across a comment on reddit saying that you have to expicitly specify UDP in the docker-compose file, if it's an UDP stream. In my case, that solved it.

Like this:
`- '34197:34197/udp' # Factorio`

**Comment by jin8111** [comment]
I have a new problem, after port forwarding, I can't use ssl, such as Synology's port 6690

**Comment by Aerialflame7125** [comment]
@jin8111 You would just use the proxy host feature within nginx proxy manager and not the streams for your case.
