### ISSUE TITLE
Issue with latest certbot implementation and previous certificates

### ISSUE THREAD

**Issue by pmorange** [jc21/nginx-proxy-manager#1525]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Since latest update (2.9.10), some previous certbot implementation has been broken :
'Namespace' object has no attribute 'dns_ovh_credentials'
Indeed, the field in the letsencrypt/renewal/npm-2.conf (in my case there is a "-2" suffix) has no prefix and is now called "credentials" instead of "dns_ovh_credentials".
A manual updates solves this issue.

**Nginx Proxy Manager Version**
2.9.10

**To Reproduce**
1. Have a previous certificate (I saw the problem with ovh) with a previous version of NPM.
The line in the certificate renewal should be something like : 
dns_ovh_credentials = /etc/letsencrypt/credentials/credentials-2
2. Update the version of NPM
3. Certbot renewal should fail with 'Namespace' object has no attribute 'dns_ovh_credentials'

**Expected behavior**
Correct certificate renewal.
If fields names in files have been modified, they should be upgraded when new NPM starts... Or a "Breaking warning" should be displayed on the release page.

**Operating System**
Linux alpine 5.10.61-0-lts #1-Alpine SMP Fri, 27 Aug 2021 05:29:55 +0000 x86_64 Linux
 Docker version 20.10.7, build f0df35096d5f5e6b559b42c7fde6c65a2909f7c5

**Comment by chaptergy** [comment]
The namespaces are deprecated in certbot for a while now and that's why they have been removed. It sounds like certbot is still on an old version in your container. Could you please run 
```
certbot --version
```
inside your container to seen what version you have installed?

**Comment by pmorange** [comment]
Hi,
If it has been deprecated a while it's weird I haven't had the problem before, because all my containers are automatically updated using watchtower... 
I have now updated and my certbot version inside the container is "certbot 1.20.0"
I close the issue, as I have manually updated my credentials file to remove the prefix : I just wanted to open it in case it could help anyone else.
Thanks.
