### ISSUE TITLE
How can i use fastcgi_pass

### ISSUE THREAD

**Issue by hermann1514** [jc21/nginx-proxy-manager#1543]
Hi,
i would like to use npm as Proxy for my Nextcloud FPM.
But, i can i configure fastcgi_pass in the ProxyManager?

Has someone running Nextcloud:FPM with Proxymanager?

Regards
Hermann

**Comment by chaptergy** [comment]
Unfortunately npm is not intended to be used that way currently. But the `proxy_pass` used when you create a normal proxy host should work just fine.

**Comment by hermann1514** [comment]
I think the fastcgi_Pass option has to become law here. Or does proxy_pass also work with FPM?

**Comment by hermann1514** [comment]
Is there a documentation how i can use advanced configuration?
Is it possible to add this Parameter to the conf File manualy?

**Comment by chaptergy** [comment]
Is it? Isn't `fastcgi_pass` meant if you want to forward within the same host? I'm pretty sure `proxy_pass` should also work, just go ahead and try it.  

Using the advanced config you can't remove things which are generated by npm, and the `proxy_pass` directive is always automatically included. You _could_ manually edit the `.conf` file within the container manually found at `/data/nginx/proxy_host/x.conf` (`x` being the id of the proxy host, found when clicking on the three dots next to the proxy host inside the admin ui). There you could replace `proxy_pass` with `fastcgi_pass` and restart the container. But as soon as you edit the proxy host and save again, the config will be overwritten.

**Comment by hermann1514** [comment]
Hmm ... proxy_pass doesn't work for me. Or I'm doing something wrong.

I have created a new proxy host with the IP from the NC FPM IMage. Unfortunately no access to it.

**Comment by chaptergy** [comment]
Unfortunately then the only way is to manually edit the `.conf` files inside the container. You would have to wait for feature request https://github.com/jc21/nginx-proxy-manager/issues/65 otherwise, but I don't think it is going to happen in v2.

**Comment by geekyayush** [comment]
Is there any way we could do this?

Sorry for commenting on this old issue, but I really need to use "fastcgi_pass" for my Wordpress site using php-fpm.
Normal Wordpress setup without php-fpm and with just PHP works fine. But when I use Wordpress php-fpm version, I get 502 error when visiting my domain.

I would really appreciate if someone could tell me a way to use "fastcgi_pass" instead of proxy_pass

**Comment by Hadatko** [comment]
Hello, just joining this thread. I would like to see this feature too. Advantage is that i don't need to download containers with apache version of solution but with fastcgi. Why to have many servers when it can be solved with one ;)

**Comment by tr1p0p** [comment]
Yeah... why a app made for "making nginx easy" doesn't... make thing easy for nginx ?

I really don't understand. Why it's SO HARD to just.. add some config to nginx config on domains ? Are we not free ?
