### ISSUE TITLE
Forwarding hosts/headers for the apps that needs it / Met with Openresty

### ISSUE THREAD

**Issue by Horuyuki** [jc21/nginx-proxy-manager#1556]
Some apps like qbittorrent-nox and airdcpp needs the header being forwarded:
https://github.com/qbittorrent/qBittorrent/wiki/NGINX-Reverse-Proxy-for-Web-UI
https://github.com/airdcpp-web/airdcpp-webclient/wiki/nginx-proxy-configuration

But I cannot for my life figure out how to add the:
```
    proxy_set_header   Host               127.0.0.1:30000;
    proxy_set_header   X-Forwarded-Host   $http_host;
    proxy_set_header   X-Forwarded-For    $remote_addr;
    proxy_cookie_path  /                  "/; Secure";
```
and:
```
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
```
to the nginx proxy config.

Directly adding them to the Advanced section of proxy host does not work, as in the UI is still unable to connect to its app backend as some they have some sort of a header verification.

I looked at other issues opened and still could not figure out a way to forward these things, can you let me know what I need to do?

Apologize for incorrect terminology as I am an amateur.

EDIT:
I did insert them into the appropriate location block and restarted the container without changing the web UI, but it did not work for qbit. Also tried to use this:
```
  add_header       X-Served-By $host;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Scheme $scheme;
  proxy_set_header X-Forwarded-Proto  $scheme;
  proxy_set_header X-Forwarded-For    $remote_addr;
  proxy_pass https://$server:$port;
```

EDIT2:
I am brought to a page called Openresty for some reason.
Caused by having the:
```
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
```
In both the location block and server block.

**Comment by chaptergy** [comment]
```nginx
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
``` 
is automatically added if you enable websockets support, so you won't need to add it manually.  
The following headers are also automatically set for proxies:

```nginx
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $remote_addr;
proxy_set_header X-Real-IP          $remote_addr;
```

So the only two things you would have to add through the advanced config are

```nginx
proxy_set_header   X-Forwarded-Host   $http_host;
proxy_cookie_path  /                  "/; Secure";
```

**Comment by Horuyuki** [comment]
> 
> 
> ```nginx
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> ```
> 
> is automatically added if you enable websockets support, so you won't need to add it manually. The following headers are also automatically set for proxies:
> 
> ```nginx
> proxy_set_header Host $host;
> proxy_set_header X-Forwarded-Scheme $scheme;
> proxy_set_header X-Forwarded-Proto  $scheme;
> proxy_set_header X-Forwarded-For    $remote_addr;
> proxy_set_header X-Real-IP          $remote_addr;
> ```
> 
> So the only two things you would have to add through the advanced config are
> 
> ```nginx
> proxy_set_header   X-Forwarded-Host   $http_host;
> proxy_cookie_path  /                  "/; Secure";
> ```
> 
> But due to a "feature" in nginx, once just one header is set in the location block, a header from the server block is no longer inherited. And the location block has headers generated by npm, so this is always the case. So if you want to add more headers, you will need to create a custom location `/` with the same target data as the normal host and add the header in the advanced config there.

Thank you for the detail, and indeed turning on the web socket made my apps work.
I am not sure if I want to add the cookie anymore as I might as well just log in every time.

I had no idea what web sockets are, it is very nice that you pointed out to me that button equates to those lines. It is most definitely critical information for noobs.

**Comment by GamerClassN7** [comment]
> ```nginx
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> ```
> 
> is automatically added if you enable websockets support, so you won't need to add it manually. The following headers are also automatically set for proxies:
> 
> ```nginx
> proxy_set_header Host $host;
> proxy_set_header X-Forwarded-Scheme $scheme;
> proxy_set_header X-Forwarded-Proto  $scheme;
> proxy_set_header X-Forwarded-For    $remote_addr;
> proxy_set_header X-Real-IP          $remote_addr;
> ```
> 
> So the only two things you would have to add through the advanced config are
> 
> ```nginx
> proxy_set_header   X-Forwarded-Host   $http_host;
> proxy_cookie_path  /                  "/; Secure";
> ```
> 
> But due to a "feature" in nginx, once just one header is set in the location block, a header from the server block is no longer inherited. And the location block has headers generated by npm, so this is always the case. So if you want to add more headers, you will need to create a custom location `/` with the same target data as the normal host and add the header in the advanced config there.

Hello,

lately I needed to utilize the following header  
`proxy_set_header X-Real-IP          $remote_addr;`

but for some reason my when I try to do the request I see only this nginx header
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/22167469/b2b873df-dd71-4bec-9741-3d19b5d85c97)

could you give me some inside what could be wrong, I even reinstalled nginx with same outcome

Could anyone verify that this header is working for him ?
