### ISSUE TITLE
Forward to a subfolder in the proxy host settings instead of just a port

### ISSUE THREAD

**Issue by Horuyuki** [jc21/nginx-proxy-manager#1563]
**Is your feature request related to a problem? Please describe.**
Some apps like guacamole by apache resides in example.com/guacamole
And in the bare metal nginx server I had before using this I did set it to forward to `127.0.0.1:8080/guacamole` instead.

**Describe the solution you'd like**
Maybe a option to enter in a custom forwarding address without the http/https, ip, and port selections?

**Describe alternatives you've considered**
Editing the config manually, it does not stay there once the proxy host is edited from the GUI end. (Unless I am mistaken.)

**Comment by chaptergy** [comment]
I don't really understand, why can't you use a custom location? Set the location `/` with scheme `http`, forward host `127.0.0.1/guacamole` and port `8080`?

**Comment by Horuyuki** [comment]
> I don't really understand, why can't you use a custom location? Set the location `/` with scheme `http`, forward host `127.0.0.1/guacamole` and port `8080`?

I did set a custom location / with forwarding to IP/guacamole, but it did not work. I was simply directed to :8080 in which tomcat was running on, no guacamole until I typed in /guacamole

Back in bare metal nginx I just used this, proxy forward http:IP:8080/guacamole with server name http://guac.example.com

And upon visiting it without a sub directory would get me to /guacamole, what do you think I could do on the GUI end to make this happen except editing the file it self?

**Comment by chaptergy** [comment]
Could you please provide the code snippet you used before on the baremetal nginx?

**Comment by Horuyuki** [comment]
> Could you please provide the code snippet you used before on the baremetal nginx?

Of course, this is it:
```
server {
    listen 80;
    listen [::]:80;
    server_name guac.example.com;

    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name guac.example.com;

    include /etc/nginx/ssl.conf;

    location / {
    proxy_pass http://127.0.0.1:8080/guacamole/;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    access_log off;
    }
}
```

**Comment by chaptergy** [comment]
That's pretty much what should be generated when adding the cusom location. It could be the missing trailing slash after `127.0.0.1/guacamole`? Try it with another slash added at the end.

**Comment by Horuyuki** [comment]
> That's pretty much what should be generated when adding the cusom location. It could be the missing trailing slash after `127.0.0.1/guacamole`? Try it with another slash added at the end.

I see what you mean, but instead now I am just redirected to a blank page. Without even the tomcat successful message.
https://i.imgur.com/RBTnRIU.png

**Comment by chaptergy** [comment]
Are you talking about `$request_uri`? That's because when using a variable in `proxy_pass` nginx no longer automatically appends the path to the url, but expects the entire url. So if it was not there, requesting `/foo` or anything else would always be redirected to just `http://172.17.0.1:8080/guacamole` instead of `http://172.17.0.1:8080/guacamole/foo`.

Are you on v2.9.11?
It most likely has to do something with the `$request_uri` being basically empty, so just a slash. Please go ahead and manually edit the config inside the container and replace this line:

```nginx
set              $upstream http://172.17.0.1:8080/guacamole$request_uri;
```
with these lines
```nginx
set              $upstream {{ forward_scheme }}://{{ forward_host }}:{{ forward_port }}{{ forward_path }};
if ($request_uri != /){
  set            $upstream $upstream$request_uri;
}
```

**Comment by Horuyuki** [comment]
> Are you talking about `$request_uri`? That's because when using a variable in `proxy_pass` nginx no longer automatically appends the path to the url, but expects the entire url. So if it was not there, requesting `/foo` or anything else would always be redirected to just `http://172.17.0.1:8080/guacamole` instead of `http://172.17.0.1:8080/guacamole/foo`.
> 
> Are you on v2.9.11? It most likely has to do something with the `$request_uri` being basically empty, so just a slash. Please go ahead and manually edit the config inside the container and replace this line:
> 
> ```nginx
> set              $upstream http://172.17.0.1:8080/guacamole$request_uri;
> ```
> 
> with these lines
> 
> ```nginx
> set              $upstream {{ forward_scheme }}://{{ forward_host }}:{{ forward_port }}{{ forward_path }};
> if ($request_uri != /){
>   set            $upstream $upstream$request_uri;
> }
> ```

Yes I am using the docker image version 
`2.9.11`

Does that mean I should pull and update it so I don't have to manually edit?

**Comment by Horuyuki** [comment]
Any ways, for whatever reason adding the custom location just does not work with guacamole client.
And after the update, I saw you used some fancy format for forwarding the proxy host, and I can no longer set the proxy pass as I used to.
I will just bookmark it with the sub directory instead.

**Comment by tdp4** [comment]
I was able to do this in v2.10.4 with a custom location of `/` -> hostname/guacamole/ on port 8080
