### ISSUE TITLE
Have you thought about HAproxy

### ISSUE THREAD

**Issue by jonny190** [jc21/nginx-proxy-manager#157]
**Is your feature request related to a problem? Please describe.**
Using this in front of an exchange server and authentication is an issue due to lack of NTLM support

**Describe the solution you'd like**
I'd live to see a for or option to use HAproxy engine

**Describe alternatives you've considered**
N/A

**Additional context**
Love this as its been setup for coming up 6 months with no issues

**Comment by jc21** [comment]
Auth request related to #159 

As for haproxy, is it that you just require load balancing that's already built in to nginx?

**Comment by chaptergy** [comment]
Closing this as a wontfix with a reference to https://github.com/jc21/nginx-proxy-manager/issues/156
