### ISSUE TITLE
"Source Sans Pro" Broken

### ISSUE THREAD

**Issue by root0091** [jc21/nginx-proxy-manager#1573]
"Source Sans Pro" fonts location broken on latest docker pull, defaults to otherwise.

**Comment by chaptergy** [comment]
In what way is it broken? What error is returned when you try to access e.g. `<admin-ui-domain>/assets/source-sans-pro-v14-latin-ext_latin-regular.woff`? Are you sure it's not just your browser or a browser extension blocking remote fonts?

**Comment by root0091** [comment]
Disregard.
