### ISSUE TITLE
Specific Location is working, General Location is giving 404 for same URI

### ISSUE THREAD

**Issue by zane-shus** [jc21/nginx-proxy-manager#1580]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
I have created a working Host.  When I added a very specific location (down to the PHP page level e.g. /subfolder/page.php ) for a sub URI to go to a different backend container I am able to get locations to work, but when I create a generic location (at the  /subfolder/ level), it is not able to work.  As I am only making a small change, I am assuming its a bug.

**Nginx Proxy Manager Version**

**To Reproduce**
1. Create two backends, and get NPM to point to the first.
2. Create a location in the host
3. 
![image](https://user-images.githubusercontent.com/50510607/141174328-169b461e-ebbe-4dcc-9b3f-7a9b64d84b28.png)
4. Hit your site.com/othercontainer/test.php and it works
5. Then, Change the location to be generic
6. 
![image](https://user-images.githubusercontent.com/50510607/141174479-249b4a2c-94e7-47dc-a4e6-8449abc1b1fe.png)
7. Now I can no longer get to site.com/othercontainer/test.php
8. I am getting a 404 Not Found which I believe is coming from site.com

**Expected behavior**
I would have expected them to hit the same content

**Screenshots**
As attached in description

**Operating System**
Using NPM within Portainer on Docker Swarm, on CentOS hosts.  All are latest versions.

**Additional context**
None

**Comment by chaptergy** [comment]
Unfortunately locations have been a little broken for a few versions, unfortunately all attempts to mitigate the problem have resulted in other issues. https://github.com/jc21/nginx-proxy-manager/pull/1578 reverted all the changes related to that hopefully resulting in locations working properly again. But you'll have to wait until a new release is published.

**Comment by zane-shus** [comment]
> 
> 
> Unfortunately locations have been a little broken for a few versions, unfortunately all attempts to mitigate the problem have resulted in other issues. #1578 reverted all the changes related to that hopefully resulting in locations working properly again. But you'll have to wait until a new release is published.

thanks for this.  Would it be possible to manually do it in this area instead?
![image](https://user-images.githubusercontent.com/50510607/141181420-019a5386-f434-4265-acda-ec7df80d1ff3.png)

(I come from HAProxy, this is my first dip into NGINX, so a little green)

**Comment by chaptergy** [comment]
Yes you can, by adding something like this:

```nginx
location /app/ {
    proxy_pass      http://othercontainer/;
}
```

**Comment by zane-shus** [comment]
> ```nginx
> location /app/ {
>     proxy_pass      http://othercontainer/;
> }
> ```

your a champion, thank you!  Worked perfect.

**Comment by chaptergy** [comment]
Great to hear! Then I'll close this for now. Be on the lookout for new releases, so you could potentially change back to the built in locations. Or leave it in the advanced config. Your choice ;)
