### ISSUE TITLE
Remove port from url (Help)

### ISSUE THREAD

**Issue by keremcankabadayi** [jc21/nginx-proxy-manager#1581]
Hi there, I'm sure, this is really piece of cake to most of you but i have an issue. 

I added two A records to my domain provider.
![image](https://user-images.githubusercontent.com/23381187/141186813-9984caa8-0fdc-4689-91f1-b0cec6e31483.png)

nginx.monolityapi.com is perfectly fine.

I want my main page is `myIp:8080`. Because my wordpress app is working on `8080`.

I configured like this

![image](https://user-images.githubusercontent.com/23381187/141187035-ebc5bb93-17f4-4e12-b0f3-45889496f537.png)

When i try to open `monolityapi.com`, it redirects to `http://monolityapi.com:8080/`

How can i configure `monolityapi.com` to `monolityapi.com` without port?

What am i missing here, any help?

**Comment by chaptergy** [comment]
WordPress likes to hard-code lots of stuff, so Wordpress is redirecting you. Got to _General_ > _Settings_ in Wordpress and change both _Wordpress Address_ and _Site Address_ to `https://monolityapi.com` (or `http://monolityapi.com` if you don't have SSL which I hope is not the case)

**Comment by keremcankabadayi** [comment]
you the real mvp! thanks.
