### ISSUE TITLE
Invalid DNSpod credentials template

### ISSUE THREAD

**Issue by yangjinhe** [jc21/nginx-proxy-manager#1599]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Now nginxproxymanager provides two parameters for DNSPod, dns_dnspod_email and dns_dnspod_api_token,
In fact, DNSPod also requires a parameter, the name is called ID, if not provided, it will prompt the following information:

[DNSPOD] Record.Create error: The login token ID is invalid
[DNSPOD] Record.List error: The login token ID is invalid
Error communicating with the DNSPOD API: The login token ID is invalid

**Nginx Proxy Manager Version**
v2.9.12

**To Reproduce**
1. Go to 'SSL Certificates'
2. Click on 'Add Let's Encrypt Certificate'
3. Scroll down to 'Use a DNS Challenge'
4. DNS Provider change to 'DNSPod'
5. modify 'Credentials File Content' ,replace dns_dnspod_email to my email, replace dns_dnspod_api_token to my token
6. Click Save.
7. See error

**Comment by sunjx97** [comment]
I found something that may be helpful to you. Here is the url: [https://www.jianshu.com/p/659dc904967f]
It said that you should write both id and key there.
> certbot_dns_dnspod:dns_dnspod_api_token = "id,key"

**Comment by chaptergy** [comment]
I don't understand much whats on that website. I've also found [an issue with the challenge plugin](https://github.com/SkyLothar/certbot-dns-dnspod/issues/2) showing exactly what this issue describes, but the author closed it, presumably because they misunderstood something? If any of you can tell me how it is correct and how it works without issues let me know. I will replace the template with your suggestion then.

**Comment by sunjx97** [comment]
As I mentioned above, maybe you just need to write both id and its token there (English half-comma separated).
For example, suppose **its id is 123456** and **its token is abcdefgfedcba**, what you should do is to write like this:
dns_dnspod_email = "name@example.com"
dns_dnspod_api_token = "**123456,abcdefgfedcba**"
