### ISSUE TITLE
can't change Strict-Transport-Security header value

### ISSUE THREAD

**Issue by fahadshery** [jc21/nginx-proxy-manager#1601]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
can't change the value of `Strict-Transport-Security` header using the `_hsts.conf` file.

**Nginx Proxy Manager Version**
latest docker version

My `_hsts.conf` file:
```
{% if certificate and certificate_id > 0 -%}
{% if ssl_forced == 1 or ssl_forced == true %}
{% if hsts_enabled == 1 or hsts_enabled == true %}
  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=15552000;{% if hsts_subdomains == 1 or hsts_subdomains == true -%} includeSubDomains;{% endif %} preload" always;
  add_header Referrer-Policy strict-origin-when-cross-origin;
  add_header X-Content-Type-Options nosniff;
  add_header Content-Security-Policy upgrade-insecure-requests;
  add_header Permissions-Policy interest-cohort=();
  add_header Expect-CT 'enforce; max-age=604800';
  more_set_headers 'Server: Proxy';
  more_clear_headers 'X-Powered-By';
{% endif %}
{% endif %}
{% endif %}
```

but I see the following `headers`:

<img width="474" alt="Screenshot 2021-11-20 at 09 01 40" src="https://user-images.githubusercontent.com/7301267/142727799-ac74296a-7680-4fea-bbf2-61811d239d34.png">

Clearly, the following `headers` are being set elsewhere:
```
Referrer-Policy
X-Content-Type-Options
Strict-Transport-Security
```

I can't seem to change the value of `Strict-Transport-Security` whereas others work fine (that's why you see `duplicates`). I think its being `overridden` elsewhere? 
Could someone point to me where I could change the `Strict-Transport-Security` so that my set value takes precedence over the default `max-age=0`?

**Comment by fahadshery** [comment]
I found the issue!
The culprit was `cloudflare`!!! Cloudflare was adding its own headers overwriting mine!
I have setup the `Strict-Transport-Security` settings in the `cloudflare` account TLS settings

**Comment by R0GGER** [comment]
@fahadshery Not a bug... 
Source `_hsts.conf` file: https://gist.github.com/R0GGER/916183fca41f02df1471a6f455e5869

**Comment by rapjul** [comment]
> I found the issue!
> The culprit was `cloudflare`!!! Cloudflare was adding its own headers overwriting mine!
> I have setup the `Strict-Transport-Security` settings in the `cloudflare` account TLS settings

If anybody else needs helps founding where to do this:

1. Go to [Cloudflare](https://dash.cloudflare.com)
2. Click on your domain
3. Click on **SSL/TLS** in the sidebar, then click on **Edge Certificates**.

Turn on all the options in HTTP Strict Transport Security (HSTS) to get a better rating.
So far I've increased the rating from "D" to "B".
