### ISSUE TITLE
redirect 301 or 302

### ISSUE THREAD

**Issue by geelenbert** [jc21/nginx-proxy-manager#161]
I would like to be able to setup temporary and  permanent redirects.

Currently my nginx config for such a redirect looks like this:
```
 server {
        listen 80;
        listen [::]:80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name upload.domain.com;

        #redirect using 302 temp redirect. 301 is permanent redirect
        return 302 https://cloud.domain.com/s/IUOBu67byubU#;
}
```

I would like to be  able to configure such a redirect.

I'm not sure this is possible at the moment

**Comment by duchenpaul** [comment]
Is it possible to config 302 instead of 301 redirect?

**Comment by chaptergy** [comment]
Yes, the redirection host now allows you to specify which http response will be served.
![image](https://user-images.githubusercontent.com/26956711/117732693-db4cd100-b1df-11eb-8065-022a6651453e.png)

**Comment by duchenpaul** [comment]
@chaptergy  I would like to set `Default Site` to have a 302 or 307 redirect, because sometime I could make mistakes on setting, I dont want to cache the 404 page, do we have this setting?
