### ISSUE TITLE
Request namecheap.com as DNS challenge support

### ISSUE THREAD

**Issue by FormBurden** [jc21/nginx-proxy-manager#1611]
**What provider would you like to see added to NPM?**

Namecheap / Namecheap.com

**Have you checked if a certbot plugin exists?**

While I tried finding a certbot plugin for Namecheap, all I could find is from this Github: [Github](https://github.com/schubc/certbot_dns_namecheap) and sadly several years old, not sure if that matters. BUT, the ACME Client on Opnsense does support the Namecheap API, and it indeed works, since I use it there. [The ACME Client Namecheap API](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_namecheap.sh) So I would assume that the same could be issued here for support for the DNS API Challenge? 

Anyway, hope it can happen.

**Comment by chaptergy** [comment]
Unfortunately we'll have to wait until the plugin is published on [PyPi](https://pypi.org/) before we can add it. It needs to be installable via `pip`.

**Comment by FormBurden** [comment]
Ah I see. No worries, thanks for the info!
