### ISSUE TITLE
stop writing default_host.log

### ISSUE THREAD

**Issue by Nuke142** [jc21/nginx-proxy-manager#1636]
How can i disable constant writing to this file?
![image](https://user-images.githubusercontent.com/19406558/145034419-44293356-dade-4280-b4e0-45cfa4b9f440.png)

**Comment by freender** [comment]
Technically default-host.log can be disabled in /nginx_proxy_manager/data/nginx/default_host/site.conf 
You can comment access_log line and reload nginx proxy manager

HOWEVER I strongly discourage doing this:
1) You should understand that the point of the default-host.log is to store all access logs for default endpoint. This is exactly what NGINX does
2) The best way to handle that would be:
a) Logging default-host.log and checking it periodically
b) Blocking connection attempts from parasite IP address / Subnet / Country. The second option cannot be implemented by NPM out of the box.

**Comment by Nuke142** [comment]
thank you. solved via router firewall
