### ISSUE TITLE
NPM as DNS for pointed base domain

### ISSUE THREAD

**Issue by itsKV** [jc21/nginx-proxy-manager#1642]
I have pointed domain name _sub.domain.com_ to NPM as base domain name. But while defining multiple services built on same base domain name, e.g _service1.sub.domain.com, service2.sub.domain.com, blog.sub.domain.com, mysql.sub.domain.com, api.sub.domain.com_ I have to explicitly modify my DNS record every time time for each service as I am using external nameServer, say Cloudflare for the DNS management. 

Is there any way so that we only have to point base domain sub.domain.com and rest of the service domains will be taken care by NPM itself at the time of defining proxy hosts on NPM dashboard????

As stated in above description, I would like to keep third party dns proxy like Cloudflare ahead of _sub.domain.com_ for security reason. 

btw, thank you for the awesome project @jc21. 👍  #love

**Comment by chaptergy** [comment]
Just create a [wildcard dns record](https://en.wikipedia.org/wiki/Wildcard_DNS_record) for `*.sub.domain.com` and all subdomains of `sub.domain.com` will be sent to NPM.
