### ISSUE TITLE
Strange Redirection issue on one network

### ISSUE THREAD

**Issue by Veeau** [jc21/nginx-proxy-manager#166]
I have one strange redirection issue and it may be specific to the network I am on.

Current setup:
Proxy host - sub.domain.com > 192.168.1.249:8080

4g/other networks
Redirects to the guacamole correctly.

Work network
sub.domain.com > 192.168.1.249 on 80/443 depending if https used. and hits a broken page of the docker container on 80 or 443.

Replicated on IOS, Chrome, IE so I think it may be this network.

Edit:

Added a second host:
plex.domain2.com > 192.168.1.254:32400

when testing on work network same as above.

sub.domain.com > 192.168.1.249 on 80/443 depending if https used. and hits a broken page of the docker container on 80 or 443.
Long shot but any suggestions?

**Comment by jc21** [comment]
So you're saying that you're trying to access `sub.domain.com:80/443` and it is configured to send upstream to `192.168.1.249:8080` ?

> sub.domain.com > 192.168.1.249 on 80/443 depending if https used
is that also sending upstream to `8080`?

Personally, I don't have any issues connecting to NPM hosts either via http or https, with or without Squid proxy, Socks proxy or via a VPN. As long as the FQDN is part of public DNS you should be fine.

For some verbosity, you can look at the logs in your data mount and see if the hits are coming through the proxy host (proxy_host-*.log) or the default host (default.log)

**Comment by chaptergy** [comment]
Closing this, since there weren't any updates provided
