### ISSUE TITLE
DNS challenge provider request ---- tencentcloud

### ISSUE THREAD

**Issue by sirliu** [jc21/nginx-proxy-manager#1662]
**What provider would you like to see added to NPM?**

```
tencentcloud(another name is dnspod.cn)
They both  belong to the same company.
```
**Have you checked if a certbot plugin exists?**
YES! here is the url of the certbot:
```
https://pypi.org/project/certbot-dns-tencentcloud/
```

**Comment by chaptergy** [comment]
So this is something different than the existing [DNSPod plugin](https://pypi.org/project/certbot-dns-dnspod/)? Or would this replace the dns pod plugin?

**Comment by sirliu** [comment]
> So this is something different than the existing [DNSPod plugin](https://pypi.org/project/certbot-dns-dnspod/)? Or would this replace the dns pod plugin?

yes，it is different than the exist DNSPod plugin，I think would not replace it。
