### ISSUE TITLE
Login gives a 502 response

### ISSUE THREAD

**Issue by acederberg** [jc21/nginx-proxy-manager#1669]
**Nginx Proxy Manager Version**
2.9.12

**To Reproduce**
It just happened after continuous operation without error, I have no idea.

**Expected behavior**
Request should have a response with a status code less than 500.

**Operating System**
Ubuntu server 20.04.

**Additional context**

I used ansible to bring up NPM and its database in a docker container for a while and configured everything through the web GUI. 

Today I needed to modify some configuration, entered my credentials, and the GUI did nothing. I looked in the developer console and there was a 502 status_code from a resquest made to an api route. 

I have backups of my configuration but the error persists when I use a backup of the databases data. I have not tried using my letsencrypt backup. I am currently triaging by reconfiguring NPM and can reload my backups to get screenshots etc if needed. Sorry for the rushed post I am low on time, I will come back and give any additional information requested in a few hours.

I do not get the error when I start with a new volume for the database container.

I tried : 

- Restarting containers.
- Destroying and rebuilding containers.
- Using backed up volumes.

I should have tried :

- attaching to the containers to see if anything pertaining to the error was logged.

Ansible-tasks : 

~~~yaml
- name : "DOCKER: Add Nginx Proxy Manager Database"
  tags : [ deploy, docker-container, app-runner ]
  community.docker.docker_container :
    # More info: https://github.com/jc21/docker-mariadb-aria
    name : '{{npm_db}}'
    image : jc21/mariadb-aria:latest
    env :
      MYSQL_ROOT_PASSWORD : '{{npm_db_root_password}}'
      MYSQL_DATABASE : 'npm'
      MYSQL_USER : '{{npm_db_username}}'
      MYSQL_PASSWORD : '{{npm_db_password}}'
    networks :
      - name  : back
    volumes :
      - ./app/data/mysql:/var/lib/mysql


- name : "DOCKER: Add Nginx Proxy Manager."
  tags : [ deploy, docker-container, app-runner ]
  community.docker.docker_container :
    image: 'jc21/nginx-proxy-manager:latest'
    name : NPM
    ports :
      - '80:80'
      - '81:81'
      - '443:443'
    env :
      DB_MYSQL_HOST : '{{npm_db}}'
      DB_MYSQL_PORT : '3306'
      DB_MYSQL_USER : '{{npm_db_username}}'
      DB_MYSQL_PASSWORD : '{{npm_db_password}}'
      DB_MYSQL_NAME : 'npm'
    networks :
      - name : back
      - name : front
    volumes :
      - ./app/data:/data
      - ./app/letsencrypt:/etc/letsencrypt
~~~

Browser : brave

**Comment by piciuok** [comment]
same, getting 502 too (Bad gateway)

**Comment by piciuok** [comment]
in logs i have got: 
`
[12/22/2021] [8:25:45 PM] [Migrate  ] › ℹ  info      Current database version: 20211108145214
[12/22/2021] [8:27:12 PM] [Global   ] › ✖  error     Command failed: pip install certbot-dns-cloudflare cloudflare
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fed6dd39208>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fed6dd39470>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fed6dd395c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fed6dd39710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fed6dd39860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
ERROR: Could not find a version that satisfies the requirement certbot-dns-cloudflare (from versions: none)
ERROR: No matching distribution found for certbot-dns-cloudflare

[12/22/2021] [8:27:13 PM] [Global   ] › ℹ  info      Manual db configuration already exists, skipping config creation from environment variables
[12/22/2021] [8:27:13 PM] [Migrate  ] › ℹ  info      Current database version: 20211108145214
[12/22/2021] [8:28:32 PM] [Global   ] › ✖  error     Command failed: pip install certbot-dns-cloudflare cloudflare
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f53c7b8b240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f53c7b8b4e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f53c7b8b630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f53c7b8b780>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f53c7b8b8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
ERROR: Could not find a version that satisfies the requirement certbot-dns-cloudflare (from versions: none)
ERROR: No matching distribution found for certbot-dns-cloudflare
`

**Comment by chaptergy** [comment]
A 502 when trying to log in usually means that the database is not available or in the worst case corrupted. You could take a look inside the database tables to see if everything looks fine in there (To connect to the database see https://github.com/jc21/nginx-proxy-manager/discussions/1529).

**Comment by acederberg** [comment]
@piciuok Thanks for contributing! Your problem looks like a DNS problem, I don't think our problems share the same origin. The logs that I got from reproducing the issue indicate that something goes awry with sql:

~~~stdout
app-npm-1  | [12/23/2021] [5:09:09 PM] [Global   ] › ✖  error     connect ECONNREFUSED 192.168.160.2:3306
app-npm-1  | [12/23/2021] [5:09:10 PM] [Global   ] › ✖  error     connect ECONNREFUSED 192.168.160.2:3306
app-db-1   | 2021-12-23 17:09:10 0 [ERROR] mysqld: Got error 'Could not get an exclusive lock; file is probably in use by another process' when trying to use aria control file '/var/lib/mysql/aria_log_control'
app-db-1   | 2021-12-23 17:09:10 0 [ERROR] Plugin 'Aria' init function returned error.
app-db-1   | 2021-12-23 17:09:10 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
app-db-1   | 2021-12-23 17:09:10 0 [Note] Plugin 'InnoDB' is disabled.
app-db-1   | 2021-12-23 17:09:10 0 [Note] Plugin 'FEEDBACK' is disabled.
app-db-1   | 2021-12-23 17:09:10 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
app-db-1   | 2021-12-23 17:09:10 0 [ERROR] Failed to initialize plugins.
app-db-1   | 2021-12-23 17:09:10 0 [ERROR] Aborting
app-db-1 exited with code 1
app-npm-1  | [12/23/2021] [5:09:21 PM] [Global   ] › ✖  error     getaddrinfo EAI_AGAIN db
app-npm-1  | [12/23/2021] [5:09:32 PM] [Global   ] › ✖  error     connect ETIMEDOUT
~~~

It looks like something is causing the database to crash. Here is the docker compose I used to reproduce the error with my volume:

~~~yaml
version : '3.7'
services :
  db :
    image : jc21/mariadb-aria:latest
    container_name : 'db'
    environment :
      MYSQL_ROOT_PASSWORD : 'insecure_root_password'
      MYSQL_DATABASE : 'npm'
      MYSQL_USER : 'nginx_proxy_manager'
      MYSQL_PASSWORD : 'insecure_password'
    networks :
      - back
    volumes :
      - ./data/mysql:/var/lib/mysql

  npm :
    image: 'jc21/nginx-proxy-manager:latest'
    container_name : 'npm'
    ports :
      - '80:80'
      - '81:81'
      - '433:443'
    depends_on :
      - 'db'
    environment :
      DB_MYSQL_HOST : 'db'
      DB_MYSQL_PORT : '3306'
      DB_MYSQL_USER : 'nginx_proxy_manager'
      DB_MYSQL_PASSWORD : 'insecure_password'
      DB_MYSQL_NAME : 'npm'
    networks :
      - back
      - front
    volumes :
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks :
  front :
    attachable : true
    driver : bridge
  back :
    attachable : true
    driver : bridge
~~~

For whatever reason this and the recommended docker compose *( in the [documentation](https://nginxproxymanager.com/setup/#using-mysql-mariadb-database) )* gives the following with fresh volumes:

~~~stdout
app-app-1  | [12/23/2021] [5:36:47 PM] [Global   ] › ℹ  info      Generating MySQL knex configuration from environment variables
app-app-1  | [12/23/2021] [5:36:47 PM] [Global   ] › ⬤  debug     Wrote db configuration to config file: ./config/production.json
app-db-1   | 2021-12-23 17:36:48 3 [Warning] Access denied for user 'npm'@'< ip add >' (using password: YES)
app-app-1  | [12/23/2021] [5:36:48 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'< ip addr >' (using password: YES)
app-db-1   | 2021-12-23 17:36:49 4 [Warning] Access denied for user 'npm'@'< ip addr >' (using password: YES)
app-app-1  | [12/23/2021] [5:36:49 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'< ip addr >' (using password: YES)
~~~

Odds are that there is something very in my configuration from the results I have, I'll give it another swing soon. I did this in WSL but will try on a new VM instead.

**Comment by acederberg** [comment]
@chaptergy I was wondering about just using sqlite instead as it reduced the number of containers and degree of networking. I think perhaps the first of the above logs might indicate corruption, but I am not too knowledgeable about mariadb so this is just speculation. Would you recommend just using sqlite instead?

**Comment by chaptergy** [comment]
@acederberg we have switched from recommending MySQL by default to having SQLite by default, so from our perspective it seems advantageous. If you want to switch, have a look at https://github.com/jc21/nginx-proxy-manager/discussions/1529#migrate-mariadb-to-sqlite-dbeaver

**Comment by acederberg** [comment]
Thank you @chaptergy.

**Comment by LonYui** [comment]
i encounter sameissue

mariadb  jc21/mariadb-aria:10.14
nginx-proxy-manager jc21/nginx-proxy-manager:2.9
