### ISSUE TITLE
error default site

### ISSUE THREAD

**Issue by imsoftware-id** [jc21/nginx-proxy-manager#1670]
Error when save Default Site configuration

![nginx-eror](https://user-images.githubusercontent.com/20951246/147126226-7418ddf7-669e-47e5-990f-ae1e9897194b.jpg)

**Comment by the1ts** [comment]
I'm able to complete that default site change as above without issue, so even though it asks for html a simple ok is saved and displayed.
Any logs that give further clues? Is it a permissions problem?

**Comment by imsoftware-id** [comment]
> I'm able to complete that default site change as above without issue, so even though it asks for html a simple ok is saved and displayed. Any logs that give further clues? Is it a permissions problem?

thanks, I fixed this change permission in nginx folder
