### ISSUE TITLE
NPM not opening port when creating a new stream.

### ISSUE THREAD

**Issue by FreshImmuc** [jc21/nginx-proxy-manager#1673]
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Title

**Nginx Proxy Manager Version**
latest

**To Reproduce**
1. Go to 'stream'
2. Click on 'add stream'
4. Add a new Stream
5. Check with a tool if the port is open

**Expected behavior**
That the port is open

**Comment by FreshImmuc** [comment]
![image](https://user-images.githubusercontent.com/65733898/147157839-31137050-9cd9-4f60-9903-15a3bd396e51.png)

**Comment by chaptergy** [comment]
Since NPM is a dockerized application, you will also need to expose that port in your docker-compose file, since npm is not able to do that. Then that port will also be accessible from the outside and should work as expected.

**Comment by FreshImmuc** [comment]
Ahhh okay I remembering now. Thank you I just used this a while ago.
