### ISSUE TITLE
Button not working for Add Certificate --> Custom

### ISSUE THREAD

**Issue by ctrlzed** [jc21/nginx-proxy-manager#1676]
**Describe the bug**
On the SSL Certificates tab, adding a custom certificate does not open a drop-down dialog, hence custom certificates cannot be added.
Adding a Let's Encrypt certificate via the same button works fine.

**Nginx Proxy Manager Version**
v2.9.13 

**To Reproduce**
1. Go to the "SSL Certificates" tab
2. Click on "Add SSL Certificate"
3. Click on "Custom"
4. No action occurs.

**Expected behavior**
A drop down dialog is presented to allow the user to add a certificate

**Screenshots**
N/A - No error or screen of any kind is presented. But something should happen when you click this button. 

**Operating System**
Unraid 6.9.2 (via Docker)

**Additional context**

**Comment by krause3284** [comment]
Fix doesnt work

**Comment by moeik** [comment]
> Fix doesnt work

Me too.

**Comment by felixoswald** [comment]
can confirm this with docker :latest image (v2.9.13)

console log on chrome
![image](https://user-images.githubusercontent.com/52625423/147344882-c9a7f719-bc43-4eac-9bdb-d4116d9e67a2.png)

**Comment by chaptergy** [comment]
@krause3284 @moeik See https://github.com/jc21/nginx-proxy-manager/pull/1677#issuecomment-1000866294

**Comment by krause3284** [comment]
@chaptergy after pulling it twice and clearing the cache a bunch of times, it decided to work. Not sure why the initial clearing of cache didn't work. Thank you!

**Comment by hoochster** [comment]
I am having this issue as well, have tried clearing cache multiple times, different browsers etc.  Have wiped/reinstalled multiple times all having same issue.  This worked just fine a couple days ago.  Let me know if you need me to provide anything.  One thing I have noted that might not be related, but first time connecting to site, gives a Warning of invalid signature in the log.  

[12/25/2021] [6:42:03 PM] [SSL      ] › ℹ  info      Renew Complete
[12/25/2021] [6:42:18 PM] [Express  ] › ⚠  warning   invalid signature

**Comment by averyhox** [comment]
After using the #1677 fix, it did not initially work on Edge browser, showing the same errors as above.  However, once I swapped to a privacy window it worked fine.  The next day, when I re-loaded my npm and database, it worked fine without a privacy window.  

I believe #1677 does fix the issue (at least for me), but something was hanging in my browser (cache) preventing it from working.

**Comment by robertfraefel** [comment]
same here: 
![image](https://user-images.githubusercontent.com/33721995/147637553-db5ccd1f-412b-473c-97cb-a7724aa8e285.png)

**Comment by chaptergy** [comment]
@robertfraefel There hasn't been a new release yet, you'll have to wait for 2.9.14
