### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by miberecz** [jc21/nginx-proxy-manager#1678]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

After setting up everything as it written on the https://nginxproxymanager.com/guide/#quick-setup page, I get 'Bad Gateway' at login. 
Checking the logs shows the following:

docker logs nginx-app-1
```
[12/23/2021] [3:16:46 PM] [Global   ] › ℹ  info      No valid environment variables for database provided, using default SQLite file '/data/database.sqlite'
[12/23/2021] [3:16:47 PM] [Global   ] › ✖  error     create table `knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime) - SQLITE_BUSY: database is locked

```
cat fallback_error.log

`2021/12/23 15:17:01 [error] 285#285: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.111, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "192.168.0.104:81", referrer: "http://192.168.0.104:81/login"`

**Nginx Proxy Manager Version**

 v2.9.13 

**Expected behavior**

To be able to login

**Screenshots**

![image](https://user-images.githubusercontent.com/13240971/147260111-f34615ad-cf08-438f-9558-6b878b1ee484.png)

**Operating System**

Linux, x86

**Additional context**

Content of docker-compose.yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

**Comment by TimekillerTK** [comment]
@miberecz I came across this issue when trying to use a mounted SMB share with specific UID/GID, this was a file permissions issue and I resolved it by using different mounts with correct permissions.

**Comment by sunjx97** [comment]
I also had this problem before when I used a mounted SMB share. I mounted my folders with the fstab file like this `//myserver /mymount cifs username=*,password=*,nolock,uid=1000,gid=1000`. As a result, I faced the same problem. 
Finally, I resolved it by setting parameters **nolock** (just like this: `//myserver /mymount cifs username=*,password=*,**nolock**,uid=1000,gid=1000`). 
You can get more infomation with this url: [Database is locked](https://blog.archiware.com/blog/pure_forum/pure-question-answers/database-is-locked/)

**Comment by miberecz** [comment]
Thank you guys, it makes sense now!

**Comment by Krojack** [comment]
An update if someone comes across this now....

The `nolock` mount option is no longer valid for cifs. You need to `nobrl`

**Comment by aogg** [comment]
+1

**Comment by RolandoV19** [comment]
> An update if someone comes across this now....
> 
> The `nolock` mount option is no longer valid for cifs. You need to `nobrl`

thanks this made it work for me , have been looking for a solution for a couple of days now
