### ISSUE TITLE
Can I re-upload a nginx-proxy-manager ssl and have it auto renew?

### ISSUE THREAD

**Issue by TeamWolfyta** [jc21/nginx-proxy-manager#1686]
Hello, I was curious if there is a way to upload a SSL cert from a previous installation of npm and have it auto renew ? When I use the custom SSL upload it doesn't provide that option and I don't wanna have to re-create another SSL cert and add another cert to my transparency logs lol

**Comment by chaptergy** [comment]
Unfortunately not. Copying old cerbot config files over would make make it available for certbot, however it would still not be possible to view and select it inside the admin panel, it would not exist there. Furthermore you would have to upload both the certificate, as well as the renew information to make it work, and then just creating a new certificate would be basically the same. Letsencrypt also [automatically publishes transparency logs](https://letsencrypt.org/docs/ct-logs/) for all issued certificates. So just  I don't really see a use case for this.
