### ISSUE TITLE
Help with fqdn not declared on dns

### ISSUE THREAD

**Issue by ricain59** [jc21/nginx-proxy-manager#169]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? no
- Are you sure you're not using someone else's docker image? no
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? no

**Describe the bug**
My problem is probably mine configuration. I have a domain public and redirect to NPM fine. NPM redirect to an virtualhost on my network and give error not found mysite.local.domain. But this virtualhost not declared on my network and on my linux machine have multiple virtualhost. Before, on my old proxy, i've put on file hosts "192.168.1.10 mysite.local.domain" and works. how do this with NPM? It's possible do this?

Thank you for help and sorry my english.

**Comment by ricain59** [comment]
I've try other solution,  "--add-host xxxx" and "--network host" on docker run but unsuccesfully.

**Comment by jc21** [comment]
You said you have the domain public and redirecting so I assume you're just talking about a sub-domain of that domain not directing?

NPM is not a DNS manager, you'll have to get your DNS provider or service to send your `mysite.local.domain` to NPM or most likely a wildcard `*.local.domain`

**Comment by ricain59** [comment]
You can close resolve using, intranet domain.
