### ISSUE TITLE
SSL for IP address

### ISSUE THREAD

**Issue by dmkjr** [jc21/nginx-proxy-manager#1695]
I've used NPM for quite some time now.  I'm running into a problem on Home Assistant (externally presented through NPM) where I included a configurator docker instance as an iframe within the configuration.yaml

All is well except it's yelling at me for attempting mixed content.  The below code was from the configuration.yaml file in Home Assistant.  I need to make that http, https and was attempting to utilize NPM to handle the Let's Encrypt certificate.  Is this possible?  We do not want to create another subdomain "something.example.com" that routes to the internal address. I can do this, but trying to just add a certificate at the LAN level that isn't presented publicly.

`panel_iframe:
 configurator:
  title: 'Configurator'
  url: 'http://10.0.10.100:3218'
  icon: mdi:wrench`

Thanks community!

**Comment by chaptergy** [comment]
Letsencrypt does not provide certificates for IP addresses, just for domains. It is generally unusual to have a certificate for an IP, except when it is a self signed certificate. And then no browser would trust this certificate, meaning you would either have to click "accept the risk" in every browser or install the certificate on every device you use.

Furthermore to route without a domain in nginx, the proxy would have to be set as the default server. Meaning everything received by nginx where it does not know where to route it to will be routed there. In npm this default server is already taken by the default page / congratulations page, so you can't do that in npm. 

So what you are asking is not possible. SSL would either have to be handled by the proxied app and you can create a stream host for it, or you need a domain which you use to redirect to there.

**Comment by dmkjr** [comment]
@chaptergy Thank you for the response.  I can certainly do the reverse proxy by domain name.  Perhaps I can find ways to lock it down outside of my normal Cloudflare policies.  Thank you for the information.
