### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by Amplificator** [jc21/nginx-proxy-manager#1699]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I have Nginx Proxy Manager set up as a proxy for several WordPress sites. The frontend of the sites work just fine but I can't login to the backend.
When entering any login credentials it just sits there and eventually gives a 504 Gateway Timeout.

I have tried the following extra configuration for each domain but it doesn't seem to make a difference:
```
fastcgi_read_timeout 300s;
proxy_connect_timeout 300s;
proxy_send_timeout 300s;
proxy_read_timeout 300s;
send_timeout 300s;
proxy_set_header Connection "";
```

**Nginx Proxy Manager Version**

2.9.13

**To Reproduce**
1. Add a proxy to a WordPress site and visit the login page. Any login details will cause the issue.

**Operating System**

AlmaLinux 8.5 with nothing but Docker on it. FirewallD is disabled.

**Comment by chaptergy** [comment]
I'm pretty sure this is a wordpress issue as I have seen this with a non-proxied wordpress instance. If I remember correctly this had something to do with wordpress hardcoding the url everywhere. So you'll need to make sure the url inside the wordpress settings is the one you use when proxying the app. So if `wp.example.com` points to your proxy, and the wordpress site is available at `user1.websitebuilder.com`, the wordpress settings need to have `wp.example.com` as the url, otherwise it won't work.

**Comment by Amplificator** [comment]
The domain is completely unchanged and as soon as I move the DNS from the proxy to the actual web server it works fine.
So the domain never changed, or am I understanding you wrong?

It's always been at domain.com both before and now with the proxy.

**Comment by chaptergy** [comment]
No, I think you understood correctly. Then I'm really not sure what the issue could be, as I don't have a wordpress installation I can't really replicate it, sorry

**Comment by Amplificator** [comment]
I can set up an empty WordPress site for you if you want? If not, thanks for trying though, I do appreciate it :)

**Comment by chaptergy** [comment]
Sure, that would be possible. You can message me via [Gitter](gitter.im) if you want.

**Comment by chaptergy** [comment]
The issue was the webhoster trotteling the requests since they suspected a brute force attack. Whitelisting the ip of the reverse proxy fixed the issue.
