### ISSUE TITLE
Checking authentication...

### ISSUE THREAD

**Issue by Aerya** [jc21/nginx-proxy-manager#17]
Hi,

Don't really know if it's about this (awesome) proxy or on the other side but trying to use it with Cardigann (and Nginx auth) I got this error: ```Checking authentication...```
Cardigann source: https://hub.docker.com/r/linuxserver/cardigann/
Nginx-proxy-manager: https://i.imgur.com/nRCh4ZX.png
Nginx auth (working with my others containers): 
```        auth_basic "Restricted Content";```
```        auth_basic_user_file /data/htpasswd/cardigann;```

**Comment by Aerya** [comment]
I use the advanced config on the proxy host. It works well for all containers (Wordpress, Jackett, Medusa...) but have this error for Cardigann. That's why I wonder if its on "your" side or Cardiganns.

**Comment by jc21** [comment]
I highly doubt it's NPM's side. I run other services that have built in basic auth behind NPM without issue as well. In some cases I also disable auth for the service and only use NPM for auth.

The best way to test is to hit Cardigan directly and see if auth is still failing

**Comment by Aerya** [comment]
Thanks, I'm discovering Cardigann, I'll look for its own auth process.

**Comment by Aerya** [comment]
Cardigann is a totally f*cked tool. Bot on your side. Thanks for support anyway.
