### ISSUE TITLE
Django Static files serving 

### ISSUE THREAD

**Issue by Maxino22** [jc21/nginx-proxy-manager#1718]
Hello am new to nginx proxy manger and soo far i have understood the workflow however in the location section am having a bit of trouble.. am running  a django app with gunicorn which only handles python code hence my static files(javaScript & CSS) are not being served..
i want to include them in the location area but every time I do it the host goes offline... if I used  an nginx config file traditionally this is what  it would look like
```nginx
server {
    listen 80;
    server_name YOUR_IP_ADDRESS;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/djangoadmin/pyapps/btre_project;
    }
    
    location /media/ {
        root /home/djangoadmin/pyapps/btre_project;    
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
```
I want the  proxy params , media and static to be included in location but I can't find a way... kindly assist

**Comment by chaptergy** [comment]
The way I understand you are trying to do it is not possible. I'm assuming you run the django app with gunicorn in a container? Then npm has no access to the files you are trying to serve. Furthermore static file serving is not supported officially by npm, there only is a [feature request](https://github.com/jc21/nginx-proxy-manager/issues/58) for it.  You should theoretically be able to have static file serving by mounting the files into the container and using the advanced config, but we can't officially support this, you might want to try the [reddit community](https://reddit.com/r/nginxproxymanager).  
But as a tip: only the three non-`/` locations are relevant, the `/` location and stuff above the locations are automatically generated. You also want to use the advanced config, as the custom locations generate code for proxying, not for file serving. But pasting the three locations into the advanced tab and mounting the files into the npm container should work.

**Comment by Maxino22** [comment]
Thank you very much for replying . I honestly did not understand but I found a work around using whitehorse to serve my statics directly from the python. I tried looking at  the credit community for answers but none of them were to detail. finally I would like some assist on redirecting  as the HTTP versions of my domain are still accessible and the www does not redirect to non www .... i saw redirect host but documentation and online searches don't quite show

**Comment by chaptergy** [comment]
Create a redirect host for `www.example.com` and redirect it to `example.com` usually with a `301` redirect. If you know, that this redirect will change in the future, use a `302` redirect to indicate it is temporary.  
To make sure you only use HTTPS just enable _Force SSL_ and _HSTS_ in your proxy host.

**Comment by Maxino22** [comment]
Wow thank you that actually worked

**Comment by keniobats** [comment]
@Maxino22 Hi! any updates on this? I'm facing the same issue. Couldn't find any references to "whitehorse" you mention. Thanks!

**Comment by Maxino22** [comment]
sorry mate its not whitehorse rather white noise... it makes running django  quite easy.... http://whitenoise.evans.io/en/stable/ ... it will be easy read the docs i beleive will solve problem

**Comment by keniobats** [comment]
Thanks @Maxino22 I'll give it a shot!

**Comment by keniobats** [comment]
I've already solved with Whitenoise, thanks @Maxino22 !!!

**Comment by Maxino22** [comment]
you welcome... Glad i could help 🔥

**Comment by snake-soft** [comment]
It can cause problems when adding an advanced configuration and enable "cache assets".
I got a 404 trying to load asset files (Django static and media).
It works after disabling "cache assets".

**Comment by mr-engin3er** [comment]
> It can cause problems when adding an advanced configuration and enable "cache assets". I got a 404 trying to load asset files (Django static and media). It works after disabling "cache assets".

This solved my issue.
