### ISSUE TITLE
Shutdown problem

### ISSUE THREAD

**Issue by jayjupdhig** [jc21/nginx-proxy-manager#1722]
After installing it withwout mariadb / mysql i saw that it needs 2-3 minutes for shutdown

![image](https://user-images.githubusercontent.com/42765391/147941389-7518ca3c-a907-4a67-bce2-00ba4beddcd1.png)

Versions: Debian 11 most current, Docker most current from doker.io

**Comment by chaptergy** [comment]
Not an issue with npm but with docker, see https://github.com/moby/moby/issues/41831

**Comment by kosuodhmwa** [comment]
thx!!

**Comment by jayjupdhig** [comment]
"Not an issue with npm but with docker, see moby/moby#41831"

Question: Does somebody know how to install an older docker version without that issue (does not happen on EVERY restart, but sometimes)

When i try to install docker from debian.org (Debian 11) i get that:

root@debian:~# apt-get install docker-ce docker-ce-cli containerd.io
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Paket docker-ce ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.

Paket docker-ce-cli ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.

E: Für Paket »docker-ce« existiert kein Installationskandidat.
E: Für Paket »docker-ce-cli« existiert kein Installationskandidat.
E: Paket containerd.io kann nicht gefunden werden.
E: Mittels des Musters »containerd.io« konnte kein Paket gefunden werden.
E: Mittels regulärem Ausdruck »containerd.io« konnte kein Paket gefunden werden.
root@debian:~#

**Comment by chaptergy** [comment]
That's not an issue for this issue tracker, have a look at various articles or the docker forums like

- https://forums.docker.com/t/how-can-i-install-a-specific-version-of-the-docker-engine/1993
- https://medium.com/@gauravsj9/how-to-install-specific-docker-version-on-linux-machine-d0ec2d4095

**Comment by jayjupdhig** [comment]
thx!!

**Comment by jayjupdhig** [comment]
Another question HERE: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1736
