### ISSUE TITLE
How to whitelist IP for the admin gui

### ISSUE THREAD

**Issue by jayjupdhig** [jc21/nginx-proxy-manager#1723]
we have an external plesk server and we would only allow the proxy manager via that ip on port 81. how to realize?

**Comment by chaptergy** [comment]
Please stop. This issue tracker is not your personal support chat. We can't help with every small little hiccup you experience. Debug a little yourself. Google the problem. Look for already existing issues. Just try out different things. A few of the issues you have opened in the past hours wouldn't have been necessary if you had googled the problem. For help with specific proxy setups, there is the [reddit community](https://www.reddit.com/r/nginxproxymanager/). This issue tracker is only for bugs and feature requests.

But to answer your question, you can do it easily through port 80 / 443 by creating a proxy host with an access list. (Note, you might need https://github.com/jc21/nginx-proxy-manager/discussions/1724). Add this IP in the access list. Unexpose / remove port 81 in the docker compose.

If it is absolutely necessary to keep it on port 81, there is no other way than to mount a different [`production.conf`](https://github.com/jc21/nginx-proxy-manager/blob/develop/docker/rootfs/etc/nginx/conf.d/production.conf) into the container to `/etc/nginx/conf.d/production.conf`, which contains a modified nginx config with an allow and deny directive.

**Comment by jayjupdhig** [comment]
Another question HERE: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1736
