### ISSUE TITLE
Is it possible to setup LAN_ONLY access to a certain webpage?

### ISSUE THREAD

**Issue by BobWs** [jc21/nginx-proxy-manager#1737]
Hi,
Is it possible to setup **LAN_ONLY** access to a certain webpage?
e.g. I would like to have **LAN-ONLY** access to `subdomain.mydomain.com/index.json`

Can anyone point in the right direction.

TIA

**Comment by Kieffer87** [comment]
You can setup LAN only access by creating a new Access List that allows your LAN subnet(s) for example `192.168.1.0/24` The default action is to deny if it doesn't match.

**Comment by BobWs** [comment]
> You can setup LAN only access by creating a new Access List that allows your LAN subnet(s) for example `192.168.1.0/24` The default action is to deny if it doesn't match.
> 
> Once the Access List has been created, you assign the list to the proxy host.

I have already done that, but the certain page `subdomain.mydomain.com/index.json` is still accessible from the internet.

I also tried to add this into the advanced tab/custom nginx configuration 
```
location /public {
  allow 192.168.0.0/24;
  deny all;
}
```
That is the folder where the index.json file is, but that is not working either.

**Comment by BobWs** [comment]
Sorry my bad!
I totally forgot that I also had this subdomain on a external server, that's why the page was still reachable from the internet.
So when I removed it from the remote server, NPM is working fine with LAN ONLY access list.

Anyway thanks for reaching out!
