### ISSUE TITLE
Ability to use Organizr as Access List / authentication provider

### ISSUE THREAD

**Issue by cmer** [jc21/nginx-proxy-manager#176]
See https://github.com/causefx/Organizr/wiki/Authentication for implementation details.

**Comment by scottluker** [comment]
Would love to see this as well, just as an update the wiki page has moved to:
https://docs.organizr.app/books/setup-features/page/serverauth

**Comment by zhdenny** [comment]
I would also love to see this too......I banged my head trying to add this using the custom configuration options provided in nginx-proxy-manager...but couldn't get it to work

**Comment by chaptergy** [comment]
Closing in favor of https://github.com/jc21/nginx-proxy-manager/issues/437
