### ISSUE TITLE
Cloudflare (not going trought) ssl not working?

### ISSUE THREAD

**Issue by IIPoliII** [jc21/nginx-proxy-manager#179]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Y
- Are you sure you're not using someone else's docker image?
Y
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
Y

So i basiclly tried to do a simple proxy host i tried this time to NOT go trought cloudflare and basiclly here is what i did :

On the dns said that test.mywebsite.com subdomain go to (in local network) 10.0.0.2 with and ssl cerftificate for test.mywebsite.com and mywebsite.com now i get "The page isn't redirected corretly" but if i do it with http only it works... my host behind isn't https here are some print screens of the config : 
![image](https://user-images.githubusercontent.com/29628512/61952583-87460d80-afb4-11e9-865e-1ec1097d585a.png)
![image](https://user-images.githubusercontent.com/29628512/61952602-9036df00-afb4-11e9-9d31-1eccd417592a.png)

**Comment by IIPoliII** [comment]
It works if i don't go trought the cloudflare proxy.

**Comment by CorySanin** [comment]
I know this was closed, but I think this should be reopened because this seems like a pretty substantial bug. I encountered this issue as well and disabling cloudflare feels like a workaround.
