### ISSUE TITLE
Logs grow indefinitely

### ISSUE THREAD

**Issue by rimas-kudelis** [jc21/nginx-proxy-manager#183]
I had an issue with a setup of nginx-proxy-manager. I have it set up for a relative of mine as a docker container in an Ubuntu virtual machine, and suddently it began glitching. The latest symptoms was that port 80 was accessible from the other machines in the network, but port 81 was not.
Apparently, the culprit was the logs which grew to over 2GB in just a few months.
By looking at `/data/logs` in the container file system, I noticed that the logs are never rotated and just grow indefinitely, and I think it's bound to hit pretty much every user at some point.
Thus I would like to suggest to either configure log rotation out of the box, or to explain how this should be done externally (since I just noticed that /data volume is a directory exposed from the host machine).
Or perhaps another option would be to allow easy disabling of nginx logging into files altogether, and instead let it log to stdout?

**Comment by beloniki** [comment]
You can use default **logrotated**:
```
/path/to/nginx/*.log {
        maxsize 500M
        daily
        missingok
        rotate 14
        compress
        notifempty
        create 0640 root root
        sharedscripts
        postrotate
                docker exec CONTAINER_NAME bash -c 'kill -USR1 `cat /var/run/nginx.pid`'
        endscript
}
```

**Comment by nekoliten** [comment]
Ran into this issue today myself when my server was suddenly out of disk space (my bad for not setting up alerts for it), upon investigation I noticed that the proxy-manager log folder contained several 25+ GB logs.

**Comment by MaxVRAM** [comment]
Would be good to have this a function of the Docker deployment itself. I just realised my Pi was filled with 4GB of logs.

**Comment by ameinild** [comment]
I'd like to chime in on this as well. Would it be possible that the container can logrotate itself, or provide some log settings etc?

**Comment by beloniki** [comment]
I think, that it would be useful to give to user a choice: send logs to stdout like this:
```
error_log /dev/stdout warn;
access_log /dev/stdout proxy;
```
, or put into files.

@MaxVRAM
You could create your **Dockerfile** and replace logging directives in /etc/nginx/nginx.conf by stdout. Then you can use native docker log method to send logs to syslog collector https://docs.docker.com/config/containers/logging/syslog/
or to store locally https://docs.docker.com/config/containers/logging/local/ and limit size by using **max-size** option.

**Comment by generalsnipe** [comment]
Just +1 on this. I too recently had a server go down due to log taking 11GB. I personally only need the last week of data. Anything over that is just taking space.

**Comment by internetfreak** [comment]
Supporting this as well, had issues to download some files and after searching for quite a while I came to check the proxy and then I saw what was wrong. This should not happen

**Comment by gadgetusaf** [comment]
I am supporting this as well and have had a similar issue. Is there an eta on when logrotate functionality will be merged in?

**Comment by shroomlife** [comment]
+1

**Comment by Mrs-Feathers** [comment]
just ran into this issue on the current build.. logs filled up 50gbs within a week and i didn't know until everything crashed.

**Comment by Kuro-orzz** [comment]
I just ran into this issue, after deploy web for just 3-5 days and testing, it grow to 500MB RAM consumption and make my web lagging
