### ISSUE TITLE
How to manually install the source code?

### ISSUE THREAD

**Issue by w796933** [jc21/nginx-proxy-manager#190]
sir 
How to manually install the source code?

**Comment by jc21** [comment]
The source code (NodeJS) was written to run within a docker container and assumes that commands like nginx and certbot are available at specific locations. There have been other requests for some sort of bundled package to run anywhere but it's just too hard to support at the moment.

**Comment by yaneony** [comment]
It's all fine, but... Any way to run it without a docker? :D

**Comment by chaptergy** [comment]
> The source code (NodeJS) was written to run within a docker container and assumes that commands like nginx and certbot are available at specific locations. 

So no, there is no easy way.  You would manually have to replicate the environmental conditions from [the main dockerfile](https://github.com/jc21/nginx-proxy-manager/blob/develop/docker/Dockerfile) and [this nginx docker image](https://hub.docker.com/layers/jc21/nginx-full/node/images/sha256-9950cc3f9bfd21267aa860ad24303716bbf0264116581789fe2e43d698a8fb2f)
