### ISSUE TITLE
Only works with container internal IP

### ISSUE THREAD

**Issue by Oujiii** [jc21/nginx-proxy-manager#191]
I'm not using the template simply because I don't know if this is the expected behaviour.

I just setup a new machine with npm and portainer. I ran npm first and it created a network called npm_default, so I run portainer passing the command --network=npm_default and it works as intended, all the three containers are in the same network.

While in the network, I can connect to 192.0.1.12:port (my internal ip) and it works. Also works it external-ip:port as it's listening on 0.0.0.0 by default, but for both portainer and npm admin page, if I try to proxy via http://192.0.1.12:9000 (portainer) and http://192.0.1.12:81 (npm admin) it doesn't work. It only proxies if I use the internal container IP + port. Is that intended? I didn't think so looking at the screenshots, that's why I'm asking.

I'm only worried as I'm deploying more containers, whenever I need to restart the node, the internal docker ips might not be the same anymore, thus messing all the proxies.

Thank you.

**Comment by beloniki** [comment]
Hi.
You can use the portainer's container name instead ip as backend address.

**Comment by Oujiii** [comment]
@beloniki Does that work for any container in the same network?

**Comment by henkisdabro** [comment]
I'm experiencing issues with this too, I can only reach proxy hosts when configured with their internal ip as in 172.17.0.9 or similar. When entering either the service name or container name into the hosts box, they result in a 502 error. I have tried adding links inside my docker-compose on each service, but they don't seem to work either. My containers are all on the bridge network, and when restarting containers the IP's change. How can I make this work with docker DNS?

**Comment by chaptergy** [comment]
See https://github.com/jc21/nginx-proxy-manager/pull/745#issuecomment-753558427

**Comment by TarikHaci** [comment]
I have the same code as the fix here, but in my case I had also to EXPOSE my port in dockerfile, since I had a mapping in docker-compose 9000:port but it wasn't working so I added the port which is EXPOSED and not mapped and it worked.
