### ISSUE TITLE
External custom or other SSL certificate support

### ISSUE THREAD

**Issue by aiminickwong** [jc21/nginx-proxy-manager#2]
Please support this feature, it's really useful! 
this is great project!

**Comment by jc21** [comment]
Version 2 is ready for someone to test besides me. Have a read of [the documentation](https://github.com/jc21/nginx-proxy-manager/blob/v2/README.md) including the [installation instructions](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/INSTALL.md) and [importing guide](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/IMPORTING.md).

The app has only a few minor bugs I want to change but I'm using it in production myself on 4 instances. 

Testing of the custom certificates in particular needs to be done, I haven't purchased a cert in forever so I don't have one to play with and they can be fairly different.

If you have issues, probably be to report them as new issues and mention that they affect version 2 in the description.

Thanks
