### ISSUE TITLE
nginxproxymanager_app can't run

### ISSUE THREAD

**Issue by sahlie1985** [jc21/nginx-proxy-manager#20]
> Uncaught Error: Cannot find module '/app/node_modules/nodemon/bin/nodemon.js'
> FROM
> Function.Module._resolveFilename (internal/modules/cjs/loader.js:1:1)
> Function.Module._load (internal/modules/cjs/loader.js:1:1)
> Function.Module.runMain (internal/modules/cjs/loader.js:1:1)
> startup (internal/bootstrap/node.js:1:1)
> bootstrapNodeJSCore (internal/bootstrap/node.js:1:1)

**Comment by jc21** [comment]
Are you running this project directly from a git clone? because that's the only way I can see this error happening and doing it that way is really only for development.

If however, you're seeing this with the official docker image, let me know.

**Comment by sahlie1985** [comment]
think you i resolved the problem.
