### ISSUE TITLE
Can't communicate by name on docker network

### ISSUE THREAD

**Issue by jfrancais** [jc21/nginx-proxy-manager#203]
I currently have this setup in a user defined docker network, "dockerwp".  In that network I have several other docker containers running as backend.  I have setup npm and have created several proxy hosts to point to the backened containers, again in that dockerwp network.  If I set npm to talk to them by name (ie http://website1) it can't communicate.  If I use the same settings and put use the internal ip address of that container (ie 172.21.0.6) everything communicates as expected.  Since I'm spinning up and removing containers quite regularly I'm, wasting a lot of time looking up the IP, it would be nice to be able to communicate by name, which should be possible on a user defined network.

**Comment by beloniki** [comment]
Can you communicate to other containers from inside the npm container?

**Comment by jfrancais** [comment]
Yes.  For example, it I do:

docker exec -it NPMCONTAINER /bin/bash
I can then ping both the IP 172.21.0.6 and website1
I can curl both the IP http://172.21.0.6 and http://website1

Using the web interface, if I set up a proxy host to point to http://172.21.0.6 on 80 it works, but if I set up http://website1 on 80 it does not.

**Comment by beloniki** [comment]
> Using the web interface, if I set up a proxy host to point to http://172.21.0.6 on 80 it works, but if I set up http://website1 on 80 it does not. (I get a 502 Bad Gateway message)

Do you see 502 error in npm logs? If you do, attach this log here, please.
Maybe this error is from the backend?

**Comment by jfrancais** [comment]
[20/Sep/2019:21:44:08 +0000] - - 502 - GET https MY.PROXY.HOST "/" [Client ##.##.##.## [Length 150] [Gzip -] [Sent-to website1] "curl/7.61.1" "-"

This is in my error log, I have changed the domain I'm using to MY.PROXY.HOST and changed my ip address.

**Comment by beloniki** [comment]
Ok, try to find what happens at this time [20/Sep/2019:21:44:08 +0000] in error.log, or find events where the website1 participates. I think this may help to find out the cause.

**Comment by jfrancais** [comment]
After reviewing all the logs, I see the issue.  My container name is "Wordpress1".  It has an uppercase W.  In NPM, it is entered as "Wordpress1", also with uppercase W.  When I reviewed the logs I see it was using "wordpress1" lowercase W.  So NPM is not using the case for the transfer host as entered, it lowercases it.  And the container name is case sensitive.  I verified this by destroying the container and recreating it with lowercase w and it started working.

So my interm fix is to name my containers all lowercase, but I think that the function that lower cases the forward host should be addressed.

**Comment by beloniki** [comment]
Good research.

**Comment by Mechazawa** [comment]
Adding `resolver 127.0.0.11;` to the proxy config fixes this issue

**Comment by chaptergy** [comment]
See https://github.com/jc21/nginx-proxy-manager/pull/745#issuecomment-753558427
