### ISSUE TITLE
Combination proxy host & stream

### ISSUE THREAD

**Issue by TheFlyingBadger** [jc21/nginx-proxy-manager#204]
I may be barking up the wrong tree here,  but I think what i'm wanting is a combination proxy/stream host.

What i'd effectively like to do is run (for instance) a ssh server on ssh.mydomain.com:443, which would then proxy to 10.1.2.x:22.  it seems to achieve this at present, i'd need to set up the stream host on 443 which would take over port 443 for my "whole" IP, rather than just traffic heading into ssh.mydomain.com...

This is all to get around pesky corporate firewalls blocking port 22 (and other useful ones!)

So is it 
1. do-able at present, i'm just being a dunderhead
2. a product enhancement
3. not able to be done within the scope of this project

**Comment by jc21** [comment]
Blunt answer: 1 and 3.

There are ways of achieving SSH over HTTP(S) but all the guides I've found are not nice or easy. More like hacks and they depend on the firewall your company is using. Google for "SSH over HTTP" if you're curious.

**Comment by jc21** [comment]
Just reading the issues backlog and found #164 which has products you might be able to deploy.
