### ISSUE TITLE
Q about serving directories

### ISSUE THREAD

**Issue by rkraken** [jc21/nginx-proxy-manager#222]
Sorry for what is likely a basic question here and probably mangled terminology.  

I have a (non dockerized) Nextcloud running on my server which is accessed through apache2, and I'm wondering if it's possible to replace apache2 with NPM.  

The reason I'm asking is I want to add additional dockerized services and have everything run through NPM.  Currently nextcloud is located in a directory under /var/www/ and I don't see an obvious way to configure NPM to access directories, only to port-based services.  What I believe I'm asking is if NPM can also function as a webserver in addition to the reverse proxy function.

Would I instead have to keep apache2 as the webserver, changing the port number, then configure a host in NPM to access it?

Thanks for any clarification.

**Comment by chaptergy** [comment]
Unfortunately this is not possible. However there is an open feature request for this: https://github.com/jc21/nginx-proxy-manager/issues/58
