### ISSUE TITLE
npm-8/fullchain.pem no such file

### ISSUE THREAD

**Issue by danmed** [jc21/nginx-proxy-manager#229]
I've just rebooted my docker server and now nginxproxymanager wont start.. the docker logs are filling up with this : 

nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-8/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-8/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

Last thing i remeber doing was deleting a proxy host and then deleting it's associated ssl certificate.

**Comment by danmed** [comment]
Managed to figure out that the proxy host i deleted, the conf file was still sat in the nginx/proxy_host folder.. Deleting that fixed the issue.. though that still signifies a problem no?

**Comment by esticle** [comment]
similar problem here, when deleting, editing and recreating a SSL'd host the certbot npm-n directories increment but the proxy_host configuration still exists / or points to a previous npm-n directory which no longer exists.

**Comment by oldgeezy** [comment]
Similar problem here.  Deleting the conf file in /nginx/proxy_host/ didn't help

`nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/npm-10/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-10/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
`

**Comment by ndaringer** [comment]
NPM won't start. Same error these folks are facing. 

error.log just fills up with this repeatedly.

`2020/06/17 05:55:05 [emerg] 9666#9666: BIO_new_file("/etc/letsencrypt/live/npm-23/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-23/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

**Comment by downtime0** [comment]
I just had the same issue after deleting a certificate. The certificate was still attached to the Host record, but I've not had issues with deleting those before.
I determined from the Audit Log that certificate # 13 was the one I deleted and it matched the missing folder number .../live/npm-13/ 

I resolved this issue by recreating the .../live/npm-13/ folder that was logged as missing, then copied all the files from another /npm-## folder and restarted the container with success.

I was expecting an error somewhere with the duplicate certificates, or at least two displayed in the GUI but no issues at all.
I finally renamed the folder I created so the app would not go looking for it, fully stopped and restarted the container, and so far no issues.

**Comment by WendingTuo** [comment]
@downtime0 When you say you renamed the folder, are you talking about the replacement npm-13 folder you created? Every time I change the folder name or rm the folder nginx fails to start again.

How do I remove this certificate completely and correctly so that NPM will start again without some old folder with a duplicate certificate in it?

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/208
