### ISSUE TITLE
Log file location on Hassio Nginx Proxy Manager

### ISSUE THREAD

**Issue by ncm-com** [jc21/nginx-proxy-manager#231]
Hi 
I'm trying to get to connection log file location on hassio addon, I 've searched on /data/logs/ but the default log shows some old data. also, I'd like to keep access log for 30 days, any idea how to do this?

Many thanks 
NCM

**Comment by frenck** [comment]
That is not related to this repository and should not be dropped onto these developers.

Please consult this with the add-on repository.
