### ISSUE TITLE
Setup without using docker-compose? 

### ISSUE THREAD

**Issue by Jxck-S** [jc21/nginx-proxy-manager#232]
I'm using a Rock64 SBC that I and others can't get docker-compose working (tried all the install methods). I was wondering how I could set this up without compose.  I've tried other unoffical nginx-proxy-manger forks with docker run but they don't support arm. Thanks!

**Comment by jc21** [comment]
Sure here's a basic command that only starts the service, not the database that it links to. Based on [docker-compose example](https://github.com/jc21/nginx-proxy-manager/blob/master/doc/INSTALL.md).

```bash
docker run -d --name npm \
  -p "80:80" \
  -p "81:81" \
  -p "443:443" \
  -v /full/path/to/config.json:/app/config/production.json \
  -v /full/path/to/data:/data \
  -v /full/path/to/letsencrypt:/etc/letsencrypt \
  jc21/nginx-proxy-manager:latest
```
