### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by VitisEK** [jc21/nginx-proxy-manager#236]
Please add IPv6 support. It seems that nginx is not configured --with-ipv6.
Nodejs (port 81) is listening on IPv6 if it is configured.

**Comment by wuast94** [comment]
would like to see that too. ipv4 is lagacy and ipv6 should be implemented :) hope to see this soon :)

**Comment by Technikte** [comment]
+1, would like to see IPv6 support..since I got at home dual stack from my provider.
