### ISSUE TITLE
Remove certbot random delay for manual renew

### ISSUE THREAD

**Issue by sarbian** [jc21/nginx-proxy-manager#238]
When  "Renew Now" is used the certificate can take a few minutes to be issued. The cert bot log has a line with "INFO:certbot.renewal:Non-interactive renewal: random delay of xxx seconds"
This can be frustrating since the UI display a timeout error and there is not way of know what is going on without looking in the log. The cert is actually issued after the random delay but it seems nginx is not reloaded and you need to enable/disable the site.

Certbot has a --no-random-sleep-on-renew option to disable that random delay and it should be used at least for renew from the interface.

**Comment by jc21** [comment]
I didn't even know this was a problem. All my cert renewals have been immediate - but I guess it might have something to do with the dns verification, which I don't use yet.

**Comment by joshbenner** [comment]
Certbot will randomly wait on renewals when running in non-interactive mode. This is intended to avoid a massive rush of crons assaulting Let's Encrypt's servers all at the same time. This is appropriate when running scheduled renewals, but when running manually, specifying `--no-random-sleep-on-renew` is appropriate.
