### ISSUE TITLE
New option to support upstream self signed ssl connections

### ISSUE THREAD

**Issue by jc21** [jc21/nginx-proxy-manager#24]
Some upstream hosts only provide a SSL connection and they are sometimes using self signed certificates (EdgeOS is one such example).

Would be nice to have an option to specify that the upstream is SSL and the nginx proxy would ignore certificate errors because the server should be in control of the user who's creating the reverse proxy.

In most cases this means that the Proxy Host setup requires SSL as well and the added benefit here is that the edge host will be using a certified certificate at all times, regardless of what the upstream host has.

**Comment by sh4444dow** [comment]
That feature is definetely needed in a bunch of situations. I even considered to produce a pull request concerning this feature. Did you start to implement it ?

Sincerely,

@sh4444dow

**Comment by jc21** [comment]
No not yet. I left this note for myself to get to later. Give me a couple of days and I'll see if I have time to put it in quickly.

**Comment by sh4444dow** [comment]
Okay =) If I'm not mistaken, this enhancement note is strongly related to #34 issue. I link it just for reminder.

Sincerely,

@sh4444dow

**Comment by jc21** [comment]
Added in v2.0.7
