### ISSUE TITLE
Non-stop redirects

### ISSUE THREAD

**Issue by akshayogra** [jc21/nginx-proxy-manager#25]
hey! 2.0.3 works fine, but 2.0.4 doesn't let me load the admin portal on port 81 - just endless reloads with an internal server error access /api/tokens

**Comment by jc21** [comment]
Oops yeah thanks for finding this. Only happens when you don't have a previous login session, so it never cam up for me.

Fixed in `latest`, `2` and `2.0.5` docker images and armhf variants respectively.
