### ISSUE TITLE
Default Site settings vis GUI

### ISSUE THREAD

**Issue by ahakobyan79** [jc21/nginx-proxy-manager#258]
Currently default sites are forwarded to the Congratulations page, and there aren't many options for default_server settings via GUI.

I am trying to change the setting so that all sites not included in the Host list to point to a specific IP.

What settings would i need to change for this?

**Comment by fareszr** [comment]
did you figure it out ?
i am trying to do the same thing for pihole docker container

**Comment by chaptergy** [comment]
From settings you can set the default page to be a redirect:
![image](https://user-images.githubusercontent.com/26956711/117867820-64b7de00-b288-11eb-956c-5d077e55a6ba.png)
