### ISSUE TITLE
host.docker.internal is not resolved by nginx

### ISSUE THREAD

**Issue by devployment** [jc21/nginx-proxy-manager#259]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
✔️ 
- Are you sure you're not using someone else's docker image?
✔️ 

**Describe the bug**

`host.docker.internal` is not resolved by nginx

**To Reproduce**

1. Run NPM
2. Run some web application on the Docker host (e.g. on port 5000)
3. Use `host.docker.internal` as target
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/7137845/70868513-d8fe2d00-1f81-11ea-8623-d2364f2a2d88.png">

4. Try to access the proxied `host.docker.internal:5000`
5. Target page is not displayed and error is logged

```
2019/12/15 19:47:17 [error] 998#998: *368 host.docker.internal could not be resolved (3: Host not found), client: 192.168.16.1, server: xxx.local.test, request: "GET / HTTP/2.0", host: "xxx.local.test", referrer: "http://localhost:81/nginx/proxy"
```

**Expected behavior**

The NPM proxied domain, should show the page running under 127.0.0.1 on the Docker host

*Workaround*

If I ping `host.docker.internal` on the running `app` container and use the resulting IP as target it works

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7137845/70868633-cd5f3600-1f82-11ea-94a3-de047596b49a.png">

**Operating System**

macOS

**Comment by devployment** [comment]
Well, seems to be a general Docker issue

https://github.com/docker/for-mac/issues/2965

**Comment by Robokishan** [comment]
I am still facing this issue. Any work around ?

**Comment by devadattas** [comment]
Same here!

**Comment by stealthdave** [comment]
This looks to be an issue with `nginx` rather than the Proxy Manager.  Nginx itself does not seem to use `/etc/hosts` as a resolver:

https://stackoverflow.com/questions/8305015/when-using-proxy-pass-can-etc-hosts-be-used-to-resolve-domain-names-instead-of/8559797#8559797

 Perhaps a feature request to add `dnsmasq` to the container that can be enabled with an environment variable, e.g. `-e "ENABLE_DNSMASQ=true"`, to allow the use of `--add-host` and/or `extra_hosts` in the docker setup as this is a _very_ common use case to set up proxy servers for the docker host.

**Comment by EDIflyer** [comment]
Just came across this bug too (seems linked to #1225).

To confirm, when I run the following command:
`docker run -it --name alpine4 --network nginx-proxy-manager_default --add-host host.docker.internal:host-gateway alpine ash`

I can happily ping 172.17.0.1 as well as host.docker.internal and can also wget to the service running on the host

However when setting up a docker proxy pointed to `host.docker.internal` least to a 502 Bad Gateway openresty error.  Changing it to `172.17.0.1` works fine.

Just to confirm this is with the following text added to the nginx proxy manager Docker compose file too, so the host should have been mapped OK at a container level.
```
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Comment by williamblair333** [comment]
"Changing the forward hostname/IP to 172.17.0.1 then works fine."  Would you give an example of that in a docker-compose file , or where would this change be made?

**Comment by EDIflyer** [comment]
> `Changing the forward hostname/IP to 172.17.0.1 then works fine.` Would you give an example of that in a docker-compose file , or where would this change be made?

Sorry thought I replied before - it was just in the npm proxy host...
![image](https://user-images.githubusercontent.com/13610277/178266353-08504926-6d67-4b00-b2e4-6018bf3b57e4.png)

**Comment by KeivanDjafarizad** [comment]
Only workaround that I found, for development environment on the same machine, is to set network_mode: host, removing the ports and then forwarding to localhost. It's not the best but considering the fact that I'm using it to resolve names for local development, works for me

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    #ports:
    # - '80:80'
    # - '81:81'
    # - '443:443'
    network_mode: host
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

**Comment by Ran-Xing** [comment]
@KeivanDjafarizad I also have network_mode: host ,
and curl and MySQL inside my container work fine
But nginx still doesn't resolve
How do you solve it now?

**Comment by hitesh-pathak** [comment]
Is this actually resolved? Or is there any other issue to follow?

**Comment by MobCode100** [comment]
The issue is with Docker's default DNS 127.0.0.11 because it does not include `extra_hosts` and `--add-host` entries which are stored to /etc/hosts file. When the resolver is set, nginx will not read /etc/hosts. 2 workarounds are:

1. Change host.docker.internal to 172.17.0.1 which it's not sure whether Docker will always use the same IP.
2. Install dnsmasq and run dnsmasq inside the container. Set nginx resolver to 127.0.0.1.

**Comment by seif2003** [comment]
> The issue is with Docker's default DNS 127.0.0.11 because it does not include `extra_hosts` and `--add-host` entries which are stored to /etc/hosts file. When the resolver is set, nginx will not read /etc/hosts. 2 workarounds are:
> 
> 1. Change host.docker.internal to 172.17.0.1 which it's not sure whether Docker will always use the same IP.
> 2. Install dnsmasq and run dnsmasq inside the container. Set nginx resolver to 127.0.0.1.

In my case, the default Docker bridge network uses `10.0.0.1`, which you can confirm by running `ip addr show docker0`. It works fine for me with 10.0.0.1.

Also, you have to add `network_mode: host` in your Docker Compose file to ensure the container shares the host's network stack

**Comment by JoshMcCullough** [comment]
> Changing the forward hostname/IP to `172.17.0.1` then works fine.

Doesn't the proper IP to use depend on your Docker network config, though?

**Comment by EDIflyer** [comment]
> > Changing the forward hostname/IP to `172.17.0.1` then works fine.
> 
> Doesn't the proper IP to use depend on your Docker network config, though?

Yes, but I've allocated a fixed IP to NPM so it doesn't keep changing.

**Comment by auxym** [comment]
> Is this actually resolved? Or is there any other issue to follow?

#1225 is open and is tracking the same issue, from what I understand
