### ISSUE TITLE
NPM and OpenVPN

### ISSUE THREAD

**Issue by axiom00** [jc21/nginx-proxy-manager#274]
Hi @jc21,

I have OpenVPN running on my home network for those times I need to remote back into my network. OpenVPN is configured to tunnel on port 1194/upd and 443/tcp. For the most part, I tunnel on port 1194 but on occasion I am at a client site that blocks port 1194 and have to resort to port 443 to exit their network.

Before installing NPM, both 1194 and 443 were forwaded to OpenVPN. 
Now that NPM is installed, 1194 is still forwarded to OpenVPN, but 80/443 to NPM. 

Any suggestions on configuring NPM and OpenVPN to share port 443?

Thanks.

**Comment by jc21** [comment]
I had a big response prepared to basically say "TCP doesn't share like that" but then a simple google has led me to this:

https://medium.com/bob-kfir-tech/how-to-have-openvpn-and-ssl-on-the-same-port-f0c8df2b2cc2

I don't use openvpn so I can't give it a go.

**Comment by axiom00** [comment]
Thanks! I'll give it a try. 

From my research, it seems you can only accomplish this by putting something in front of NPM to split the traffic. sshl or haproxy.

Out of curiosity, what VPN are you using to remote back to your home network if you're using one?

**Comment by jc21** [comment]
I'm not. My domains are public and I use http method for letsencrypt verification.

**Comment by axiom00** [comment]
Got it. Thanks for the info.

**Comment by gartenbauer** [comment]
@axiom00 Did you find a solution?

**Comment by axiom00** [comment]
@gartenbauer Unfortunately no. I tried running HAProxy on my pfsense firewall to split VPN and https but was unsuccessful. I'll make sure to update this issue if I end up figuring out a solution.
