### ISSUE TITLE
Proxy Hosts 

### ISSUE THREAD

**Issue by atefibra** [jc21/nginx-proxy-manager#275]
Hello friends, 
so first of all am a nooby, who has worked with HAPROXY-WI and now am trying to work with Nginx Proxy Manager, 
so after ive finished the installation, now am trying to create some Proxy hosts but always i got this 
![image](https://user-images.githubusercontent.com/35434021/72514219-9369a400-384e-11ea-8fc1-4ccca2b38192.png)

**Comment by jc21** [comment]
yeah really hard to tell what's wrong without knowing your hosts configuration or what you put in the browser address bar to get here.

**Comment by miguelwill** [comment]
is probably heading to a port unreachable by the NPM host
