### ISSUE TITLE
"SyntaxError: Unexpected end of JSON input" when trying to change default site

### ISSUE THREAD

**Issue by netcop82** [jc21/nginx-proxy-manager#277]
When I try to change de default landing site, whatever option I choose `("Congratulations Page", "404 Page", "Redirect" or "Custom Page")`, i get the error `"SyntaxError: Unexpected end of JSON input"`.

**Comment by jc21** [comment]
Definitely can't replicate this with the latest version. Can you try opening developer tools in your browser and inspecting the network response you get from saving the setting, and if there's an error paste it here.

**Comment by netcop82** [comment]
never mind, after I few restarts it just worked. I'll close this issue, thanks.
