### ISSUE TITLE
Able to generate new certs but can't renew one

### ISSUE THREAD

**Issue by lekoOwO** [jc21/nginx-proxy-manager#281]
Generating a new cert works well, but when renewing the cert is the case, it fails.
I'm sure that my server is publicly accessible (generating new cert is working as well). Here's the log for renewing.
Thanks.

```
[1/27/2020] [10:17:04 AM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates for Cert #1: mydomain.me


[1/27/2020] [10:17:28 AM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot renew -n --force-renewal --disable-hook-validation --cert-name "npm-1" 


Saving debug log to /var/log/letsencrypt/letsencrypt.log


Plugins selected: Authenticator webroot, Installer None


Renewing an existing certificate


Performing the following challenges:


http-01 challenge for mydomain.me


Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.


Waiting for verification...


Cleaning up challenges


Attempting to renew cert (npm-1) from /etc/letsencrypt/renewal/npm-1.conf produced an unexpected error: Failed authorization procedure. mydomain.me (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https://mydomain.me/.well-known/acme-challenge/THE_ACME_KEY: Timeout during connect (likely firewall problem). Skipping.


All renewal attempts failed. The following certs could not be renewed:


  /etc/letsencrypt/live/npm-1/fullchain.pem (failure)


1 renew failure(s), 0 parse failure(s)
```

**Comment by jc21** [comment]
So from the log it seems that `mydomain.me` might not be configured in DNS to point to the IP you're running NPM on.

If you can confirm that your requests to that domain on HTTP at least are working as expected and coming through, then try and manually renew that certificate only in the Certificates page.

**Comment by rexx0520** [comment]
> So from the log it seems that `mydomain.me` might not be configured in DNS to point to the IP you're running NPM on.
> 
> If you can confirm that your requests to that domain on HTTP at least are working as expected and coming through, then try and manually renew that certificate only in the Certificates page.

Generating a new cert for the same domain works well, but neither auto renew and manually renew doesnt work.

**Comment by mikimite** [comment]
what worked for me is to change the npm-x.conf where x is your certificate to
`[webroot_map]
yourdomain.whatever = /var/www/html/
`


seems that the webroot is originally set to /data/letsencrypt/... but this is not the folder that nginx serves as webroot

**Comment by jc21** [comment]
I'm able to replicate the issue, looking at fixes.

**Comment by jc21** [comment]
Can anyone who has problems renewing certs manually, try this new docker image:
`jc21/nginx-proxy-manager:github-develop`
and let me know how you go.

**Comment by mikimite** [comment]
deployed, but i don't have any cert in renew period
I used --dry-run and failed, seems with the same issue because I checked the .conf file of the cert and remains the same
Do I have to do a clean deploy? or maybe generate a new cert and try to renew that?

**Comment by rexx0520** [comment]
I'm sorry that my server is down due to service migration. Will try in 3 days, thanks.

**Comment by chaptergy** [comment]
It you're still experiencing the problem let me know, I can reopen this.
