### ISSUE TITLE
444 drop connection on default site

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#287]
Would it be possible to have an additional radio button on the default site options to allow us to do 444 connection dropped?

Mostly to prevent processing requests with undefined server names, a bit nicer on security, especially if something gets screwed up on a config.

E.g. https://til.hashrocket.com/posts/cfd23c1a40-drop-connections-with-nginx

**Comment by jc21** [comment]
Definitely possible and would be an easy addition :)

**Comment by modem7** [comment]
Have moved to Traefik, will close issue unless someone else requires this functionality.
