### ISSUE TITLE
Wrap source domains on proxy hosts listing.

### ISSUE THREAD

**Issue by stk21** [jc21/nginx-proxy-manager#289]
I have a proxy host that is serving data for 10+ domain names.  When I put all of the domains in, the proxy host listing for each domain doesn't wrap, so the page scrolls way off to the right.  

Is there a way to allow the listings to wrap.  I have provided a screen shot for a visual. 
![Screen Shot 2020-02-05 at 9 31 40 AM](https://user-images.githubusercontent.com/32824148/73861566-721b2880-47fa-11ea-9b35-4264fcc51d60.jpg)

**Comment by stk21** [comment]
disregard.  I modified the main.css file inside of the container to remove the nowrap.  it might have ill effected on other areas that will wrap, but for this specific instance it fixed my issue and the domain names wrap now.  Probably would have been smarter to alter the css tag on that specific element in the tabler setup, but I didnt dig that deep into it.

**Comment by jc21** [comment]
This fix seems to have been added by another contributor, just not merged in to the latest yet. It's coming though :)
