### ISSUE TITLE
Setting up docker is not installation

### ISSUE THREAD

**Issue by john-clark** [jc21/nginx-proxy-manager#291]
**Describe the bug**
- Setting up your docker image should not be called installing

**To Reproduce**
1. Click on installation instructions
2. No installation information present

**Expected behavior**
1. Click on installation instructions
2. Information on installing presented

**Comment by jc21** [comment]
Closing - troll commenting on numerous github projects without any hope of contribution.

**Comment by john-clark** [comment]
Being abusive is not an answer.
