### ISSUE TITLE
proxy_headers_hash

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#292]
During startup of the Nginx container, I get the following message:

```
today at 4:35 PM 2020/02/11 16:35:39 [warn] 190#190: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
today at 4:35 PM nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
today at 4:35 PM 2020/02/11 16:35:39 [warn] 190#190: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
today at 4:35 PM nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
```

![image](https://user-images.githubusercontent.com/4349962/74260388-5a0f4180-4cf1-11ea-81da-334a9c6f668b.png)

Is there any way to pass an environmental variable to increase this, or do it dynamically?

Thanks

**Comment by modem7** [comment]
Have moved to Traefik, will close issue unless someone else requires this functionality.

**Comment by casperse** [comment]
My proxy just crashed showing this error? any fix to this? (Yes I have 33 sites running on it)

**Comment by jeremysherriff** [comment]
Create or edit the `custom/http.conf` file and add the following two lines;
```
proxy_headers_hash_max_size 1024;
proxy_headers_hash_bucket_size 128;
```

I have increased x2 over the defaults, you may choose other values that feel appropriate.

**Comment by FroggMaster** [comment]
> Create or edit the `custom/http.conf` file and add the following two lines;
> 
> ```
> proxy_headers_hash_max_size 1024;
> proxy_headers_hash_bucket_size 128;
> ```
> 
> I have increased x2 over the defaults, you may choose other values that feel appropriate.

I know it's been awhile since you posted this but what is the full path of `custom/http.conf` ? Encountering this error right now and I do not have a custom folder, or an http.conf within my NPM data directory.

**Comment by dmzoss** [comment]
It returns to me the same error and I insert the next configuration to the main nginx.conf file under /etc/nginx folder in the http scope
```
    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;
```

**Comment by Healzangels** [comment]
I was just working to resolve this and was trying something similar to what you had been @dmzoss. 
@FroggMaster Edit is the answer you're looking for where ever your /config has been mounted on the host will be a nginx folder. Mine contains things like directories: cache, dead_host, proxy_host.

In that location you'll want to create a new folder call custom like FroggMaster mentions above. Then with a http.conf with the two proxy _head lines also mentioned above.

Hope that helps!
