### ISSUE TITLE
wait-healthy script

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#297]
Heya, 

I realise it was only uploaded a few hours ago, but it's definitely something I've been looking for for a while. 

The wait-healthy script usage, is this more of an internal develop script, or would one be able to put it in a docker-compose file (e.g. command: ["./wait-healthy.sh", "db"]?

Thanks and apologies!

**Comment by jc21** [comment]
This script is used in CI to make sure the test stack is up and ready before integration testing can begin. It's something you have to use outside of docker/docker-compose - it just queries the `docker inspect` output to check for the healthy flag that docker sets itself with the internal `HEALTHCHECK` command. So it only works on containers that have this configured.

**Comment by modem7** [comment]
Ahhah! 

Thank you very much for explaining it! Appreciate it a lot!
