### ISSUE TITLE
add alias domain proxy

### ISSUE THREAD

**Issue by javadalmasi** [jc21/nginx-proxy-manager#3]
Hello
Please add alias domain proxy in the next version.
Thanks

**Comment by jc21** [comment]
Can do :)

**Comment by jc21** [comment]
Version 2 is ready for someone to test besides me. Have a read of [the documentation](https://github.com/jc21/nginx-proxy-manager/blob/v2/README.md) including the [installation instructions](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/INSTALL.md) and [importing guide](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/IMPORTING.md).

The app has only a few minor bugs I want to change but I'm using it in production myself on 4 instances. 

If you have issues, probably be to report them as new issues and mention that they affect version 2 in the description.

Thanks
