### ISSUE TITLE
help with Jellyfin Config

### ISSUE THREAD

**Issue by palitu** [jc21/nginx-proxy-manager#305]
I have jellyfin running in a container (via dockstarter), and it is reverse proxy'd by the letsencrypt container.  I am trying to migrate to NPM, but cannot figure out the settings.

Does anyone have a working jellyfin Rproxy that they can help me with?

I have tried the adding a folder, as per the standard instructions, but then the GUI shows, but wont play movies. 

This is the config for the letsencrypt nginx rev proxy:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jellyfin.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.X valid=30s;
        set $upstream_jellyfin jellyfin;
        proxy_pass http://$upstream_jellyfin:8096;

        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
    }

    location ~ (/jellyfin)?/embywebsocket {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.X valid=30s;
        set $upstream_jellyfin jellyfin;
        proxy_pass http://$upstream_jellyfin:8096;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
   }
}
```

how would i recreate this in NPM?

ta

**Comment by jc21** [comment]
It should be as simple as this:

![jellyfin](https://user-images.githubusercontent.com/1518257/75121928-9163f200-56e4-11ea-8e4e-b1f530ba3ee2.png)

where `192.168.0.10` is your upstream ip or hostname.

If you find that some things work in the browser and some don't, you have to inspect the Javascript/Developer tools console of your browser to get more info about why.

**Comment by palitu** [comment]
Thanks, i will try it as is an give it a go.

**Comment by palitu** [comment]
thanks - turns out i also needed a location

![image](https://user-images.githubusercontent.com/6634784/75637049-c4673200-5c5e-11ea-9e0f-b93a0cff4cd1.png)

**Comment by bunducafe** [comment]
> It should be as simple as this:
> 
> ![jellyfin](https://user-images.githubusercontent.com/1518257/75121928-9163f200-56e4-11ea-8e4e-b1f530ba3ee2.png)
> 
> where `192.168.0.10` is your upstream ip or hostname.
> 
> If you find that some things work in the browser and some don't, you have to inspect the Javascript/Developer tools console of your browser to get more info about why.

That's what I tried. Without SSL it is working, but with force SSL it quits with "internal error". Any hints?
