### ISSUE TITLE
tzdata not present in alpine image used in NPM

### ISSUE THREAD

**Issue by miguelwill** [jc21/nginx-proxy-manager#307]
the tzdata package is required to activate the time zone selected in the TZ environment variable

I installed the tzdata package in the container with the newest version, and after that the time zone was enabled

**Comment by jc21** [comment]
Okily will add that to the next build

**Comment by jc21** [comment]
Images have been rebuilt (latest, 2, 2.1.1), just pull again and the package will be there.
