### ISSUE TITLE
Cloudflare support

### ISSUE THREAD

**Issue by edouardkleinhans** [jc21/nginx-proxy-manager#308]
Is it possible to use certbot with cloudflare in front of it ?
https://certbot-dns-cloudflare.readthedocs.io/en/stable/

**Comment by jc21** [comment]
This has been logged as another task specifically to deal with DNS verification.

The problem is the UI - it doesn't have a flow for returning and waiting for DNS entries to be added and verified yet.

**Comment by webbson** [comment]
I am able to generate Let's encrypt certs through the interface with Cloudflare running in front of it on the domain without any problem.

**Comment by realJoshByrnes** [comment]
@webbson I'm also able to generate certificates behind a CloudFlare proxy, but I think @edouardkleinhans is asking for DNS verification

**Comment by edouardkleinhans** [comment]
Yes, i want to be able to use dns verification

**Comment by JoschaMiddendorf** [comment]
Yes please add support for DNS verification

**Comment by Dulanic** [comment]
Would love to see this, only thing preventing me from using this.

**Comment by chaptergy** [comment]
DNS challenges with cloudflare should be possible since mid 2020.
