### ISSUE TITLE
Option to disable ipv6 in 2.1.1 and above

### ISSUE THREAD

**Issue by axiom00** [jc21/nginx-proxy-manager#312]
Updated to the latest 2.1.1 and npm container no longer starts. Following error appears multiple time in the log.
`80 failed (97: Address family not supported by protocol)`

Researched the issue and it seems to be related to ipv6 being disabled and in my case ipv6 is turned off on my host.

As a temporary fix, I re-enable ipv6 and npm started no problem.

**Comment by asadhaider** [comment]
I also had this problem, have no need for ipv6 on my network so its' disabled and got the same error when trying to deploy Nginx Proxy Manager. Fixed it by enabling ipv6 on the host again.

**Comment by vsc55** [comment]
Hi,
I have had the same problem my solution was to modify the nginx configuration in the container to disable ipv6.

**Process:**
1. Check that the container is started.
2. We connect to the container:
`# docker exec -it nginx-proxy-manager /bin/bash`
My container name is "nginx-proxy-manager", you can get container list with:
`docker container list -a`
3. We install nano:
`#apk add nano`
4. We disable ipv6:
`#cd /etc/nginx/conf.d/`
`# nano default.conf`
We comment lines:
listen [::]: 80;
listen [::]: 443 ssl;
`#nano production.conf`
We comment lines:
listen [::]: 81 default;

With this, it would work again without ipv6 support.

**Comment by axiom00** [comment]
@jc21 Thank you for implementing the option to disable ipv6. Latest v2.2.2 works perfectly with the host's ipv6 disabled.

**Comment by jc21** [comment]
Glad to hear :)

**Comment by poudenes** [comment]
> 4\. nano production.conf



> Hi,
> I have had the same problem my solution was to modify the nginx configuration in the container to disable ipv6.
> 
> **Process:**
> 
> 1. Check that the container is started.
> 2. We connect to the container:
>    `# docker exec -it nginx-proxy-manager /bin/bash`
>    My container name is "nginx-proxy-manager", you can get container list with:
>    `docker container list -a`
> 3. We install nano:
>    `#apk add nano`
> 4. We disable ipv6:
>    `#cd /etc/nginx/conf.d/`
>    `# nano default.conf`
>    We comment lines:
>    listen [::]: 80;
>    listen [::]: 443 ssl;
>    `#nano production.conf`
>    We comment lines:
>    listen [::]: 81 default;
> 
> With this, it would work again without ipv6 support.

Maybe im stupid.
What to do after this?

I restart the Add-On inside HA, but then the old values are back.

**Comment by vsc55** [comment]
Hi @poudenes,
With the latest versions there is no need to do anything.
An option has been added in the docker to disable IPv6.
You have to use the following "ENV":
`DISABLE_IPV6=true`

https://github.com/jc21/nginx-proxy-manager/blob/546f8622360747e85ec07306ddf7ec0eef35e177/docker/docker-compose.dev.yml#L18

**Comment by poudenes** [comment]
> Hi @poudenes,
> With the latest versions there is no need to do anything.
> An option has been added in the docker to disable IPv6.
> You have to use the following "ENV":
> `DISABLE_IPV6=true`
> 
> https://github.com/jc21/nginx-proxy-manager/blob/546f8622360747e85ec07306ddf7ec0eef35e177/docker/docker-compose.dev.yml#L18

Thanks. I have installed this all as Add-On in HA. But let me look into it

**Comment by webspes** [comment]
> > Hi @poudenes,
> > With the latest versions there is no need to do anything.
> > An option has been added in the docker to disable IPv6.
> > You have to use the following "ENV":
> > `DISABLE_IPV6=true`
> > https://github.com/jc21/nginx-proxy-manager/blob/546f8622360747e85ec07306ddf7ec0eef35e177/docker/docker-compose.dev.yml#L18
> 
> Thanks. I have installed this all as Add-On in HA. But let me look into it

This options seems to no longer work, not supported key during build.

**Comment by webspes** [comment]
> > 4. nano production.conf
> 
> > Hi,
> > I have had the same problem my solution was to modify the nginx configuration in the container to disable ipv6.
> > **Process:**
> > 
> > 1. Check that the container is started.
> > 2. We connect to the container:
> >    `# docker exec -it nginx-proxy-manager /bin/bash`
> >    My container name is "nginx-proxy-manager", you can get container list with:
> >    `docker container list -a`
> > 3. We install nano:
> >    `#apk add nano`
> > 4. We disable ipv6:
> >    `#cd /etc/nginx/conf.d/`
> >    `# nano default.conf`
> >    We comment lines:
> >    listen [::]: 80;
> >    listen [::]: 443 ssl;
> >    `#nano production.conf`
> >    We comment lines:
> >    listen [::]: 81 default;
> > 
> > With this, it would work again without ipv6 support.
> 
> Maybe im stupid. What to do after this?
> 
> I restart the Add-On inside HA, but then the old values are back.

Don't restart the app, just enter "nginx -s reload". I found out after an hour of searching :)
