### ISSUE TITLE
Force Renewals

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#316]
Due to issues such as: https://www.cyberciti.biz/security/letsencrypt-is-revoking-certificates-on-march-4/?fbclid=IwAR2tqrjC2UVXpY2qx6dIYcg9-M8oSjhEZmiPN3CPFAd2Nsb6Z2NqkYYjyE0 and other compromise problems, it would be a good idea to have a "force renewal" option. 

I attempted the "renew" button, but all I got was:

```
today at 7:25 PM The following certs are not due for renewal yet:
today at 7:25 PM /etc/letsencrypt/live/npm-2/fullchain.pem expires on 2020-05-06 (skipped)
today at 7:25 PM No renewals were attempted.
```

**Comment by jc21** [comment]
The renew now option should be forcing, but I'll have to check if something has changed with the recent certbot update.

**Comment by modem7** [comment]
Have moved to Traefik, will close issue unless someone else requires this functionality.
