### ISSUE TITLE
mariadb-aria:latest

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#318]
Heya, 

Just as an FYI, for databases, it's typically not best practise to have "latest" listed, for minor versions, not too problematic, but for major versions, this can really break things if people aren't too used to databases and schemas. 

It might be worthwhile putting a static version number on there with instructions on how to update the database version + backing up.

db:
image: jc21/mariadb-aria:latest

**Comment by jc21** [comment]
Totally get that, which is why there is [also a 10.4 tag as well](https://hub.docker.com/repository/registry-1.docker.io/jc21/mariadb-aria/tags?page=1).

**Comment by modem7** [comment]
Ahhah! Perfect! Just making sure things were available! 

Just had a hiccup during the autoupdate to latest (a simple delete/recreate was enough to resolve), so thought I'd pop in and be "that guy" :P
