### ISSUE TITLE
HTTP Services all 404

### ISSUE THREAD

**Issue by coolsaber57** [jc21/nginx-proxy-manager#32]
Hello,

This may be more of an NGINX issue, but I'm trying to proxy my internal services (just HTTP at this point)(Sonarr/Radarr/Lidarr/etc.) to my server that's running the services, but all show the 404 page.

I'm trying to access, for example:   

`my.site/emby`

My config for this is: 

```
location /emby/ {
proxy_pass http://127.0.0.1:8096; # Local emby ip and non SSL port

proxy_hide_header X-Powered-By;
proxy_set_header Range $http_range;
proxy_set_header If-Range $http_if_range;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

#Next three lines allow websockets
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
```
I have a working config on another machine (just command line/config files only) where this works.  

For other services, I had to use:

`proxy_pass http://localip:8800/sabnzbd/`

Which appends a "/sabnzbd" after the Port number (Sonarr/Radarr/Lidarr/Sabnzbd require this).  

My questions are:

- For the 1st example (emby), is there something I'm missing to be able to get this to work? I can provide my other config (for the Server section) if needed.
- For the 2nd example (Sonarr/Radarr/Lidarr), is there a way to append that URL piece after the Port?

**Comment by coolsaber57** [comment]
As an addendum to this, setting these up as sub-domains instead of the folder structure does work (forwards correctly).

**Comment by cTurtle98** [comment]
I believe you are having the same problem as issue #40

**Comment by chaptergy** [comment]
Closing this, as there now are custom locations available for hosts.
