### ISSUE TITLE
Help configure proxy with path

### ISSUE THREAD

**Issue by mkozhin** [jc21/nginx-proxy-manager#320]
How can I configure the proxy in the web interface so that the stream 
http://mystream.com/stream.mp3
opens on my subdomain
https://stream.site.com

P.S. Sorry for my English

**Comment by miguelwill** [comment]
I think you can't redirect a file access directly without using a url rewrite rule

**Comment by chaptergy** [comment]
You can add a proxy host and under the advanced tab add

```
location = / {
  proxy_pass http://mystream.com/stream.mp3;
}
```
