### ISSUE TITLE
Cannot for the life of me, get nginx-proxy-manager to work with Discourse in a reverse-proxy-configuration.

### ISSUE THREAD

**Issue by Phoenixthedoggo** [jc21/nginx-proxy-manager#324]
I tried deploying (locally) a VM running Ubuntu Server 18.04 to run a piece of forum software called "Discourse"

The issue is when I attempt to forward traffic going to `domain.xyz` to address `x.x.x.x` and using certs installed / created locally on nginx-proxy-manager.

The installer (For discourse) _refuses_ to acknowledge port 443 is open, and when checking the authenticity of the domain it fails every time stating that 443 is unreachable, and that 80 **IS** reachable.

As for testing it myself, I get error 502's via Chrome, indicating the webserver is DOWN. Which is odd. It must be hunting for a file or something when it runs that test. ¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/20131900/76554488-f6994080-6463-11ea-9b8e-3cb468319d19.png)

I've read their documentation in regards to running it behind an NGINX server, but I don't understand how to apply it to nginx-proxy-manager itself. 🤔
(https://meta.discourse.org/t/running-other-websites-on-the-same-machine-as-discourse/17247)

If anyone here has experience in deploying a Discourse in a situation like this, I'd love some input. But as for now, I'm stuck here and cannot proceed any further.

**Comment by Phoenixthedoggo** [comment]
I should probably also include the config as displayed in Nginx-Proxy-Manager itself...
![image](https://user-images.githubusercontent.com/20131900/76555051-e9c91c80-6464-11ea-9d58-3f2c8586fc03.png)

**Comment by Phoenixthedoggo** [comment]
After further review, the above configuration was **correct.**
The issue I was facing was on Discourse's end, and it's configuration documentation in regards to using reverse proxies.

In their documentation they state to use / add the following argument into the `app.yml` file before compiling / building with Docker:
`- "templates/web.socketed.template.yml"  # <-- Added`
and to comment out:
```
- "80:80" # http
- "443:443" # https
```

After doing a complete wipe, redownload of Discourse's AiO installer and clean install **IGNORING** all of the aforementioned "requested steps" Discourse worked right out of the box if you just run ./discourse-installer, ignore the error and just slap your domain details into `app.yml` as well as SMTP mail server details into the file and compile / build with `./launcher rebuild app`

I'm marking this as closed, and for anyone else who happens upon this issue, this is how you fix it.
You can further contact me via my email listed on my Github Profile. 👍

**Comment by Vorkosigan76** [comment]
Hi @PhoenixSheppy , how did you finally set up discourse within npm?

1) which IP address and which port did you enter? My understanding is that the configuration used do not expose any ports...

2) if you are using the docker network bridge (the default discourse one), did you also install npm on bridge? Thats not very clean.
