### ISSUE TITLE
internal error when trying to issue certificate.

### ISSUE THREAD

**Issue by zaywalker** [jc21/nginx-proxy-manager#33]
First of all, thanks for the npm app :)

Just like as the title, when I try to get a certificate, npm returns internal error.

The log is bellow

```
Command failed: /usr/bin/certbot certonly --cert-name "npm-2" --agree-tos --email "admin@example.com" --preferred-challenges "http" -n -a webroot -d "test.example.com" 


/bin/sh: 1: /usr/bin/certbot: not found
```

I've looked into npm container /usr/bin, there is no certbot. It looks like changed to certbot-auto.

thanks again the npm!

**Comment by jc21** [comment]
Ok looks like I merged something I shouldn’t have. Use the ‘2.0.6’ docker tag for the previous version for now until I fix

**Comment by jc21** [comment]
I've reverted the upstream changes and the latests docker images are working as expected now.
