### ISSUE TITLE
Transfer all traffic who is not defined to one host

### ISSUE THREAD

**Issue by IIPoliII** [jc21/nginx-proxy-manager#335]
I am trying to pass all my traffic that is not from any of the mentioned domain to one host. 
I saw some post about transfering all nginx traffic to one reverse proxy host but it's not possible to make `*.*.*` in nginx proxy manage how could i transfer all the domains that are not defined to a machine?

**Comment by back2root** [comment]
Have a look under Settings -> Default Site -> Edit -> Redirect
![grafik](https://user-images.githubusercontent.com/9200239/77301684-6921e000-6cf0-11ea-9958-067bfd017136.png)

Is that what you are looking for?
