### ISSUE TITLE
URL based Reverse Proxy 

### ISSUE THREAD

**Issue by armagankaratosun** [jc21/nginx-proxy-manager#337]
Hello all,

I want to use nginx-proxy-manager to access my internal web services. But my problem is, I only want to use the IP of the nginx-proxy-manager to redirect my services based on URL, like

internal-service-1 -> http://nginx-proxy-manager-ip/internal-service-1
internal-service-2 -> http://nginx-proxy-manager-ip/internal-service-2
internal-service-3 -> https://nginx-proxy-manager-ip/internal-service-3

like; 

```
location /internal-service-1 {
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass              http://internal-service-1-ip:3000/;
}
```

Is it possible? If yes, how?

Regards,

**Comment by miguelwill** [comment]
yes, It works
only check with DNS

**Comment by armagankaratosun** [comment]
The problem is I don't have DNS, I only have IP address of the proxy-manager. I can't even edit my /etc/hosts file (or Windows equivalent).

**Comment by miguelwill** [comment]
to take advantage of the option to use a name that is addressed to several IPs I would recommend using dnsmasq, since you can define them using the hosts table

**Comment by wtf911** [comment]
![image](https://user-images.githubusercontent.com/5151430/79398150-e76b4e00-7f4d-11ea-9f98-e8020d103424.png)

You can use the custom location in nginx-proxy-manager to do this super easy no dnsmasq needed. make /service1/ point to service 1 and add location for /service/2 to point to service 2 ...and poof it works. www.test.com/service2/ etc.....

**Comment by miguelwill** [comment]
That's right, using folders you can route to other destinations and ports
the use of DNS was to direct in round-robin mode to more than one system or IP in the backend, as in the case of a cluster of web servers

**Comment by Motordom** [comment]
@wtf911 could you share your setup for qbittorrent? I cant get it working, keep getting 502 :(

**Comment by wtf911** [comment]
@Motordom You need to change a setting in qbittorrent. You have to disable one of those security ones under webui in options so it will allow that kind of redirect I think that's what I did.

![image](https://user-images.githubusercontent.com/5151430/81418353-884ac480-911a-11ea-899d-735b86c10dd8.png)
