### ISSUE TITLE
Error 400 on dotnet core + Blazor server application websocket

### ISSUE THREAD

**Issue by damianog** [jc21/nginx-proxy-manager#340]
I deployed a dotnet core application based on Blazor that make use of websocket communication.
a simple post on the host-proxy caused an Error 400 page

I am running the docker nginx proxy manager image v2.2.0
I configured my host-proxy by enabling with an SSL certificarte 

I managed to fix this strange behavior by editing the template file:

**/app/templates/proxy_host.conf**

and changed the following line

`
proxy_set_header Connection "upgrade";
`

in 

`
proxy_set_header Connection $http_connection;
`

Than after creating the host-proxy all run perfectly.

Here the origin of solution

https://github.com/aspnet/KestrelHttpServer/issues/1263

**Comment by jc21** [comment]
Thanks for doing the investigation. This all makes sense. I'll merge soon.
