### ISSUE TITLE
Mariadb

### ISSUE THREAD

**Issue by raidoo9** [jc21/nginx-proxy-manager#346]
Using Docker for Desktop on Win 10, when composing this:

> db:
    image: jc21/mariadb-aria:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql

I get this an error and the container won't run:

> The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!

However when composing this, no errors, container runs fine and I can log into NPM:

>   db:
    image: 'mariadb:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql

Can NPM work pulling mariadb from official repo or does it need to come from yours?

**Comment by divad942** [comment]
When I updated docker Windows from 2.2.0.4 to 2.2.0.5 I also stared receiving same error.
This are latest release notes from docker:
### 2020-03-31 2.2.0.5

* Bug fixes and minor changes
  - Docker Desktop generates `fsnotify.WRITE` events in Linux containers when files are changed on the host. Fixes [docker/for-win#5530](https://github.com/docker/for-win/issues/5530#issuecomment-585572414).
  - Fixed a race condition in `readlink` on shared volumes using "mfsymlinks". Fixes [docker/for-win#5793](https://github.com/docker/for-win/issues/5793).
  - Made the VM time sync more reliable. See [docker/for-win#4526](https://github.com/docker/for-win/issues/4526).
  - Fixed bug where files did not change in shared volumes when using `volumes_from` in `docker-compose.yml`. See [docker/for-win#5530](https://github.com/docker/for-win/issues/5530).
  - Fixed a bug where opening a read-only file would fail with an `Operation not permitted` error. Fixes [docker/for-win#6016](https://github.com/docker/for-win/issues/6016) and [docker/for-win#6017](https://github.com/docker/for-win/issues/6017).

@raidoo9 thanks for advice

**Comment by miguelwill** [comment]
yes, it can work with original images of mariadb, or bitnami, etc
in my case I have a 2-system cluster with the master-slave function using the bitnami image, which works without problems

**Comment by ionred** [comment]
For anyone else with this problem, I came across this as well. The latest mariadb even caused this error for me. I ended up pinning mariadb:10.2 and it worked like a charm

**Comment by jc21** [comment]
Also try `jc21/mariadb-aria:10.4.12` as it should forcibly disable innodb.

**Comment by maltokyo** [comment]
is the official mariadb docker image supported?  I would prefer to use that for long term support needs.  Any reason why we "need" to go for jc21/mariadb-aria?

**Comment by miguelwill** [comment]
yes, with the official mariadb as with the bitnami version with replication, so it should work with other mysql/mariadb implementations (with or without the docker, in the configuration file the connection host is indicated)

**Comment by maltokyo** [comment]
Thanks!
