### ISSUE TITLE
LE wildcard certs

### ISSUE THREAD

**Issue by BaneOfSerenity** [jc21/nginx-proxy-manager#36]
Does this container support using wildcards for the LE certs? Can it do the dns challenge for google? I looked through the images for the LE interfaces but i don't see anything that would allow this.

**Comment by jc21** [comment]
Unfortunately no. Because LE wildcards require DNS setups, I don't bother supporting them in this project. You can specify multiple domains for a single LE certificate however.

**Comment by ZataH** [comment]
Will you support it at some point?

**Comment by koshia** [comment]
I would like to +1 on this request; however low priority.  @jc21 I do agree it lets you add multiple domains/sub-domains, but i believe you are still limited to 10 per 90 days, iirc.  I'm already @ 8 subdomains and can see adding another 4-6 in the future.

**Comment by jc21** [comment]
The project's initial goal was to let beginners create ssl reverse proxies. Using LE wildcards requires that the app force users to leave it, add entries to dns, then come back and finish any setup. At this point, it doesn't feel "simple" and as such, very low priority for me.

**Comment by BaneOfSerenity** [comment]
That's true if you want to arbitrarily use wildcard certs. I use https://hub.docker.com/r/linuxserver/letsencrypt/ with the google plugin. You give the credentials, it passes those through to certbot and uses these scripts https://github.com/certbot/certbot/tree/master/certbot-dns-google to automatically create and destroy dns records in order to do dns validation for the wildcard certs. Maybe just the sites that have scripts to do these automatic records be a good start?

**Comment by jc21** [comment]
Yeah that's an interesting point. Supporting AWS and Google Cloud to begin with might be easiest. As long as the user understands the security implications of saving their service credentials and the UI process is simple.

**Comment by vrelk** [comment]
Take a look at this project, either for collaboration or inspiration.

https://github.com/Neilpang/acme.sh

**Comment by jc21** [comment]
Refer to #85 and #120.

**Comment by toxic0berliner** [comment]
sadly, neither #85 not #120 enable support for LE wildcard certificate.
I'd be very interested to have the gui to do this in nginx-proxy-manager, for the time beeing I cannot request any certificate for *.example.com since the ui doesn't let me, I've also seen some javascript alert message somewhere explicitely telling me it doesn't support it....
Any luck of reopening the issue and implementing it now that DNS challenge seems to be working ?
