### ISSUE TITLE
Help: Url base

### ISSUE THREAD

**Issue by joelang1699** [jc21/nginx-proxy-manager#363]
Hope someone can help.

I have multiple services runnings which I'd like to reverse proxy. I'm currently using nginx on an Ubuntu VM which I'd like to replace with NPM.

This is my current setup....

http://myservername/radarr to http://service-ip:port
http://myservername/ombi to http://service-ip:port

If I try and do this in NPM I just get a 404 return. I know it can be achieved using subdomains which I'd like to avoid. Can someone please tell me how to do this in NPM.

**Comment by nightcomdev** [comment]
1. https://nginxproxymanager.com/setup/ did you follow this Guide?
2. Did you add domain with A record at your domain provider? 
3. Ports 80 and 443 on your modem/router forward traffic to NPM?

**Comment by joelang1699** [comment]
Thanks for replying.

1. NPM is in a docker and is ready to run.

2. The domain is setup properly as I'm currently using CLI nginx.

3. All the ports are setup correctly it's simply the configuration of NPM I'm having trouble with.

Just been doing some research since my first post. It's seems NPM is not capable of supporting subfolders?

**Comment by nightcomdev** [comment]
I don't know about subfolders in NPM, not using this kind of solution so you need to wait on author.
You can make workaround on web server side, to listen domains (addresses) and forward to correct folder - this should work.

**Comment by joelang1699** [comment]
So I got it working...partially. Some services work perfectly, others don't. I still have my functioning standard nginx installation which dodes work.

The thread below details the use of subfolders by the author.
https://github.com/jc21/nginx-proxy-manager/issues/104

Thanks for your help mate.
