### ISSUE TITLE
Address already in use after update

### ISSUE THREAD

**Issue by Thijmen** [jc21/nginx-proxy-manager#371]
Hi all,

I am running this fantastic tool for a while. I want to update to the latest image, because of #356 (which got merged recently 🥳 ).

This is the error I get:

> app_1  | [4/15/2020] [12:58:05 PM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
> app_1  | [4/15/2020] [12:58:05 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
> app_1  | [4/15/2020] [12:58:05 PM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
> app_1  | Uncaught Error: listen EADDRINUSE: address already in use :::3000

I used `docker-compose pull` and I was under the impression that it would be an easy upgrade. I tried ` jc21/nginx-proxy-manager:2` and ` jc21/nginx-proxy-manager:latest`

Is there any way I can help debug this?

**Comment by Thijmen** [comment]
Nevermind, I found it. Apparently the newer version binds to port `3000`, and I am also proxy'ing a port 3000. Solved!

**Comment by Thijmen** [comment]
In hindsight, it would be nice if https://github.com/jc21/nginx-proxy-manager/blob/bb0f4bfa626bfa30e3ad2fa31b5d759c9de98559/backend/index.js#L24 was an env-variable. Maybe I'll contribute that in the future!

**Comment by jc21** [comment]
Well no it doesn't matter what port the backend binds to **inside** of it's own network. It matters to you, what port you expose to your host that maps to this internal port of 3000.

**Comment by Thijmen** [comment]
No, but if I already use port 3000 for nginx (streaming ports), it makes sense :) The message came from the container, not the host.

**Comment by jc21** [comment]
Ah yes of course

**Comment by Thijmen** [comment]
How do you feel about making it an ENV-var, @jc21 ?

**Comment by jc21** [comment]
I feel uneasy about it. The backend api can listen on any port easy enough with a env var deciding what that port is. But, the Nginx configuration forwards requests from the Admin UI to the API with `127.0.0.1:3000` and that would need to be dynamic as well.

**Comment by jc21** [comment]
As a workaround for yourself, you can map ports in your docker-compose file `3000:3001` and then set up a stream for `3001` to forward wherever you like.

**Comment by Thijmen** [comment]
Hmm yes, did not think of that, good point @jc21. I changed my infrastructure to adapt with the change anyway.
