### ISSUE TITLE
Unable stream

### ISSUE THREAD

**Issue by ghost** [jc21/nginx-proxy-manager#377]
I really love this useful project, I already add proxy host and it works perfectly. If I'm not mistaken understanding the stream feature, it can forward tcp/udp. However it fails when I try to forward my ftp or ssh session. Anyone knows how can I troubleshoot this? Any help would be greatly appreciated. Thank you

**Comment by jc21** [comment]
So you've probably set up a stream to forward, for example, port 21 to 192.168.0.10:21

But you probably haven't opened up the Docker Container to accept connections on port 21. I know this isn't a widely documented feature, but the ports aren't a widely used feature either.

Modify your docker-compose.yml file to open the ports you want to stream onwards and see how you go

**Comment by NanoG6** [comment]
The scenario is I want to forward incoming port TCP 1010, to destination IP xx.xx.xx.xx port (SSH) TCP 2020. I tried 1010:1010, 1010:2020, 1-65535:1-65535, but still no luck.
Sorry if it looks silly, I hope I understand this right.

**Comment by NanoG6** [comment]
Hi I got this working now, I just forgot to restart the docker-compose, my bad.
Anyway, can I just open all ports in docker-compose.yml so I don't need to specify one by one, and let me decide which port to use in NPM dashboard?

**Comment by jc21** [comment]
I do not recommend opening all ports with `1-65535:1-65535` as this converts to the native docker command `-p 1:1 -p 2:2 -p 3:3 ...` and it slows a lot of stuff down as well as being impractical.

The better solution is to run NPM docker container in [Host Network Mode](https://docs.docker.com/network/host/). If you are running your db in a docker container too, that might also have to be in host network mode and when doing so, the hostname for the database would be `127.0.0.1`
