### ISSUE TITLE
IP Based ACL

### ISSUE THREAD

**Issue by vrelk** [jc21/nginx-proxy-manager#38]
Please add support for IP based ACLs and Cloudflare IP correction.

https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-

**Comment by Fidelix** [comment]
This would be pretty cool. I'm currently doing this by adding an include manually to every host, but having this built-in is probably a natural feature.

**Comment by sjabby** [comment]
yes please.

**Comment by jc21** [comment]
Right so yeah I was also wanting IP range based options for the Access Lists but I forgot to consider the cloudfare / cloudfront ip forwarding as well. I'm able to get the latest cloudfront ip ranges with a script that I can program to fire once a day and I just saw [cloudfare has a list too](https://www.cloudflare.com/ips-v4)

**Comment by Subv** [comment]
Can this be closed now that #360 is merged?

**Comment by jc21** [comment]
Sounds good to me

**Comment by risiman** [comment]
That sounds great to me
