### ISSUE TITLE
A little help with a web server

### ISSUE THREAD

**Issue by PyroFD3S** [jc21/nginx-proxy-manager#381]
Hello, 
I'm trying to get my webserver to work with NPM but not having any luck. I had my Nginx server before moving to NPM to have a root of /var/www/html and I would serve pages off a subfolder of that root, like a wiki... so when I went to http://mydomain.ca/wiki it would serve the pages from /var/www/html/wiki 

in my Nginx conf, all I had to do was put :
    location /wiki {
	}
but that doesn't seem to work with NPM 
Could I get some help please?

**Comment by nightcomdev** [comment]
use "Custom Locations" in settings of domain - that's what it is for
