### ISSUE TITLE
Redirects get Connection refused

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [jc21/nginx-proxy-manager#386]
**Describe the bug**
- Running v2.2.3
When using any of the proxy hosts, I get an 'connection refused' error. However, these hosts are accessible when I use the CLI inside the NginxProxyManager container. Both the proxy manager and these hosts are in a docker network together. 

I've tried many things, like recreating proxymanager container, recreating the proxy hosts container. Changing ports, etc. Nothing seems to work. 

**To Reproduce**
1. Go to proxy hosts page
2. Click on the source URL of any of the proxy hosts
3. Browser shows connection refused error
4. Going to the destination URL directly does work (i.e. hosts are up and accessible)

**Expected behavior**
1. Go to proxy hosts page
2. Click on the source URL of any of the proxy hosts
3. Get redirected to the proxy host

**Operating System**
- Running on Unraid 6.8.3 with MariaDB database.

**Comment by BlaM** [comment]
I have the same problem - Did you solve the issue? Or just close the ticket?

**Comment by Baukebrenninkmeijer** [comment]
@BlaM at some point it just started working again. I think I did start fresh again, and had to reset all connections. It was not fun, and I did not really 'solve' the issue.
