### ISSUE TITLE
Disabling caching

### ISSUE THREAD

**Issue by Laizrod** [jc21/nginx-proxy-manager#389]
Hi. I don't even know if this is an actual issue, but I'm facing a caching problem with one of my websites (running Apache). 
After investigations, I found out that nginx cache was causing my problem. I tried a lot of things I've googled, but nothing worked.
Could you please tell me how to disable nginx cache on a specific proxy host?

Thank you

**Comment by mrneutron42** [comment]
I'm having the same problem.  It looks like Cache Assets control does not work in the GUI.
Thus, we have to put the line:
proxy_cache off;
into each of the proxy config files.
I think it goes in the "location / {" section of:  ~nginxproxymanager/data/nginx/proxy_host/1.conf

I got this from reading:
https://stackoverflow.com/questions/54136265/nginx-reverse-proxy-disable-cache
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache

**Comment by chaptergy** [comment]
I think you misunderstand the cache assets toggle. All it does is specifically cache css / js / image files by including [this nginx config](https://github.com/jc21/nginx-proxy-manager/blob/develop/docker/rootfs/etc/nginx/conf.d/include/assets.conf).

The cache should be disabled by default I think. But just to make sure you can just add the three lines you have mentioned to the advanced config tab:

```nginx
proxy_no_cache 1;
proxy_cache_bypass 1;
proxy_cache off;
```

**Comment by mrneutron42** [comment]
> The cache should be disabled by default I think.
No, the default is clearly proxy_cache on, which is why we were trying to find a way to turn it off.
I've got a webcam image on a weather station webserver.  The webcam image got cached by NGINX and the same image was repeated (not refreshed) with each refresh of the web page.
Adding the 3 conf file lines I mentioned, stopped the caching and the webcam image now updates, with each page refresh, as desired.

**Comment by chaptergy** [comment]
Weird, I'm not sure why it should be activated, since the only config contained in npm seems to be [to switch it off](https://github.com/jc21/nginx-proxy-manager/search?q=proxy_cache). But glad it works.

**Comment by mrneutron42** [comment]
Do you think it would be difficult to add switch to the GUI to turn off the cache?
That would be a nice feature to have!
Should I make a feature request?

**Comment by chaptergy** [comment]
Sure, go ahead
