### ISSUE TITLE
500 Internal error on access lists

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#393]
![image](https://user-images.githubusercontent.com/4349962/80892716-2de9d800-8cc4-11ea-9c9d-6738240424e7.png)

Latest version

**Comment by Indemnity83** [comment]
Any chance of getting the java console log, network response, or docker log for this? not going to be able to do much without more information here.

**Comment by modem7** [comment]
> 
> 
> Any chance of getting the java console log, network response, or docker log for this? not going to be able to do much without more information here.

Of course!


```
[5/10/2020] [8:39:35 AM] [Express  ] › ⚠  warning   select `access_list_client`.* from `access_list_client` where `access_list_client`.`access_list_id` in (1, 3, 2, 4, 5) - ER_UNKNOWN_STORAGE_ENGINE: Unknown storage engine 'InnoDB'


[5/10/2020] [8:39:37 AM] [Express  ] › ⚠  warning   select `access_list_client`.* from `access_list_client` where `access_list_client`.`access_list_id` in (1, 3, 2, 4, 5) - ER_UNKNOWN_STORAGE_ENGINE: Unknown storage engine 'InnoDB'
```

Docker log:
https://pastebin.com/rhJvhKtz

Docker compose:
https://pastebin.com/7Ny5fRTi

Let me know if you need the java log and network response (unsure how to get the network response in this case) on top of these.

Thanks!

**Comment by Indemnity83** [comment]
I notice in your compose file you have an image commented out; did you use `mariadb:latest` when upgrading to v2.2.3?

It may have created to access_list_client table using `InnoDB`. the `jc21/mariadb-aria` image [disables `InnoDB`](https://github.com/jc21/docker-mariadb-aria/blob/08926ef8228978c92e72edbf1c955a9647bb30dd/00_aria.cnf#L5), which would cause the error you're seeing above. 

Try swapping back to `mariadb:latest` and see if it works. I'm not sure what the ramifications are of using `InnoDB` here are, @jc21 would probably have to weigh in if it means you need to actually 'fix' your database or just stick with `mariadb:latest`.

**Comment by modem7** [comment]
Ah no, the update was done a few months ago - I need to clean up my docker compose!

I've been on mariadb-aria since just before March.

**Comment by Indemnity83** [comment]
It may still be that the database is set to use InnoDB as the default table storage engine.

I still think it is worth trying (after making a backup) swapping back to the `mariadb:latest` image for the DB. It really looks like your accees_list_clients table got built with the InnoDB engine and `jc21/mariadb-aria` won't be able to open it

**Comment by Indemnity83** [comment]
```sql
ALTER TABLE accees_list_clients ENGINE=Aria;
```

*seems* like it would fix it, but I obviously have no way to test this

**Comment by modem7** [comment]
Ahhah - do you know if (and I'll make a backup regardless of the volume(s)) npm will re-create the database entries and populate with the data?

If not, it's no biggie, bit of a bugger but 20 minutes of work will restore the whole thing

**Comment by Indemnity83** [comment]
the DB container *should* just come up with all the data still in-tact (it's all in the /var/lib/mysql volume).

**Comment by modem7** [comment]
Looks like switching to mariadb did the job! 

Do we want to keep this open to investigate jc21/mariadb-aria or close it?

Thank you very much!

**Comment by Indemnity83** [comment]
I’m certain it’s because the DB was created in one environment then switched. Generally not a problem until a new table is added. 

There may be a similar alter database command to change the default table engine too.

**Comment by modem7** [comment]
For now, let's assume that your thoughts are correct on this one! I know I did recreate things, but whether I did it with the same volume or not, I cannot recall! 

We'll close this for now as things are working as intended, and hopefully it won't resurface!

Thank you once again!
