### ISSUE TITLE
Letsencrypt broken for IPv6

### ISSUE THREAD

**Issue by thomaspurchas** [jc21/nginx-proxy-manager#394]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? ✅ 
- Are you sure you're not using someone else's docker image? ✅ 
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? ✅ 

**Describe the bug**
Unable to create Lets Encrypt certificates when server is only accessible via IPv6

**To Reproduce**
1. Create _only_ AAAA DNS record for domain.
2. Try and create Lets Encrypt SSL cert.

**Expected behaviour**
SSL certificate should be created

**Additional context**
The Let Encrypt `.conf` does not listen on IPv6.
https://github.com/jc21/nginx-proxy-manager/blob/4c60bfb66bae09ae5d3edb930fbd414232951261/backend/templates/letsencrypt-request.conf#L3-L5

I think this can be fixed by adding
```
{% if ipv6 -%}
  listen [::]:80;
{% else -%}
  #listen [::]:80;
{% endif %}
```
to the template, or including `_listen.conf` instead of statically defining the `listen` directive

**Comment by jc21** [comment]
Ah yes that would do it..

Thanks for the comprehensive report by the way :)
