### ISSUE TITLE
No loading of configuration after reimport of SQL dump

### ISSUE THREAD

**Issue by MartinKuhl** [jc21/nginx-proxy-manager#399]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? -> xes
- Are you sure you're not using someone else's docker image? -> yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? -> yes

**Describe the bug**
- after a restore of the configuration (db entries) all SSL Certificates and Configuration is back. But it is not functional. I have to open a configuration an simply save it without any edit and now the SSL configuration is working.  

**To Reproduce**
after a restore (docker exec -it db bash -c "mysql -uXXX -pYYYY nginx < /var/www/html/interface/nginx/nginx-backup.sql")  of the configuration (db entries) all SSL Certificates and Configuration is back. But it is not functional. I have to open a proxy host configuration and simply save it without any edit and now the SSL configuration is working.  
Without these "edit" I get a NET::ERR_CERT_INVALID error message.
Is there any way to do these edit via script?

**Expected behavior**
After loading the backup everything working without editing and saving each entry of host proxy configuration.

**Operating System**
- Docker in Mac OS (latest versions)

**Additional context**
- Chrome and Safari

**Comment by Indemnity83** [comment]
When you restored the SQL backup, did you also restore all the configuration files that are stored in the /data volume?

Nginx doesn't read its configurations from the database, it loads the files stored in /data. It sounds like you've restored the database but not the configuration files. Re-saving the hosts will re-generate the Nginx configs and reload Nginx so it picks up the changes.

**Comment by MartinKuhl** [comment]
That was the missing hint. After saving and restoring the folder /data/nginx together with a database dump and restore now everting is back and ready to work.
