### ISSUE TITLE
Make it available for ARM?

### ISSUE THREAD

**Issue by andlil** [jc21/nginx-proxy-manager#4]
Hi!
This looks like an awesome thing for a RaspberryPi, any chance of building a docker image for armv7l?

Best regards
//A

**Comment by jc21** [comment]
It was a nightmare but I managed to get a `armhf` docker build together.

You can instantiate it on your raspberry pi with this example command:
```bash
docker run -d \
    --name nginx-proxy-manager \
    -p 80:80 \
    -p 81:81 \
    -p 443:443 \
    -v /path/to/config:/config \
    -v /path/to/letsencrypt:/etc/letsencrypt \
    --restart always \
    jc21/nginx-proxy-manager:latest-armhf
```

I've only tested that the UI shows and basic nginx functions work. Let me know if there are any issues, especially with Let's Encrypt.
