### ISSUE TITLE
Configuring Nginx Proxy Manager with wordpress??

### ISSUE THREAD

**Issue by wagners1** [jc21/nginx-proxy-manager#400]
Hi,

Has anyone had any success configuring NPM with wordpress.  I have been trying to figure it our for agers with no success.  The website can be accessed normally but when I point NPM to the ip address and port it will not work.  I just get a connection timeout.  I get the domain and the port.

I have about 10 services that NPM work flawlessly with but I just cant get wordpress to work.  Can someone assist please?

Thanks in advance.
Simon

**Comment by wagners1** [comment]
I finally figured it out....  thx to below link.  Minor edit below.

https://ahenriksson.com/2020/01/27/how-to-set-up-wordpress-behind-a-reverse-proxy-when-using-nginx/

In order to fix this you first have to add this at the very start of your wp-config.php.

define('FORCE_SSL_ADMIN', true);
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
 $_SERVER['HTTPS']='on';

Then in the end of the file add the following, replacing “website.com” with your own URL.

define('WP_HOME','https://website.com');
define('WP_SITEURL','https://website.com');

The website should now work correctly.

for me 
proxy_set_header X-Forwarded-Proto https;
was not required in NPM

**Comment by theraw** [comment]
if you install ssl on your wordpress on nginx proxy manager use port `443` not `80` if your wordpress has no ssl then use port 80, i don't see a reason why it should fail.

**Comment by Abs0lutZero** [comment]
I've got the same problem. Deployed Wordpress using OpenLiteSpeed

The Wordpress Admin page works flawlessly but the main site is not loading all its content.

I tried your fix @wagners1 but it didnt work for me

**Comment by theraw** [comment]
@Abs0lutZero that is just your template problems or browser cache has nothing to do with this project
![image](https://user-images.githubusercontent.com/32969774/81737526-84ab9a80-9498-11ea-8baa-30057514a900.png)
![image](https://user-images.githubusercontent.com/32969774/81737561-92f9b680-9498-11ea-8f06-552b627b9948.png)
![image](https://user-images.githubusercontent.com/32969774/81737628-ac026780-9498-11ea-8512-6b79412bfafe.png)
![image](https://user-images.githubusercontent.com/32969774/81737654-b7ee2980-9498-11ea-9b56-9dd2c74362bb.png)

tested with multiple themes

**Comment by Abs0lutZero** [comment]
Thanks @theraw 

I did a clean install of my OLS + WP deployment and set up the proxy as http on port 80 and now everything works.

**Comment by huangwb8** [comment]
@wagners1 Your setting is not work for me. I still get ERR_TOO_MANY_REDIRECTS.

Would you please share your NPM settings?

**Comment by jr0w3** [comment]
> @wagners1 Your setting is not work for me. I still get ERR_TOO_MANY_REDIRECTS.
> 
> Would you please share your NPM settings?

A few days ago, I had the same problem as you. This one didn't come from npm, but from the apache config.

I share you my settings if it can help you:

**My vhost:**
**__________________________________________**
<VirtualHost *:80>
ServerAdmin webmaster@mydomain.com
ServerName mydomain.com
ServerAlias mydomain.com.dev

DocumentRoot /mnt/nfs/vhost/mydomain.com
<Directory /mnt/nfs/vhost/mydomain.com/>
        Options FollowSymLinks
        AllowOverride Limit Options FileInfo
        DirectoryIndex index.php
        Require all granted
</Directory>

<Directory /mnt/nfs/vhost/mydomain.com/wp-content>
 Options FollowSymLinks
        Require all granted
</Directory>

ErrorLog /mnt/nfs/vhost/system/mydomain.com/logs/error.log
**__________________________________________**

**Line added to my wp-config.php:**
**__________________________________________**
define( 'WP_HOME', 'http://mydomain.com' );
define( 'WP_SITEURL', 'http://mydomain.com' );
**__________________________________________**

**My host in NPM**
**__________________________________________**
Source: mydomain.com
Destination: http://IPADRESS:80
SSL: Custom

Details:
![image](https://user-images.githubusercontent.com/86167909/171686326-33a21699-32bf-4058-978a-47786a545ee9.png)

SSL:
![image](https://user-images.githubusercontent.com/86167909/171686412-430ba632-c29b-4581-b571-d1fbcd65cb7e.png)
**__________________________________________**

For me, this config work. I hope it will help you.

**Comment by daominhsangvn** [comment]
For the people who tried all above method not working, try this (its working for me, none of above did)
Add the following config to your nginx config file
```
...
location / {
        proxy_set_header        Host $host:$server_port;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass http://10.0.0.1:80; <<< Correct this to your WordPress internal server IP and port
}
...
```

**Comment by theraw** [comment]
@daominhsangvn remember that if you change something from panel these custom changes manually done to nginx configs could be lost.

**Comment by huangwb8** [comment]
@RapidFire05 Yes, NPM is OK. My solution is use Full mode of SSL/TLS in Cloudflare, the DNS provider of my domain:
![image](https://user-images.githubusercontent.com/35643122/220783109-3261dd42-9ada-4883-950c-34e0b4d7b119.png)
Sorry for the delay reply. I just forget the problem I ask (ฅ´ω`ฅ)

**Comment by coderofsalvation** [comment]
Ok, just for completeness, one of the main culprits is `$request_uri` (which is passed by default to proxies using `include /data/nginx/custom/server_proxy[.]conf;`).

`$request_uri` always represents the **original** url (not affected by nginx rewrites/redirects etc).
This is sane & secure proxy-behaviour, so for simple wordpress rewrites you can just copy/paste its contents to the advanced-tab (but excluding `$request_ur`)

```
# START Nginx Rewrites for Rank Math Sitemaps
rewrite ^/sitemap_index.xml$ /index.php?sitemap=1 last;
rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
# END Nginx Rewrites for Rank Math Sitemaps 

# this is basically: include /data/nginx/custom/server_proxy[.]conf (but without $request_uri )
location / {
  add_header       X-Served-By $host;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Scheme $scheme;
  proxy_set_header X-Forwarded-Proto  $scheme;
  proxy_set_header X-Forwarded-For    $remote_addr;
  proxy_set_header X-Real-IP          $remote_addr;
  proxy_pass       $forward_scheme://$server:$port;
} 
```

**Comment by s-wighton** [comment]
I've been following this issue as I've had my own problems with the site health complaining of:

- Error: cURL error 28: connection timed out after 10001 milliseconds (http_request_failed)
- Error: cURL error 35: error:0A00010B:SSL routines::wrong version number (http_request_failed)

This may help others troubleshooting WP / NPM config issues.

Additional step that resolved the errors for me was adding the NPM server IP and website domain name on the WordPress web server  **/etc/hosts**

```shell
127.0.1.1 wp.homelab wp
127.0.0.1 localhost
192.168.1.1 www.website.com
``` 

For completeness my configs are:

**/var/www/website.com/wp-config.php**

```shell
define('WP_HOME','https://website.com/');
define('WP_SITEURL','https://website.com/');

if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
        $_SERVER['HTTPS'] = 'on';
}

if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
        $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}

if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
    $mte_xffaddrs = explode( ',', $_SERVER['HTTP_X_FORWARDED_FOR'] );
    $_SERVER['REMOTE_ADDR'] = $mte_xffaddrs[0];
}
```

**/etc/apache2/sites-enabled/website.com.conf**

```shell
<VirtualHost *:80>
        ServerAdmin admin@website.com
        ServerName wp.homelab
        ServerAlias www.website.com
        DocumentRoot /var/www/website.com
        <Directory /var/www/website.com/>
                Options FollowSymLinks
                AllowOverride Limit Options FileInfo
                DirectoryIndex index.php
                Require all granted
        </Directory>
        <Directory /var/www/website.com/wp-content>
                Options FollowSymLinks
                Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

Same NPM set up as above, however I removed **all** the Custom Nginx Configuration, and it's still working. 🙏

**Comment by robtry** [comment]
I wrote a tutorial with the config that worked for me
https://robgg.hashnode.dev/wordpress-docker-nginx-proxy-manager-cloudfare
