### ISSUE TITLE
Allow user to download SSL certificate

### ISSUE THREAD

**Issue by theraw** [jc21/nginx-proxy-manager#404]
Hello,

I would like to be allowed to download ssl/cert/key from dashboard.

also it would be nice if you replace the number count of vconf file and ssl folder from number to domain/subdomain name!

ex when i create first proxy_host you create nginx vhost as `1.conf` it will be better if `domainname.com.conf` this way i more easy to find out where is domain config file or ssl folder!

**Comment by gkroonder** [comment]
There are some good questions in #683; I personally would like to see certificate-foldernames in /etc/letsencrypt/live/ to use the certificate name as show in the GUI. I.e. "domain.ext".

That IMHO would make it much easier to re-use the certs from NPM in other docker containers, something that will come up again and again...

I've looked at the code and I see it is not a simple change.
But maybe it is possible to make symlinks the active certs to a 'static' [cert displayname] location?
I.e. /certificates/mydomain.ext (wildcard or tld) or /certificates/host.mydomain.ext (for hostname certs).
It could be a separate dir && docker-volume i.e. /certificates, or a dir under the data or letsencrypt volumes.

I wish I was a programmer and could help a bit, but alas, I can just (barely) get the gist of the code.

Thanks for listening to my input.

Best regards,

George

**Comment by chaptergy** [comment]
For now https://github.com/jc21/nginx-proxy-manager/pull/1100 has been implemented to make it generally possible to know which certificate is which.

**Comment by chaptergy** [comment]
Added via https://github.com/jc21/nginx-proxy-manager/pull/1343
