### ISSUE TITLE
Add Upstream to Proxy Hosts

### ISSUE THREAD

**Issue by mmhy2003** [jc21/nginx-proxy-manager#410]
I love your solution but I wish if you can extend your solution feature to support upstream where you can add multiple IP/Hosts per proxy host **Loadbalancing**

**Comment by netsujit** [comment]
+1 for this ^^

**Comment by jc21** [comment]
There are some considerations with upstreams but yep definitely on the nice-to-have list!

**Comment by SDekkers** [comment]
Could we maybe bump this to the should-have list? 
There isn't any other way to configure upstreams having multiple hosts it seems.

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/156
