### ISSUE TITLE
All in one docker container 

### ISSUE THREAD

**Issue by antipiot** [jc21/nginx-proxy-manager#418]
Hello!
First of all thanks for your great work, Nginx-proxy-manager looks great and is very easy to use!

I may suggest some changes to make things even easier for beginners:

Actually for Nginx Proxy Manager to work, you need 2 containers running and i feel it would be great and easier to run if everything was packed in a single container, so both Nginx and db would reside in the same docker container.

This way you may not to have to create a config file and  use docker compose and just run docker run -d
As another + i have a lot of containers running, and if every one of them would reside on external db, it may possibly double the number of running containers .

It may be possible to leave support for an external db in case of need

**Comment by Tontonjo** [comment]
> Yes, but if every container uses an external DB you just need one single DB to provide storage for them all, and don't need to run many instances of the same little used DB system.
> 
> You already can run this without creating a config file, or using SQLite.

Sorry for my late answere - thanks for your reply.
You're absolutely right - i'm not used to this :-)

Thanks for helpling and clarifying!

**Comment by antipiot** [comment]
> Yes, but if every container uses an external DB you just need one single DB to provide storage for them all, and don't need to run many instances of the same little used DB system.
> 
> You already can run this without creating a config file, or using SQLite.

Sorry for my late answer - thanks for your reply.
You're absolutely right - i'm not used to this :-)

Thanks for helping and clarifying!
