### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by NanoG6** [jc21/nginx-proxy-manager#424]
I'm stuck at version 2.2.3, how to update/upgrade to 2.2.4? Thank you

**Comment by jc21** [comment]
Just pull and use the `latest` or `2` or `2.2.4` docker image.

```bash
docker-compose pull
docker-compose up -d
```

**Comment by NanoG6** [comment]
Great thanks! Learn new thing everyday 😃

**Comment by NanoG6** [comment]
Hi @jc21, I think your README or how to tutorial need to cover basic command like this. 

Like how to setup from scratch, in detail, for example:
1. mkdir and cd to npm directory
2. vi config.json and docker-compose.yml
3. Etc..

I visited this github page several times, but sadly the one who make me successfully install NPM is another fellow's blog 😅

**Comment by ylluminate** [comment]
I also would agree that alternate installation methods would be nice. Many consider Docker somewhat dead at this point with all of the horrible news over the last few years. Personally I'd prefer to use an LXC on Proxmox or a simple straight install as well.

**Comment by jc21** [comment]
I'm locked into docker due to the inconsistencies with NodeJS. It's hard enough to support this project when I have control over the container, environment, binaries and versions within it. I am planning to move away from NodeJS in future and provide the base files for anyone to extend and create an LXC for example. It's slow going though.

@NanoG6 any chance you could share the link, would like to give this person kudos!

**Comment by NanoG6** [comment]
@jc21 it's https://agurk.net/install-nginx-proxy-manager/
He's blocking my country in his firewall/waf so I need to use VPN, don't know if you can access his blog or not.

As you can see, he write a quite detailed step by step to install NPM, starting from mkdir npm, cd npm, touch config.json, etc, etc,. Something you missed at the beginning of your tutorial.

For 5 years old like me, reading your tutorial (https://nginxproxymanager.com/#quick-setup, and https://nginxproxymanager.com/setup/) be like,
"what is the config file name? Where should I put that file? Etc.." :D

**Comment by jc21** [comment]
Thanks I can see his site.

I have this conflict between what I think my target users are and what they actually are, the latter of which I don't have much visibility over.

I thought my target was people who understand IP networks and Ports and are capable of running their own home services. But just want an easy way to manage web access from outside of their network in a secure manner.

It seems the big blocker for people is the docker/docker-compose way of spinning up these services which is understandable.

**Comment by NanoG6** [comment]
> I thought my target was people who understand IP networks and Ports and are capable of running their own home services. But just want an easy way to manage web access from outside of their network in a secure manner.

That's why I'm here. I know what is IP address, firewall, ports, reverse proxy (in general way).

> It seems the big blocker for people is the docker/docker-compose way of spinning up these services which is understandable.

That's correct Sir!
I love this product because it's useful, yet very simple, straight to the point. Keep up the good work!

**Comment by ylluminate** [comment]
I will say that I'm a "Docker resister". While we've deployed some such apps over the years, most of our own clients still hate Docker and such tech unless it's very nicely wrapped (such as Nanobox that DO acquired). 

Personally I found this useful and ended up deploying with PhotonOS on a Hyper-V system we're underutilizing: https://web.archive.org/web/20190315113829/https://blog.sportel.eu/nginx-proxy-manager/

Sadly the original seems to be having problems. 

I also modified the steps somewhat and combined some from this:
https://shiftfourteen.com/reverse-proxy-nginx-proxy-manager-duck-dns/

I also used CloudFlare for an adhoc DDNS service via this with a tiny Alpine LXC on Proxmox:
https://letswp.io/cloudflare-as-dynamic-dns-raspberry-pi/

**Comment by raffieyeah** [comment]
@jc21 I just installed npm following the guide on the website, but like @NanoG6 mentioned, there's a few steps that are missing so to speak (for noobs) such as creating a directory, creating the config.json file (using vim or nano for example) and creating the docker-compose.yml (same). If you'd like I am willing to add these things.

I guess you could add the guide pages in this repo and then auto upload to your website hosting on commits? Just a suggestion!
