### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by modem7** [jc21/nginx-proxy-manager#426]
**What is troubling you?**

For some unusual reason, all my sites are currently saying 502 bad gateway. 

IP address hasn't changed, internally all docker containers are working as expected, and no changes have been made on my end. Things seem to have been working until a system reboot. 

Which logs would you guys need? I'm not quite sure where the issue lies in this case. 

Docker compose:
https://pastebin.com/AAU3RtDE

Error log:
[error.log](https://github.com/jc21/nginx-proxy-manager/files/4685361/error.log)

Issue started in the last 4 hours or so.

Thanks in advance!

**Comment by modem7** [comment]
User error. NIC config was incorrect and applied on reboot

**Comment by ylluminate** [comment]
@modem7 where did you find this log?
