### ISSUE TITLE
2.3.0 - Access list allow rules not applying to nginx config files.

### ISSUE THREAD

**Issue by Chewza** [jc21/nginx-proxy-manager#434]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Yes
- Are you sure you're not using someone else's docker image?
Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
Yes

**Describe the bug**
2.3.0 does not apply the ALLOWED IP access lists to the individual nginx config files.

**To Reproduce**
1) Create access list with IP address with ALLOW rule.
2) Attach rule to proxy_host
3) Observe that no Allow rule is created above the deny all rule.

**Expected behavior**
Specified allow rules should apply above the default deny all; 

Issue not present in 2.2.4 branch.

**Comment by Subv** [comment]
Could you try #435 please? it seems to fix the issue

**Comment by cmitz** [comment]
Can confirm #435 fixes this issue
