### ISSUE TITLE
NPM is down: "finish: applet not found"

### ISSUE THREAD

**Issue by SAOPP** [jc21/nginx-proxy-manager#436]
Hi!

Guys, after the latest docker container upgrade have an next issue:

![image](https://user-images.githubusercontent.com/5647009/83321216-b2ddf800-a256-11ea-9b71-0522d344a978.png)

Also, admin webface is not available. So, my npm is down, redeploy also is the same resault. What's happened who know?

**Comment by jc21** [comment]
I've encountered this problem just recently, with 2 different Centos 7 hosts running latest version of docker. This only seems to happen when building the container in CI on those hosts, but when running an image built with a different host, it works fine.

The error you're seeing suggests that the Nginx binary inside the container is not built for the architecture you're running it on, however I'm 100% sure it's a red herring and the problem is a result of something else.

Could you please check that the docker tag `2.2.4` works differently?

For reference, here's my docker version:
```
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9424aeaee9
 Built:             Thu May 28 22:18:06 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.10
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9424aeaee9
  Built:            Thu May 28 22:16:43 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
and kernel: `3.10.0-1127.8.2.el7.x86_64`

**Comment by SAOPP** [comment]
Hi. one second I will check... before I'm had trying to use tag 2 and 3... instead latest, but faced with the same issue.

**Comment by SAOPP** [comment]
Yes this build is working thanks. +1

**Comment by SAOPP** [comment]
Solution: https://github.com/jc21/nginx-proxy-manager/issues/436#issuecomment-636289064

**Comment by jc21** [comment]
My comment was not a solution, it was a downgrade for those with this current problem.

**Comment by jc21** [comment]
Right so I think I've got to the bottom of it. 2.3.0 uses OpenResty now instead of Nginx vanilla.

OpenResty by default only supports cpu's with SSE 4.2+ by default. Looking in to a fix.

**Comment by jc21** [comment]
The `latest`, `2` and `2.3.0` tags have been rebuilt to support those older CPUs. Please try again and reopen if you have more troubles.

**Comment by SAOPP** [comment]
Pulled now latest image and redeploy it, all seems fine now. Thanks. And actually yes, my copy running at very old small pc, I'm using it for some small docker server, and on board something like pentium d500 like that.

**Comment by jc21** [comment]
Awesome. I'm likely to drop support for those older CPU's in version 3 but that's a while off.

**Comment by SAOPP** [comment]
Essentially, if, then this is the right decision, since the problems of old processors are not rational in a brand new software.
