### ISSUE TITLE
502 Bad Gateway due to proxy buffer size

### ISSUE THREAD

**Issue by damianog** [jc21/nginx-proxy-manager#438]
I am using `jc21/nginx-proxy-manager:latest` 2.3

During POST action of an asp.net core Blazor application I get 502 error 

from /data/logs/error.log I discovered the cause:

`...upstream sent too big header while reading response header from upstream...`

I found the solution by configuring the Custom Nginx Configuration on "Advanced" tab with the following parameters:

```
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k; 
```
as explained on http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size

Please consider to add these parameters by default or make them configurable by panel settings.

**Comment by MartinKuhl** [comment]
@damianog could you post your full entry in the Advanced tab?

**Comment by damianog** [comment]
Hi @MartinKuhl,

cut and paste exactly as I wrote

![image](https://user-images.githubusercontent.com/2786682/109854801-c3912380-7c57-11eb-8f28-79fbf87246b9.png)

**Comment by MartinKuhl** [comment]
thanks a lot, that fixes my issue too!

**Comment by douglas1dev** [comment]
thanks a lot
