### ISSUE TITLE
Forward port after ip than entire ip/sub-path

### ISSUE THREAD

**Issue by capitangiaco** [jc21/nginx-proxy-manager#441]
I am trying to set this proxypass:
http://172.16.0.212:9081/VirtualHostBase/http/www.museocomunicazione.it:80/laretina/museo-comunicazione/VirtualHostRoot

But from the gui I am only able to make this:
http://172.16.0.212/VirtualHostBase/http/www.museocomunicazione.it:80/laretina/museo-comunicazione/VirtualHostRoot:9081

Is it possible to put the forward port after the ip than the entire URL ?

thanks

Giacomo

**Comment by chaptergy** [comment]
You can leverage the _Custom Locations_ tab for this. So add a proxy host for this with JUST the IP (No path is supported on the main hostname) and then switch to the locations tab, where you can add a location `/` which has the host `172.16.0.212/VirtualHostBase/http/www.museocomunicazione.it:80/laretina/museo-comunicazione/VirtualHostRoot` and port `9081`. The port will then be put directly after the IP.
