### ISSUE TITLE
Exchange 2007/2010 ActiveSync and autodiscover.xml

### ISSUE THREAD

**Issue by josbmw** [jc21/nginx-proxy-manager#442]
I've already done a lot of research to get this problem solved. There are solutions, but I have no idea how to implement them in a config file of Nginx Proxy Manager.
The advanced functionality isn't documented anywhere as far as I can see.

Version: v2.3.0
OS: Ubuntu Server 20.04 LTS

When I go directly to the autodiscover link https://autodiscover.xxx.xxx/Autodiscover/Autodiscover.xml without nginx in between, I get an authentication pop-up where you enter the user credentials.
The answer is "600 Invalid Request", which is normal behaviour for the autodiscover file.

But with nginx in between, authentication isn't passed through to IIS. You get the pop-up to enter the credentials, and then it stops.

The problem looks like the one described here: https://stackoverflow.com/questions/14839712/nginx-reverse-proxy-passthrough-basic-authenication

Only: I have no idea how I can modify the config file.
The relevant config file for https://autodiscover.xxx.xxx in this case is 4.conf in the nginx folder.
When I manually modify this file with other parameters to test, I can't even access the control panel anymore of Nginx Proxy Manager.

Is there somewhere a clear config manual available for applications like these and other popular ones?

Outlook Web Access for example works out of the box (I do use a wildcard certificate for Nginx and the Exchange server).
But an RD Gateway also is an issue, looks like it's the same authentication issue as the autodiscover.xml file. Authentication just isn't passed through correctly to IIS.

Thanks,

Jos

**Comment by pittbull** [comment]
Did you find a solution to this? I am currently in the same situation.

**Comment by josbmw** [comment]
No, not with Nginx. I switched over to ARR.
Have a look at https://techcommunity.microsoft.com/t5/iis-support-blog/setup-iis-with-url-rewrite-as-a-reverse-proxy-for-real-world/ba-p/846222

This works, though it took some fiddling with the configuration. But there is enough info on the internet about it.

**Comment by pittbull** [comment]
Thank you. Was hoping this could be solved using NPM but it seems not doable.

**Comment by josbmw** [comment]
Yeah, I know. You can spend a lot of time in trying and testing and modifying config files...
That's why I decided to look for another solution.

Of course, you need an extra Windows machine.
But configuration is far easier and it just works.

**Comment by chaptergy** [comment]
The text you put in the advanced tab is put into the `server` configuration of nginx. But according to the stackoverflow link you posted, a `location` fixes your issue. You can go to the _Custom locations_ tab on your proxy host, and add a location `/` there, and add the code from stackoverflow, excluding the `proxy_set_header Host` and `proxy_pass` line. 

Since this issue is fairly old I will close it, but if anyone in the future is testing this and having issues I can reopen it.

**Comment by CoReYeDe** [comment]
Hi,
im struggeling with the same problem in combination of npm and exchange 2016
All web-services from exchange are fine but autodiscover isnt working with authentication.

i get the basic-auth and then 401 from openresty.

if i add a custom location / and add these content i get an ssl-trust-exception and the host is "offline" in npm
this is also happen, if i only add proxy_http_version 1.1 to custom location config.

![image](https://user-images.githubusercontent.com/22613068/144140574-00864fb6-4767-48e8-aabd-49af0f3b91ad.png)


```
proxy_http_version 1.1;        
proxy_pass_request_headers on;
proxy_pass_header       Date;
proxy_pass_header       Server;
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        Accept-Encoding "";
more_set_input_headers 'Authorization: $http_authorization';
proxy_set_header Accept-Encoding "";
more_set_headers -s 401 'WWW-Authenticate: Basic realm="hsrv01.xxx.local"';

```

actually im using haproxy and want switch to npm.
all services without bigger problems.. only autodiscover left ;(

haproxy-config for exchange (all webservices)
```

backend pve01_vm_hsrv01
        balance     roundrobin
        redirect scheme https code 301 if !{ ssl_fc }
        server hsrv01 hsrv01.xxxxx.local:443 check

```

**Comment by badincite** [comment]
Same here. Trying to switch from pfsense/squid thing breaks all the time

**Comment by chaptergy** [comment]
You can see which directives are in a location by default in the [location template file](https://github.com/jc21/nginx-proxy-manager/blob/develop/backend/templates/_location.conf). The advanced config is added at the very bottom. Some directives cause the config to be invalid if they are duplicated. `proxy_http_version` seemingly being one of them. That means you have enabled websocket support for the host, and this directive is automatically to the location. Note that there might be more directives, whose duplication might cause the config to be invalid. So only add the lines, which are not already in the template file or are meant to be duplicated / are able to overwrite existing directives.
