### ISSUE TITLE
SSL Termination

### ISSUE THREAD

**Issue by markhotchkiss** [jc21/nginx-proxy-manager#443]
Hi All,

Apologies if this is a bit of a basic question but I am new to reverse proxy and maybe I am missing the point!

I essentially want to use this application to do 2 things:

1. Point to a Web Page that is running as a Docker container.  This means taking port 80 and pointing it at port 9000 - this I have done successfully.

2. As a second part of this, I now want to take an incoming connection over port 443 using SSL and pass to a HTTP backend (pointing to the same port 9000).  Is this possible?? Every time I try to set this up my Proxy Host shows as offline.  Not sure what I am missing.

Any help would be greatly appreciated!!

Thanks!

**Comment by jc21** [comment]
As [per the documentation](https://nginxproxymanager.com/#quick-setup) you should also forward 443 to 443 in the container. Then you'll be able to create SSL terminated hosts  with either LetsEncrypt or your own certs.

If you hover the Offline text on your proxy host list, it will tell you why it failed to reload Nginx.

**Comment by markhotchkiss** [comment]
Hi, I did read the docs before posting; but I just couldn't seem to find the way forward!  After using your tip to hover over the Offline text, I can see it was the Certificate that was causing the issue as there was no valid certificate chain.  I have resolved this and now everything seems to be working.  Thank you for all your help :)
