### ISSUE TITLE
How to track down logs / sources of problems?

### ISSUE THREAD

**Issue by ylluminate** [jc21/nginx-proxy-manager#444]
I'm getting some "502 Bad Gateway (openresty)" error that I'm not able to yet track down.

I assume that I should be using `docker logs --follow nginx-proxy-manager` or `docker exec -it nginx-proxy-manager bash` and track them in /var/log... but I'm not seeing any error via these methods when I hit the 502 error.

Where do I look to find such errors?  I don't think the error would be coming from elsewhere due to the `openresty` message and nothing else behind it is using this, but I'd sure like to understand how to see everything flowing through with as high of a degree of transparency as possible in order to understand what errors are happening from whatever cause, etc.

Could you please clarify this to me in terms of troubleshooting and what you'd do to track such details down @jc21?

**Comment by m4lki3r** [comment]
You need to use the container name to utilize the docker command, not the image name. For example, `docker logs --follow npm_app_1`. 

If you don't know the container name use `docker ps -a`.

**Comment by jc21** [comment]
For 502 errors they should show in the Nginx error log, inside the container this is `/data/logs/error.log` but since you should also be mounting this data folder from outside of the container you can access it without having to enter the container.

**Comment by belizejackie** [comment]
did you fix the problem ? im getting the same error !

**Comment by SyedAsimAliSE** [comment]
i am hit with the similar error, tried reinstalling it etc: 

i am wondering it gets the certificate but not redirecting to the destination.

her's the error log

```shell
2021/04/07 16:47:30 [error] 3008#3008: *4822 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.45, server: cit.science.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:7007/", host: "cit.science.com", referrer: "http://0.0.0.0:81/"
2021/04/07 16:47:32 [error] 3008#3008: *4827 connect() failed (111: Connection refused) while connecting to upstream, client: 162.XXX.XXX.XX, server: cit.science.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:7007/favicon.ico", host: "cit.science.com", referrer: "https://cit.science.com/"
```

thank

**Comment by chaptergy** [comment]
I don't think you should use `127.0.0.1` or `localhost` as the forward  ip / hostname as this will forward the request inside the NPM docker container, where it does not find anything. You will need to use the IP in your local network.
So `localhost` or `127.0.0.1` is NOT your host machine in NPM, it is the NPM docker container itself.

But this is a little off topic for this issue, as it is about how to debug errors.
