### ISSUE TITLE
Loading issue on 4G

### ISSUE THREAD

**Issue by eoghan2t9** [jc21/nginx-proxy-manager#447]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

I seem to be having an odd issue. Whenever connected to any WiFi or Lan network everything works fine however when I try to access my sites via my phone's 4G connection I keep getting connection reset errors. When running haproxy on my pfsense box I never had such issue. I have tried clearing my browser cache etc but still not loading pages. Forward ports have been enabled for both 80 and 443.

Any ideas on how I could debug this issue.

Also pinging the domain and or subdomains lead to the correct IP address.

**Comment by theraw** [comment]
if you can give a try to look `/data/logs/` we may can find some useful output

**Comment by eoghan2t9** [comment]
Sorry for the late reply I got a hold of a friends phone that was on a different provider that what we use at home. Turns out my service provider blacklisted my domain for some daft reason and now it's been corrected.
