### ISSUE TITLE
RFE - Duo Security 2FA Support

### ISSUE THREAD

**Issue by ansred** [jc21/nginx-proxy-manager#449]
**Describe the solution you'd like**
To support Duo Security 2FA 

**Additional context**
Here is a simple setup on how integrate Duo Security MFA using Web SDK in any application
[https://duo.com/docs/duoweb](url)

Example:
[https://guacamole.apache.org/doc/gug/duo-auth.html](url)

**Comment by chaptergy** [comment]
These are getting too many 2FA issues. Closed in favor of https://github.com/jc21/nginx-proxy-manager/issues/313
