### ISSUE TITLE
[Feature Request] Set up a mail server behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by aitkar** [jc21/nginx-proxy-manager#450]
Hi,

First of all, many thanks to have created this great tool to handle reverse proxy servers in a simple and great UI.

I need to "stream" some mails servers ports (25,110,143 etc...) following a sub domain e.g. mail.example.com

An example here:

```
mail {
    server_name mail.example.com;
    auth_http   localhost:9000/cgi-bin/nginxauth.cgi;

    proxy_pass_error_message on;

    ssl                 on;
    ssl_certificate     /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/certs/server.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen     25;
        protocol   smtp;
        smtp_auth  login plain cram-md5;
    }

    server {
        listen    110;
        protocol  pop3;
        pop3_auth plain apop cram-md5;
}

     server {
        listen   143;
        protocol imap;
    }
}
```

I am using jc21/nginx-proxy-manager:latest 2.3

Thank you for considering this new feature request.

**Comment by Shifter2600** [comment]
I would be interested in this as well.  I was able to get reverse proxies going for pop but I don't have it working for imap. Wonder if anyone has imap working.

**Comment by kennylajara** [comment]
Any update on this issue?

**Comment by Tradeforlife** [comment]
I would also like to see this thanks.

**Comment by b10126** [comment]
I would also recommend this feature.

Today the ports are routed directly from the fritzbox to my Mailserver, which is not behind the proxy. The certificate is copied manually to the Mailserver, very manual. :-(

Or does anyone has a workaround?

Many thanks.....

**Comment by vincemd22** [comment]
Hello,
I am very interested in the function of proxymail
Is it possible to manually add an SSL on a stream on the current version of NPM ?

**Comment by chaptergy** [comment]
@vincemd22 No, that's unfortunately not possible. The way streams work in nginx a stream can't do basically anything because it does not look at the body of a request. Streams work on the TCP / UDP, so protocol specific things like SSL can't be done there. SSL termination only work within the nginx http block (so normal proxy hosts in npm) or in a mail block, which does not exist in npm and is what this feature request is about.

**Comment by ahknight** [comment]
Yes, it can.  mailu is a project that uses nginx as a TLS proxy for HTTP, SMTP, IMAP, and POP.  Here's their config: https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf

**Comment by chaptergy** [comment]
@ahknight I said it is not possible using streams, as was the question. It is possible in general in nginx, just not in npm. It currently has no way to add servers inside a [mail block](https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf#L254), expect by mounting your own `mail` block into `/data/nginx/custom/root.conf`. (See [custom mountpoints](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations))

**Comment by chaptergy** [comment]
Also closing this in favor of https://github.com/jc21/nginx-proxy-manager/issues/450, since it has more upvotes.
