### ISSUE TITLE
Forgot login / password 

### ISSUE THREAD

**Issue by ohmaxx** [jc21/nginx-proxy-manager#451]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? Yes
- Are you sure you're not using someone else's docker image? Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? not the problem

**Describe the bug**
- I have forgot my password and my account name i dont know what i can do 
- What version of Nginx Proxy Manager is reported on the login page? v2.2.4

**To Reproduce**
Try to login but cant remember login and password 

ofc i tried the default login password but dont work

**Operating System**
- Unraid Server docker container

So is it possible to rest password or something like that ? :/

Thanks for your work

**Comment by theraw** [comment]
duplicate https://github.com/jc21/nginx-proxy-manager/issues/230
