### ISSUE TITLE
how to do base URL's 

### ISSUE THREAD

**Issue by docfactory37** [jc21/nginx-proxy-manager#453]
Hi All,

First love Nginx proxy manager.

i just want to ask how to do base URL's

so if i have my <url> gose to one site and if i do <url>/media forward to my media server or if i have <url>/cloud forwards to mt nextcloud server is this possable or not?

Regards

**Comment by collunz** [comment]
I believe this should be possible, yes. 

In "Edit Proxy Host" under "Custom locations" add a location, and choose where it should be forwarded to.

Do this for both /paths and you should be set.

Hope this helps.

**Comment by docfactory37** [comment]
> I believe this should be possible, yes.
> 
> In "Edit Proxy Host" under "Custom locations" add a location, and choose where it should be forwarded to.
> 
> Do this for both /paths and you should be set.
> 
> Hope this helps.

i have done this as below 
![image](https://user-images.githubusercontent.com/20963053/84262864-bd0acb00-ab61-11ea-80ca-23e2b2427887.png)

and i get this error 

![image](https://user-images.githubusercontent.com/20963053/84262893-cac05080-ab61-11ea-8474-55761695116e.png)

when i go to example.com.au/media

**Comment by docfactory37** [comment]
So it looks like it's not possible at this stage, would be great if it was, hope this will be fix / implemented.

**Comment by ggl-wolfy** [comment]
This seems to work for me: instead of `your.ip.address` in the forward hostname field, put `your.ip.address/` instead (with the trailing slash). 

Also enter `set $port 8096;` (with your own port number) in the custom nginx configuration (click the gear icon).

**Comment by docfactory37** [comment]
> This seems to work for me: instead of `your.ip.address` in the forward hostname field, put `your.ip.address/` instead (with the trailing slash).
> 
> Also enter `set $port 8096;` (with your own port number) in the custom nginx configuration (click the gear icon).

Thank you for your help i will try this, and let you know how I go

**Comment by factoryhub** [comment]
still dose not work 100% will there be a proper solution develop and implamented in future?

**Comment by docfactory37** [comment]
still dose not work 100% will there be a proper solution develop and implamented in future?

**Comment by chaptergy** [comment]
This is a general thing with nginx, not with NPM (see e.g. [this Stackoverflow](https://serverfault.com/questions/562756/how-to-remove-the-path-with-an-nginx-proxy-pass/562850#562850). Generally you could replicate most nginx configs using the advanced fields, so there is nothing inherently wrong in NPM.

**Comment by luixal** [comment]
Hi,

Just got here looking for this exact feature. Doing what @ggl-wolfy suggests has worked for me. I just added the trailing slash to the ip address. In my case, no need to add the `set $port XXX;`.

It would be nice to have this kind of configuration so instead of custom locations, you could also use full path redirection in the domain config. Why? I have only one proxy host entry, but I'm redirecting to several services using custom locations because I have to use tplinkdns and it doesn't work well with subdomains.

Thanks!
