### ISSUE TITLE
Access Lists not working.

### ISSUE THREAD

**Issue by joe9624** [jc21/nginx-proxy-manager#455]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Yes
- Are you sure you're not using someone else's docker image?
Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
N/A

**Describe the bug**
V2.30

Just to start! NPM is awesome! I love that little to no maintenance needs to go into setting up my proxies. Thank you for all your hard work! 

When trying to add access rules it does not seem to apply it to the Ngnix config. I am trying to allow only my local subnet to get access to a certain page.

**To Reproduce**
Add ip or ip range to access list.
I do not add anyone in for authorization.
Save.
I then add the access rule to a new proxy that I setup. I am using Lets Encrypt to get the certificate.

**Expected behavior**
I expect to be able to access my page from the IPs specified. I keep getting 403 on the pages. I checked the conf file for the proxy and there seems to be nothing added under the section where access list is commented. All that is there is the default deny all rule.

**Operating System**
Ubuntu Server 18.04 VM

Thank you in advance.

**Comment by jc21** [comment]
Can you try `2.3.1` or `2` or `latest` docker tags please

**Comment by joe9624** [comment]
That did it. Didn't see there was a new version posted! Thank you very much!

**Comment by smarteshome2020** [comment]
Hi, i have the same problem with V2.9.15. If i use any access List the Password never works. eg. I create Access Lsit with Name =test, User=Test pw= Test. If i try to enter the page i will ask for User and PW. If i user Test/Test i get the responde {
  "message": "invalid username or password"
}
