### ISSUE TITLE
Broken SSL cert after proxied host update, works after disable/enable host in NginxProxyManager

### ISSUE THREAD

**Issue by spiffzilla** [jc21/nginx-proxy-manager#470]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Yes, sort of... newest in Unraid
- Are you sure you're not using someone else's docker image?
Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
Yes

**Describe the bug**
- A clear and concise description of what the bug is.
See below
- What version of Nginx Proxy Manager is reported on the login page?
2.2.4 (from Unraid repo)

**To Reproduce**
1. I have Gitea installed works fine with domain name, gitea.tld.com SSL cert is working fine
2. Update Gitea docker container via Unraid
3. I get the SSL error
   Your connection is not private
   Attackers might be trying to steal your information from gitea.tld.com (for example, passwords, 
   messages, or credit cards). Learn more
   NET::ERR_CERT_AUTHORITY_INVALID
4, In NiginxProxyManager I disable the Gitea host
5. In NiginxProxyManager I enable the Gitea host
6. The SSLcertificate works agaion

NginxProxyManager is set up with an access list, only allowing LAN users
When I connect after the disable/enable i need to enter creds matching the access list

All is done on the local network....
**Expected behavior**
Should just work even after a container update

**Operating System**
- Please specify if using a Rpi, Mac, orchestration tool or any other setups that might affect the reproduction of this error.
Unraid

**Comment by spiffzilla** [comment]
I just noticed that it's not the "original", but I might need explanation anyway if possible.

My version is:
Author:	jlesage
DockerHub:	jlesage/nginx-proxy-manager
Repository:	Djoss' Repository  Maintainer Profile
Categories:	Network:Web, Network:Proxy, Tools:Utilities
DockerHub Stars:	 46
Added to CA:	December 19, 2018
Total Downloads:	More than 5,000,000
30 Day Trend:	Ranked #137 Trending 
(As of June 12, 2020 9:08 pm)

**Comment by chaptergy** [comment]
As this is fairly old I will close this issue for now. If you are still experiencing the issue, please let me know, I could reopen the issue. But you should include more information, e.g. the error log at `/data/logs/error.log`
