### ISSUE TITLE
How to deploy on swarm

### ISSUE THREAD

**Issue by iamapinan** [jc21/nginx-proxy-manager#471]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

How to deploy on multiple docker swarm cluster and run with a stack deploy command.

**Comment by johncadengo** [comment]
Any updates on this @iamapinan ?

**Comment by iamapinan** [comment]
> Any updates on this @iamapinan ?

No any answer from developers team.

**Comment by jakane** [comment]
I could use some hints for this too

**Comment by chaptergy** [comment]
Deploying any other way than the official one described is not necessarily the expertise of the developers of a software. This would be better suited for the [Gitter Chat](https://gitter.im/nginx-proxy-manager/community) or the Reddit community (not sure what the status of that is). But if anyone from the community knows how to do this, leave a comment here, but I will close this for now.
