### ISSUE TITLE
Option to disable IPV6

### ISSUE THREAD

**Issue by broizter** [jc21/nginx-proxy-manager#473]
I have IPV6 disabled at a kernel level, so when I try to run Nginx proxy manager docker container it won't run and this message is spammed in the logs:

`nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)`

From what I see there is no way to disable IPV6 since the nginx.conf isn't exposed in the external volume where one could change the listen setting.

**Comment by vsc55** [comment]
Hi,
To disable ipv6 you have to add this ENV in the docker.
`DISABLE_IPV6=true`
