### ISSUE TITLE
Export SSL cert

### ISSUE THREAD

**Issue by andysom25** [jc21/nginx-proxy-manager#477]
I am needing to export an ssl cert I have for a certain site I am using the reverse proxy for, it needs a file path to the cert. 
Is there an easy way to export these certs generated by lets's encrypt from the proxy manager?

**Comment by N4v41** [comment]
the certs that are being used should be under /etc/letsencrypt/live into the nginx proxy manager container.
you should be able to use docker cp to copy the files like that:
docker cp <docker container name or id>:/etc/letsencrypt/live ./live
