### ISSUE TITLE
use domannames after reinstall

### ISSUE THREAD

**Issue by tayanov** [jc21/nginx-proxy-manager#478]
I use https://github.com/hassio-addons/addon-nginx-proxy-manager
i have trouble with #230 
Now i reinstall npm to docker without hassio-addons.

And i cant use my older domain-names, now they is already used (busy).
How i can use my domenames which use with hassio-addons.

another i have api key with duckdns. can i use it or it too?

**Comment by chaptergy** [comment]
On speratate NPM instances you can add the same domain names, since there is no actual connection from NPM to the domain, just the other way round. What you need to do is point your domain to the new NPM instance, and change the DNS entries there. But this is not an issue with NPM.
