### ISSUE TITLE
Too many redirect errors.

### ISSUE THREAD

**Issue by Landelor** [jc21/nginx-proxy-manager#48]
Hi,
I'm using the docker on unRAID and I'm receiving "too many redirect" errors when configuring a domain for use.
Any ideas?

Regards,

**Comment by Landelor** [comment]
It looks like it's happening when I enable "Force SSL"

**Comment by jc21** [comment]
You might want to install a browser extension that tracks the redirections, or enable developer tools window and preserve history to see what's happening. Forcing SSL from NPM simply redirections `http` to `https` and what I would guarantee is happening, is your upstream server is redirecting back to `http` immediately.
