### ISSUE TITLE
Error running compose file

### ISSUE THREAD

**Issue by whisperdancer** [jc21/nginx-proxy-manager#482]
RaspberryPi 3B+ running latest Rasp Pi OS

Followed your instructions to a t, then run docker-compose up -d and get this error:

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.app.environment contains an invalid type, it should be an object, or an array

Googled it and found nothing helpful.

**Comment by sqsmike** [comment]
I came across to the same issue and it was because of an blank line at the end of the docker-compose.yml

**Comment by neb1426** [comment]
Running in to the exact same issue!
![image](https://user-images.githubusercontent.com/67613340/99368040-d08b4080-290e-11eb-9650-c98cb4d6d951.png)

**Comment by neb1426** [comment]
No empty spaces at the end line either

**Comment by sqsmike** [comment]
Then an another issue maybe the database image, try to change your db line to this: 

db:
image: 'yobasystems/alpine-mariadb' 

also keep your mind on the single quotes around some strings  ' '  try them also.

My working docker-compose.yml file
![εικόνα](https://user-images.githubusercontent.com/34960926/99388299-0b28b500-28de-11eb-98f8-c9a5486b5fb6.png)
