### ISSUE TITLE
Default WWW directory

### ISSUE THREAD

**Issue by DJFraz** [jc21/nginx-proxy-manager#485]
Hello,

Quick question here, what is the default www directory and is there anything specific I have to do to be able to use it?
I'm switching from another docker with similar features, but that allows me to use the base URL to access the site.

**Comment by samr28** [comment]
Are you trying to host a static site? If so, I don't think it's supported with this (see #280).

The way that I solved it was to create a docker container from the standard nginx and then make a proxy host in nginx-proxy-manager. It's inefficient to be having multiple nginx instances running but I think this may be the only way to do it until they decide to enable that feature.

Scroll down to "Hosting some simple static content": https://hub.docker.com/_/nginx

**Comment by DJFraz** [comment]
Thanks for the response. In the end, that's what I ended up doing. I was originally using another docker that does everything NPM does, except it required manual configuration of everything. That allowed root sites to be hosted and was hoping NPM did as well. Not a huge deal, just another container to run.

**Comment by samr28** [comment]
Yeah kindof annoying though since nginx has this functionality built in...

Maybe it'll get added at some point :)

**Comment by punksinatra** [comment]
> This is a little different but it technically answer to your question (and I'll be able to find it again when I need to). I wanted to change the default congratulation page with my own with a couple of images so I checked this, I still have to try but it should work (I'll update later).
> The default page is taken from /var/www/html so just map that in your `docker-compose.yml`. For example with the official file:
> 
> ```
> version: '3'
> services:
>   app:
>     image: 'jc21/nginx-proxy-manager:latest'
>     ports:
>       - '80:80'
>       - '81:81'
>       - '443:443'
>     volumes:
>       ....
>       - ./html:/var/www/html
>   db:
>     ...
> ```
> 
> And place your site in the newly created html folder. Of course this will be displayed for every subdomain not already redirected, I don't know if this fits your use case. We have an option for custom html pages but it only allows text (I think)
> 
> The trick to find stuff like this is enter the container and look around for the correct file `docker exec -it ngix_manager_container_name /bin/bash` (or check the source folder in the repository)

Hi,

I did this but it does not work for some reason. Should the folder be "html" for the host or can I use a different name?

**Comment by LivingWithHippos** [comment]
Host folder name does not matter. Try to enable the custom html first and check where it is.

**Comment by chaptergy** [comment]
Closing this with a reference to https://github.com/jc21/nginx-proxy-manager/issues/58
