### ISSUE TITLE
Redirect the main webpage ?

### ISSUE THREAD

**Issue by Connor2397** [jc21/nginx-proxy-manager#487]
Hi All,

I may be being dumb here but I have tried searching around for what I am trying to achieve but no luck. I have managed to get all my sub domains working great however, I would like my main website to be on the the domain so they would go to example.com and that would take them to my website on wordpress. I have tried adding a proxy host with the domain example then the ip of the server and the port but when i go to example.com nothing happens.

How would I go abouts doing this. Any advise would be great :)

**Comment by mar005** [comment]
Did you figure this out?
