### ISSUE TITLE
Why proxy host needs a port?

### ISSUE THREAD

**Issue by cranxi** [jc21/nginx-proxy-manager#491]
Hi there,

I'm trying to add a seperate running host machine to the proxy hosts on NPM. The UI of the host is not using a port, but it is required to use a port when adding a proxy host in NPM.

Can this been done without and if yes, how?

Many thanks.

**Comment by trydalch** [comment]
Not sure I understand what you're saying.

If the server you're trying to add is running any sort of web service, in order to serve that up (UI or API), it must be listening on some port.

What is running on this new server that you're wanting to proxy using NPM?

**Comment by cranxi** [comment]
Sorry I already found the answer. I'm running P1 Monitor on a raspberry pi, in the webadres the ip had no port but I found out by using port 80 on NPM it worked.
