### ISSUE TITLE
more setting request

### ISSUE THREAD

**Issue by NoName805** [jc21/nginx-proxy-manager#5]
Could you please add some settings as below config?

Because I have no idea to forward my site to my back-end  https server? --> proxy_pass https://x.x.x.x/;.

I just modify the config file as below for make my site work now.

       location / {
		proxy_pass https://x.x.x.x/;
		proxy_http_version      1.1;
 	        proxy_set_header Connection "";
		proxy_read_timeout      360;
		proxy_pass_header       Date;
		proxy_pass_header       Server;
		proxy_pass_header       Authorization;
		proxy_set_header        Host $host;
		proxy_set_header        X-Real-IP $remote_addr;
		proxy_set_header        X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_pass_request_headers on;
		proxy_set_header Accept-Encoding "";
		proxy_request_buffering off;
		proxy_buffering off;
		#proxy_set_header Connection "Keep-Alive";
		}

Many thanks.

**Comment by SGStino** [comment]
Perhaps the advanced configuration should by default show the entire `server { }` configuration contents, just automatically generated, and the variables from the first tab provided as $variables?

(so basically move the `location / { }` to the advanced configuration by default?)
As long as nobody goes to the advanced tab, it's still simple to use, but also more powerfull for more experienced users?

So far i've been able to do the websockets for most scenarios, except now for mosquitto. Where the root seems to be the websocket path.

**Comment by jc21** [comment]
Yep I considered that as an option. In your case, it might be worth adding a option to enable websocket upgrades for the entire site, as the quickest solution. I've been considering that anyway and no reason why both ideas can't co-exist. I'll look in to it in a week

**Comment by jc21** [comment]
This doesn't solve the original issue, but I've added another setting for Proxy Hosts in version 2.0.3 for any hosts that need websocket upgrades. Just turn on "Allow Websocket HTTP Upgrades" and hopefully everything works without the need for advanced config.

**Comment by tarkh** [comment]
Thanx for cool software!
It would be nice to have`proxy_set_header` option `X-Forwarded-For` with value `$proxy_add_x_forwarded_for;`. Now it's hardcoded to `$remote_addr`, so I need to override with Advanced configuration. This option is pretty common when you want to serve different domains/subdomains on same ip with same server behind proxy. Thanx!

**Comment by chaptergy** [comment]
As custom nginx configuration for hosts and locations are possible, I think this issue does not have to stay open anymore.
