### ISSUE TITLE
No file name displayed when uploading custom certs

### ISSUE THREAD

**Issue by vrelk** [jc21/nginx-proxy-manager#50]
On the "Add Custom Certificate" page, after selecting a file, it still says "Choose file" instead of switch to the file name of the file about to be uploaded.

I have tried this with both Firefox and Chrome.

**Comment by jc21** [comment]
Yeah I knew this was a problem, but never got around to fixing it, I was in a hurry to release at the time.

**Comment by chaptergy** [comment]
This is working in the current version
