### ISSUE TITLE
Mixed Content won't load with HTTPS

### ISSUE THREAD

**Issue by mromr** [jc21/nginx-proxy-manager#500]
Hi I have a site that will not load some modules due to Mixed Content when HTTPS is enabled via Proxy Manger.

What options do I have to resolve this ?

**Comment by chaptergy** [comment]
It seems this site tries to load things which are either external and do not have SSL  or it has `http` hardcoded in some references. Anyhow, I don't think this is a problem with NPM but with the page you are proxying.
