### ISSUE TITLE
does it support webdav?

### ISSUE THREAD

**Issue by htogether** [jc21/nginx-proxy-manager#503]
I can connect to webdav and it shows the list of folder and files but I can't change directory or play mp4 files nor list files in the folder.

**Comment by htogether** [comment]
I found correct setting for webdav, need to add following setting on advanced tab and it works fine


https://k.kakaocdn.net/dn/WbLI5/btqFDaDcmnv/1BKfFCWc8jVjfeeDqXWOc1/img.png

**Comment by ensleep** [comment]
can't rename files

**Comment by Waldorf3** [comment]
> Thanks, this worked for me. Here it is in text form so that others don't have to type it.
> 
> ```nginx
> location / {
>   proxy_set_header Host $host;
>   proxy_set_header X-Real-IP $remote_addr;
>   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>   proxy_set_header X-Forwarded-Proto $scheme;
>   proxy_pass http://192.168.0.10:1234$request_uri;
>   proxy_read_timeout 90;
> }
> ```
> 
> Keep in mind that you cannot have this under a different location other than `/` unless you can figure out a way to have nginx map your file paths out of that location.
> 
> `proxy_pass` line has to include your WebDAV server hostname and port. Be careful not to put a slash after the port, as `$request_uri` seems to include the initial slash.

I'm trying to get ionelmc/webdav working with nginx-proxy-manager but getting error 401.   Looking up this error, should be an authentication problem, but I am not even getting a login prompt at this time.

I've added the location code above, but as I'm using docker network as explained here https://nginxproxymanager.com/advanced-config/#running-processes-as-a-user-group the proxy_pass line reads

` proxy_pass http://webdav:8080$request_uri;
`

**Comment by WeskerC** [comment]
Thanks, this one works for me

> > Thanks, this worked for me. Here it is in text form so that others don't have to type it.
> > ```nginx
> > location / {
> >   proxy_set_header Host $host;
> >   proxy_set_header X-Real-IP $remote_addr;
> >   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >   proxy_set_header X-Forwarded-Proto $scheme;
> >   proxy_pass http://192.168.0.10:1234$request_uri;
> >   proxy_read_timeout 90;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Keep in mind that you cannot have this under a different location other than `/` unless you can figure out a way to have nginx map your file paths out of that location.
> > `proxy_pass` line has to include your WebDAV server hostname and port. Be careful not to put a slash after the port, as `$request_uri` seems to include the initial slash.
> 
> I'm trying to get ionelmc/webdav working with nginx-proxy-manager but getting error 401. Looking up this error, should be an authentication problem, but I am not even getting a login prompt at this time.
> 
> I've added the location code above, but as I'm using docker network as explained here https://nginxproxymanager.com/advanced-config/#running-processes-as-a-user-group the proxy_pass line reads
> 
> `proxy_pass http://webdav:8080$request_uri;`

**Comment by andyman1222** [comment]
Requesting to reopen this issue as I want to be able to proxy both https:// and webdavs:// from port 443. The advanced options here do not work. I am currently running KDE on Ubuntu, trying to add Nextcloud via kio-ggdrive.

When Dolphin the file manager sees https:// in the remote folder's path, it treats it like a website and opens the URL into the web browser. When changing to webdavs:// it throws an error that the path doesn't exist. My suspicion is that nginx proxy manager isn't forwarding the webdavs:// protocol, despite it being an extension of https.
