### ISSUE TITLE
Redirection target formatted incorrectly thus no redirect possible

### ISSUE THREAD

**Issue by markverg** [jc21/nginx-proxy-manager#504]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? **yes**
- Are you sure you're not using someone else's docker image? **yes**
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? **N/A**

**Describe the bug**
- Using v2.3.1, ~I previously used v2.0.12 that didn't have the issue for sure~ issue was in v2.0.12 as well
- When adding a redirection host, the forward domain gets obfuscated which causes all redirects to fail

Forwarding destination ``https://www.google.com`` gets obfuscated to ``https//www.google.com/``.
- it allways add ```/``` at the end
- it will remove the colon after ```https```

![image](https://user-images.githubusercontent.com/21355013/87401690-c3ee8880-c5ba-11ea-962a-ba0f35815115.png)

![image](https://user-images.githubusercontent.com/21355013/87401731-d23ca480-c5ba-11ea-9967-f1f279b47ae1.png)

I tried whether or not it makes a difference when setting up SSL or not, or changing some other settings.
But in all cases it gets the wrong format.

**Comment by gururise** [comment]
I am experiencing this same issue.

**Comment by BoxedBrain** [comment]
The bug is still persistent in v2.5.0

**Comment by chaptergy** [comment]
This should be fixed by now, as it is working as expected.
