### ISSUE TITLE
Proxy on LAN doesn't work

### ISSUE THREAD

**Issue by ColonelMouts** [jc21/nginx-proxy-manager#505]
Hello,

I've setup a test VM running Ubuntu Server 19.10 (had trouble with installing Docker on Ubuntu 20.04...) by following the instructions at https://nginxproxymanager.com/setup/. Keep in mind this is a vanilla setup, I've changed nothing in the config files.

For the life of me I can't seem to be able to proxy to any other server on a different local IP. Everything is going through my LAN; nothing is coming or going to the Internet so it's not a DNS issue.

Here's the network info:

- DMZ - 192.168.10.0/24
- LAN - 192.168.0.0/24
- Firewall rules are OK for HTTP / HTTPS trafic between DMZ and LAN. For testing purposed I've allowed any trafic from/to 192.168.10.17 and 192.168.0.70
- NPM-VM (192.168.10.17)
- Bookstack-VM (192.168.0.70)
- DNS entry on my local DNS server for wiki.domain.com points to 192.168.10.17(NPM-VM)

So on Nginx Proxy Manager I do the following : 

1. Add proxy host
2. Domain Names = wiki.domain.com
3. Scheme = http ; Foward hostname / IP = 192.168.0.70 ; Foward Port = 80
4. Save, entry is enabled and Online

When I test it in a browser I get ERR_CONNECTION_TIMED_OUT so obviously nothing gets to the target VM.
I've checked my logs on my firewall and there's no trafic going from 192.168.10.17 to 192.168.0.70. It's like Nginx Proxy Manager is not even trying to send data over to 192.168.0.70
I've logged in the VM using SSH to do a ping test and it works fine. I've tried it in the docker container as well and trafic gets trough.

I really don't know what it could be so I was hoping you could help me with that

Thank you

**Comment by jtc42** [comment]
Presumably unless your docker container is set up to use the host network, it’ll be isolated from your LAN? I thought that’s how dockers internal network works.

**Comment by chaptergy** [comment]
Are you able to get the default page when visiting 192.168.10.17? If not, this has to be an issue with exposing NPM to the network. If you do, check this directory inside the docker container: `/data/logs/` and in there are a few files named `proxy_host-x.log`. Look into these files to check whether the requests were received by nginx.

But as this issue is fairly old and there hasn't been any activity lately I will close this for now.
