### ISSUE TITLE
Add Letsencrypt dns api support

### ISSUE THREAD

**Issue by shellus** [jc21/nginx-proxy-manager#507]
When I use in LAN, I don't have the default port 80，So i can't verify through webroot

Please allow me to configure my dns provider and my dns key in the metadata

DNS API see：https://github.com/acmesh-official/acme.sh/wiki/dnsapi

**Comment by shellus** [comment]
If you need to support dns api, you need to replace `certbot` with `acme.sh`, which will bring compatibility issues and very big changes

Please tell me what to do

**Comment by chaptergy** [comment]
Since the end of 2020 certbot support was broadened to include dns challenges for many providers. Though there is no acme.sh support, certbot will already cover many things.
