### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by aruznieto** [jc21/nginx-proxy-manager#508]
When I try to install it on docker, with de imagen on docker hub, only appear this following ports: 8080, 4443, 8181, but not 80 or 443

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
- Are you sure you're not using someone else's docker image?
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
- A clear and concise description of what the bug is.
- What version of Nginx Proxy Manager is reported on the login page?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System**
- Please specify if using a Rpi, Mac, orchestration tool or any other setups that might affect the reproduction of this error.

**Additional context**
Add any other context about the problem here, docker version, browser version if applicable to the problem. Too much info is better than too little.

**Comment by chaptergy** [comment]
You can set the ports you want outside of the container yourself. You probably specified different ports here: 

![image](https://user-images.githubusercontent.com/26956711/117998654-a2be0c00-b333-11eb-9c7f-4864344179fe.png)
