### ISSUE TITLE
Cannot upload certificate files

### ISSUE THREAD

**Issue by Grekkor** [jc21/nginx-proxy-manager#52]
I cannot upload certificate files,
It just does nothing and then says: "Upload failed: 0"

**Comment by jc21** [comment]
Anything in the docker logs?

**Comment by GregorEeckels** [comment]
Only: "Connection Error: Error: Connection lost: The server closed the connection."
I generated the certificate files with ssh-keygen on linux. They are 4096 bit RSA keys and I got two .pem files.
I tried uploading them as .crt and .key files aswell but no luck.

**Comment by chaptergy** [comment]
This issue should be fixed, certificate upload is currently working.
