### ISSUE TITLE
Can I create a cert at the root of the domain?

### ISSUE THREAD

**Issue by mar005** [jc21/nginx-proxy-manager#522]
I want to essential have a redirect of https://www.example.com > https://example.com but also able to go directly to https://example.com which ultimately points to my ghost blog running locally where NPM is on. 

My setup at my DNS is 2 records

CNAME www.example.com to ddns.example.com (my own IP for NPM to reverse proxy) 
A example.com to own IP. 

by NPM setup has a cert for www.example.com that points to my ghost blog. Ok my proxy host I lumped in my example.com too but that gives a warning when I use my browser at https://example.com because obviously the cert is for the www.example.com subdomain. 

how do I do what I want above? I’m thinking I need to remove that other cert for the www and only do it for example.com and then do a redirect in NPM for the www.example to example.com? Keep the DNS as it is?

**Comment by dash74** [comment]
You can register ssl certificates in npm for both www.example.com and example.com.

**Comment by mar005** [comment]
Thanks! I got it working!
