### ISSUE TITLE
Custom Certificate not uploading.

### ISSUE THREAD

**Issue by neb1426** [jc21/nginx-proxy-manager#524]
Hello, I have install the proxy manager and create host's ect, But I'm, trying to upload my ssl certificate that I have repurchased. When i go to do this and select the file i wish to upload. The file does not upload i get 0 errors in the logs and have tried different browser's. I'm sure it is something simple i have missed but any help would be appreciated. :)

**Comment by wzaatar** [comment]
Similar error. Trying to upload files and getting "Upload failed: 400". No file names appear to be selected when I browse for the certs. Tried Safari and Firefox.

**Comment by neb1426** [comment]
I found the files would upload but did not show they were until click accept. Essentially have to do it with no indication it is working until it is the step!

**Comment by r3draid3r04** [comment]
> I found the files would upload but did not show they were until click accept. Essentially have to do it with no indication it is working until it is the step!

What do you mean? I don't ever see an accept button to click. I select my files and click upload and then nothing, it just sits there until I close out.

**Comment by ananiasfilho** [comment]
i have same issue. Select right files (same used on others nginx) click on SAVE button, but not happen.
My certs are from godaddy.
Server.key
Server.crt
intermediate.crt
How make it work?

**Comment by neb1426** [comment]
I'm afraid I cant replicate it anymore. From memory it just looked like it wasn't working but it did... Don't know what more I can say sorry. Not 100% but may have had to clear the cache of my browser for it work or maybe I tried another browser...

**Comment by neb1426** [comment]
Also refer to this duplicate: https://github.com/jc21/nginx-proxy-manager/issues/594

**Comment by ananiasfilho** [comment]
I have changed version to 2.4.0 and its working now. But latest/2.5.0 not work. just show it on browser console:
uncaught function cloudflare_use ....

**Comment by AlexAshs** [comment]
Maybe this is helpful to others:
For me it did not work with the latest build (see date of this post), but with 2.4.0 it did only work on chrome, not on firefox.

**Comment by RedUlf** [comment]
Still same error

**Comment by AlexAshs** [comment]
This is by no means an answer to the problem, merely a suggestion.
I strongly recommend you to use caddy as a reverse proxy.
I use it for over 20 subdomains and all I had to do was create a caddyfile, which looks like this:
```
my.domain.com {
  reverse_proxy 1.2.3.4:80
}
...
```

That's all you need, literally, it takes care of your letsencrypt certificates on its own and is also available as a docker container.

**Comment by neb1426** [comment]
Try turn off your firewall and see if that helps. Think that fixed my issue.

**Comment by mlamb18** [comment]
> I have changed version to 2.4.0 and its working now. But latest/2.5.0 not work. just show it on browser console:
> uncaught function cloudflare_use ....

How did you change versions? In the docker compose file or docker file or other?

**Comment by AlexAshs** [comment]
You need to append the version of the docker image, you want to pull after the image name, as in following scheme: <docker-image-publisher>/<docker-image-name>:<tag-version>
You can find the tag version on docker hub under the section "Tags"
In your Example, it would have to look like this:
jc21/nginx-proxy-manager:2.5.0.
Sometimes, with other images, the version has a prefix, like stable or nightly, so you can reference different release-branches.

**Comment by AlexAshs** [comment]
sry, the scheme, i wrote so carefully, got parsed away, but you can find it on stackoverflow anywhere
just search for docker image version and you'll be fine

**Comment by chaptergy** [comment]
Things have changed since then (https://github.com/jc21/nginx-proxy-manager/pull/774), so this should be fixed.
