### ISSUE TITLE
NPM does not proxy?

### ISSUE THREAD

**Issue by R0yk3** [jc21/nginx-proxy-manager#527]
**Checklist**
YES - Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
NO - Are you sure you're not using someone else's docker image?
YES - If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
With the proxy hosts enabeld i get no connection to the site. When i disable the proxy hosts i see the default congratulations from NPM. 
So the dns points correct. 
Ports are opend correct (port 80 and 443)

- What version of Nginx Proxy Manager is reported on the login page?
V 2.3.1

**To Reproduce**
1. Go to test.sieliakus.nl (http and https) --> do not enforce ssl (yet)
2. Go to home.sieliakus.nl (only http)
Both pointed to the same ip.

**Expected behavior**
See a nginx welcome page.

**Screenshots**
[dashboard](https://prnt.sc/tpsjoq)

**Operating System**
debian 10 container on proxmox

Log files from data directory:
`2020/07/28 09:41:08 [error] 9875#9875: *6171 upstream timed out (110: Operation timed out) while connecting to upstream, client: 84.105.86.217, server: test.sieliakus.nl, request: "GET / HTTP/1.1", upstream: "http://192.168.1.184:8080/", host: "test.sieliakus.nl"
2020/07/28 09:42:39 [error] 9875#9875: *6217 upstream timed out (110: Operation timed out) while connecting to upstream, client: 84.105.86.217, server: test.sieliakus.nl, request: "GET /favicon.ico HTTP/1.1", upstream: "http://192.168.1.184:8080/favicon.ico", host: "test.sieliakus.nl", referrer: "https://test.sieliakus.nl/"
2020/07/28 09:43:41 [error] 9875#9875: *6247 upstream timed out (110: Operation timed out) while connecting to upstream, client: 63.88.73.138, server: test.sieliakus.nl, request: "GET / HTTP/1.1", upstream: "http://192.168.1.184:8080/", host: "test.sieliakus.nl"
2020/07/28 09:46:28 [error] 10577#10577: *6336 upstream timed out (110: Operation timed out) while connecting to upstream, client: 84.241.203.139, server: test.sieliakus.nl, request: "GET / HTTP/1.1", upstream: "http://192.168.1.184:8080/", host: "test.sieliakus.nl"
2020/07/28 09:47:59 [error] 10577#10577: *6380 upstream timed out (110: Operation timed out) while connecting to upstream, client: 84.241.203.139, server: test.sieliakus.nl, request: "GET /favicon.ico HTTP/1.1", upstream: "http://192.168.1.184:8080/favicon.ico", host: "test.sieliakus.nl", referrer: "http://test.sieliakus.nl/"
`

**Comment by s4b3rt0oth** [comment]
Are you positive your DNS is setup correctly for this use-case?

<img width="235" alt="Screen Shot 2020-07-28 at 6 10 31 AM" src="https://user-images.githubusercontent.com/3665270/88652856-5a31ac80-d099-11ea-8105-3665f375cccc.png">

**Comment by R0yk3** [comment]
Yes, you see the cloudflare IP adresses, not my home address.
But both pointing at the same ip wit a different outcome.

**Comment by s4b3rt0oth** [comment]
If you're strictly allowing traffic only from Cloudflare, then that would explain why LetsEncrypt is unable to reach 84.105.86.217.

**Comment by R0yk3** [comment]
Wel, tested it with another domain name not behind cloudflare.
test.jeanineburgers.nl (point internal to nginx site)
test2.jeanineburges.nl (no rule made for yet) 
both http.

BTW, the letsencrypt certificate is given, so communication is happening. only npm is not 'forwarding'

**Comment by R0yk3** [comment]
Excuse me, i had UFW installed blocking everything. Turned it off now it works. Sorry for the screwup MYBAD...
