### ISSUE TITLE
2FA - Yubikey or Authy

### ISSUE THREAD

**Issue by michael-pellegrini** [jc21/nginx-proxy-manager#528]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
2 factor authentication using yubikey, Authy app, etc

**Describe alternatives you've considered**
None, run nginx proxy manager gui on private lan only.

**Additional context**
Great solution, works like a charm,  but wishing for 2fa.

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/313
