### ISSUE TITLE
Certificate file is too large (> 5kb)

### ISSUE THREAD

**Issue by echowings** [jc21/nginx-proxy-manager#53]
Dear, Developers
I met an issue 'Certificate file is too large (> 5kb)', When i try to uploading custom ssl certification which purchased from godaddy.

Your Sincerely!

**Comment by JosFr** [comment]
Hi Developers,

I ran into the same problem, I want to upload my wildcard ssl certificate but I get the same notification.
Can this please be solved?

Greetings from a proxy newbie

**Comment by jc21** [comment]
Sure I can increase the size, can you tell me what the size (in bytes) your files are?

**Comment by echowings** [comment]
> Sure I can increase the size, can you tell me what the size (in bytes) your files are?

Thanks for your quick responding. Would you please change the limited size to 1MB or 50kB, Since I use wildcard ssl certification it is about 8kb large. 
And would you tell me how to change it with configuration file ? or chang code? or we need to upgrade docker version ?

**Comment by jc21** [comment]
I'll push the change as a new docker version. 100kb should be fine, I don't want to make it too crazy to prevent people uploading images or something unknowingly malicious.

**Comment by echowings** [comment]
> the change as a new docker version. 100kb should be fine, I don't want to make it too crazy to prevent people uploading images or something unknowingly malicious.

Okay,That's great ! Thank you so much!:)

**Comment by jc21** [comment]
Changes applied to docker images: `2`, `2.0.9` and `latest`
