### ISSUE TITLE
How do i password protect a single Host?

### ISSUE THREAD

**Issue by danmed** [jc21/nginx-proxy-manager#530]
I thought it was using Access Lists, but if it is.. i have no clue how to do it..

**Comment by SAOPP** [comment]
As I understand it... u mean how to close an application helped with basic authentication that does not have its own security methods?

**Comment by danmed** [comment]
> 
> 
> As I understand it... u mean how to close an application helped with basic authentication that does not have its own security methods?

Thats correct.. I have a gui on another system that has no authentication.. 

And i've just redone what i originally did.. and it appears to be working now.. lol
