### ISSUE TITLE
 proxy_pass http://127.0.0.1:8080

### ISSUE THREAD

**Issue by echowings** [jc21/nginx-proxy-manager#54]
Dear Developer
I met an issue that is how to setup reverse proxy with option:
``` nginx
location / {
proxy_pass http://127.0.0.1:8080
}
```

I just checked configuration file but got comment like this.

``` nginx
# TODO: Preserve Path Option

  location / {



        return 301 $scheme://gcdemoshell.azurewebsites.net$request_uri;

  }
```
How to set each website with custom option like this?

**Comment by jc21** [comment]
You want to create a "Proxy Host", not a "Redirection Host".

and fwiw, the preserve path option is already part of the interface, the comment is left there by mistake

**Comment by echowings** [comment]
> You want to create a "Proxy Host", not a "Redirection Host".
> 
> and fwiw, the preserve path option is already part of the interface, the comment is left there by mistake

Is that possible to let it can be set with web option?
