### ISSUE TITLE
DNS challenge for local domain

### ISSUE THREAD

**Issue by yecine06** [jc21/nginx-proxy-manager#540]
Hello,

I would like to setup reverse proxy for local domains.

For those domains i would like to setup ssl certificate. But is those are local domain (https://example.lan) i can't setup http challenge. On the web i found that those that have achieve creating LE certs for local domain have used dns challenge.

How can i create ssl certificate for local domains ?

Thanks for you help

**Comment by chaptergy** [comment]
LetsEncrypt generally only supports certificates for domains with a top level domain registered with IANA, which `.lan` is not. So I don't think this could ever be relialy possible with certbot, which fails with the error message:

```
The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "example.lan": Domain name does not end with a valid public suffix (TLD)
```
