### ISSUE TITLE
deleting a user which has created hosts makes ui unusable

### ISSUE THREAD

**Issue by a575606** [jc21/nginx-proxy-manager#541]
Thanks for your work on this much needed project. I just came across a bug which you may have missed, and just wanted to mention it.

I created some hosts to test out the software and get it working. Afterwards, I decided to create a new admin user, deleting the old admin after logging in with the new credentials. 

The user was deleted, but hosts and certificates created by that user were now pointing to an unknown user id, creating errors on those pages. I had to log in to the mysql database to change those items to the new user's id before the ui was usable.

**Comment by cal940** [comment]
yes, I know the problem. I  think an option to transfer the ownership for all referenced objects of a user (by deleteion) could be helpfull here. Wordpress for example (and of course other software) have a  feature like this:

![image](https://user-images.githubusercontent.com/23076743/115965527-fe158f00-a529-11eb-9635-f2feb7d9f805.png)

**Comment by chaptergy** [comment]
I'll group this with https://github.com/jc21/nginx-proxy-manager/issues/541
