### ISSUE TITLE
proxy host and dashboard (blank page)

### ISSUE THREAD

**Issue by aguyonp** [jc21/nginx-proxy-manager#547]
A just pull the lastest 2.4.0 image, at now all is working fine exept proxy host and dashboard (blank page)
https://i.imgur.com/YFTGiWX.png

**Comment by kjw1985** [comment]
Try another browser and/or clear your cache. Had the same problem (in Firefox) tried in chromium (which I normally don't use) and worked. After clearing cache in Firefox it worked again.

**Comment by aguyonp** [comment]
Indeed, I have cleared my browser's cache:
https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

NPM works perfectly again!
Thank you very much for the efficient support
