### ISSUE TITLE
Nginx Reverse Proxy for Apache webserver causing problems with IOS clients

### ISSUE THREAD

**Issue by fhm0514** [jc21/nginx-proxy-manager#548]
Hello, am new to all of this, I am by no means an expert on Nginx and Apache.  My Apache Webserver is behind the Nginx Reverse Proxy, overall it is working, except for IOS devices.  IOS devices trying to access my website in the Apache server will get an error "The operation couldn’t be completed. Protocol error with a code of "  regardless of the browser.  This only happens with IOS devices, Android, Windows, and Linux does not show this problem and works as expected.  

After googling, a possible solution is to set the Nginx reverse proxy to "proxy_hide_header Upgrade;" or my Apache server with "Header unset Upgrade", both of which I do not know how to do.   Please help.

The source of this information came from this [link](https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache.html#solution-2-apache)

**Comment by florianeichincode** [comment]
Same issue with workarround https://github.com/jc21/nginx-proxy-manager/issues/661

**Comment by chaptergy** [comment]
Closing in favor of https://github.com/jc21/nginx-proxy-manager/issues/661
