### ISSUE TITLE
Authelia with Nginx Proxy Manager

### ISSUE THREAD

**Issue by nicoolaro** [jc21/nginx-proxy-manager#553]
Is there a guide on how to use NPM with Authelia, i am wondering where to add config files as explained in the [Authelia docs](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html) 

Anyone managed to do it?

**Comment by willnnotdan** [comment]
Yeah had success with this guide: https://github.com/ibracorp/authelia

**Comment by argash** [comment]
+1 for built in Authelia support!

**Comment by chaptergy** [comment]
As for SSO support see https://github.com/jc21/nginx-proxy-manager/issues/437
