### ISSUE TITLE
Letsencrpyt with DNS challenge

### ISSUE THREAD

**Issue by jiatao99** [jc21/nginx-proxy-manager#554]
I managed to make the WebGui works with letsencrypt with dns challenge. However, I found a bug in your ```backend/internal/certificate.js``` line 735:

```
			'--preferred-challenges "dns,http" ' +
			'--webroot ' +
```

Those two line is unnecessary and should be removed because those two value can be specified in line 731: `'--config "' + le_config + '" ' +`

By just install the `certbot-dns-cloudflare` in the docker build and modify the ini file with the above changes, I make the dns challenge works with existing GUI. 

I you want, I can create a branch and pull request for my changes. 

Thanks for your great project.

**Comment by jiatao99** [comment]
Also is it possible to allow user to set renew interval (from configure)? It is now hard coded here

```
	interval_timeout:    1000 * 60 * 60, // 1 hour
```

Since the cert expires every 90 days. Set it to 1 hour is way too much.

**Comment by cristiangauma** [comment]
I would be really interested in this feature. Would the DNS challenge work for wildcard domains? (*.foo.bar)

**Comment by jiatao99** [comment]
yes. wild card letsencrypt work on my docker. But I must change their source code. It seems like the owner of this repo does not care about this feature.

**Comment by gregfr** [comment]
I would love to be able to use wildcard certs automatically, because I use NPM for several servers reachable with the same name.

**Comment by micha1983** [comment]
would be cool if you share it. i'm also very interested in this feature. i also use cloudflare for DNS.

**Comment by jiatao99** [comment]
I am using a 3rd party docker image (from jlessage) which allows me to reference the cloudflare secret outside the docker. I shared the process here: https://github.com/jlesage/docker-nginx-proxy-manager/issues/101.

**Comment by chaptergy** [comment]
DNS challenges for many providers are available since mid to end of 2020, which should have also fixed this issue.
