### ISSUE TITLE
REX: HA using Gluster and Galera

### ISSUE THREAD

**Issue by gregfr** [jc21/nginx-proxy-manager#569]
As a return of experience, here is how I successfully installed NPM to use on several synchronized hosts:

- DB is handled by MariaDB+Galera: each host as its own instance
- files are shared by GlusterFS: the `data` and` letsencrypt` folders are actually shared, the `docker-compose.yml` file is the same, only the `config.json` file differs on the "local" database to use

Its seems to work fine. The only caveats is that you need to generate the LE certs on the hosts that DNS points to, because it's the only one where Nginx has been reloaded.

There's probably a way to make all Nginx reload, but maybe it's outside the goals of this project?

Regards

**Comment by chaptergy** [comment]
Thanks for sharing!

You're right, that is outside of the goals of this project. Though I remember an issue about synchronizing two instances, I can't find it right now.

**Comment by gregfr** [comment]
A follow up after a while: I'm still using it in production, but threw away Gluster which actually doesn't work.
