### ISSUE TITLE
Ombi having weird issue

### ISSUE THREAD

**Issue by KillerKongFu** [jc21/nginx-proxy-manager#57]
Ombi isn't working with this.  I see the website but I can't login.  If I try to log into Ombi with my ple﻿x account it just sends me to small login window again.  Looks like this: https://snag.gy/3ldut5.jpg Any ideas?
My settings - 
![ombi](https://user-images.githubusercontent.com/17061759/51631226-be5a3a00-1f11-11e9-8ade-1e0286b034b1.png)
![ombi2](https://user-images.githubusercontent.com/17061759/51631227-be5a3a00-1f11-11e9-958b-073241a93873.png)
![ombi3](https://user-images.githubusercontent.com/17061759/51631228-be5a3a00-1f11-11e9-8c1d-d3e66f6ae281.png)

**Comment by vrelk** [comment]
Did you set the application URL in ombi?

looking at the configs listed at 
https://github.com/tidusjar/Ombi/wiki/Reverse-Proxy-Examples
try adding the following in advanced

proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Ssl on;
proxy_read_timeout  90;
