### ISSUE TITLE
iOS 14 devices will not resolve reverse proxy addresses from external IP

### ISSUE THREAD

**Issue by JCandle** [jc21/nginx-proxy-manager#571]
My subdomain (for example, homeassistant.mydomain.com) would never load from an external IP after hours of trying everything. Page could not load. After scouring the net, I found some information about adding proxy_hide_header Upgrade; in the nginx config which still didn't work. Redid the whole docker multiple times redid my DNS entries on cloudflare multiple times, re did my firewall settings multiple times, etc.

Turns out, for a reason far beyond my ability to troubleshoot, I cannot access any of my reverse proxy domain names from devices running iOS 14 on an external IP. If I do it from my wifi on my iPhone, no problem. The second I disconnect my WiFi, to see if my reverse proxy is working externally, the pages stop working. Naturally I thought it was just a mistake on my end but I finally read something about iOS causing issues way back in '16 and instead used my hotspot to try from my mac and voila, everything worked fine.

I tried externally from an iOS 13 device and no issues.

How to reproduce:
Take any working reverse proxy that you have
Use an iOS 14 device to try to connect to the subdomain from an external IP.
Get "Safari cannot open the page because the server cannot be found."

I am happy to share my domains for testing with any dev that wants to reproduce.

**Comment by florianeichincode** [comment]
I have the same problem

If i connect via http it works but if i connect via https it doesn`t.
Maybe this helps for debugging

**Comment by florianeichincode** [comment]
Same issue with workarround https://github.com/jc21/nginx-proxy-manager/issues/661

**Comment by chaptergy** [comment]
Closing in favor of https://github.com/jc21/nginx-proxy-manager/issues/661
