### ISSUE TITLE
How to implement self signed certificate ?

### ISSUE THREAD

**Issue by Cassiopeia23** [jc21/nginx-proxy-manager#576]
Hi, 
I wanted to ask, what I have to do or where I have to put the informations, to use a self signed certificate.

We want to use it in our internal network and therefore we don't need a "real" letsencrypt certificate.

After creating a certificate by hand, should I put it in the container or on a mounted volume outside the container ?

**Comment by gregfr** [comment]
When adding a cert in the GUI, you have the option "add ssl cert" -> "custom" to upload the 3 files of the cert (the CA, the cert itself, and the key). You don't have to add a file inside the container, you can do it with the web interface.

**Comment by Cassiopeia23** [comment]
Hi and sry for the late reply.

WOW Thank you, I didn't think that it can be so easy.

Thank you very much !!!
