### ISSUE TITLE
How to setup A or CNAME record so I don’t have to use “www.”?

### ISSUE THREAD

**Issue by QuantiumDev** [jc21/nginx-proxy-manager#583]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)  DONE
- Please read the [FAQ](https://nginxproxymanager.com/faq/)  DONE

**What is troubling you?**

I know this is super basic but so far, I’ve only been able to get my websites working with “www.[sitename].tld” but I’d much prefer using just “[sitename].tld”. What should the A or CNAME record look like for the latter?

**Comment by dash74** [comment]
When setting up the A or CNAME record. You would want to create two A or CNAME records. One with www and one using the @ symbol. That should allow you too just type in domain.com or www.domain.com.

**Comment by QuantiumDev** [comment]
Thanks, dash74! That’s how I had it setup but it wasn’t working. Now it seems to be.
