### ISSUE TITLE
How-to access WordPress Docker with Custom Port

### ISSUE THREAD

**Issue by ansred** [jc21/nginx-proxy-manager#588]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**
How-to access WordPress Docker with Custom Port

I have other basic project that can be accessed with their custom ports, except for Wordpress docker image 

I have this setup

![image](https://user-images.githubusercontent.com/5244872/91653829-ff152000-ea71-11ea-9354-65a58451b5aa.png)

FYI, 
As you can see, I can access the website locally

![image](https://user-images.githubusercontent.com/5244872/91653844-15bb7700-ea72-11ea-9aed-073fd8afe665.png)

And admin dashboard 

![image](https://user-images.githubusercontent.com/5244872/91653799-cd9c5480-ea71-11ea-8823-64e7b0152748.png)

Please advise.

I can share the domain for testing as well.

Thank you.

**Comment by LivingWithHippos** [comment]
Is that the ip address you use? It's a [special](https://www.speedguide.net/ip/10.0.12.16) address so maybe that's the problem.

If that is not the problem,
1. did you put the correct domain name (first screen)? If your domain is yourdomain.com you must put either that or a subdomain such as sub.anydomain.com
2. does your domain resolve to the correct IP? Try it from a command line with ping yourdomain.com

If you join the docker networks between the wordpress and the nginx containers you can follow the instruction in my other [post](https://github.com/jc21/nginx-proxy-manager/issues/555#issuecomment-677893307)

**Comment by ansred** [comment]
@LivingWithHippos I can confirm that the domain and its DNS is not the problem.

I have other sub-domains are working fine.

I can confirm that the subdomain in question can be resolved without issues ot the public IP address where I have my services hosted.

Checked with:
https://www.whatsmydns.net/

**Comment by dash74** [comment]
I think I have figured out your issue. Did you setup wordpress using your internal ip? After you launch your wordpress docker image. You can go to your internal ip and make sure it works, but stop at the screen below. You should be able to access your site through the domain name and complete the setup process.

![image](https://user-images.githubusercontent.com/28696570/91876989-620ddf00-ec4b-11ea-80a1-8828bb5d372c.png)

**Comment by ansred** [comment]
@dash74 

Thanks for testing on your end.

I can confirm that I had no issues in accessing the WordPress docker instance with the local IP address and I can access with NAT the external IP address + the port.

However, I noticed something, which I think it's related maybe to a bug in the system.

So, I managed to get it working by changing the sub-domain ... creating a new Wordpress Instance + Different Port + Creating New Sub-domain and then Proxy Manager, worked!

**Comment by alejandrobalderas** [comment]
> I think I have figured out your issue. Did you setup wordpress using your internal ip? After you launch your wordpress docker image. You can go to your internal ip and make sure it works, but stop at the screen below. You should be able to access your site through the domain name and complete the setup process.
> 
> ![image](https://user-images.githubusercontent.com/28696570/91876989-620ddf00-ec4b-11ea-80a1-8828bb5d372c.png)

I had the exact same problem and this actually did the trick for me as well. It is important to configure wordpress from the url from which you are going to be accessing the website

**Comment by ansred** [comment]
> > I think I have figured out your issue. Did you setup wordpress using your internal ip? After you launch your wordpress docker image. You can go to your internal ip and make sure it works, but stop at the screen below. You should be able to access your site through the domain name and complete the setup process.
> > ![image](https://user-images.githubusercontent.com/28696570/91876989-620ddf00-ec4b-11ea-80a1-8828bb5d372c.png)
> 
> I had the exact same problem and this actually did the trick for me as well. It is important to configure wordpress from the url from which you are going to be accessing the website

I found the issue and managed to fix it.

Always run the initial setup for your wordpress instance using the public domain and not the internal domain/IP.

After that, everything should work fine.

Thanks for reminding me to share my fix here with everyone!
