### ISSUE TITLE
how to install nginx proxy manager to google cloud platform? 

### ISSUE THREAD

**Issue by 2n2n** [jc21/nginx-proxy-manager#589]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**
i was able to install and run the app in a debian vm instance, but when accessing mysite_ip:81 it is not loading. is it because of the firewall rules? 

thank you

**Comment by rml596** [comment]
More than likely this is because GCP's firewall isn't allowing traffic. Watch [this video](https://www.youtube.com/watch?v=bLUsc6rWrAs) to see how to enable it.
