### ISSUE TITLE
cant forward zoneminder

### ISSUE THREAD

**Issue by cTurtle98** [jc21/nginx-proxy-manager#59]
I am using the docker for zoneminder here
https://hub.docker.com/r/dlandon/zoneminder/

zoneminder cannon be run on the root directory it always runs on example.com/zm

how do I proxy https://mydomain.com:443/zm to https://example.com:44302/zm
mydomain.com is external
example.com is internal

this might be similar to issue #40 but I'm not sure

**Comment by jc21** [comment]
You should still be able to forward to zoneminder with a proxy host. The base url `/` will go to the zm docker and it will do whatever it does but you can still access `https://mydomain.com/zm` and it will forward to `/zm` on the destination.

**Comment by cTurtle98** [comment]
I have my website running on the base domain, that is already proxying to the docker hosting my website

**Comment by jc21** [comment]
Ah ok then you want #40

**Comment by cTurtle98** [comment]
![image](https://user-images.githubusercontent.com/24465356/59394988-aeaf8680-8d36-11e9-867f-d0e91cc45bf3.png)
yay thank you for adding the custom locations tab it works now
