### ISSUE TITLE
Add ngx_http_geoip2_module

### ISSUE THREAD

**Issue by darkcloud784** [jc21/nginx-proxy-manager#595]
Adding ngx_http_geoip2_module module (https://github.com/leev/ngx_http_geoip2_module) would be useful for visualizing locations using docker images such as https://github.com/gilbN/geoip2influx

**Comment by zorflieg** [comment]
I agree integrating geo location for geoblocking is a big part of protecting an NGINX install.  I tried shoe horning it in through apk edge install and such but it resulted in bad nginx 'stream' config errors.  It would be great to have the GeoIP2 module.

**Comment by PsychoD** [comment]
+1

**Comment by ansred** [comment]
That would be a great thing to have geoip maxmind is part of the Access List, options of restrictions + adding exceptions of IPs if needed

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/46
