### ISSUE TITLE
how to make domain name with ipaddress with path

### ISSUE THREAD

**Issue by hermanekaputra** [jc21/nginx-proxy-manager#597]
I run application in docker in my server not vps with IP public 
I have guacamole in http://172.16.1.21:8080 and I want to it will be accesed in 172.16.1.21/guacamole
172.16.1.21/guacamole -> 172.16.1.21:8080
please teach me how..thanks
i have tried with this step but fail
in domain names i fill 172.16.1.21/guacamole, forward hostname ip : 172.16.1.21 forward port 8080
but when akses url 12.16.1.21/guacamole 404 not found

**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

_Clear and concise description of what you're trying to do and what isn't working for you_

**Comment by chaptergy** [comment]
You _should not_ include paths (so anything containing a `/`) on the details tab of a host. This is most likely the problem. But since this is fairly old, I'll close this for now.
