### ISSUE TITLE
File downloads with WEBdavs/https stop at 1.1 GB

### ISSUE THREAD

**Issue by theniwo** [jc21/nginx-proxy-manager#598]
I divert from a dyndns url to a dav server on my local network with npm. Connection works fine.
But when ever I try to download a file from that dav share, the file transfer stops at 1.1 GB. (Error message something like end of stream). It gives me no log entries. It just stops. Uploading doesn't even get that far.

**Comment by chaptergy** [comment]
NPM simply generates nginx configurations, so nginx handles all the actual proxying. So this is more of an nginx issue that it is an NPM one.
