### ISSUE TITLE
How to set up HTTPS for internal-only domains

### ISSUE THREAD

**Issue by rclough** [jc21/nginx-proxy-manager#599]
**What is troubling you?**

I currently use Nginx Proxy Manager to expose a nextcloud instance to the public web so I can access it. It works great for this use case and is very easy to configure.

I would also like to use it to serve HTTPS for internal-only services on a private network that I don't feel as comfortable exposing to the public web. It's not clear to me how this should be accomplished with NPM:

From my understanding, for NPM to get a LE cert, the domain (which can't be wildcard) needs to answer a challenge/response to LE, which means that the DNS must point to a public IP address, and that IP address must respond to public traffic.

If I'm not missing something (which I'm not an https expert, so I could be/hope I am), this means that any of my services which I want to have https must also be served to the public internet (much bigger attack surface for a private server I keep in my home). Arguably I could do this for a limited time to get the cert, and then change the DNS record for that subdomain to an internal IP, but then when it comes time for renewal in 90 days, it would fail, no?

**Comment by andrej-g** [comment]
The way I do it:

- Obtain a Let's Encrypt certificate outside of NPM; I've set up acme.sh on my Synology NAS for mydomain.tld, *.mydomain.tld, *.lan.mydomain.tld + an auto renewal script/cron job,
- Create a custom certificate in NPM and upload the LE certificate + key, so that the certificate is visible in the interface and NPM knows from where to load it,
- the autorenewal script copies all the certifcate files to the directory where I keep my Docker volumes,
- map the certificate files to the NPM container at /config/custom_ssl/npm-10/ (or wherever NPM decides to store the uploaded custom certificate files)

NPM's certificates tab won't update the expiration time but that doesn't really matter.

It's kind of roundabout but that's the only reliable way I was able to do it without exposing NPM to the internet.

**Comment by Telain** [comment]
In NPM, set an access list with only your internal subnet. Otherwise, configure as you would any other service. NPM is the only thing that needs outside exposure for certificates.

**Comment by axiom00** [comment]
@Telain - Your suggestion works perfectly. Any thoughts on how to return 444 if not in the internal subnet?

**Comment by JamesValero** [comment]
To @andrej-g 's point, can we add a way to update/refresh the certs either when the service restarts, a command-line feature, or something else?

**Comment by ragaimeena** [comment]
> **What is troubling you?**
> 
> I currently use Nginx Proxy Manager to expose a nextcloud instance to the public web so I can access it. It works great for this use case and is very easy to configure.
> 
> I would also like to use it to serve HTTPS for internal-only services on a private network that I don't feel as comfortable exposing to the public web. It's not clear to me how this should be accomplished with NPM:
> 
> From my understanding, for NPM to get a LE cert, the domain (which can't be wildcard) needs to answer a challenge/response to LE, which means that the DNS must point to a public IP address, and that IP address must respond to public traffic.
> 
> If I'm not missing something (which I'm not an https expert, so I could be/hope I am), this means that any of my services which I want to have https must also be served to the public internet (much bigger attack surface for a private server I keep in my home). Arguably I could do this for a limited time to get the cert, and then change the DNS record for that subdomain to an internal IP, but then when it comes time for renewal in 90 days, it would fail, no?

Is there anyway you could please consider sharing your config file and NPM settings since I can't get it to work with an external subdomain. Thank you

**Comment by chaptergy** [comment]
Since the end of 2020 nginx proxy manager supports DNS challenges for many providers. This means only the DNS zone for this domain needs to be public. So you do need a valid domain from one of the supported DNS providers, but these domains do not actually need to point to anything.
