### ISSUE TITLE
SAN certificate setting request

### ISSUE THREAD

**Issue by NoName805** [jc21/nginx-proxy-manager#6]
Hi again,

San certificate should be easy to management the site that have multiple domain names, can you add this feature also? 

https://letsencrypt.org/docs/rate-limits/

**Comment by jc21** [comment]
Ok people, version 2 is ready for someone to test besides me. Have a read of [the documentation](https://github.com/jc21/nginx-proxy-manager/blob/v2/README.md) including the [installation instructions](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/INSTALL.md) and [importing guide](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/IMPORTING.md).

The app has only a few minor bugs I want to change but I'm using it in production myself on 4 instances. 

If you have issues, probably be to report them as new issues and mention that they affect version 2 in the description.

Thanks
