### ISSUE TITLE
Unable to use location / configs

### ISSUE THREAD

**Issue by vrelk** [jc21/nginx-proxy-manager#60]
I am trying to make a proxy host, but to get this one to work I need to be able to make changes in the "location / {" section. It looks like your configs also create that session, so it fails to "offline" and never creates the config file when trying to add a custom config that includes "location / {"

**Comment by RaNaMaster** [comment]
im aslo trying to do same thing please look in to this thank you
https://github.com/jc21/nginx-proxy-manager/issues/60

**Comment by jc21** [comment]
Would be possible with #65

**Comment by jc21** [comment]
This is solved with #79
