### ISSUE TITLE
Non default database password

### ISSUE THREAD

**Issue by ondrousn** [jc21/nginx-proxy-manager#603]
Hello, I would like to change default database password, as using just _npm_ does not seem really secure to me.

I changed the password in both _docker-compose.yml_ and _config.json_ files (from documentation), but am now failing with `Access denied for user 'npm'@'172.19.0.3' (using password: YES)` database error and can not log into web UI.

I tried switching to mysql container with root account and altering the password for _npm_ user and everything works fine after that, but I would like to set the password using _json_ and _yaml_  before running `docker-compose up -d`.

Please is this somehow possible and where is the problem?

**Comment by andrej-g** [comment]
The MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD variables are only used when initializing a fresh instance of the MySQL/MariaDB image (see https://hub.docker.com/_/mariadb, Initializing a fresh instance).

So either you'll have to recreate the database container from scratch with your new username/password or drop to the container console and modify the password manually.
