### ISSUE TITLE
Is It Possible To Serve The Front End Under The Scheme HTTPS?

### ISSUE THREAD

**Issue by mcbeav** [jc21/nginx-proxy-manager#606]
Due to some very specific restrictions, I need to serve the nginx-proxy-manager as HTTPS. Forcing an SSL certificate and doing an HTTP rewrite will cause a "Too Many Redirects" error. I am aware of why this is happening, and the fix for my situation is to serve the front end over the 443 port rather than through http. Is it possible to do this?

**Comment by andrej-g** [comment]
Does something like this not work for you?:

![npm](https://user-images.githubusercontent.com/61613562/93495206-2858fb80-f90e-11ea-8f24-7da95fe0dc69.png)

proxy.lan.mydomain.tld is the LAN accessible URL for the NPM frontend, the Forward Hostname/IP is NPM's hostname on the Docker network it's connected to (in the format of container-name.network-name; in my case that's nginx-proxy-manager.proxy).

Port 8181 is not published in the NPM container, SSL is forced and HTTP/2 support is enabled. With that the frontend is only accessible via https://proxy.mydomain.tld.

**Comment by chaptergy** [comment]
Yeah, you have to proxy it yourself. For the built-in feature request see https://github.com/jc21/nginx-proxy-manager/issues/182
