### ISSUE TITLE
Access lists without user (ip address only)

### ISSUE THREAD

**Issue by madmurl0c** [jc21/nginx-proxy-manager#612]
**Checklist**
- [x] Please read the [setup instructions](https://nginxproxymanager.com/setup/) 

- [x] Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

I use NginxProxyManager to redirect subdomains to specific docker containers.
Since I'd like specific containers to only be available from my local network I've set up the following access list through the web gui (just an example):

> **Satisfy any**
> false
> **User**
> local:local
> **Access List**
> 10.10.0.0/16

Is there a way to only use ip access lists without a user/login?

**Comment by Kipjr** [comment]
Will this work?
![image](https://user-images.githubusercontent.com/12066560/94989991-11a2dd80-0579-11eb-8fe8-4ab2a1013aec.png)
![image](https://user-images.githubusercontent.com/12066560/94989998-1a93af00-0579-11eb-8d11-2182f777aabc.png)

**Comment by madmurl0c** [comment]
@Kipjr Unfortunately not, if I configure it like that it still asks me for a username/password and if I enter nothing and just press "Sign in" the dialog comes up again

**Comment by Kipjr** [comment]
Did you check/uncheck "Satify Any" and re-add the list to the host?
![image](https://user-images.githubusercontent.com/12066560/94991878-64cf5d00-0586-11eb-987b-d010c07f7ce7.png)

**Comment by madmurl0c** [comment]
That seems to have fixed it, I just had to turn on Satisfy any, remove all users and re-add the list. Thanks a lot
