### ISSUE TITLE
NGINX + WORDPRESS + NEXTCLOUD need help with mySQL

### ISSUE THREAD

**Issue by Vendo232** [jc21/nginx-proxy-manager#616]
I`ve been trying to install WORDPRESS and NEXTCLOUD beyond NGINX Proxy and I always endup with some database error.
Here is my config https://pastebin.com/RDeJUAJk

A friendly help pointing to the problem with the mySQL setup would be awesome.

<img width="678" alt="Ca321321321pture" src="https://user-images.githubusercontent.com/44098230/94345524-bb1b2980-ffe3-11ea-93a8-e5d10cea4823.PNG">

**Comment by Kenchava** [comment]
In the app service in the proxy manager stack try putting:

`    depends_on:
      - db`
