### ISSUE TITLE
Prevent local application from rewriting url

### ISSUE THREAD

**Issue by jerommeke-bos** [jc21/nginx-proxy-manager#618]
I have a question, I configured a proxy host to reach a local webserver from the outside, ie xyz.domain.tld -> internal_ip:80. However the application running on that internal_ip:80 rewrites the url. Is it possible to prevent the rewriting in NGINX Proxy Manager (I can't change the rewriting in the application itself, so i hope it is possible to do it in NGINX Proxy Manager)?

**Comment by chaptergy** [comment]
Unfortunately no, NPM or nginx in general is not able to change anything that happens n your app.
