### ISSUE TITLE
nginx-proxy-manager in production

### ISSUE THREAD

**Issue by oxismailxo** [jc21/nginx-proxy-manager#619]
Hello nginx-proxy-manager Team,

First of all i wanna thank you about this great project cause for me like a Sysadmin is a very helpful solution also makes your life easy !, and i'm here cause i have a question about nginx-proxy-manager in production, is it safe to serve our docker projects with nginx-proxy-manager ? , if yes, my second question is: can nginx-proxy-manager huddle too many requests ?

**NOTE:** we are using it with Django projects.

thanks again,

**Comment by TWhidden** [comment]
We are running this in production. We wrote our shell scripts to manage spin up for our docker stacks  with the Proxy Manager in the middle of it. From our experience, a thing to note is that if your container is missing (or unresolvable), nginx will not start (with how its currently setup), which will put the nginx/proxy manager in a reboot loop.  We will work on fixing that soon, but number of requests goes through nginx around work world makes it a good assumption that its totally fine for a production system. The proxy manager IMO makes for a nice administrative layer, keeping people from messing with CLI / configs.

**Comment by oxismailxo** [comment]
Thank you so much @TWhidden for the clarification.
