### ISSUE TITLE
Support multiple upstream server

### ISSUE THREAD

**Issue by allblue** [jc21/nginx-proxy-manager#620]
**Is your feature request related to a problem? Please describe.**
I am using the PVE virtualization platform with a decentralized design, log in to any  node tcp 8006 port to manage the cluster.
However，currently npm can only reverse proxy a single node.

**Describe the solution you'd like**
In order to prevent the  node from going down, it is hoped to add  multiple upstream hosts supoort to realize the main-standby switch, eg “Forward Hostname / IP”  can be configured as a list with weight. 

**Describe alternatives you've considered**
Configure multiple reverse proxies in npm

**Additional context**
none

**Comment by elit3ge** [comment]
Yes please! +1

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/156
