### ISSUE TITLE
How to simply redirect no-www to www

### ISSUE THREAD

**Issue by Maritima** [jc21/nginx-proxy-manager#623]
Hi

I just want the domain to be redirected to a www if it is no-www  (https)
I tried this :

![image](https://user-images.githubusercontent.com/56633872/94811516-c0b6ac00-03f5-11eb-9336-4b42cb182d5e.png)

And 
![image](https://user-images.githubusercontent.com/56633872/94811562-ce6c3180-03f5-11eb-88c3-5a1c6d7c93ca.png)

But it doesn't work.

I wanted to avoid going through Redirection Hosts
![image](https://user-images.githubusercontent.com/56633872/94827495-cbc70780-0408-11eb-930e-d893a4720504.png)

do you have a simpler solution?

Thank you

**Comment by neojp** [comment]
I'm pretty new to NPM, but if I remember correctly the upstream `nginx-proxy` script would add the **custom nginx configuration** inside the `server { server_name; }` block, so you wouldn't be able to do it the way you're trying to.

**Comment by chaptergy** [comment]
Yes, the advanced config does go inside the server block. So no, this would need code outside of the server block, which is unfortunately not possible with NPM. So the redirect host would be your best bet.
