### ISSUE TITLE
Edit Access List :  error  code: 400

### ISSUE THREAD

**Issue by pablfr** [jc21/nginx-proxy-manager#624]
Hi,

If i put "*" on Access, I have this return :

![image](https://user-images.githubusercontent.com/1676195/94843385-ea36fe00-041c-11eb-84a6-0b753ca8b687.png)

`
error | Object { code: 400, message: "data.clients[0].address  should match pattern  \"^([0-9]{1,3}\\.){3}[0-9]{1,3}(/([0-9]\|[1-2][0-9]\|3[0-2]))?$\",  data.clients[0].address should match pattern  \"^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}\|:))\|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}\|((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3})\|:))\|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})\|:((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3})\|:))\|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})\|((:[0-9A-Fa-f]{1,4…4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3}))\|:))\|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})\|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3}))\|:))\|(:(((:[0-9A-Fa-f]{1,4}){1,7})\|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3}))\|:)))(%.+)?s*(/([0-9]\|[1-9][0-9]\|1[0-1][0-9]\|12[0-8]))?$\",  data.clients[0].address should match pattern \"^all$\",  data.clients[0].address should match exactly one schema in oneOf" }
-- | --
code | 400
message | "data.clients[0].address  should match pattern  \"^([0-9]{1,3}\\.){3}[0-9]{1,3}(/([0-9]\|[1-2][0-9]\|3[0-2]))?$\",  data.clients[0].address should match pattern  \"^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}\|:))\|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}\|((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3})\|:))\|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})\|:((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3})\|:))\|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})\|((:[0-9A-Fa-f]{1,4…4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3}))\|:))\|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})\|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3}))\|:))\|(:(((:[0-9A-Fa-f]{1,4}){1,7})\|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)(.(25[0-5]\|2[0-4]d\|1dd\|[1-9]?d)){3}))\|:)))(%.+)?s*(/([0-9]\|[1-9][0-9]\|1[0-1][0-9]\|12[0-8]))?$\",  data.clients[0].address should match pattern \"^all$\",  data.clients[0].address should match exactly one schema in oneOf"

`

**Comment by chaptergy** [comment]
Year, it should either be a subnet in CIDR notation or `all`, so in your case you need `all`.
