### ISSUE TITLE
Update issue - Help!

### ISSUE THREAD

**Issue by crazybadger** [jc21/nginx-proxy-manager#634]
I've been running this for a few months and it works beautifully, so thanks to begin!

I'm running this in a ubuntu 18.4.5 VM on FreeNAS and have about 15 subdomains for various services I'm running configured with Proxy Hosts and SSL certificates  I noticed that the certificates that are due for renewal on the 18 October hadn't, so manually updated one, which worked fine.  When I came to look on the website and then here, I noticed I was a little behind (I was running 2.2.3) so through I'd update.

I couldn't see any specific instructions so pulled the latest images and then stopped and started the containers using:

docker pull jc21/nginx-proxy-manager 
docker pull jc21/mariadb-aria
docker-compose down
docker-compose up -d

It started back up and I can access the WUI and see I now have 2.5.0, but when I click on a few of the menus nothing happens, specifically the Dashboard and SSL Certificate menus.

It's still working, and even appears to have updated the certificates that were due, but I can't see the menu to check.

Any ideas what I've done wrong and how to fix?

Thanks in advance

**Comment by crazybadger** [comment]
I guess I'll just roll back to the previous version.

It would be helpful to add some update guidance on the website/github page to avoid similar issues.

**Comment by LewisSmallwood** [comment]
I also have this problem @crazybadger upgrading from version 2.2.3 to 2.6.1.

How did you get it working again?

**Comment by k9barry** [comment]
Try clearing your browser cache.....  worked for me.

**Comment by jc21** [comment]
When you have these kind of problems more information is required. The docker logs would contain something if it were a backend issue and the browser console (F12) would contain something if it were frontend related.

@k9barry's solution is probably correct. Assuming this was a frontend caching issue, I have not encountered this before. The javascript assets of the UI are appended with the version number which should prevent browser caching and the UI will forcibly auto-reload if the backend is updated to a different version than the one the UI has expected. If clearing the browser cache doesn't fix the problem for you, please take a look at the logs/console and paste here if you need more help.

**Comment by crazybadger** [comment]
If it was something as simple as clearing the browser cache, that would support my suggestion for some better documentation around updating even more.
