### ISSUE TITLE
proxy a 'folder behind port'  like :8080/guacamole

### ISSUE THREAD

**Issue by aroundmyroom** [jc21/nginx-proxy-manager#636]
is this possible?

my.domain.com:8080/guacamole

to

new.domain.com:80

I do not want to write the quacamole part but it should be to the root part of a domain.

**Comment by PANiCnz** [comment]
To proxy Guacamole you need to add a "Custom Location", something like [this](https://ibb.co/cvBpfsW).

**Comment by aroundmyroom** [comment]
Great thanks .. 
I needed a trailing slash at the end to get it working .. awesome
