### ISSUE TITLE
LDAP authent 

### ISSUE THREAD

**Issue by Mr-icat59** [jc21/nginx-proxy-manager#638]
**Describe the solution you'd like**

Hello, is it possible to add an LDAP authent ? 

I tried to add an apache proxy with ldap authent ( yes i know it's weird) in front of the nginx proxy manager, but I have an error like "unauthorized" when i tried to authenticate with my user in the proxy manager.

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/159
