### ISSUE TITLE
not-responding form on add custom certificate

### ISSUE THREAD

**Issue by miguelwill** [jc21/nginx-proxy-manager#645]
currently using the latest version estabe 2.5.0

in the form to add a new custom certificate, when you press the button "save", it is static and without doing anything else

when I check the error console in the browser, I get the following message, indicating an error when checking a property not defined in that form (maybe it was inherited from the cloudflare form)

17.bundle.17.js:1 Uncaught TypeError: Cannot read property 'cloudflare_use' of undefined
    at i.click @ui.save (17.bundle.17.js:1)
    at HTMLDivElement.dispatch (main.bundle.js?v=2.5.0:27)
    at HTMLDivElement.p.handle (main.bundle.js?v=2.5.0:27)

I hope this problem can be solved soon

thanks

**Comment by M4tZeSS** [comment]
I seem to be having the same issue with a Cloudflare origin certificate.

**Comment by miguelwill** [comment]
I just tried on the recently released version 2.6.0 and the problem still persists

16.bundle.16.js:1 Uncaught TypeError: Cannot read property 'dns_challenge' of undefined
    at i.click @ui.save (16.bundle.16.js:1)
    at HTMLDivElement.dispatch (main.bundle.js?v=2.6.0:27)
    at HTMLDivElement.p.handle (main.bundle.js?v=2.6.0:27)

**Comment by jc21** [comment]
See #655 - which was submitted after 2.6.0 release.

**Comment by miguelwill** [comment]
thank you for the notice
i proceed to close the issue
