### ISSUE TITLE
The Picture not working

### ISSUE THREAD

**Issue by Yanis-93** [jc21/nginx-proxy-manager#651]
**What is troubling you?**
I have a question. 
I have a problem that my images won't load. When I connect behind the reverse proxy then the images load, but when I go back via the reverse they don't load.

Sorry my english is not good. I have Translated.
Before Reverse-Proxy
![Bildschirmfoto 2020-10-13 um 16 17 15](https://user-images.githubusercontent.com/61939521/95872991-bf7b6c80-0d6f-11eb-8291-f2352953328e.png)
After Reverse-Proxy
![Bildschirmfoto 2020-10-13 um 16 17 30](https://user-images.githubusercontent.com/61939521/95872995-c0ac9980-0d6f-11eb-916a-cfee20d43c52.png)

**Comment by rlogiacco** [comment]
What is the src URL of the missing images? 
What is the URL of the page after reverse-proxy? 
What is the URL of the page before reverse-proxy?

**Comment by Yanis-93** [comment]
The ip before revsere-proxy is 192.168.178.59.
The IP after Reverse Proxy is cloud.dreamliferoleplay.de
The Nextcloud is full configured with reverse Proxy.
 Number one is: http://cloud.dreamliferoleplay.de/remote.php/dav/addressbooks/system/system/system/Database:Mr.%20Ping.vcf?photo&size=32
Numer two is
http://cloud.dreamliferoleplay.de/remote.php/dav/addressbooks/system/system/system/Database:DerMatz.vcf?photo&size=32

**Comment by rlogiacco** [comment]
@Yanis-93 I never asked IP addresses, I'm asking for URLs... Anyways, I suppose you need to introduce content rewriting via the `sub_filter` [directive](http://nginx.org/en/docs/http/ngx_http_sub_module.html)

It worked for me in #652

**Comment by chaptergy** [comment]
As there has not been any activity for a while I will close this
