### ISSUE TITLE
Can I use `sub_filter` in proxy host advanced config?

### ISSUE THREAD

**Issue by rlogiacco** [jc21/nginx-proxy-manager#652]
**Checklist**

- [x] Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- [x] Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**
I'm trying to specify a `sub_filter` directive for a location within a proxy host, but it doesn't seem to work. By the [nginx documentation](http://nginx.org/en/docs/http/ngx_http_sub_module.html), it seems the module must be enabled separately during Nginx build: is it enabled in your build?

**Comment by rlogiacco** [comment]
Looks like I already ha

**Comment by wisoez** [comment]
Same question!
