### ISSUE TITLE
Certificate Failure on Configuration Check on Line 43 with a ; (semi-colon)

### ISSUE THREAD

**Issue by fanuch** [jc21/nginx-proxy-manager#655]
**Checklist**
[x] Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
[x] Are you sure you're not using someone else's docker image?
[x] ~If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?~

**Describe the bug**
Failure to apply certificate to proxy route on certificate request

**To Reproduce**
1. Go to SSL tab
2. Create certificate via defaults or even CloudFlare DNS
3. Receive "Internal Error" pop up box
4. Note that in the error, clicking "create" again will make another `/data/nginx/proxy_host/N+1.conf` too. 
i.e. `9.conf`,`10.conf`, and `11.conf` are all for the same host with the same error on the same line (line 43)

**Expected behavior**
Network access is not a problem.
Let's Encrypt not a problem.
CloudFlare API access is not a problem.

Error message should better reflect the issue.

**Screenshots**
![Screen Shot 2020-10-15 at 12 39 54 pm](https://user-images.githubusercontent.com/4865267/96065024-fb374300-0ee3-11eb-80fc-3fd748f47eb4.png)
**Note** relative number column is on. That is line 43 despite the picture saying otherwise.

**Operating System**
- NUC > ESXI > Ubuntu 18.04 LTS > Docker-Compose

**Additional context**
**Edit the first**: Failure to use web GUI as there is a startup failure for the same conf file issue. Just keeps looping, checking, failing, looping.

**Edit the second**: forcefully removing the stray semicolon allows the configuration to save the SSL options and apply the cert to proxy conf.

**Comment by jc21** [comment]
Looks like you forgot to mention that you've assigned an Access List to this failing host?

**Comment by fanuch** [comment]
Guess so.
![image](https://user-images.githubusercontent.com/4865267/96210264-45402780-0fbd-11eb-9593-8bcfae982090.png)

Valid internal CIDRs
![Screen Shot 2020-10-16 at 2 39 04 pm](https://user-images.githubusercontent.com/4865267/96210354-7882b680-0fbd-11eb-831f-624a997873c3.png)

**Comment by jc21** [comment]
Just pushed a commit to fix this. Keep an eye out for it in v2.6.1 soon

**Comment by fanuch** [comment]
Thank you!

Not sure if this helps, but manually created a wildcard cert and have been using that after deleting the failed conf without issues on all new proxy hosts.

I'll try recreate the issue after the release 😄
