### ISSUE TITLE
Problem using https on IOS devices (Safari browser)

### ISSUE THREAD

**Issue by sudvej** [jc21/nginx-proxy-manager#661]
When you turn on the https protocol on IOS devices, the web page does not appear. Letsencrypt certificate used. Apache server. In other browsers (Opera, Firefox, MS Edge) the secure connection works without problems.

**Comment by jc21** [comment]
Can't seem to replicate. I used these hosts on my iPhone every day.

**Comment by Wadera** [comment]
I've fo
Just set into **Custom Nginx Configuration**:
```
 proxy_hide_header Upgrade;
```

Full list of useful configs:
```
proxy_hide_header Upgrade;
proxy_hide_header X-Powered-By;
add_header Content-Security-Policy "upgrade-insecure-requests";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Cache-Control "no-transform" always;
add_header Referrer-Policy no-referrer always;
add_header X-Robots-Tag none;
```

**Comment by thefirst100yearsaredifficult** [comment]
I can’t replicate the issue too.

**Comment by Wadera** [comment]
What's your httpd server behind proxy? What's configuration you using?
In my case it's: 
* **Apache version 2.4.46.** behind proxy
* **Scheme:** https -> https (self-signed, server cert behind proxy and Let's encrypt on front from NPM)
* **x-Frame-Option**  set in in proxy and in apache config (where `192.168.1.123` is my proxy server IP):
```
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 192.168.1.123
```

**Comment by florianeichincode** [comment]
> proxy_hide_header Upgrade;
> proxy_hide_header X-Powered-By;
> add_header Content-Security-Policy "upgrade-insecure-requests";
> add_header X-Frame-Options "SAMEORIGIN";
> add_header X-XSS-Protection "1; mode=block" always;
> add_header X-Content-Type-Options "nosniff" always;
> add_header Cache-Control "no-transform" always;
> add_header Referrer-Policy no-referrer always;
> add_header X-Robots-Tag none;

That worked for me thanks

**Comment by matfortu** [comment]
Thanks a lot, this fix worked perfectly for me too!

> I've faced similar issue too. To fix just set into **Custom Nginx Configuration**:
> 
> ```
>  proxy_hide_header Upgrade;
> ```
> 
> Full list of useful configs:
> 
> ```
> proxy_hide_header Upgrade;
> proxy_hide_header X-Powered-By;
> add_header Content-Security-Policy "upgrade-insecure-requests";
> add_header X-Frame-Options "SAMEORIGIN";
> add_header X-XSS-Protection "1; mode=block" always;
> add_header X-Content-Type-Options "nosniff" always;
> add_header Cache-Control "no-transform" always;
> add_header Referrer-Policy no-referrer always;
> add_header X-Robots-Tag none;
> ```

**Comment by chaptergy** [comment]
I think this issue can be closed now? Let me know if I my assumption is wrong.

**Comment by tx-fz** [comment]
Can anyone offer some insight into why this happens and what the fix does? Is this something that would happen on any nginx setup?

**Comment by chaptergy** [comment]
It seems to be an nginx issue, so yes, it would happen on any nginx setup. See [the nginx issue](https://trac.nginx.org/nginx/ticket/915) or [an explanation on serverfault](https://serverfault.com/questions/937253/https-doesnt-work-with-safari)

**Comment by serjsv87** [comment]
It worked for me, thanks a lot for your help, many hours couldn't figure out what the problem was

**Comment by C-Sovandy** [comment]
I meet error the css and javascript doesn't loading on Safari but Chrome is ok
![Uploading CleanShot 2024-05-01 at 20.38.25@2x.png…]()

**Comment by russeldsouzaFRM** [comment]
I'm running a React JS application on an Nginx server (Ubuntu 22.04) and encountering problems with video playback on iOS devices. The videos play correctly on other platforms.
![ios-ss](https://github.com/user-attachments/assets/f8e9d912-ccc5-41f3-94bc-7f373122c0f6)
