### ISSUE TITLE
Internal hostname re-write/redirect

### ISSUE THREAD

**Issue by whattheschnell** [jc21/nginx-proxy-manager#667]
I want to use nginx-proxy-manager to access my internal web services.  I have an unraid server with several docker containers deployed.  Some use host, some use BR0, some bridge.  How can I configure a forward/rewrite/redirect to specific docker containers?

I have AdGuard Home running managing any of the DNS re-writes: 
unraid.lan --> 10.0.0.5

But am looking for forward along the lines of (in addition to above) : 

plex.lan --> 10.0.0.5:32400/web

Is it possible to manage with reverse proxy?  DNS cannot handle ports. If yes, how?

**Comment by chaptergy** [comment]
You can add a custom location `/` and then add Hostname `10.0.0.5/web` with port `32400` in there.

**Comment by balajeek** [comment]
Are you able to figure out, I have the same adguard home and npm installed, using npm primarly for local dns names by defining hosts in npm, works fine, but could this be done without npm?  I am not sure if i understand the previous response that add a custom location, in adguard or npm?
