### ISSUE TITLE
Resolver directive not working?

### ISSUE THREAD

**Issue by rlogiacco** [jc21/nginx-proxy-manager#669]
**Checklist**

- [x] Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- [x] Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

I'm using proxy manager to proxy docker containers but when a container is restarted the proxy manager reports a 502 BAD GATEWAY.
I tried adding the `resolver` directive in the advanced configuration, like `resolver 127.0.0.11 ipv6=off valid=30s;` but it doesn't seem to work:
![image](https://user-images.githubusercontent.com/199473/96600141-eba76800-12f0-11eb-9b37-03c0bdbaa948.png)

Do I need to use a variable for the resolve to work properly?

**Comment by Elmardus** [comment]
This may be related to the issue #633

**Comment by rlogiacco** [comment]
I managed to have it working and it also solves #633 : you must use a variable and the resolver directive. The variable prevents the DNS resolution at boot from nginx, the resolver determines how frequently such variable is checked against the internal docket DNS.

**Comment by Wadera** [comment]
I would suggest to show full resolution (for any other people who may face similar problem) and close Issue then ;)

**Comment by Elmardus** [comment]
@rlogiacco How did you use the variable and the resolver directive?
I found [this guide](https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/), but I have not figured out how to implement this in Nginx Proxy Manager.

**Comment by chaptergy** [comment]
I'm pretty sure he means like this:

```
location / {
    resolver 127.0.0.11 valid=30s;
    set $custom_upstream example.com;
    proxy_pass http://$custom_upstream:80;
}
```

The `$custom_upstream` is the variable which will prevent DNS resolution at startup.

Which you can paste into your advanced tab.

**Comment by kabadisha** [comment]
For anyone who finds this in future:
This is a valid workaround for the problem where Nginx Proxy Manager fails to start if it can't resolve on of the upstream servers (e.g. another docker container on your unRaid server that is not currently started).

This issue only occurs with Proxy Hosts in NPM that have custom locations defined. The workaround is to remove the custom location and instead declare it manually in the 'Advanced' tab of the host like so:
```
location / {
    resolver 127.0.0.11 valid=30s;
    set $custom_upstream example.com;
    proxy_pass http://$custom_upstream:80;
}
```
Just replace `example.com` with the host that is not always available.
