### ISSUE TITLE
Unable to build locally using 'docker build' from latest release

### ISSUE THREAD

**Issue by binhex** [jc21/nginx-proxy-manager#67]
Hi, currently its not possible to build a new docker image from what is on github, if you pull down the latest release (or branch master) and then attempt a docker build you will see missing files used in the build, output:-

`Step 9/21 : ENV NODE_ENV=production
 ---> Running in 0ae14e229c19
Removing intermediate container 0ae14e229c19
 ---> f483986396ed
Step 10/21 : ADD dist                /app/dist
ADD failed: stat /var/lib/docker/tmp/docker-builder216809384/dist: no such file or directory`

so im assuming that all files ADDed at build time are not currently on github, any chance you could push these up please.

**Comment by alaszlotrend** [comment]
Have you tried to install the npm deps and build the application?
```sh
$ bin/yarn install
$ bin/yarn build
$ docker build .
```
I've just pulled down the latest and code and seems to be working

**Comment by binhex** [comment]
i downloaded latest master branch and used the included Dockerfile to attempt build, according to some of the comments in the Dockerfile it should have all included dependencies from the base image used.

if those dependencies should be built as part of the build of the image then i would expect to see them included in the Dockerfile to be honest, as it stands its not really complete at the moment.

i will have a further play, thanks for the comment.

**Comment by jc21** [comment]
Take a look at the CI script, `Jenkinsfile` from line 64 to 71. You can ignore any commands using the `$DOCKER_CI_TOOLS` image, it's just a docker container with some helper commands.

Reopen if you still have problems.
