### ISSUE TITLE
letsencrypt wildcard certificates (without aliyun)

### ISSUE THREAD

**Issue by bookser** [jc21/nginx-proxy-manager#670]
I would like to be able to use letsencrypt wildcard certificates without being limited to aliyun.

https://www.aliyun.com/

**Comment by miguelwill** [comment]
difficult to implement, since let's encrypt certificates are associated with a specific domain.
wildcard helps to use the same certificate with different sub-domains or host names, but all under one main domain.

**Comment by chaptergy** [comment]
Letsencrypt wildcard certificates are possible using the DNS-challenge. You could request a certificate for `*.example.com` and you receive a wildcard certificate. However Aliyun is not yet in the list of the supported DNS providers. You can check which providers are supported in the [`certbot-dns-plugins.js`](https://github.com/jc21/nginx-proxy-manager/blob/master/global/certbot-dns-plugins.js) file.

**Comment by chaptergy** [comment]
FYI, Aliyun has also been available a little while later.
