### ISSUE TITLE
Is it possible to point domain to directory ?

### ISSUE THREAD

**Issue by lucius100** [jc21/nginx-proxy-manager#671]
Hi, I still don't know very well about nginx proxy manager.
I can setup everything, and works fine.
I just want to know does nginx proxy manager work like nginx/apache2 ?
Because I want to point my domain to the live directory, is it possible ?
Or it's just for proxying the port ?

**Comment by spoolr** [comment]
Like "mydomain.com" -> "192.168.0.1:81/live" ?

Yes, it can forward to a subfolder, but it was tricky many months ago when I originally tried it, probably still is.  You have to set up the first tab in the proxy, then duplicate the info in the second tab of the proxy (which is confusing...) and then you have to make sure you have a back slash on the directory (which is also confusing...)  It's possible the process has been improved upon, but I doubt it.    Expect a lot of "this should work but it doesn't" moments with NPM.

**Comment by ansred** [comment]
Yes, you can.

For example, in MS Exchange, you have different webpages to manage, ECP, OWA and etc.

If you wish to setup a subdomain to access directly a directory/page in the URL.

You may setup the subdomain first

http://ecp.example.com

 and then go to "Edit Proxy Host" >> "Advanced" >> and add the following line

> location = /{return 301 $scheme://$http_host/ecp;}

![image](https://user-images.githubusercontent.com/5244872/98005565-2d3f1500-1dbf-11eb-891d-1c6040eac46c.png)


That should takes directly to:

host.com/ecp

I hope that helps

**Comment by Strizz02** [comment]
Sorry, but for me it does‘t work. I have the impression that the inserted line leads to a request like

http://sub.mydomain/sub 

instead of 

http://myip/sub

At any case it doesn‘t help. Still looking for solution.

**Comment by chaptergy** [comment]
See https://github.com/jc21/nginx-proxy-manager/issues/104#issuecomment-490720849
