### ISSUE TITLE
i18n not defined

### ISSUE THREAD

**Issue by AdamHghs** [jc21/nginx-proxy-manager#672]
upon clicking proxy hosts when first signing into NginxProxyManager, I receive this error 
![image](https://user-images.githubusercontent.com/28889195/96767284-523c8c80-13aa-11eb-989c-68def3b795f7.png)

I can refresh the page and it goes away but I have noticed other strange interactions. the Drop down on the SSL tab for a new proxy host doesnt populate my existing certs and I cant select anything other than None. The proxy server itself still functions, but the web user interface not super usable now

**Comment by calvinbr** [comment]
i have the same problem. :(

**Comment by Lord117-SY** [comment]
Hello same here.
Corrected after cleaning my web browser cache.
This issue appeared just after updating from version 2.5.0 to version 2.6.1.
As the issue was not present with another browser, I just cleaned my cache and everything went back to normal.

**Comment by AdamHghs** [comment]
Clearing Cache solved my issue
