### ISSUE TITLE
Change the version

### ISSUE THREAD

**Issue by mlamb18** [jc21/nginx-proxy-manager#684]
I have developed the reverse proxy but am getting a time out issue when I add a new ssl certificate. I read on the issues page that reverting back to version 2.4 may help resolve this. 

How do I revert the proxy manager back to version 2.4?

**Comment by ikomhoog** [comment]
I don't know what platform you are using to install this container, but somewhere the is an URL for jc21/nginx-proxy-manager
this will automatically refer to jc21/nginx-proxy-manager:latest, but if you don't want the latest you can use an older version.
In your case you want 2.4 which will result in jc21/nginx-proxy-manager:2.4.0 is the URL you need.

If you need a different version, just check the dockerhub tags to see which tag is for your version https://hub.docker.com/r/jc21/nginx-proxy-manager/tags
