### ISSUE TITLE
Can't add any host to the nginx-manager since 2 days

### ISSUE THREAD

**Issue by dbeeren** [jc21/nginx-proxy-manager#685]
Since two days, out of the blue, i couldn't  add hosts to the UI anymore running on aarch64. The interface will work but there is no response from any panel on the dashboard. I've tried to rebuild everything but with the same result. Tested it on a armv7 image and it worked like a charm.

**Comment by ri4162** [comment]
Same for me, Logs show that its closing mysql and shutting down. Only started happening a day or 2 ago.

**Comment by chaptergy** [comment]
As this happened a while ago we probably don't have a chance at finding the issue now. If anyone ever experiences the issue again please open a new issue.
