### ISSUE TITLE
1.1.1.1 used as a placeholder, despite being real external website/address

### ISSUE THREAD

**Issue by TopBanana123** [jc21/nginx-proxy-manager#686]
Under edit Proxy Host, it states to use 1.1.1.1/path for sub folder forwarding

1.1.1.1 should not be used like this, as its a valid external address and website

![2020-11-03 12_18_49-Nginx Proxy Manager](https://user-images.githubusercontent.com/43852644/98025185-ff61cc80-1dce-11eb-8db7-bd7102fba76b.png)

**Comment by evulhotdog** [comment]
@TopBanana123 seems like an easy fix. Why not open up a PR?

**Comment by Julez404** [comment]
This one can be closed, was fixed with #1396
