### ISSUE TITLE
Stream Ports are not active

### ISSUE THREAD

**Issue by wasn-eu** [jc21/nginx-proxy-manager#688]
**Describe the bug**
If i create a new stream port this port will not be opened.
I have to manually edit the docker-compose file to add these ports.

**Expected behavior**
the ports should be opened automatically

**Operating System**
Debian 10

**Comment by jc21** [comment]
This is not a bug. This software does not have the ability to control Docker configuration. However you can overcome your issue by starting your container in [host networking mode](https://docs.docker.com/network/host/). [Docker-compose config](https://docs.docker.com/compose/compose-file/#network_mode)
