### ISSUE TITLE
more than one proxy host with the same domain name but different listening ports

### ISSUE THREAD

**Issue by wasn-eu** [jc21/nginx-proxy-manager#689]
**Describe the solution you'd like**
i have sometimes more than one port for a domain that i need to open and use a lets encrypt certificat.
i would like to add a the same domain multiple times with different listen ports and forward these to different ips and ports.

**Comment by chaptergy** [comment]
As the advanced config is inserted inside the `server { }` block:

```
server {
  listen 80;
  listen 443 ssl;

  # Advanced code will be added here <--------
}
```

you can add custom nginx configuration there to do this. As the advanced tab is just normal nginx code, support on this github repo will be very limited for this. If anyone wants to share their working configuration, you are very welcome to do so, but unfortunately we can't provide nginx help.

**Comment by ylluminate** [comment]
@chaptergy thank you for your example and suggestion. Can you clarify that if simply wanting to listen to multiple ports, say 80, 443, and 3000, one might simply have the following without any `ssl_certificate_key`, `location`, etc. definitions so that Nginx Proxy Manager handles those aspects for us?:
```
 server {
      listen 80;
      listen 443 ssl;
      listen 3000;
}
```

**Comment by Freddyqt** [comment]
I had a similar problem, that I needed to open port 8080 of a service. what I did was set up the docker-compose.yml file and add '8080:8080' , then create a proxy host and manually had to set it to listen on port 8080 and not port 80.
