### ISSUE TITLE
Problem adding proxy host

### ISSUE THREAD

**Issue by kurpaige** [jc21/nginx-proxy-manager#693]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

Not able to add a host and get a ssl cert.  I get Internal Error and in the error logs I see:
[error] 242#242: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "127.0.0.1:81"

In a container and the network is set to bridged.  This is a brand new container and the first host i'm trying to add.

**Comment by jc21** [comment]
when running something in a docker container in the default bridged networking mode, 127.0.0.1 doesn't mean what you think it means. If you want to access an open port on the docker host, you will have to specify a network card IP address.

If you don't want to do that, you can look at running the docker container in host network mode, so NPM will act as if it's running on the host directly and 127.0.0.1 will, in fact, be the docker host.

**Comment by kurpaige** [comment]
Thanks.  My real problem is that I have my ISP router, x.x.1.1 and my lab router off it this x.x.8.1 and I had to port forward on both servers.  Once I did this letsencrypt was able to verify the cert.  New problem might be just something npm is not set up to do.  this is the new error:
[error] 4954#4954: *1415 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.1.1, server: home.stafat.work, request: "GET /favicon.ico HTTP/2.0", upstream: "http://192.168.8.5:8081/favicon.ico", host: "xxx.staf.work", referrer: "https://xxx.staf.work/"

Is this just because it's not possible to proxy through two routers?

**Comment by MeikelLP** [comment]
@jc21 thanks that's what I needed to know. I though about this but some sub domains worked completely fine while others returned 502. I'd recommend updating the docs as many people seem to get this wrong 👍

**Comment by Kourgiantakis** [comment]
Having the same issue, but i don't really understand what i have to do to fix it.

**Comment by MeikelLP** [comment]
@Kourgiantakis are you running the proxy manager in a docker container?

**Comment by Kourgiantakis** [comment]
@MeikelLP, yes I'm running it via docker compose. I just used the example compose file.

**Comment by MeikelLP** [comment]
@Kourgiantakis please refer to https://github.com/jc21/nginx-proxy-manager/issues/693#issuecomment-722787481
