### ISSUE TITLE
Log Analyzer

### ISSUE THREAD

**Issue by wasn-eu** [jc21/nginx-proxy-manager#698]
**Describe the solution you'd like**
would like to see a log analyzer in the gui.
a short overview of actual access and historic

**Comment by ansred** [comment]
Or maybe to send a syslog traffic to Splunk or any syslog server. Yeah that would be nice.

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/401
