### ISSUE TITLE
Set default/global email for LetsEncrypt

### ISSUE THREAD

**Issue by BramCeulemans** [jc21/nginx-proxy-manager#7]
Allow to set a global LetsEncrypt email so that the field is filled by default

**Comment by jc21** [comment]
Yep, this is one of the first things completed in v2.

**Comment by jc21** [comment]
Version 2 is ready for someone to test besides me. Have a read of [the documentation](https://github.com/jc21/nginx-proxy-manager/blob/v2/README.md) including the [installation instructions](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/INSTALL.md) and [importing guide](https://github.com/jc21/nginx-proxy-manager/blob/v2/doc/IMPORTING.md).

The app has only a few minor bugs I want to change but I'm using it in production myself on 4 instances. 

If you have issues, probably be to report them as new issues and mention that they affect version 2 in the description.

Thanks
