### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by the-holger** [jc21/nginx-proxy-manager#700]
I set up npm using sqlite as my db. When following the setup guide (https://nginxproxymanager.com/setup/)  one detail is missing from the config.json file, instead of 
```
{
  "database": {
    "engine": "knex-native",
    "knex": {
      "client": "sqlite3",
      "connection": {
        "filename": "/data/database.sqlite"
      }
    }
  }
}
```

one should add the "useNullAsDefault" option for knex like this:

```
{
  "database": {
    "engine": "knex-native",
    "knex": {
      "client": "sqlite3",
      "connection": {
        "filename": "/data/database.sqlite"
      },
      "useNullAsDefault": true
    }
  }
}

```

Cheers!
Holger

**Comment by chaptergy** [comment]
On what environment did you encounter this issue? On most machines it should work like it does in the documentation.

**Comment by Karatekid2407** [comment]
Only for complete information in this ticket.
On my side it was Raspberry Pi4 8GB with the same issue
