### ISSUE TITLE
running on top os ESXI?

### ISSUE THREAD

**Issue by cTurtle98** [jc21/nginx-proxy-manager#701]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

_Clear and concise description of what you're trying to do and what isn't working for you_

hello

what is the best way to run this software on top of esxi? I have switched from unraid to esxi and I want to continue using your software. currently the best I can think of is to make a ubuntu vm and install portainer on it and install it ontop of that but I feel like there must be a better way

**Comment by Kipjr** [comment]
Similar situation here. I solved it recently. 

- Create a VM with 32GB storage and 2GB RAM. 
- Download a minimal 64bit Ubuntu version. 
- Install it (with OpenSSH-server)
- Create static IP
- Download docker and git
- Download docker-compose (portainer is optional)
- "Git clone Https://GitHub.com/jc21/nginx-proxy-manager.git"
- Enter folder and edit docker-compose.yml (ports)
- Enable UFW (SSH, HTTP(s) and take precautions against port and IP issues)
- Do "docker-compose up -d"
- Go to http://vm:port and profit
