### ISSUE TITLE
Menu is collapsed on mobile devices

### ISSUE THREAD

**Issue by Kipjr** [jc21/nginx-proxy-manager#702]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? YES
- Are you sure you're not using someone else's docker image? YES
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? YES

**Describe the bug**
- Non-desktop (responsive design) does not show all tabs and features
- What version of Nginx Proxy Manager is reported on the login page? 2.62

**To Reproduce**
- get android phone and chrome
- open NPM in browser
- login
- see the difference between desktop and smartphone

**Expected behavior**
- Same options and tabs as on desktop

**Screenshots**
![Screenshot_20201107-094655_Chrome.jpg](https://user-images.githubusercontent.com/12066560/98437216-c08a8a00-20e0-11eb-842b-71dc94a9eaf2.jpg)
**Operating System**
- Android + Chrome
- Windows + Crome

**Comment by dshedden** [comment]
Can confirm I'm seeing the same issue. 

Using the latest chrome browser on a pixel. Doesn't matter if you view the page in mobile mode or desktop mode.

**Comment by NuttCorp** [comment]
Having same issue. Unable to access SSL section from mobile web browser. Tried Chrome and Firefox. Switching to desktop view makes no difference. Definitely gonna buy you a coffee. Love the tool.

**Comment by infeeeee** [comment]
This is an issue on all mobile devices. This is reproducible in any browser's dev tools' [responsive design mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode)

On the UI a _collapse_ class is added to the menu, so it collapses on small screens. This class is also applied on the [tabler demo page](https://preview.tabler.io/), but there is no button to uncollapse the menu on npm's frontend.

Quick and dirty fix on your instance: 
- inside the container edit this file: `/app/frontend/css/main.css` 
- find and delete this section: `.collapse{display:none};`

This is just a temporary fix, it will be overwritten on next update. Create a backup of this file before editing if you don't know what you are doing.

More permanent fix should be to fix it in the repo, but I couldn't find a documentation how to set up a build environment for this project, and I don't want to create an untested PR, so if anyone can test this, please create a PR:

Easy solution: do not collapse the menu at all, as npm is not 100% responsive, I think this won't be a big problem.
Just simply delete the word 'collapse' from this line: https://github.com/jc21/nginx-proxy-manager/blob/b42cc9ed3ef3a875feae5026c8f7b8b71b7856e9/frontend/js/app/ui/menu/main.js#L9

The page should look something like this with this fix:

![kép](https://user-images.githubusercontent.com/1271737/116827954-204b8480-ab9c-11eb-9223-34f2a120e296.png)

Better solution should be to create a button for uncollapsing, as it's on tabler's demo page, but I have no idea how to do that.

**Comment by thunderclap82** [comment]
I'm surprised this hasn't been fixed yet considering it's been nearly a year. Looking at the suggestion it seems like a fairly straightforward fix. This isn't to belittle the developer -- real world life gets in the way, I get it -- but more of a reminder bump. :)

Overall, I really appreciate the work on this project.
