### ISSUE TITLE
Trouble with an http app over SSL

### ISSUE THREAD

**Issue by ylluminate** [jc21/nginx-proxy-manager#706]
I run multiple http (non-encrypted) web apps over SSL (https) via Nginx Proxy Manager and I've always had great success with this and having these apps converted to SSL handily.  I've finally met an app that's a closed source system and provides no http server logging.

For some reason or another it simply will not function with https access from the Internet.  Is there any way I can isolate any potential issues by what Nginx Proxy Manager might be seeing with this?

**Comment by chaptergy** [comment]
Unfortunately that's too little information to make any guesses. But since this issue is fairly old I'm not sure if you're still experiencing the issue. Hence I'll close this for now.
