### ISSUE TITLE
Custom SSL Certificate: Upload failed

### ISSUE THREAD

**Issue by chepetsk** [jc21/nginx-proxy-manager#712]
I have try to add custom ssl (https). It's valid.
nginx-proxy-manager last version.
![Screenshot at Nov 11 17-55-48](https://user-images.githubusercontent.com/71059922/98826866-468f3380-2447-11eb-8a9d-47995b7aa894.png)

**Comment by Paul-dH** [comment]
I'm also facing the same error

**Comment by flyos777** [comment]
Same

**Comment by lux4rd0** [comment]
Had the same problem right after I updated to the latest docker image. Switched back to:

`jlesage/nginx-proxy-manager:v1.10.2`

Was able to upload certs just fine.

Hope that helps in the short term...

**Comment by markverg** [comment]
same error here, also had to downgrade to work around the issue

**Comment by reda-alaoui** [comment]
I was using an RSA private key.
Modifying my key following https://github.com/jc21/nginx-proxy-manager/issues/759#issue-757712401 fixed the issue.

**Comment by chaptergy** [comment]
Fixed with https://github.com/jc21/nginx-proxy-manager/pull/774
