### ISSUE TITLE
Another 502 Error

### ISSUE THREAD

**Issue by daffgn** [jc21/nginx-proxy-manager#715]
**What is troubling you?**
Error 502 on several servers

_Clear and concise description of what you're trying to do and what isn't working for you_
I have 2 VM running various applications

One with Webmin and a Home Automation application
One with Webmin and a Genealogy Server

Everything is perfectly accessible on my local network on http

Both webmin app are accessible in https from outside 
The two other apps return a 502 error. The home automation used to work in https ....but stop working ....for some unknown reason

Any ideas where to look for ? logs on apps ? on nginx docker   (not sure where to locate them) ?  any configurations to be checked

Thanks in advance

Daf

**Comment by chaptergy** [comment]
[This](https://github.com/jc21/nginx-proxy-manager/issues/444#issuecomment-641615603) should help you. But as this issue is already fairly old I assume it has resolved itself.
