### ISSUE TITLE
I am try to upload a custom Certificate

### ISSUE THREAD

**Issue by fagnerpatricio** [jc21/nginx-proxy-manager#717]
Hi!
I'm trying to make use of my organization's own certificate in NPM, but for some reason I'm not able to upload it, I go through the web interface and add the certificate as shown in the image below:

![2020-11-13_07-54](https://user-images.githubusercontent.com/1405203/99064993-7d6b6380-2585-11eb-9cd5-d3fd95627695.png)

As soon as I give this command in the nginx logo that is in data / logs / error.log this line appears:

`2020/11/13 10:33:19 [warn] 258 # 258: * 225 a client request body is buffered to a temporary file / tmp / nginx / body / 2/00/0000000002, client: 10.100.0.10, server: nginxproxymanager, request: "POST / api / nginx / certificates / validate HTTP / 1.1", host: "10.128.1.140:81", referrer: "http://10.128.1.140:81/nginx/certificates"`

the web interface stays on that screen for several minutes:

![2020-11-13_07-45](https://user-images.githubusercontent.com/1405203/99064300-8c9de180-2584-11eb-86ac-eac2b615a8d7.png)

After a long time he presents this error in the web interface:

![2020-11-13_07-50](https://user-images.githubusercontent.com/1405203/99064731-1ea5ea00-2585-11eb-9849-4f6370c99166.png)

and in the logs the following message appears:

2020/11/13 10:48:19 [error] 258#258: *225 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.100.0.10, server: nginxproxymanager, request: "POST /api/nginx/certificates/validate HTTP/1.1", upstream: "http://127.0.0.1:3000/nginx/certificates/validate", host: "10.128.1.140:81", referrer: "http://10.128.1.140:81/nginx/certificates"

I'm using it via Docker following the instructions on the page:

`https://nginxproxymanager.com/setup/`

I've tried using both mariadb and sqllite as a database
I’ve also tried uploading using Firefox, Chorme and Cromium

**Comment by jc21** [comment]
Lets continue this discussion on #594
