### ISSUE TITLE
Restrict access to Admin Panel from outside the lan

### ISSUE THREAD

**Issue by rParslow** [jc21/nginx-proxy-manager#722]
Hi 

I've redirected ports 80/443 to the IP where nginx-proxy-manager is hosted 
From the internet if I try to connect to my.public.ip:81 the admin panel is prompted 
Same with a domain I've wildcardly redirected a domain to my IP and dummy.mydomaine.tld:81 prompt admin panel 

Could it be an settings to allow only connecting to the admin panel from the lan ?

**Comment by Wadera** [comment]
1. Disable port forwarding for port 81 ;)
2. Set new proxy, example: 
![image](https://user-images.githubusercontent.com/407236/99252283-a3536b00-2806-11eb-8c5a-1cf6fdd772b2.png)

3. Restrict IP for your proxy server for your own and local, for example:

```
satisfy any;
allow 192.168.0.1/15;
allow 172.0.0.1/8;
allow 123.123.123.123;
deny all;
```

![image](https://user-images.githubusercontent.com/407236/99252480-ee6d7e00-2806-11eb-8d0d-ce44d916136c.png)


Where `192.168.0.1` is your local network and `1233.123.123.123` is your own IP ;)

**Comment by rParslow** [comment]
Thanks @Wadera it works fine when I'm on my Lan 

But when I'm from an external IP 
As I've a wildcard domain pointing on my Ngnix Reverse proxy ponting on anysubdomain.maydomain.tld:81 or 42.42.42.42:81 
prompt the login panel of the manager. 

Where can I modify the host config of the pannel ?

**Comment by Wadera** [comment]
Like I said on first post: If you using proxy over some router - block port 81 (disable forwarding). 

> Disable port forwarding for port 81 ;)

If you don't have access to router - then block in on your Dorcker host machine over Firewall (example: iptables):
https://stackoverflow.com/questions/7423309/iptables-block-access-to-port-8000-except-from-ip-address

**Comment by Rustymage** [comment]
Try accessing from another location, such as someone else's internet connection or over a VPN.

I think you'll find you won't be able to connect.

I believe it only happens when you're on the same LAN. There's a technical explanation that I'll find the link too. However, in the meantime, try my suggestion.
