### ISSUE TITLE
ARMHF: node binary damaged

### ISSUE THREAD

**Issue by axute** [jc21/nginx-proxy-manager#73]
i can not start the docker image on raspi B+ (rev 1.2)

```
root@raspberrypi:/etc# cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 1000010
Serial          : 000000008a23b701

```

```
./run: line 11:  1508 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
./run: line 11:  1510 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
./run: line 11:  1512 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
./run: line 11:  1514 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
./run: line 11:  1516 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
./run: line 11:  1518 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
...

root@raspberrypi:/etc# docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS                                                                         NAMES
a4e3e92e8091        jc21/nginx-proxy-manager:2-armhf   "/usr/bin/entry.sh /…"   13 minutes ago      Up 13 minutes (unhealthy)   9876/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:8081->81/tcp, 0.0.0.0:8443->443/tcp   nginx-proxy-manager-app

```

tried following
```
root@raspberrypi:/etc# docker run -it jc21/nginx-proxy-manager:2-armhf /bin/bash
[root@docker-5e20de9aabf9:/]# node -v
Illegal instruction (core dumped)
```
running with docker version 18.06.1 (other are damaged in raspbian stretch)

**Comment by jc21** [comment]
Hmm interesting. Will take a look.

**Comment by jc21** [comment]
Can you give me the following outputs from your Pi console:
`uname -a`
`cat /proc/cpuinfo | grep Revision`

**Comment by axute** [comment]
```
root@raspberrypi:~# uname -a
Linux raspberrypi 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/Linux
root@raspberrypi:~# cat /proc/cpuinfo | grep Revision
Revision        : 1000010
```

**Comment by jc21** [comment]
Yeah so you're using a 5 year old Pi and the `armhf` docker image is for the `armv7l` instruction set. Honestly, I'm not even sure that the b+ can handle running this docker stack and a database :/

**Comment by axute** [comment]
hm okay, yesterday before starting the container, i installed the mariadb-server (per apt on host OS) and created an user with database for nginx-proxy-app. 

At the moment i have a nginx-proxy-server running (native, not in docker), also letsencrypt certbot ...
but your UI is much better then my scripts ;-)
where can i find your base-image for the armhf build? i will try to build an armv6 build ;-)

**Comment by jc21** [comment]
Cool so you'll have to build 2 docker images, one is the base for the other one. I've just added the dockerfiles for `armv6` to the repos but as I can't build them, I can't guarantee they'll work :)

To build the base:
```
git clone https://github.com/jc21/nginx-proxy-manager-base.git
cd nginx-proxy-manager-base
docker build -t jc21/nginx-proxy-manager-base:armv6 -f Dockerfile.armv6 .
```

To build the app:
```
git clone https://github.com/jc21/nginx-proxy-manager.git
cd nginx-proxy-manager
docker run --rm -v $(pwd):/app -w /app jc21/nginx-proxy-manager-base:armv6 yarn install
docker run --rm -v $(pwd):/app -w /app jc21/nginx-proxy-manager-base:armv6 npm run-script build
sudo rm -rf node_modules
docker run --rm -v $(pwd):/app -w /app jc21/nginx-proxy-manager-base:armv6 yarn install --prod
docker build -t jc21/nginx-proxy-manager:armv6 -f Dockerfile.armv6 .
```

Let me know how you go!

**Comment by hmehra** [comment]
Unable to build with this error -

`
Architecture: ARM v6
OS: Debian Bullseye
Variant: run variant
Default variable(s): UDEV=off
Extra features:
- Easy way to install packages with `install_packages <package-name>` command
- Run anywhere with cross-build feature  (for ARM only)
- Keep the container idling with `balena-idle` command
- Show base image details with `balena-info` command
Get:1 http://archive.raspberrypi.org/debian bullseye InRelease [23.5 kB]
Get:2 http://archive.raspbian.org/raspbian bullseye InRelease [15.0 kB]
Err:1 http://archive.raspberrypi.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:2 http://archive.raspbian.org/raspbian bullseye InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://archive.raspberrypi.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.raspberrypi.org/debian bullseye InRelease' is not signed.
W: GPG error: http://archive.raspbian.org/raspbian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.raspbian.org/raspbian bullseye InRelease' is not signed.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
`
