### ISSUE TITLE
Proxy Host - Limit access to local IP only

### ISSUE THREAD

**Issue by tristanXme** [jc21/nginx-proxy-manager#732]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Yes
- Are you sure you're not using someone else's docker image?
Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
Not a LetsEncrypt Problem

**Describe the bug**
- A clear and concise description of what the bug is.

I try to limit access to some proxy hosts only for my local network. but i can't get it work. Somewhere I read, that it's not supported, but on the other hand, I read that people are able to manage this.

- What version of Nginx Proxy Manager is reported on the login page?
v2.7.1

**To Reproduce**
Add a "Access List"
Add an IP to "Allow" at "Access"
Save

Assign the Access List to a Proxy Host and save the host

**Expected behavior**
Access from the local IP that was configured should work, other traffic should be blocked.
It works as soon as i enter my external IP, but as it change every 24 hours, thats not realy an option.

**Operating System**
Docker inside KVM Host

**Comment by l4rm4nd** [comment]
Have you configured a custom location? If yes, this is a bug for NPM currently, where an access list is not enfoced if there is a custom location configured. Otherwise, it works for me. 

Just specify the following private IP subnets and external access should be denied:

![image](https://user-images.githubusercontent.com/21357789/112673691-4ecf9480-8e65-11eb-98bf-72f9d4bc8247.png)

**Note**: Usually, your domain names should be resolved by an internal DNS server then. Do not leave a public DNS A-record, which points to your external ip address.

**Comment by hakunamatata97k** [comment]
> Have you configured a custom location? If yes, this is a bug for NPM currently, where an access list is not enfoced if there is a custom location configured. Further, disable the HTTP/2 option for SSL, this will also break some stuff often. Otherwise, it works for me. 
> 
> Just specify the following private IP subnets and external access should be denied:
> 
> ![image](https://user-images.githubusercontent.com/21357789/112673691-4ecf9480-8e65-11eb-98bf-72f9d4bc8247.png)
> 
> **Note**: Usually, your domain names should be resolved by an internal DNS server then. Do not leave a public DNS A-record, which points to your external ip address.
> 

Hello im having the same issue, i hope you can help :) 
I left my A-Record points to my public Ip address. Like my domain is from namecheap and i use dockerized ddclient to tell namecheap what my public ip is 🤷 . So im not quite sure what you mean? Would you care to elaborate 😊
