### ISSUE TITLE
Fail2Ban

### ISSUE THREAD

**Issue by Trrw** [jc21/nginx-proxy-manager#734]
Hello,

can you add Fail2Ban?

Thanks you!

**Comment by F-0PS** [comment]
I would also like to vote for adding this when your bandwidth allows. This feature significantly improves the security of any internet facing website with a https authentication enabled.

**Comment by Danie10** [comment]
Yes fail2ban would be the cherry on the top!

**Comment by crazybadger** [comment]
How would fail2ban work on a reverse proxy server?  Isn't that just directing traffic to the appropriate service, which then handles any authentication and rejection?

**Comment by Rustymage** [comment]
> How would fail2ban work on a reverse proxy server?  Isn't that just directing traffic to the appropriate service, which then handles any authentication and rejection? 

Unless you could parse the logs downstream at each service and update the list of banned IPs for npm to block upstream.

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/39
