### ISSUE TITLE
Thousands of xxxx_csr-certbot.pem file in csr folder

### ISSUE THREAD

**Issue by lettore** [jc21/nginx-proxy-manager#737]
Hello
I'm using NPM from long time and I'm really happy with it.
Today I found that in the csr folder of letsencrypt I have more than 33k files named xxxx_csr-certbot.pem and the same in keys directory named xxxx_key-certbot.pem.
There is a way to delete the unused files, I have only 126 certificates at the moment so I don't really understand why it keep creating so many *.pem files.
Thank you in advance.

**Comment by jc21** [comment]
I think this would be a [certbot](https://github.com/certbot/certbot) issue. 33k does seem like an excessive amount!

**Comment by lettore** [comment]
Maybe it is, but at the moment how I can know which files are currently
used as active certificates from NPM?
There should be a way to delete the unused files.

Il Lun 23 Nov 2020, 00:48 jc21 <notifications@github.com> ha scritto:

**Comment by jc21** [comment]
I've just had a google and [this answer suggests](https://community.letsencrypt.org/t/remove-all-generated-csr-to-free-disk-space/78237) that these csr files can be removed without impact. I've got 14k of them myself and I just deleted them without any problems.

**Comment by thomasesr** [comment]
I got 17,544 keys and csr files. Does anyone knows why this happens?

**Comment by chaptergy** [comment]
Linking some info:
- [LetsEncrypt Community Thread](https://community.letsencrypt.org/t/remove-all-generated-csr-to-free-disk-space/78237/9)
- https://github.com/certbot/certbot/issues/8525
- https://github.com/certbot/certbot/issues/4635
- https://github.com/certbot/certbot/issues/4634

**Comment by LiamKarlMitchell** [comment]
To remove these files from nginx proxy manager I read through the link suggested by jc21

I had to cd to each keys or csr directory.
And run the following.

Can probably delete them all but rm -rf * said there were too many args, this was taking up a decent chunk of disk space on my dev wsl2 after a few years.

```
find ./ -type f -name '*.pem' -mtime +91 -exec rm -rf {} \;
```

If the change to not save them to disk was made in letsencrypt, maybe nginx-proxy-manager is still using an older version of letsencrypt?
I haven't updated my nginx proxy manager in a fair while so if it's already fixed no worries.
