### ISSUE TITLE
Option to use TLSv1.2 instead of TLSv1.3

### ISSUE THREAD

**Issue by PlasmatikSteak** [jc21/nginx-proxy-manager#748]
**Is your feature request related to a problem? Please describe.**
Not a problem with nginx-proxy-manager, but Home Assistant and SmartThings integration not working with TLSv1.3.

**Describe the solution you'd like**
Option use TLSv1.2 instead of 1.3 under settings for any given proxy-host.

**Describe alternatives you've considered**
I tried to add ssl_protocols TLSv1.2; to the "Custom Nginx Configuration" section under Advanced for a given proxy-host but the result is that TLSv1.3 is still used.

**Additional context**
https://www.home-assistant.io/integrations/smartthings/#webhook-troubleshooting-checklist

**Comment by mochman** [comment]
It looks like this is an [issue](https://trac.nginx.org/nginx/ticket/676) with nginx itself.  
A workaround would be to set all of your sites to v1.2.  You can do that by modifying the `ssl_protocols` portion of the `/etx/nginx/conf.d/include/ssl-ciphers.conf` file in the app container.
