### ISSUE TITLE
Ali DNS support in DNS Challenge

### ISSUE THREAD

**Issue by wwkjfj** [jc21/nginx-proxy-manager#751]
Can you add Ali DNS support in DNS Challenge when apply to Let's encrypt certificate.
Or is there any way to add my own SSL certification, I found a custom_ssl folder but don't know how to set it up.

**Comment by chaptergy** [comment]
Is Ali DNS something different than the Aliyun provider? Aliyun is for the Alibaba cloud as far as I know.
