### ISSUE TITLE
Adress bar shows up the port of the destination webserver

### ISSUE THREAD

**Issue by v9999** [jc21/nginx-proxy-manager#754]
Hey there,
I have wordpress docker image running on a VPS with port 8080.
NGINX Proxy Manager is running with docker image too, with ports 80, 81 and 443.
I did a test with a dynv6 domain: _something_.**dns.army**. This address is set to get to my VPS' ip. 

NGINX Proxy Manager, then, is set to get the request for "something.dns.army" and get to the wordpress at port 8080.

It works, but the address bar now shows: something.dns.army:**8080**. Also, SSL functions don't work.

Am I doing something wrong? I thought that in a reverse proxy the port of the services behind wouldn't show up.

Thanks.

**Comment by null-burn** [comment]
Maybe your wordpress site is publicly available via docker?
