### ISSUE TITLE
Question about the API

### ISSUE THREAD

**Issue by inmanturbo** [jc21/nginx-proxy-manager#758]
I'm wondering if there's a way to expose the js api to backend services. What I'm trying to do is have services create their own Proxy Hosts on deployment in an automated fashion, perhaps with jwt token. I haven't surfed the code yet ...

**Comment by Xantios** [comment]
Not sure if i get what you want... but by some reverse engineering i figured out most of the API.

You can request a JWT token by posting your username and password to the auth route, store the JWT token and request almost anything you want with that. 

I build something like that for docker, so when i deploy a container it gets automagically wired into NPM

**Comment by shorkin** [comment]
> Not sure if i get what you want... but by some reverse engineering i figured out most of the API.
> 
> You can request a JWT token by posting your username and password to the auth route, store the JWT token and request almost anything you want with that.
> 
> I build something like that for docker, so when i deploy a container it gets automagically wired into NPM

Any news ?

**Comment by Xantios** [comment]
> > Not sure if i get what you want... but by some reverse engineering i figured out most of the API.
> > You can request a JWT token by posting your username and password to the auth route, store the JWT token and request almost anything you want with that.
> > I build something like that for docker, so when i deploy a container it gets automagically wired into NPM
> 
> Any news ?

About my little pet project? Check my GitHub profile. It’s called nginx proxy manager assistant . 

If you need anything from the developer, if I can figure it out, I’m sure you can! The man has a fulltime job, so I wouldn’t hold your breath

**Comment by inmanturbo** [comment]
> > > Not sure if i get what you want... but by some reverse engineering i figured out most of the API.
> > > You can request a JWT token by posting your username and password to the auth route, store the JWT token and request almost anything you want with that.
> > > I build something like that for docker, so when i deploy a container it gets automagically wired into NPM
> > 
> > 
> > Any news ?
> 
> About my little pet project? Check my GitHub profile. It’s called nginx proxy manager assistant .
> 
> If you need anything from the developer, if I can figure it out, I’m sure you can! The man has a fulltime job, so I wouldn’t hold your breath

Don't we all?  :smile: 
thanks for the tip, you didn't need anything to be added for csrf?

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/341
