### ISSUE TITLE
SSL Cert / vhost naming in filesystem

### ISSUE THREAD

**Issue by osnet** [jc21/nginx-proxy-manager#761]
If generating a SSL cert  it gets  stored  like  this

```
  ssl_certificate /etc/letsencrypt/live/npm-16/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-16/privkey.pem;
```

this is a little bit confusing. since i have to "extract" or copx the generated certs to  instances like  mailserver, gitlab etc.
Is there a way to geht them names correctly like the corresponding vhost ?

thx in advance

**Comment by osnet** [comment]
or at least add a hint in the frontend  on every ssl host  which ID the cert has

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/174
