### ISSUE TITLE
nginx-proxy-manager with high load traffic website

### ISSUE THREAD

**Issue by oxismailxo** [jc21/nginx-proxy-manager#781]
Hello NPM Community,

I wanna thank you for this great solution that makes sysadmins life easier, and the hard work!

I just have a question if is it okay to serve high load traffic website with Nginx-proxy-manager? if yes is there any configuration or hacks to use or any values to change in Nginx?

thank you in advance.

**Comment by MichelBaie** [comment]
There's no reason why it wouldn't withstand heavy traffic, I think it will run perfectly!

**Comment by oxismailxo** [comment]
@MichelBaie thank you for your response, I just looking for someone who already tested, let's wait for the others.

**Comment by inmanturbo** [comment]
@oxismailxo you may want to implement some from of logrotate.
