### ISSUE TITLE
Not passing (or completing) ssllabs.com tests

### ISSUE THREAD

**Issue by matt-benett** [jc21/nginx-proxy-manager#785]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? - Yes, using latest image, pulled on 2020 Dec 21st
- Are you sure you're not using someone else's docker image?  No
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?  Yes

**Describe the bug**
- A clear and concise description of what the bug is.
    I have my sites setup to use SSL from lets encrypt.  In the browser all seems ok.  But if i try to do a test at ssllabs.com, it only gets a couple of tests in before the test fails.
- What version of Nginx Proxy Manager is reported on the login page?    2.7.1

**To Reproduce**
1. Go to SSL and get a SSL cert from lets encrypt (i have tried wildcard and non-wildcard)
2. Apply this cert to a host
3. Force HTTPs, but no other settings checked.
4. Go to https://www.ssllabs.com/ssltest/  and enter your site.  
5. It will then fail a few checks in.
6. But it seems to work perfect in a browser.

**Expected behavior**
A report from SSL labs on the health of the SSL setup

**Comment by ssheduardo** [comment]
Some error, when set a ssl letsencrypt, the page show error.
This is my configuration

![image](https://user-images.githubusercontent.com/1160138/103419189-3ddaf400-4b92-11eb-9ee5-e745b2a19c13.png)
![image](https://user-images.githubusercontent.com/1160138/103419251-84305300-4b92-11eb-9f9e-49512a177ab1.png)

When open the url, the page show error.
![image](https://user-images.githubusercontent.com/1160138/103419368-0f114d80-4b93-11eb-8494-f25091f531dc.png)

**Comment by c0by85** [comment]
Can't confirm. Works fine.

![image](https://user-images.githubusercontent.com/25707747/104120440-31476000-5337-11eb-83c2-ed014c689680.png)
