### ISSUE TITLE
Removing /config folder causing user shares to disappear reboot required [UNRAID]

### ISSUE THREAD

**Issue by bluasoar** [jc21/nginx-proxy-manager#793]
**Describe the bug**
When I delete the config folder for NGINX Proxy Manager on unRAID it causes the shares to completely disappear, I couldn't figure out what was causing it, but I am fairly certain this is it as I've had the system crash on me 3+ times and each time it's after deleting the /config folder and restarting the container.

Version - v2.7.1

**To Reproduce**
1. 'shut down Container go to /config folder and remove it, restart container. 
All of my Shares are completely removed and I am greeted with an error that says "There are no exportable user shares". It seems to do something to the Network though I am outside of my depth. Reason I say this is all of the containers just stopped working. There is nothing that I could do to solve the issue besides a reboot. 

**Expected behavior**
I was expecting to Remove the /config folder and start the container back up with 0 issues.

**Screenshots**
Unfortunately didn't get any.

**Operating System**
- unRAID Version 6.9.0-beta30

**Additional context**
Nothing to add.

**Comment by chaptergy** [comment]
I'm very confused. What shares? And what config folders? This seems very specific to unRaid and has nothing to do with NPM.
