### ISSUE TITLE
Unable to add certificates

### ISSUE THREAD

**Issue by WilcoKakkenberg** [jc21/nginx-proxy-manager#794]
After several attempts I'm requesting help with my configuration of nginx-proxy-manager.

I'm running nginx-proxy-manager within the Docker environment on my QNAP NAS. 

docker-compose file:
version: "3"
services:
  nginx-proxy-manager:
    ## image: 'jc21/nginx-proxy-manager:latest'
    image: 'jc21/nginx-proxy-manager:github-develop'
    restart: always
    ports:
      - '1880:80'
      - '1881:81'
      - '18443:443'
    environment:
      DISABLE_IPV6: 'true'
      DB_MYSQL_HOST: "maria-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm-admin"
      DB_MYSQL_PASSWORD: "*********"
      DB_MYSQL_NAME: "npm"
      TZ: "Europe/Amsterdam"
    depends_on:
      - "maria-db"
    volumes:
      - '/share/data/containerstation/shared/npm/data:/data'
      - '/share/data/containerstation/shared/npm/letsencrypt:/etc/letsencrypt'
      - '/share/data/containerstation/shared/npm/config:/config'
  maria-db:
    image: 'jc21/mariadb-aria:10.4'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm-admin'
      MYSQL_PASSWORD: '**********'
      TZ: "Europe/Amsterdam"
    volumes:
      - '/share/Data/Container Station/Shared/npm/mysql:/var/lib/mysql'

I have set up the port forwarding in my router accordingly.
The nginx-proxy-manager seems to run fine. http host redirection is working properly.

When trying to add an SSL cert to a new or existing proxy host I get an "Internal Error"

This is the corresponding part in the log file:

[12/28/2020] [11:08:40 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-7" --agree-tos --email "email@mydomain.com" --preferred-challenges "dns,http" --domains "host.mydomain.com" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for p1mon.mydomain.com
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain p1mon.mydomain.com
http-01 challenge for host.mydomain.com
Cleaning up challenges
Some challenges have failed.

For privacy reasons I changed the host and domain name with "host" and "mydomain.com" in this post.

Thnx in advance for helping me out with this issue.

**Comment by anselal** [comment]
By me the redirection works too and I get a similar error like:

Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-6" --agree-tos --email "t.selalmasidis@gmail.com" --preferred-challenges "dns,http" --domains "git.example.com" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for git.example.com
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain git.example.com
http-01 challenge for git.example.com
Cleaning up challenges
Some challenges have failed.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

I also changed  the domain name

**Comment by WilcoKakkenberg** [comment]
I resolved the issue. 
Turned out that UPnP on my router opened another port.
After disabling UPnP on my router the only open ports were limited to 80 and 443.
