### ISSUE TITLE
Import letsencrypt configurations and certifications to nginx-proxy-manager

### ISSUE THREAD

**Issue by heliomcp** [jc21/nginx-proxy-manager#799]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

_Clear and concise description of what you're trying to do and what isn't working for you_
---
First, thank you, @jc21 for this great tool ;-)

I have successful to configure ngnix-proxy-manager as a docker for my pi host, but now I need to migrate all my local letsencrypt configuration and certifications to nginx-proxy-manager. I realize that it is not only a `cp -Rp` from local /etc/letsencrypt folder to the docker folder.

Are there any documentations to help me on this?

Best regards

**Comment by chaptergy** [comment]
Unfortunately there is not. For it to show up in the database you have to manually add them through the GUI. You could also try to write a script to automate this using the [api](https://github.com/jc21/nginx-proxy-manager/issues/341), but generally this is not supported.
