### ISSUE TITLE
Allow temporary disable of a proxy using checkbox

### ISSUE THREAD

**Issue by BramCeulemans** [jc21/nginx-proxy-manager#8]
As the title says, a proxy or redirect should be able to be disabled using a checkbox on the edit modal.

**Comment by jc21** [comment]
And what should a user see in their browser when a host is disabled? The default landing page, which is a http 200, or should they get a 404 not found?

**Comment by BramCeulemans** [comment]
Perhaps a default nginx 404. Or the screen you get when the proxies IP is not available. On Aug 22, 2018 00:40, jc21 <notifications@github.com> wrote:And what should a user see in their browser when a host is disabled? The default landing page, which is a http 200, or should they get a 404 not found?

**Comment by Daxx13** [comment]
> 
> 
> And what should a user see in their browser when a host is disabled? The default landing page, which is a http 200, or should they get a 404 not found?

+1 to this, when disabled I think the user should see default page when no matching hostname is configured. (same behavior as if you delete it, but without deleting of course haha)

Thanks!

**Comment by Saldash** [comment]
I'd like to up vote this one as well. Although I would opt for a global configuration setting that would let you choose what response code to return - Not Found, Service Unavailable etc...

**Comment by jc21** [comment]
Added in v2.0.8.
