### ISSUE TITLE
How to start the NGINX Proxy automatically after reboot

### ISSUE THREAD

**Issue by joergklein** [jc21/nginx-proxy-manager#800]
Operating System: CentOS 7

After a reboot the server, the NGINX Proxy Manager don't start automatically. Maybe with systemctl start nginx?????

**Comment by Berfi96** [comment]
Hi,
Do you launch the application in docker? 
Add a directive `restart: always` or `restart: on-failure` to your docker-compose.yml 

https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by joergklein** [comment]
restart: always works fine.
