### ISSUE TITLE
Call to Community - Kubernetes!

### ISSUE THREAD

**Issue by inmanturbo** [jc21/nginx-proxy-manager#805]
Wouldn't it be great to deploy this as an ingress controller/load balancer in kubernetes?

This is not so much a request for the original developer as it is a call to the community. Is there anyone else out there using this in k8's? Do any of you have experience with chart development?

Lately I've been moving some services to k8's and deploying (jc21/nginx-proxy-manager) along with metallb as an L7 load balancer, for simple self-service ssl termination. Having a chart to deploy as a k8's aware/compliant ingress controller would be very nice. Also, when scaling I have been using session affinity, but something like the ability to connect to Redis or Memcached would be better. I've been researching how to accomplish all of this myself but the truth is I could use a little help in that department. I'm more than willing to contribute to such a project, however I would much prefer someone with more chart development experience involved. Is there anyone out there interested in such a project?

Also @jc21 if you don't like this being posted here, please lmk. If you're interested I may be able to sponsor something like a Discourse forum for Nginx Proxy Manager! :heart:

**Comment by chaptergy** [comment]
Since this is, as you said, _a call to the community_, I will mark this as closed. You should still be able to comment if anyone wants to.

**Comment by danriedl** [comment]
Hi @inmanturbo , is there something we could work on together?
Trying to do sth similar.
