### ISSUE TITLE
Not working on LAN

### ISSUE THREAD

**Issue by gomme600** [jc21/nginx-proxy-manager#809]
Works externally (from my 4g connection for example), but not on my LAN.
With https I get an error about the site not being trusted and with http I get "this page isn't working".
My router, livebox 4, does support loopback and if I use the domain name with a port for example mydomain.com:8888 then that works from both my LAN and from 4g but none of the proxy hosts redirect from the LAN! Could anybode help please? Thanks!

**Comment by gomme600** [comment]
Ok, fixed. It was a router problem I think, I had to add my device to the DMZ on my router. I'm not sure why but hopefully the information helps others.

**Comment by benjujo** [comment]
> Ok, fixed. It was a router problem I think, I had to add my device to the DMZ on my router. I'm not sure why but hopefully the information helps others.

Indeed. Thank you!
Still can't understand what happened 🤔
