### ISSUE TITLE
Local domains / custom domains stopped working

### ISSUE THREAD

**Issue by dogmatic69** [jc21/nginx-proxy-manager#81]
I've been using this for my home automation and using `home` as a tld with bind server locally. This was working great until the last week or so, now I can no longer create certs for domains like `foo.home`.

After digging in the code (there is only a generic `internal error` popup in the UI) it seems that the domain needs to respond with some sort of endpoint to prove it exists. Any reason for this change?

This makes it really difficult to have certificates locally as now I would need to set up a fake service somewhere publicly to serve this endpoint just so that the certificate "validation" will pass.

**Comment by jc21** [comment]
> I can no longer create certs for domains like foo.home
I assume you mean LetsEncrypt certs created through this application. In that case, you should _never_ have been able to do so. If letsencrypt servers can't reach `foo.home` on your public ip and dns records, with ports open to Nginx Proxy Manager, you won't get a certified letsencrypt cert period.

This has been the case from day 1 - this is not a new change. If you want fully valid certified certs for privately hosted DNS records on your network, I don't think you're going to get it from any Certificate Authority.

**Comment by dogmatic69** [comment]
It's 100% has worked previously. I'll find another way then.

![image](https://user-images.githubusercontent.com/94674/53369717-1b4f7280-394c-11e9-89dd-a9b5ceb724cb.png)
