### ISSUE TITLE
Does Project Support use of Docker Secrets?

### ISSUE THREAD

**Issue by kevdogg** [jc21/nginx-proxy-manager#818]
Most docker projects I'm working with have started adopting docker secrets for storing important information such as passwords.

For example in the npm docker-compose example:

DB_MYSQL_PASSWORD: "npm"

With secrets this may translate to something like:

DB_MYSQL_PASSWORD_FILE: /var/run/secrets/npm

Does this project support this type of notation?

**Comment by ahgraber** [comment]
Bump - but also, it looks like NPM uses an s6 overlay, so I think you should able to crib the logic from something like [this](https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/01-envfile) and drop it into the /root/etc/cont-init.d folder.
I may give it a go and make a PR if it works.
