### ISSUE TITLE
Avoid port redirection

### ISSUE THREAD

**Issue by xNuno** [jc21/nginx-proxy-manager#82]
Hi, 

I'm using pihole and I want to be able to access to it without exposing it's port like i'm doing for other services but when I open the url https://mydomain.duckdns.org i'm redirected to https://mydomain.duckdns.org:4865/admin ... it's possible to avoid this port redirection without changing pihole config?

For instance Portainer use port 9000 but i'm able to access to it since it don't change port url to include the port...

Regards,
Nuno

**Comment by jc21** [comment]
That's something specific to the upstream server. There might be a setting in Pihole to say that despite running on port 4865, you want to access it behind a reverse proxy on port 80 (or https 443).
