### ISSUE TITLE
RPi4 - "Bad Gateway" on first login

### ISSUE THREAD

**Issue by willsmi1256** [jc21/nginx-proxy-manager#821]
**What is troubling you?**
First some info about my system:
- RPi4 4GB (part of a swarm of 5) running Raspbian Lite which is fully up to date
- Currently installed is Docker and docker-compose and I'm running the Portainer service on this machine as well

I'm pretty new to Docker in general, so I figured I would follow the default instructions to start with. I used the exact docker-compose file on [this page](https://nginxproxymanager.com/setup/). The install goes off without a hitch, but the app ends up in an unhealthy state. I did some looking and found [bug 483](https://github.com/jc21/nginx-proxy-manager/issues/483) which is exactly my error as well as several other similar threads posted elsewhere. 

I've read through as much as I could, but I can't seem to make any of the suggested compose files work either. They all give me the same errors. From what I can tell, the issue is that the app can't connect to the DB because it's not an ARM version, but I've tried several different mariadb versions as well SQLite (following the instructions on that setup page) that are supposed to be ARM friendly that also don't work.

I guess I'm really just hoping for some guidance here since it doesn't seem like the provided instructions are valid for my set up. 

Logs here: [_pi_app_1_logs.txt](https://github.com/jc21/nginx-proxy-manager/files/5799305/_pi_app_1_logs.txt)

**Comment by SF73** [comment]
I'm also running it on a rpi4. I had the same problem and found a solution.
I changed the mariadb image from `jc21/mariadb-aria:10.4` to `yobasystems/alpine-mariadb:armhf`

**Comment by willsmi1256** [comment]
> I changed the mariadb image from `jc21/mariadb-aria:10.4` to `yobasystems/alpine-mariadb:armhf`

Just gave this a shot. Same deal "Bad Gateway"

**Comment by Jiriteach** [comment]
Im running NPM on a RPI4/8GB and no problems. Use yobasystems/alpine-mariadb:latest as the db image. Make sure your environment has MYSQL_ prefixes instead of MARIADB_ and also change the default passwords.

Launch and use Portainer to check if its running after launch. If not - check the log from Portainer which will show you what error is being thrown.

**Comment by willsmi1256** [comment]
For some reason, switching to the Latest branch from the Armhf was what did the trick. I already had new passwords and the Mysql prefixes in my file, so that was all that changed. Thanks so much!

**Comment by mbino** [comment]
> 
> 
> I'm also running it on a rpi4. I had the same problem and found a solution.
> I changed the mariadb image from `jc21/mariadb-aria:10.4` to `yobasystems/alpine-mariadb:armhf`

How do you do this?

**Comment by willsmi1256** [comment]
Here's the compose file I used. Replace #PASS# with your passwords

version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "#PASS#"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '#PASS#'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: '#PASS#'
    volumes:
      - ./data/mysql:/var/lib/mysql

**Comment by NovaViper** [comment]
I tried this solution but it's still giving me that error on my pi 4

**Comment by Zusier** [comment]
Using `yobasystems/alpine-mariadb:latest` instead of `yobasystems/alpine-mariadb:armhf` Worked for me. Thanks
