### ISSUE TITLE
Last version downloaded show as 2.7.2 and should be 2.7.3

### ISSUE THREAD

**Issue by mcnahum** [jc21/nginx-proxy-manager#823]
I just downloaded the last version and it should be the 2.7.3 but the version number is 2.7.2...

Wrong version or wrong number?

**Comment by mochman** [comment]
Did you look at the [changes](https://github.com/jc21/nginx-proxy-manager/releases/tag/v2.7.3) for 2.7.3? Nothing changed with NPM, just the base container NPM runs on.

**Comment by mcnahum** [comment]
I'm extremely picky with version number...

**Comment by jc21** [comment]
My bad I forgot to update a file.
