### ISSUE TITLE
Warning on Container Up: "sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning."

### ISSUE THREAD

**Issue by johntdavis84** [jc21/nginx-proxy-manager#825]
Hello!

I'm getting a non-fatal warning when I bring up the container, using SQLite as the back-end.

> sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).

I think this wants me to change something in the `config.json`, but I can't figure out what. I've read a few docs but everything I've tried so far just keeps the container from launching. ¯\_(ツ)_/¯

Here's my config.json:

> cat ~/docker/dcomposers/nginx-pm/nginx-proxy-manager/config.json 
> {
>   "database": {
>     "engine": "knex-native",
>     "knex": {
>       "client": "sqlite3",
>       "connection": {
>         "filename": "/data/mydb.sqlite"
>       },
>       "pool": {
>         "min": 0,
>         "max": 1,
>         "createTimeoutMillis": 3000,
>         "acquireTimeoutMillis": 30000,
>         "idleTimeoutMillis": 30000,
>         "reapIntervalMillis": 1000,
>         "createRetryIntervalMillis": 100,
>         "propagateCreateError": false
>       },
>       "migrations": {
>         "tableName": "migrations",
>         "stub": "src/backend/lib/migrate_template.js",
>         "directory": "src/backend/migrations"
>       }

I'd appreciate any suggestions. :)

**Comment by chaptergy** [comment]
Have a look at https://github.com/jc21/nginx-proxy-manager/issues/700
