### ISSUE TITLE
Cannot Access the Reference Website from any browser https://nginxproxymanager.com/

### ISSUE THREAD

**Issue by dkupper76** [jc21/nginx-proxy-manager#833]
I cannot access the reference website: https://nginxproxymanager.com/setup/, but when I try to visit that website, I get the following error message from Firefox:

Secure Connection Failed

An error occurred during a connection to nginxproxymanager.com. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

And from Chrome I get the following error:

This site can’t provide a secure connectionnginxproxymanager.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

It doesn't matter what computer I use.

Also, I added comments to the issue "Bad Gateway" at Login Page after Upgrading to 2.7.0 #727 as I am having the same issue, and one of the recommendations in that issue is to visit the https://nginxproxymanager.com/setup/, which as I stated, I am unable to visit because of the aforementioned website security issues.

**Comment by dkupper76** [comment]
I incorrectly filed this as a bug, but I discovered it was actually a problem with the 2 Windows PCs I was using, when trying to access the website.

**Comment by darylf** [comment]
@dkupper76 Do you remember what the problem was with the 2 Windows PCs you were using?

I'm getting this error with Firefox and Chrome on Linux and I'm unable to visit the site
