### ISSUE TITLE
Can I use a non-standard ssl port for source?

### ISSUE THREAD

**Issue by timsayshey** [jc21/nginx-proxy-manager#844]
![image](https://user-images.githubusercontent.com/1148940/105766198-0f490280-5f1f-11eb-99e3-57ca717a6cf8.png)

I'm using this to expose a service from my home server over ssl. I don't want to open up 443 to the world. I'd prefer to use a non-standard port like 8443 or 3827 for access to my service. 

My question, is there a way to serve over a non-standard port?

**Comment by jozefrebjak** [comment]
I want this functionality too.

**Comment by petkin700** [comment]
> ![image](https://user-images.githubusercontent.com/1148940/105766198-0f490280-5f1f-11eb-99e3-57ca717a6cf8.png)
> 
> 
> 
> I'm using this to expose a service from my home server over ssl. I don't want to open up 443 to the world. I'd prefer to use a non-standard port like 8443 or 3827 for access to my service. 
> 
> 
> 
> My question, is there a way to serve over a non-standard port?

You can listen on additional ports, just add in advanced configuration tab line
```
listen 8443 ssl http2;
```

![image](https://user-images.githubusercontent.com/30834618/106514037-6aa96080-64dc-11eb-9b10-909a07f82ec3.jpeg)

**Comment by mosaati** [comment]
Hi @petkin700
I'm sorry to post here. I am trying to figure out a custom Nginx configuration to load-balance more than 1 host with different IPs. for the domain set up in the details tab. I think it requires a specific syntax to be added in the advanced tab that I can't figure out. Could you help me out with this?

My goal is let's say I have 3 instances of a kubernetes cluster and I wan to load balance them with their own subdomain and sub subdomains.

To explain, lets say 192.168.1.2, 192.168.1.3 and 192.168.1.4 are a kubernetes group with kub.example.com domain and any kub.example.com and *.kub.example.com requests should be forwarded to the cluster.

**Comment by chaptergy** [comment]
This should be done through the docker configuration. You can map it to any port outside of the docker container. So inside you docker-compose: 
![image](https://user-images.githubusercontent.com/26956711/118053716-8e4e3380-b374-11eb-87bf-c9a4d9e236ee.png)

**Comment by chaptergy** [comment]
@mosaati This has nothing to do with this issue. For your issue see feature request https://github.com/jc21/nginx-proxy-manager/issues/156

**Comment by chung1905** [comment]
Hello @chaptergy ,

Can we re-open this issue?

Your suggestion works.

But in my case, I need nginx-proxy-manager create 2 server with different listen ports, the same hostname, and different proxy_pass.
Using mapping in docker configuration won't allow me to listen to the same hostname.

Thanks

**Comment by chaptergy** [comment]
@chung1905 That's an entirely different thing. And is not possible without major rewrites of how npm works.  

You _could_ abuse the advanced config and add something that would generate a valid nginx config file when replacing the `{{advanced_config}}` inside [the template file](https://github.com/jc21/nginx-proxy-manager/blob/develop/backend/templates/proxy_host.conf). To get you started here is how it might look, it is untested and I have just copy pasted something to gether, I'm not sure if it works just like that: 

```nginx
  location / {
    # If you want HSTS 
    add_header Strict-Transport-Security "max-age=63072000; preload" always;

    # Proxy!
    include conf.d/include/proxy.conf;
  }
}
server {
  set $forward_scheme {{ forward_scheme }};
  set $server         "{{ forward_host }}";
  set $port           {{ forward_port }};

  listen <port>; # Add ssl if you want `ssl`
  # listen [::]:<port>; # If you want ipv6, you can also add `ssl` if you want ssl
  server_name <domain name>;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-<certificate id>/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-<certificate id>/privkey.pem;

  # If you want HSTS 
  add_header Strict-Transport-Security "max-age=63072000; preload" always;

  # If you want websockets
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
  proxy_http_version 1.1;

  access_log /data/logs/proxy-host-additional-listen_access.log proxy;
  error_log /data/logs/proxy-host-additional-listen_error.log warn;
```
Of course you need to replace the variables in the angled brackets: `<port>` (the non-default-port), `<domain name>`, and `<certificate id>`.

The documentation about the [listen directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen) might also help you.

But remember, this is a hacky workaround since this is not supported, and you will have to do some research yourself to make it work.

**Comment by ClearSeve** [comment]
Is there a solution to this problem?

**Comment by tangweiji** [comment]
I want this functionality too. @timsayshey

**Comment by sabey** [comment]
I assume this still doesn't work?

The only response I can get is over http which is the openresty json response `{"status":"OK","version":{"major":2,"minor":11,"revision":1}}`
and https wont return a tls certificate
