### ISSUE TITLE
Can`t access webui on port 82

### ISSUE THREAD

**Issue by Lifedruid** [jc21/nginx-proxy-manager#851]
Hello everyone,
i`m new in this self hosting world and i`m trying to setup nginx proxy manager to use with my cloud. I have openmediavault alongside the nginx server. I used docker to setup nginx proxy manager on port 82. When i go on localhost port 80 i have the page with Nginx proxy manager successfuly installed.... But when i go to localhost 82, the admin webui, it says unable to connect (firefox). I tried with chrome as well and no success. 
my docker compose file looks like this. Any help? 

version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '82:82'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "smth"
      DB_MYSQL_PASSWORD: "smthpass"
      DB_MYSQL_NAME: "smthdb"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'smthpass'
      MYSQL_DATABASE: 'smthdb'
      MYSQL_USER: 'smth'
      MYSQL_PASSWORD: 'smthpass'
    volumes:
      - ./data/mysql:/var/lib/mysql

**Comment by sirastynax** [comment]
I think your typo is at
`# Admin Web Port:
- '82:82'`
Internal ports should be at 81 for admin port, unless I am missing something somewhere.

**Comment by Lifedruid** [comment]
i changed it to 81 and moved omv to 82 but still no success. the admin web page says conection refused

**Comment by bwees** [comment]
Try swapping the numbers. Your docker port config should be -p 82:81. I sometimes get the order mixed up.

**Comment by Lifedruid** [comment]
In the end i identified the mistake. I changed the config only in portainer and always recreated the container with the yaml file. The file had 82 and in portainer i put 81. After i edited the yaml file and made it 81 it worked
