### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by sirastynax** [jc21/nginx-proxy-manager#852]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/) -Yup
- Please read the [FAQ](https://nginxproxymanager.com/faq/) - Yup

**What is troubling you?**
Most likely a configuration problem on my end, but I cannot seem to get Force SSL to work. I keep getting Too Many Redirects.

Currently using:
v 2.7.3
Chrome Browser and Edge
Both subdomain certificate and wildcard certificate

It is most likely a configuration I missed somewhere, but not sure where.

**Comment by Barbait** [comment]
+1 i'm interested as well

**Comment by lieven121** [comment]
If you manually go to the https website (with force ssl off) does this work?

**Comment by sirastynax** [comment]
Sorry I did not get an alert there were responses to this message.

The sites I was having an issue with were all http sites that I was proxying a connection to. I did however find part of the configuration issues that I had. Force SSL may not work with CloudFlare proxying. Since I was not able to get it to work at the server level, I enabled Strict SSL Enforcement on CloudFlare.

**Comment by mwgaillardetz** [comment]
@sirastynax I have been working on this for days and your solution was the only one that fixed my error. Thank you sir!!

**Comment by chaptergy** [comment]
Yeah, often Cloudflare is causing issues just like in this case. The cloudflare proxy does not actually follow the redirect nginx sends, which results in this error. You probably need to set the SSL/TLS encryption mode to `Full` or `Full (Strict)` or remove the additional CloudFlare proxy.

<sup>[Source](https://stackoverflow.com/questions/35143193/cloudflare-and-nginx-too-many-redirects/64853372#64853372)</sup>

**Comment by fahadshery** [comment]
> Yeah, often Cloudflare is causing issues just like in this case. The cloudflare proxy does not actually follow the redirect nginx sends, which results in this error. You probably need to set the SSL/TLS encryption mode to `Full` or `Full (Strict)` or remove the additional CloudFlare proxy.
> 
> [Source](https://stackoverflow.com/questions/35143193/cloudflare-and-nginx-too-many-redirects/64853372#64853372)

this solved my issue. had to change the settings in cloud flare

**Comment by wiqram** [comment]
> Yeah, often Cloudflare is causing issues just like in this case. The cloudflare proxy does not actually follow the redirect nginx sends, which results in this error. You probably need to set the SSL/TLS encryption mode to `Full` or `Full (Strict)` or remove the additional CloudFlare proxy.
> 
> [Source](https://stackoverflow.com/questions/35143193/cloudflare-and-nginx-too-many-redirects/64853372#64853372)

solved my issue. been at it for days on and off. damn such a simple change...

**Comment by Berg1042** [comment]
I met this issue too, @wiqram , could you please tell me what is your changed? thanks

**Comment by ultrask14** [comment]
> Sorry I did not get an alert there were responses to this message.
> 
> The sites I was having an issue with were all http sites that I was proxying a connection to. I did however find part of the configuration issues that I had. Force SSL may not work with CloudFlare proxying. Since I was not able to get it to work at the server level, I enabled Strict SSL Enforcement on CloudFlare.

Is the location for this setting in: website (the domain i have listedn in cloudflare) > rules > page rules > create new rule > SSL: full or SSL: full strict. 

This does not solve the issue entirely - i am now able to access the site however all formatting for the website is broken, its now basic HTML and any bitton press on the option on the menu shows the error "this page isnt redirecting properly)

**Comment by cye18** [comment]
> > Sorry I did not get an alert there were responses to this message.
> > The sites I was having an issue with were all http sites that I was proxying a connection to. I did however find part of the configuration issues that I had. Force SSL may not work with CloudFlare proxying. Since I was not able to get it to work at the server level, I enabled Strict SSL Enforcement on CloudFlare.
> 
> Is the location for this setting in: website (the domain i have listedn in cloudflare) > rules > page rules > create new rule > SSL: full or SSL: full strict.
> 
> This does not solve the issue entirely - i am now able to access the site however all formatting for the website is broken, its now basic HTML and any bitton press on the option on the menu shows the error "this page isnt redirecting properly)

@ultrask14 Thanks for the instruction. Same here. I can access the site but the format is messed up.

**Comment by cye18** [comment]
> > > Sorry I did not get an alert there were responses to this message.
> > > The sites I was having an issue with were all http sites that I was proxying a connection to. I did however find part of the configuration issues that I had. Force SSL may not work with CloudFlare proxying. Since I was not able to get it to work at the server level, I enabled Strict SSL Enforcement on CloudFlare.
> > 
> > 
> > Is the location for this setting in: website (the domain i have listedn in cloudflare) > rules > page rules > create new rule > SSL: full or SSL: full strict.
> > This does not solve the issue entirely - i am now able to access the site however all formatting for the website is broken, its now basic HTML and any bitton press on the option on the menu shows the error "this page isnt redirecting properly)
> 
> @ultrask14 Thanks for the instruction. Same here. I can access the site but the format is messed up. Did you by chance find a fix?

@ultrask14 I got it. It's not in Page Rules. It's under SSL/TSL -> Overview.
![image](https://user-images.githubusercontent.com/83248325/173733684-7596fe94-48d7-49d5-bb61-e86ac308bd31.png)
It works for me.

**Comment by baldunderwear** [comment]
> Yeah, often Cloudflare is causing issues just like in this case. The cloudflare proxy does not actually follow the redirect nginx sends, which results in this error. You probably need to set the SSL/TLS encryption mode to `Full` or `Full (Strict)` or remove the additional CloudFlare proxy.
> 
> [Source](https://stackoverflow.com/questions/35143193/cloudflare-and-nginx-too-many-redirects/64853372#64853372)



> > > > Sorry I did not get an alert there were responses to this message.
> > > > The sites I was having an issue with were all http sites that I was proxying a connection to. I did however find part of the configuration issues that I had. Force SSL may not work with CloudFlare proxying. Since I was not able to get it to work at the server level, I enabled Strict SSL Enforcement on CloudFlare.
> > > 
> > > 
> > > Is the location for this setting in: website (the domain i have listedn in cloudflare) > rules > page rules > create new rule > SSL: full or SSL: full strict.
> > > This does not solve the issue entirely - i am now able to access the site however all formatting for the website is broken, its now basic HTML and any bitton press on the option on the menu shows the error "this page isnt redirecting properly)
> > 
> > 
> > @ultrask14 Thanks for the instruction. Same here. I can access the site but the format is messed up. Did you by chance find a fix?
> 
> @ultrask14 I got it. It's not in Page Rules. It's under SSL/TSL -> Overview. ![image](https://user-images.githubusercontent.com/83248325/173733684-7596fe94-48d7-49d5-bb61-e86ac308bd31.png) It works for me.

Worked for me as well!

**Comment by thraizz** [comment]
The UI changed here, you need to go to "SSL/TLS Overview" in the sidebar, then click "configure".
![image](https://github.com/user-attachments/assets/8ec012f7-d41a-453a-ab11-84572cc155e2)

Then you need to select "Custom SSL/TLS" there the option "Full (strict)" and then "save".
![image](https://github.com/user-attachments/assets/77b51d2c-c41e-4c11-ba28-caf29d379a03)
