### ISSUE TITLE
support open non standar, low ranges, like 53tcp/udp...

### ISSUE THREAD

**Issue by aocana** [jc21/nginx-proxy-manager#857]
Does anyone know why it is not possible to use the low range ports like 53 or 22...?

**Comment by aocana** [comment]
hi!

I am getting the following error in the log:
`nginx: [emerg] bind() to 0.0.0.0.0:53 failed (13: Permission denied)`

it seems to be caused because these ports belong to the protected port range, but how to do then to be able to have a dns proxy, as indicated here;
https://www.nginx.com/blog/load-balancing-dns-traffic-nginx-plus/

**Comment by chaptergy** [comment]
Since NPM runs in a docker container you can use any port internally. Just map outside port `53` to inside port e.g. `5353`, then you can use `5353` in NPM.

![image](https://user-images.githubusercontent.com/26956711/118054770-64960c00-b376-11eb-8248-8f73d68ea984.png)
