### ISSUE TITLE
Default Site Settings

### ISSUE THREAD

**Issue by mat-m** [jc21/nginx-proxy-manager#858]
I enabled "default site" setting to display the Congrats page for 
> What to show when Nginx is hit with an unknown Host

As the subfield tells
I have 2 proxy hosts a.example.com  and b.example.com

When I try to reach c.example.com, I expect to see the Congrats page. instead I have a browser message about insecure connection with the Dummy certificate from Nginx Proxy Manager.

Did I miss a configuration here ?

**Comment by mat-m** [comment]
Looks like the proxy manager doesn't have an SSL-ready URL to publish the page.
Bug, feature or missing piece of config ?

**Comment by mat-m** [comment]
HTTPS on non-existing hosts is doomed to fail.
Need a wildcard domain to maybe be able to support this. I don't know if it's enough.

**Comment by hwcltjn** [comment]
@mat-m were you able to figure this out? It seems `/etc/nginx/conf.d/default.conf ` includes the dummy certs by default. Is there really no way of setting the default site correctly?
