### ISSUE TITLE
Installation Instructions are not clear

### ISSUE THREAD

**Issue by johntdyer** [jc21/nginx-proxy-manager#86]
so I think I need a little more info to install this.  I currently have a nginx server running and I have certbot running to handle my certs.  I would love to take this for a spin. So I have created a mysql database and now what? How do I migrate from a manual Ubuntu install to your tool ?    What do I need to put in the data dir ?  Do I point to a new Lets Encrypt folder ?   It would be great ot have a walk through for this type of scenario since I imagine most people will have had nginx installed before they try this tool.  Thanks and I look forward to trying this out once I'm able to get it installed correctly

**Comment by jc21** [comment]
This project is primarily distributed as a Docker image. It already contains cerbot and nginx along with configuration specific for use with this application.

The reason I've done this containerization is to control the running environment - and not have to handle more issues relating to individuals setup.

I recommend installing Docker and referring to the [Running instructions](https://github.com/jc21/nginx-proxy-manager/blob/master/doc/INSTALL.md).

**Comment by neil-bowers** [comment]
@jc21 I have to agree with @johntdyer here - at least for the Raspberry Pi docker image.

The first part of the installation instructions references either Vanilla Docker or Docker compose, but the Raspberry Pi instructions are just for Vanilla Docker - fair enough.

What isn't clear from the Raspberry Pi instructions is that users need to install MySql/MariaDb on their own, whereas your example Docker Compose file contains both elements - this image, plus the requisite database.

**Comment by jc21** [comment]
Installing mysql/maria on the pi host is not required, as the `mariadb` dockerhub image supports all those pi architectures - so does `nginx-proxy-manager:latest` as of a couple of months ago. However the example installation refers to `jc21/mariadb-aria` image which isn't multiarch and probably should be updated.

**Comment by elRadix** [comment]
so what's the correct database image to use with the appropriate settings in config.json  for rpi3?

**Comment by talondnb** [comment]
There doesn't seem to be one, but please someone correct me if I'm wrong.

I've tried the linuxserver/mariadb one which is supposed to be 10.3 I believe, but I'm getting syntax issues during launch.

**Comment by aitgelion** [comment]
> 
> 
> There doesn't seem to be one, but please someone correct me if I'm wrong.
> 
> I've tried the linuxserver/mariadb one which is supposed to be 10.3 I believe, but I'm getting syntax issues during launch.

I've the same problem with a Pi 3 and linuxserver/mariadb image.

`error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1`

**Comment by talondnb** [comment]
See here: https://github.com/jc21/nginx-proxy-manager/issues/146#issuecomment-533845196

**Comment by aitgelion** [comment]
> 
> 
> See here: [#146 (comment)](https://github.com/jc21/nginx-proxy-manager/issues/146#issuecomment-533845196)

The proposed database image "yobasystems/alpine-mariadb:latest" worked perfectly. Thank you!
