### ISSUE TITLE
Renewing SSL cert using digitalocean DNS challenge fails

### ISSUE THREAD

**Issue by the-holger** [jc21/nginx-proxy-manager#860]
I have a setup using the digitalocean DNS challenge to get SSL certs from letsencrypt, specifically a wildcard cert for my domain, which is only available when using the DNS challenge.

I could generate the cert using nginx-proxy-manager without any problems, however I couldn't renew the certs. The webui just gives me a "timeout" error, in the docker logs for the container I found the following:

```
[2/3/2021] [8:58:38 AM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
Renewal configuration file /etc/letsencrypt/renewal/npm-2.conf (cert: npm-2) produced an unexpected error: 'Namespace' object has no attribute 'dns_digitalocean_credentials'. Skipping.
0 renew failure(s), 1 parse failure(s)
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

I have absolutely no idea where to start debugging, as the issuing of the certificate was no problem at all. Any help would be really appreciated!

**Comment by stavros-k** [comment]
Having same issue here. While i can delete  then re add the cert i can't renew them.
Not wildcard but subdomains. Cloudflare DNS challenge


```
Processing /etc/letsencrypt/renewal/npm-93.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewal configuration file /etc/letsencrypt/renewal/npm-93.conf (cert: npm-93) produced an unexpected error: 'Namespace' object has no attribute 'dns_cloudflare_credentials'. Skipping.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by chaptergy** [comment]
Does your issue still persist?
Could you add what the content of your configuration file `/etc/letsencrypt/renewal/npm-2.conf` is?
