### ISSUE TITLE
How to use Ipv6 to reverse proxy

### ISSUE THREAD

**Issue by prayag17** [jc21/nginx-proxy-manager#861]
Hello,
I created an open media vault server and wanted to access its control panel outside my local network but my ISP has CGNAT on ipv4 but I can connect to my server using a public ipv6 address(given below). I found out about Nginx Proxy Manager a few weeks back and was able to install it on my server properly with the DB working correctly, but when I create a proxy host it would save it but will not bind to my subdomain. I have changed my Open media Vault's port to 82 to open port 80 and if it is on port 80 I can access it but I want to use subdomains as I have a plan to install Next Cloud and some other services too.
Ask me if you need more detail. PS: I am using Cloudflare as my DNS configurator.

Details:
External IP(IPV6 address): [2405:201:2002:8826:dea6:32ff:fe58:6c70] 
External IP(IPV6 address) for Open Media Vault: [2405:201:2002:8826:dea6:32ff:fe58:6c70]:82
Domain: prayagnet.tk
Subdomain: openmediavault.prayagnet.tk

Image: 
![image](https://user-images.githubusercontent.com/55829513/106759796-298a8b00-6659-11eb-93ff-72a6e8a8f002.png)

**Comment by prayag17** [comment]
Found a way to fixed it

**Comment by shaojs321** [comment]
I have the same question

**Comment by prayag17** [comment]
Turn's out all you need to do is give npm's container ipv6 address and use internal ipv4 address in the forward ip

**Comment by cellulosa** [comment]
> Turn's out all you need to do is give npm's container ipv6 address and use internal ipv4 address in the forward ip

heya could you be a bit more specific? I'm trying to achieve the same thing. Thanks!

**Comment by prayag17** [comment]
All you need to do is that, allow ipv6 mode in rocker's bridge network (you can google it), and that will allow NPM to access the letsencrypt servers. You need to make sure tho that your server has an ipv6 address assigned (can be checked with `ifconfig` command and under wlan or eth0 or lan or similar you can check whether there is a field called inet6 or ipv6, if present then you have public ipv6 address and also just to confirm, open that ip address on your phone which is not connected to your lan
`[ipv6Addr]:80` and if you see the nginx landing page then it worked). 

After assigning the ipv6 address, just add your normal ipv4 address to the hostname field and select the enable SSL cert option and it should work. If not then send me some SS of log

**Comment by cellulosa** [comment]
heya thanks for helping!

So to recap:
- I [enabled IPv6 support in the Docker daemon](https://docs.docker.com/config/daemon/ipv6/)
- Double-checked this is enabled by `docker network inspect bridge`
```"EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                },
                {
                    "Subnet": "2001:db8:1::/64"
                }
            ]
        },```
- [Retrieved by IPv6 address via `ifconfig en0` (under `inet6`)](https://ibb.co/L9wSZHG)
- Then realised that [`IPv6 networking is only supported on Docker daemons running on Linux hosts`](https://github.com/docker/for-mac/issues/1432)... And I'm on MacOS...
