### ISSUE TITLE
Godaddy dns wildcard support

### ISSUE THREAD

**Issue by JohnGalt1717** [jc21/nginx-proxy-manager#863]
**Is your feature request related to a problem? Please describe.**
Right now it appears that GoDaddy is not supported as a wildcard dns host while almost everything else is and acme.sh supports GoDaddy.

**Describe the solution you'd like**
Please add Godaddy wildcard support

**Describe alternatives you've considered**
Manually configuring. Yuk.

**Comment by pierrebengtsson** [comment]
I google search and I ended up here. I am also looking for godaddy support in the dns-challenge.

**Comment by arogic** [comment]
I am also looking for this feature. Thanks in advance.

**Comment by JohnGalt1717** [comment]
It appears that this might be possible to juse use ACME-DNS but I can't find an example of how to set this up.

**Comment by miigotu** [comment]
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_gd.sh

**Comment by chaptergy** [comment]
Nginx proxy manager uses certbot internally for LetsEncrypt certificates. This means, there needs to exist a certbot DNS plugin for this provider. Though there was [some progress made](https://github.com/certbot/certbot/pull/6135) to create such a plugin, no one seems to have actually [published a plugin like this](https://pypi.org/search/?q=certbot+godaddy).

If anyone is interested in publishing a plugin for GoDaddy, [this netcup plugin](https://github.com/coldfix/certbot-dns-netcup/blob/master/certbot_dns_netcup.py) can serve as inspiration.

**Comment by chaptergy** [comment]
Yes, that is correct. However certbot does not [directly support any lexicon provider](https://github.com/certbot/certbot/issues/6178). It always requires an additional layer in form of a plugin. 
It is not hard at all to create a plugin like this because of lexicon. But I can not personally create a plugin for a service I do not have and thus cannot test. I can only support anyone who would like to publish such a plugin.

**Comment by miigotu** [comment]
I have started on a plugin, but I have not tested it yet or debugged it. https://github.com/miigotu/certbot-dns-godaddy

**Comment by miigotu** [comment]
@chaptergy it is tested and working after a few updates, propagation time is defaulted to 30s rather than the usual 10s, but I only tested with 90s. 

```
Var dns_godaddy_credentials=./config.ini (set by user).
Writing new config /home/miigotu/Projects/certbot-dns-godaddy/work/renewal/miigotu.com.conf.
Reporting to user: Congratulations! Your certificate and chain have been saved at:
/home/miigotu/Projects/certbot-dns-godaddy/work/live/miigotu.com/fullchain.pem
Your key file has been saved at:
/home/miigotu/Projects/certbot-dns-godaddy/work/live/miigotu.com/privkey.pem
Your certificate will expire on 2021-08-10. To obtain a new or tweaked version of this certificate in the future, simply run certbot again. To non-interactively renew *all* of your certificates, run "certbot renew"
Reporting to user: If you like Certbot, please consider supporting our work by:

```

**Comment by chaptergy** [comment]
Nice work :+1: But for the propagation seconds the default value should be working, as this will be left at the default value most of the time. So could you please test it at the default propagation time as well or increase it to the value where you hat stable results?

**Comment by miigotu** [comment]
The netcup one defaults to 10 seconds (as does all of the ones built into certbot), and is recommended to use 900 seconds in the readme lol. I will test it more later though.

**Comment by chaptergy** [comment]
Yeah, it depends on how fast the DNS provider (GoDaddy) propagates DNS changes. Most are pretty fast, but not everyone. I'm not doing this to annoy you, its just that most people using NPM will never look at the readme, so the default value should be a sensible one. It could happen that GoDaddy is almost never able to propagate these changes within 30s, so the request would always fail (unless they overwrite the propagation time). Though it is unlikely, but I don't know anything about GoDaddy.

But it is really great that you took the time to publish this plugin :+1:

**Comment by miigotu** [comment]
```
2021-05-12 10:17:54,102:INFO:certbot.plugins.dns_common:Waiting 30 seconds for DNS changes to propagate
2021-05-12 10:18:24,130:INFO:certbot._internal.auth_handler:Waiting for verification...
...
2021-05-12 10:18:29,334:DEBUG:certbot._internal.reporter:Reporting to user: Congratulations! Your certificate and chain have been saved at:
/home/miigotu/Projects/certbot-dns-godaddy/work/live/random.com/fullchain.pem
```

**Comment by miigotu** [comment]
Off topic somewhat, bit how often do you merge develop to master and release new versions? I don't see an easy way to use this in homeassistant yet 😂
