### ISSUE TITLE
Azure Wildcard Support

### ISSUE THREAD

**Issue by JohnGalt1717** [jc21/nginx-proxy-manager#864]
**Is your feature request related to a problem? Please describe.**
Currently it doesn't appear that Azure DNS is supported by DNS Challenge but acme.sh supports it.

**Describe the solution you'd like**
Please add Azure DNS support

**Describe alternatives you've considered**
Manual configuration. Yuk

**Comment by vbap** [comment]
I would like this also

**Comment by chaptergy** [comment]
I have created a PR which includes this change. You can already test to see if it works before the next release if you use the docker image `jc21/nginx-proxy-manager:github-pr-1083` (in your docker compose) instead of `jc21/nginx-proxy-manager:latest`
