### ISSUE TITLE
Custom HTML for all different Error Pages (403,404,400,....)

### ISSUE THREAD

**Issue by Secarius** [jc21/nginx-proxy-manager#870]
**Describe the solution you'd like**
It would be very nice to be able to setup the error pages to custom html pages
It should be a "general" setting for all the proxy hosts.

**Describe alternatives you've considered**
changing them manual in the code will destroy the oportunity to update i think

**Additional context**
in the settings menu would be nice to have a option: 
example:
- add error page:
- - error numbe: 403
- - error handling:
- - - standard error page
- - - custom html
- - - rediect

**Comment by kwmc-lucas** [comment]
+1

I'm looking for exactly this, when we have some downtime when updating a site I would like to present a static page for the 502 error.

**Comment by codeagencybe** [comment]
any update on this? Would also like to see this feature

**Comment by Secarius** [comment]
any update so far?

**Comment by chaptergy** [comment]
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/26

**Comment by b4sh1t1** [comment]
> Duplicate of #26

it's not duplicate; the guy in issue #26 explain how to add a custom page; not how to add a custom 502!

**Comment by kylethedeveloper** [comment]
You may try my solution:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/26#issuecomment-1100295543
