### ISSUE TITLE
CLI to add custom ssl certificate?

### ISSUE THREAD

**Issue by bdf0506** [jc21/nginx-proxy-manager#874]
First off, THANK YOU so much to @jc21 for doing this project. It has made life sooooo much easier! I also recognize that there are over 400 issues on this project, so this may never be addressed, but figured I would try.

I use GoDaddy for my DNS, and unfortunately GoDaddy is not currently supported today. So instead, I'm using the dehydrated application to generate my SSL certificates that I need. It auto renews and everything is great.

But, every time my cert expires, I have to manually pull the generated certificate, upload it to nginx proxy manager, and then update the proxy host to use that SSL cert. I see that I can manually place the certificate in the custom_ssl/npm-x folder, where x is the number of the certificate. However, simply adding the file here doesn't do me anything other than getting it onto the filesystem. I also need a way to tell nginx proxy manager that the cert has been added here, so that it can actually be uploaded to the database. Is there any way that I can tell it from the cli to add the new cert to the database? If so, I can then script this up the proper way, hopefully.

**Comment by christian-skjetne** [comment]
If you have the certs in the local file system you can maybe use this: https://github.com/jc21/nginx-proxy-manager/issues/87#issuecomment-742831838 as a workaround for now.

**Comment by bdf0506** [comment]
This will work for now! I'll close this out since it seems to be a dupe of #87. Thanks for the pointers.

**Comment by gomme600** [comment]
Would love this too!

**Comment by Ducksoul** [comment]
I had to declare absolute paths within the include lines. Otherwise the proxy hosts went offline:
`include /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf;`
