### ISSUE TITLE
How to increate upload size?

### ISSUE THREAD

**Issue by trigun539** [jc21/nginx-proxy-manager#878]
**Is your feature request related to a problem? Please describe.**
Upload failed due to max upload size

**Describe the solution you'd like**
In advanced config, ability to set max upload size value

**Describe alternatives you've considered**
Tried custom nginx.conf file in advanced config but didn't work.

**Comment by trigun539** [comment]
This turned out to not be an issue with nginx-proxy-manager but the php side of things behind the nginx proxy manager. A fairly large file was able to be uploaded, so I think nginx allows large files through it.

**Comment by war3zlod3r** [comment]
Sorry to necro up an old post but I'm trying to find the php.ini file to make modifications or work around this same problem but struggling to find the file, can  you point me in the right direction please?
