### ISSUE TITLE
[Feature request] Add X-Frame-Options setting to allow loading Proxy Manager inside of Organizr

### ISSUE THREAD

**Issue by xdasqurl** [jc21/nginx-proxy-manager#88]
As you describe in the project goal, Proxy Manager is meant to be as simple to use a monkey can do it. Since a lot of us monkeys use Organizr to manage their services, I think I would be nice to have a toggle inside the GUI to allow Proxy Manager to be loaded inside an iframe within Organizr (or any other service), so we don't have to go monkeying around with the nginx config :)

`add_header x-frame-options allow-from uri`

Thanks in advance for considering this.

**Comment by jc21** [comment]
This seems like a bit of an oversight. I'll try to add this as a docker environment variable.

**Comment by xdasqurl** [comment]
Awesome, thanks!
