### ISSUE TITLE
Access-Control-Allow-Origin for all

### ISSUE THREAD

**Issue by fturiot** [jc21/nginx-proxy-manager#882]
Problem with cors reject 
how can i change add_header Access-Control-Allow-Origin 
i have add in host config but no result
thanks for help

**Comment by vercas** [comment]
What you need is this, as far as I know:  
```nginx
proxy_set_header 'Access-Control-Allow-Origin' "https://example.com";
```

**Comment by fturiot** [comment]
yes but i have solve thanks

**Comment by vercas** [comment]
@fturiot Then close the issue?

**Comment by aguirre-julian** [comment]
> Lo que necesitas es esto, hasta donde yo sé:
> 
> ```nginx
> proxy_set_header  'Access-Control-Allow-Origin'  "https://example.com" ;
> ```



where?

**Comment by aguirre-julian** [comment]
> si pero lo he solucionado gracias

how?
