### ISSUE TITLE
Support vor acme-dns Validation API

### ISSUE THREAD

**Issue by jonasled** [jc21/nginx-proxy-manager#884]
**Is your feature request related to a problem? Please describe.**
I'd like to use nginx proxy manager in combination with DNS validations, but my provider doesn't have a dns API

**Describe the solution you'd like**
Please add support for the acme-dns service

It would be nice to add support for the [acme-dns](https://github.com/joohoi/acme-dns) DNS api, this is a service you can host yourself to add DNS Validation support to services, which don't have a API (or just not a plugin for certbot). There is already a working plugin for certbot which can be implemented: https://github.com/pan-net-security/certbot-dns-acmedns

**Comment by chaptergy** [comment]
Closing due to PR https://github.com/jc21/nginx-proxy-manager/pull/946 and similarity to https://github.com/jc21/nginx-proxy-manager/issues/836
