### ISSUE TITLE
Can't download big file from nextcloud server cos of nginx proxy manager...

### ISSUE THREAD

**Issue by Zantag** [jc21/nginx-proxy-manager#891]
Pls help me to config the nginx proxy manager. I cant download big files from nextcloud which i access from nginx proxy manager hosted on ubuntu vm via docker.

I made small video clip to show exactly what happen when i try to download bigger files:

https://streamable.com/m53q0h

The video clip is speedup x4. In the video i use chrome for download 13 GB file... above you can see that i use "top" command from my VM where is hosted nginx proxy manager... I add more RAM to the VM with the hope that i will fix the problem... no success... I tried with many browsers and different computers on different networks same result - download is failed.

This is the whole entries that i add to the nginx proxy manager:

Without first 4 entries i have exact same problem but also with smaller files...

proxy_set_header Host $host;

proxy_set_header X-Forwarded-Proto $scheme;

proxy_set_header X-Real-IP $remote_addr;

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_max_temp_file_size 16384m;

fastcgi_max_temp_file_size 0;

client_max_body_size 0;

**Comment by l4rm4nd** [comment]
Try to specify the following in the advanced settings of a custom location:

````
client_max_body_size 0;
````

**Comment by CC1337** [comment]
I have the same issue with Nexctcloud - but a simple apache hosted directory behind another proxy entry works, so my current guess is that nextcloud is (still) misconfigured for bigger files/requests and it's nothing you can fix in nginx proxy manager.
