### ISSUE TITLE
Starting w/ 2.8.0 seeing errors and significant CPU usage

### ISSUE THREAD

**Issue by yieldhog** [jc21/nginx-proxy-manager#892]
Using 2.8.0 docker image on Synology. Have been successfully using this tool for over a year (its great). I noticed with the latest version my CPU usage has been spiking quite a bit, logs show a looping error as follows, I did not change any settings from 2.7.3 to 2.8.0, thank you.

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:81 failed (98: Address in use)
nginx: [emerg] bind() to [::]:81 failed (98: Address in use)


./run: line 18:  2711 Illegal instruction     (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
```

**Comment by appleimperio** [comment]
Same here on Open Media Vault raspberry pi 4, image v 2.8.0

`nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:81 failed (98: Address in use)
nginx: [emerg] bind() to [::]:81 failed (98: Address in use)`

**Comment by Jiriteach** [comment]
I experienced this as well as part of the upgrade. I killed my containers and re-launched with existing config and all is working fine now.

**Comment by yieldhog** [comment]
@Jiriteach Thanks, I deleted the container and restarted. No longer getting prior error. I tried renewing an SSL certificate but am getting this error now, are you?

```
Renewing Let'sEncrypt certificates via Cloudflare for Cert #7: XXXX.com
Command failed: /usr/bin/certbot renew --non-interactive --cert-name "npm-7" --disable-hook-validation
Another instance of Certbot is already running.
```

**Comment by yieldhog** [comment]
Nevermind, looks like it has to do with DNS challenge on my part related to Cloudflare.

As far as the issue above and "address in use" / excessive CPU usage on upgrade to 2.8.0, it seems like the solution is to delete the container and build again. Thanks for the help.

**Comment by appleimperio** [comment]
> @Jiriteach Thanks, I deleted the container and restarted. No longer getting prior error. I tried renewing an SSL certificate but am getting this error now, are you?
> 
> ```
> Renewing Let'sEncrypt certificates via Cloudflare for Cert #7: XXXX.com
> Command failed: /usr/bin/certbot renew --non-interactive --cert-name "npm-7" --disable-hook-validation
> Another instance of Certbot is already running.
> ```

I use Cloudflare too and getting similar error how did you solve it? 
[2/13/2021] [11:07:00 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation

**Comment by yieldhog** [comment]
@appleimperio I had to delete the SSL, re-create using additional information from issue #680 I added:

```
# Cloudflare API token
dns_cloudflare_email=something@hotmail.com
dns_cloudflare_api_key = 0123456789abcdef0123456789abcdef01234567
```

After re-creating the SSL cert using the above, seems as if I am able to renew as well.

**Comment by Nenodema** [comment]
Rebuilding the container was indeed the solution...!
