### ISSUE TITLE
How to use infront of Docker Swarm

### ISSUE THREAD

**Issue by palitu** [jc21/nginx-proxy-manager#893]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**DONE**

**What is troubling you?**

Hey team - love this, makes it so easy to add a new service to my list of proxies, with SLL of course!

I am wanting to move to docker swarm, across a few servers, and want to be able to be able to proxy to any of the servers that is running the proxy.

Obviously swarm has an internal proxy, but if a server is off it cannot do any routing for me.

Has anyone used this infront of swarm, referencing all the nodes within the swarm for a service?

Thanks!

Palitu

**Comment by mosaati** [comment]
This is something I want to know too. Right now I don't see a way to implement it out of the box. Their might be a way to do it in the advanced tab while adding a host but I honestly don't know how and hoping someone could help with the syntax.

**Comment by chaptergy** [comment]
Relevant feature request: https://github.com/jc21/nginx-proxy-manager/issues/156
