### ISSUE TITLE
💬 Best ways to get support

### ISSUE THREAD

**Issue by jc21** [jc21/nginx-proxy-manager#898]
Following the popularity of the project, it's probably best to separate these communication areas for visibility. You'll be more successful with your questions if you ask in the right place.

### Bugs and Feature Requests
Create them [right here](https://github.com/jc21/nginx-proxy-manager/issues/new/choose), as issues on GitHub.

### Product Support: docker, proxying services, ports, distributions etc
There's a [Reddit community](https://www.reddit.com/r/nginxproxymanager/) that's best for asking for this kind of support. Probably the best place to announce something new you've contributed to the project as well.

### Contribution support, code review discussions etc
[Gitter Chat](https://gitter.im/nginx-proxy-manager/community) is great for developers to get together to talk about this kind of stuff.

**Comment by Jiriteach** [comment]
Thanks an awesome work on this project so far! Loving the updates and features.

Another option that could assist those interested in the project is the new feature on Github - Discussions which can be enabled for the repo. Ideas's etc. can be posted into there as well.

**Comment by sercankd** [comment]
Can't ask questions in Reddit community as subreddit is restricted to approved users..

**Comment by ma-karai** [comment]
same: please open up the reddit community, i feel there are a lot of people using NPM and i really like to see some working examples there too.

**Comment by netstx** [comment]
The subreddit looks pretty dead.

**Comment by ma-karai** [comment]
its because its locked, and there should not be a reason why.

**Comment by ejtc84** [comment]
Hello everyone, may is a dumb question but, NPM works on main domain "mydomain.com" for example? i tried to configure but dont work for me

**Comment by chaptergy** [comment]
For those wondering about the Reddit community, it is now back! See [this post](https://www.reddit.com/r/nginxproxymanager/comments/nr6tpl/nginxproxymanager_subreddit_is_back/) for more information

**Comment by jayjupdhig** [comment]
Support for nginx proxy manager??

-> LOL... :-)
