### ISSUE TITLE
[v2] Internal error when uploading custom certificates

### ISSUE THREAD

**Issue by NochEinKamel** [jc21/nginx-proxy-manager#9]
Hi,

great work so far!

I was trying to add a custom certificate and only got a popup showing "internal error".
Also got the following log entry:
[Express ] › ⚠  warning                      dir is not defined

Looks like the dir variable is not available in the then function here:
https://github.com/jc21/nginx-proxy-manager/blob/a4b918e648d6b992ca1934196253a3643aeb175d/src/backend/internal/certificate.js#L444

Thanks

**Comment by jc21** [comment]
Yep looks like you're correct. I've fixed the scope, pull the docker image again to get the fix.
