### ISSUE TITLE
[Feature Request] Export Settings

### ISSUE THREAD

**Issue by danmed** [jc21/nginx-proxy-manager#90]
I have this up and running finally using the mariadb as part of the stack, but i'd like to move it to my external MySQL server.. Unfortunately that means (as far as i can tell) i'm going to have to add all my hosts again... (i think).

Is there any way to export the current config, rebuild the docker, and import it again once it's pointing at MySQL instead?

**Comment by jc21** [comment]
Sure I can see how an export feature might be useful. For now though, you only need to keep your config file, `data` folder, `letsencrypt` folder and dump your sql.

You can export your database with a script like this:

```bash
MYSQL_USER=npm
MYSQL_PASS=npm
MYSQL_DB=npm
docker exec -ti nginx-proxy-manager_db_1 mysqldump -u $MYSQL_USER --password=$MYSQL_PASS $MYSQL_DB > dump.sql
```

For the rest of the data I guess it depends on how you're running the docker environment.

**Comment by MartinKuhl** [comment]
when I try to import the exported data on a new created docker image, all information are back. I can see all the configuration within the UI. But it isn't working. I have to edit each proxy configuration and save it (without modification) and now it works. Is there any script for reinitializing the confoguration?

**Comment by danmed** [comment]
Did you reimport the database?

**Comment by MartinKuhl** [comment]
yes I did.

**Comment by MartinKuhl** [comment]
The missing key was the folder /data/nginx. After saving and restoring the folder /data/nginx together with a database dump and restore now everting is back and ready to work.

**Comment by johncadengo** [comment]
Just for anyone else attempting this, I had a little trouble running the command as is:

```
docker exec -ti nginx-proxy-manager_db_1 mysqldump -u $MYSQL_USER --password=$MYSQL_PASS $MYSQL_DB > dump.sql
```

Because it would default to `localhost` for the hostname. I would get this error:

```
$ cat dump.sql 
mysqldump: Got error: 1045: "Access denied for user 'npm'@'localhost' (using password: YES)" when trying to connect
```

Not sure why, but I had to supply the hostname as `127.0.0.1` to get mine to work:

```
docker exec -ti nginx-proxy-manager_db_1 mysqldump -u $MYSQL_USER --password=$MYSQL_PASS -h 127.0.0.1 $MYSQL_DB > dump.sql
```

**Comment by rtthane** [comment]
> The missing key was the folder /data/nginx. After saving and restoring the folder /data/nginx together with a database dump and restore now everting is back and ready to work.

Can i ask what restore command you used please?

**Comment by MartinKuhl** [comment]
Hi @rtthane,
first I save the following folders:
docker exec -it nginx tar -zcvf /transfer/backup/nginx/SSL_backup.tar.gz /etc/letsencrypt/
docker exec -it nginx tar -zcvf /transfer/backup/nginx/nginx_conf.tar.gz /data/nginx

and the DB:
docker exec -it db bash -c "mysqldump -uadmin -p123456 nginx > /transfer/backup/nginx/nginx-backup.sql"

For the restore I use the following commands:

docker exec -it db bash -c "mysqldump -uadmin -p123456 nginx > /transfer/backup/nginx/nginx-backup.sql"
docker-compose restart nginx
docker exec -it nginx nginx -t
docker exec -it nginx nginx -s reload

**Comment by rtthane** [comment]
> Hi @rtthane,
> first I save the following folders:
> docker exec -it nginx tar -zcvf /transfer/backup/nginx/SSL_backup.tar.gz /etc/letsencrypt/
> docker exec -it nginx tar -zcvf /transfer/backup/nginx/nginx_conf.tar.gz /data/nginx
> 
> and the DB:
> docker exec -it db bash -c "mysqldump -uadmin -p123456 nginx > /transfer/backup/nginx/nginx-backup.sql"
> 
> For the restore I use the following commands:
> 
> docker exec -it db bash -c "mysqldump -uadmin -p123456 nginx > /transfer/backup/nginx/nginx-backup.sql"
> docker-compose restart nginx
> docker exec -it nginx nginx -t
> docker exec -it nginx nginx -s reload

@MartinKuhl  really useful info, thanks for taking the time to post it.

**Comment by chaptergy** [comment]
Closing this in favor of https://github.com/jc21/nginx-proxy-manager/issues/168
