### ISSUE TITLE
[SOLVED] Another let's encrypt Cloudflare DNS challenge with TOKEN

### ISSUE THREAD

**Issue by j2l** [jc21/nginx-proxy-manager#906]
Great project! Thank you!

**Checklist**
- [x] Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? 
- [x] Are you sure you're not using someone else's docker image?
- [x] If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
Issuing a temporary token from Cloudflare didn't make letsencrypt happy enough:

- What version of Nginx Proxy Manager is reported on the login page?
- 2.8.0

**Screenshots**
![image](https://user-images.githubusercontent.com/65325/108492924-0214fe80-72a6-11eb-9f23-208fc8208bbb.png)

![image](https://i.imgur.com/CvnAxn2.png)

![image](https://user-images.githubusercontent.com/65325/108493776-02fa6000-72a7-11eb-928c-3cb33809a4f2.png)
a read access is enough right?

**Operating System**
- Rpi (Rock Pine64)

**Additional context**
I'm sure I didn't use a KEY :smile: 

Thanks!

EDIT, SOLUTION : a read access is NOT enough right, needs EDIT access to write a DNS TXT entry.
It's non sense since letsencrypt has enough with read access though API to prove it's your domain.
BTW, don't forget to delete the token and check DNS after lets encrypt did its trick.

**Comment by Dudleydogg** [comment]
Any reason why Nginx wont remember the token when selection of a new cert I have to go reset my token if I did not store it in my notes. seems like it should remember that token for each time it updates a certificate?
