### ISSUE TITLE
AWS Application Balancer with Nextcloud

### ISSUE THREAD

**Issue by techc0de** [jc21/nginx-proxy-manager#910]
Hi all,

I'm currently using NPM for my services on AWS with ALB.
Nextcloud and other web services are working fine.
I also configured the Nextcloud config.php with 'overwriteprotocol' => 'https' .
However, I have to enter like this: https://nextcloud.mydomain.com to get the the Nextcloud site.
If I enter just: nextcloud.mydomain.com, it would not redirect to Nextcloud.
It does not auto redirect from HTTP to HTTPS.
I'm using only HTTP as my listener for the ALB.

environment setup: 
Docker:
NPM: 80:80; 443:443
http://172.17.0.1:81

Nextcloud (Linuxserver.io): 4443:443; 8080:80
  https://172.17.0.1:4443

Am I missing something ?

**Comment by p-fruck** [comment]
Hi,
I don't know about your proxy configuration, but when you configure a proxy redirection host, you need to select the option 'force ssl redirection'. I case you redirected to your nextcloud using a custom location, there's currently a bug that can be worked around as described [here](https://github.com/jc21/nginx-proxy-manager/issues/1028#issuecomment-822564256)

**Comment by techc0de** [comment]
I found the issue.
I was using the Load Balancer and one of the Security Group didn't allow direct access to port 80.
So by allowed it direct access both to ports 80, and 443, it worked.
