### ISSUE TITLE
Problems with Nextcloud Push

### ISSUE THREAD

**Issue by MGoeppl** [jc21/nginx-proxy-manager#913]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? Yes, updated every 6hrs with watchtower.
- Are you sure you're not using someone else's docker image? Yep. 
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? Not a problem w/ LE. 

**Describe the bug**
- A clear and concise description of what the bug is.
The X-Forwarded-For header is not forwarded. Nextcloud thinks I am connecting from the outside IP, not the Proxy IP. 

- What version of Nginx Proxy Manager is reported on the login page?
2.8.0

**To Reproduce**
Adding the following to the "Advanced" config does not forward the IP of the Proxy itself:
```
location /push/ {
    proxy_pass http://<Nextcloud-IP>:7867/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
This also happens when I add the following to the "Locations" tab, just without the last one and the first two lines. 

The Proxy is using Host Networking, Nextcloud is running on another machine. 

Running
```
./occ notify_push:setup https://cloud.<MY-DOMAIN>.<MY-TLD>/push
```
returns the following:
```
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
🗴 push server is not a trusted proxy, please add '<PUBLIC-IP>' to the list of trusted proxies or configure any existing reverse proxy to forward the 'x-forwarded-for' send by the push server.
```

**Expected behavior**
Forward the X-Forwarded-For to Nextcloud

**Screenshots**

**Operating System**
RPI

**Additional context**
My Nextcloud config.php:
```
...
  'trusted_proxies' => 
  array (
    0 => '<NPM-IP>',
  ),
);

```

**Comment by debmus** [comment]
Hello, 
have you tried to add the line below in nextcloud's **config.php** file ?

```sh
'overwriteprotocol' => 'https' 
```

**Comment by MGoeppl** [comment]
Yes, that's my default config whenever I deploy one. 

I found another solution, which is described after updating the notify_push app and executing the command again. It skips the nginx proxy entirely.

**Comment by MGoeppl** [comment]
Yes, that's my default config whenever I deploy one.

I found another solution, which is described after updating the notify_push app and executing the command again. It skips the nginx proxy entirely.
