### ISSUE TITLE
Unknown connections on 443

### ISSUE THREAD

**Issue by legendariusx** [jc21/nginx-proxy-manager#923]
Hello, I'm new to using NPM and I've got a questing about my use case.
I've set up the proxy manager and forwarded ports 80 and 443.
When I checked today there were two IPs connected to port 443 idling. Might this be the result of someone port scanning? Is there any chance uf misuse by these connections?

**Comment by jerry110** [comment]
Same here

**Comment by legendariusx** [comment]
I tracked the connections with tcptrack and I can see that their state is SYN_SENT. I did some research and found [this](https://en.wikipedia.org/wiki/SYN_flood) on Wikipedia about SYN flood. I do not get many of these connections and most of them close about 20-30 seconds after sending the SYN-Packet. So I assume these connections are malicious although they do not seem to actively do anything. Can anyone confirm?

**Comment by legendariusx** [comment]
I couldn't find additional information but since this isn't a problem with NPM, I'll close the issue.
