### ISSUE TITLE
404 links on docker hub

### ISSUE THREAD

**Issue by Zerwin** [jc21/nginx-proxy-manager#930]
**Are you in the right place?**
- Yes

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? 
No, this is not about the docker image
- Are you sure you're not using someone else's docker image? 
Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
I don't have problem with Let's Encrypt

**Describe the bug**
- On the docker hub https://hub.docker.com/r/jc21/nginx-proxy-manager under the getting started section, the links for the installation instructions and the doc/example/ folder point to the wrong location. They point to /nginx-proxy-manager/blob/master/**doc**/ which doesn't exist ( I guess anymore). The links therefore just land on a 404 page.

**To Reproduce**
1. Go to https://hub.docker.com/r/jc21/nginx-proxy-manager
2. Click on the links in the Getting Started section
3. Land on 404 page

**Expected behavior**
I land on the installation instructions or the examples

**Comment by jc21** [comment]
The docker listing doesn't get automatically updated with new deploys and is probably out of date anyway. I've changed it to point to the official documentation and github.
