### ISSUE TITLE
No Crontask to run auto-renewal in Docker-Container?!

### ISSUE THREAD

**Issue by typoworx-de** [jc21/nginx-proxy-manager#932]
The docker-container does not seem to provide any kind of crontask to ensure auto-renewal for certbot is running in regular schedule?!

Why isn't there anything in /etc/periodic/daily? Also can't find anything in Dockerfile pointing to ensure auto-renewal is running automatically?

And even Healthcheck is not used to schedule to run certbot renewal at least every 1-3 days (Attention: do not run too often to avoid "too much requests" API denial).

**Comment by typoworx-de** [comment]
Trying to fix it by creating separate docker bind-mount on /etc/periodic
and this script:

/etc/periodic/daily/certbot.sh 
```
#!/bin/sh
echo "Running Certbot Renewal";
echo "---------------------------";
echo "Job started: $(date)";
/usr/bin/certbot renew --non-interactive --config "/etc/letsencrypt.ini";
echo "Job finished: $(date)";
```

**Comment by jc21** [comment]
The nodejs process will renew certs on docker start and [every 1 hour thereafter](https://github.com/jc21/nginx-proxy-manager/blob/b7b808d98d787b25548265055d9f8621d31b580e/backend/internal/certificate.js#L29). There does not need to be another process running in the container just for that.
