### ISSUE TITLE
add certbot plugin for req.ru DNS challenge

### ISSUE THREAD

**Issue by centralhardware** [jc21/nginx-proxy-manager#938]
**Is your feature request related to a problem? Please describe.**

my domain register by req.ru and nginx proxy manager don't have provider for them.

**Describe the solution you'd like**

I found a certbot plugin on github that allows to use DNS authenticator with reg.ru
https://github.com/free2er/certbot-regru

**Describe alternatives you've considered**

maybe there are solutions that will allow dns authorization to go through without tying to a specific dns provider, the certbot cli itself, in my opinion, can do this

**Comment by chaptergy** [comment]
I have created a PR which includes this change. You can already test to see if it works before the next release if you use the docker image `jc21/nginx-proxy-manager:github-pr-1083` (in your docker compose) instead of `jc21/nginx-proxy-manager:latest`
