### ISSUE TITLE
How to pass to VPN Server?

### ISSUE THREAD

**Issue by CyberSecGuy** [jc21/nginx-proxy-manager#94]
Hi, I'm running a [Pulse Secure VPN](https://www.pulsesecure.net/) on my network, and was wondering what I need to do to allow access to my VPN using this. Any info would be great, thanks!

**Comment by jc21** [comment]
So you're running a VPN on your network and:
1. you want to allow VPN requests to pass through this software using port fowarding? or
2. you want to access NPM proxied sites after connecting to your VPN, and they are not accessible to the public internet?

**Comment by CyberSecGuy** [comment]
The former. Right now I port-forward 80/443 to vpn.ip.address.here which meams I cant access nextcloud, jenkins, gitlab etc, because they all want 80 as well.

So I was hoping with this software I could just do vpn.domain.com and ci.domain.com etc.

**Comment by jc21** [comment]
I would think your VPN wouldn't run on HTTP/S ports unless it's for the Web Management interface.  

But anyway, yes you can foward 80/443 to this product and create a Proxy Host for `vpn.yourdomain.com` and access the VPN that way, same for your other services.

**Comment by jc21** [comment]
However if you are using 80/443 for your VPN tunnelling connections, then you're a bit screwed and should change your VPN ports to something else.

**Comment by CyberSecGuy** [comment]
I'm sorry, I'm stupid as shit... when I was creating the proxy hosts for the VPN, I set the port to be 80, even though I selected HTTPS. Setting the port to 443 instead, resolved the issue.

**Resolved!**
