### ISSUE TITLE
Cannot get the original IP address of visitor.

### ISSUE THREAD

**Issue by Rhandyx** [jc21/nginx-proxy-manager#952]
First of all
I´m beginner in docker and in nginx-proxy.
I install it because I need run 2 vm´s with different web sites under same ip.

For DNS I use cloudflare:

I´m using xenserver (xcp-ng) 3 Vm´s
1st Vm is running docker and nginx proxy manager
other Vm´s runs Ubuntu server and apache.
My problem is I can´t get the original Ip address from visitors on apache server logs. I need it too work with fail2ban.
I only see cloudflare ips. Not original Ips.

Best Regards

**Comment by Rhandyx** [comment]
I fix it!
Sorry.
Fisrt I have to enable apache remoteip module.

and add this lines
`RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 192.168.1.X`

After I have to create on custom file
`vi /data/nginx/custom/server_proxy.conf`
and add this
`real_ip_header CF-Connecting-IP;`

**Comment by NajibNour** [comment]
@Rhandyx Hey could you help me out with this? I'm having trouble setting this up.

**Comment by ex3me4me** [comment]
> 
> 
> @Rhandyx Hey could you help me out with this? I'm having trouble setting this up.

The easy way > Open your NPM> go to hosts > proxy hosts > choose desired host. click on 3dots menu and choose edit. Go to Advanced and paste `real_ip_header CF-Connecting-IP;` into Custom Nginx Configarition > save
Check if it's working:)

**Comment by NajibNour** [comment]
Hey yes I ended up getting it, npm I figured out that npm automatically pulls Cloudflare proxy ips and loads them in. All that’s needed is the real ip header In the advanced tab. Also there seems to be a bug where it only accepts the acl config after you do the following. You must have the host enabled, Create the ACL, Then set the ACL then Unset then set The ACL. That was the only way I could get it to work.

thanks for the help! Hopefully my comment helps others!

> > @Rhandyx Hey could you help me out with this? I'm having trouble setting this up.
> 
> The easy way > Open your NPM> go to hosts > proxy hosts > choose desired host. click on 3dots menu and choose edit. Go to Advanced and paste `real_ip_header CF-Connecting-IP;` into Custom Nginx Configarition > save
> Check if it's working:)

**Comment by NajibNour** [comment]
See issue https://github.com/jc21/nginx-proxy-manager/issues/919
For more help
