### ISSUE TITLE
SSL Cert request not working

### ISSUE THREAD

**Issue by antonstech** [jc21/nginx-proxy-manager#954]
Hello, the Certificate Create Function is not working on a completely new installed docker
```
3/16/2021] [10:15:51 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #1: retorte.antonstech.de
[3/16/2021] [10:15:57 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[3/16/2021] [10:15:58 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-1" --agree-tos --email "kontakt@antonstech.de" --preferred-challenges "dns,http" --domains "retorte.antonstech.de" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for retorte.antonstech.de
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain retorte.antonstech.de
http-01 challenge for retorte.antonstech.de
Cleaning up challenges
Some challenges have failed.
```
These are the Logs

**Comment by antonstech** [comment]
Was Not a Prob with Nginx Proxy Manager

**Comment by kjlhgfds** [comment]
Hi there !
I have the same issue. What did you do to fix it ?
Thanks !

**Comment by antonstech** [comment]
Hey m8, what is your "setup"?
My Issues is that i enabled the Cloudflare Proxy so when it did the DNS Check it did saw the IP of the Cloudflare Servers not mine.
When this is your Issue just quickly disable it, get your SSL Cert and enable it again.
If not just tell me your issue :)
Greetings, Anton

**Comment by kjlhgfds** [comment]
Well, I did a fresh install of Docker and all container using tutos from this guy (https://www.youtube.com/c/TheDigitalLifeTech/videos), and now it work very well.
Thanks anyway !

**Comment by antonstech** [comment]
Thats nice to hear :)
