### ISSUE TITLE
Proxy to other docker containers

### ISSUE THREAD

**Issue by jrichet** [jc21/nginx-proxy-manager#96]
How do I connect to other docker containers? 

I've tried connecting to localhost/127.0.0.1 on an alternate port exposed in those containers, but no joy. Is there a trick I'm not aware of?

I keep getting a 502.

It would be super helpful if the documentation included some troubleshooting tips

**Comment by jc21** [comment]
I assume you're running your NPM docker image in `bridge` mode, which is the default. In this mode `127.0.0.1` only connects back to the NPM docker image network stack, not the host machine.

You have 3 options:

1. Run NPM in [`host` mode](https://docs.docker.com/network/host/).
2. Add your other services to the bridge network stack: add them as services in the `docker-compose.yml` file and connect to them using the service name as the hostname.
3. Connect to your other services by the machine's host IP address on the local network, ie: 192.168.1.50.
