### ISSUE TITLE
How to run a personal website at npm?

### ISSUE THREAD

**Issue by talesam** [jc21/nginx-proxy-manager#962]
I researched and found nothing about it.
If I want to run a personal website and use npm as a web server or want to set up a package repository, how do I do this?

I'm trying to create an archlinux repository but I don't know how to set this up in npm ...
```
server {
    server_name repo.sun.hexor.ru;
    listen [::]:443 ssl;
    listen 443 ssl;
    include security.conf;
    include letsencrypt.conf;
    root /srv/arch-repo;
    location / {
        autoindex on;
        try_files $uri $uri/ =404;
    }
    access_log /var/log/nginx/logs/repo.sun.hexor.ru.access.log custom;
    error_log /var/log/nginx/logs/repo.sun.hexor.ru.error.log;
}
```

**Comment by DarioViva42** [comment]
npm is not a web server. its a reverse proxy.
you need to set up a webserver first, and then configure npm to proxy webrequests to your webserver.
thats at least how I have understood this program …

**Comment by talesam** [comment]
> npm is not a web server. its a reverse proxy.
> you need to set up a webserver first, and then configure npm to proxy webrequests to your webserver.
> thats at least how I have understood this program …

Thanks!!

**Comment by chaptergy** [comment]
There is a feature request for this though: https://github.com/jc21/nginx-proxy-manager/issues/58
