### ISSUE TITLE
Add ssl certificate using DNS-01 via duckdns

### ISSUE THREAD

**Issue by pbranly** [jc21/nginx-proxy-manager#969]
Hi
Could you add the possibility to get ssl certificate using DNS-01 via duckdns  as with this docker 
https://hub.docker.com/r/wuodan/docker-dehydrated-duckdns-cron
Thanks
Philippe

**Comment by steled** [comment]
Hi,

I also would appreciate this solution.

Thanks and best regards

**Comment by pbranly** [comment]
Hi
Very good news
Is it operational with the « latest » suffix ?
Philippe

Envoyé depuis mon IPhone SE 2020

**Comment by hepelayo** [comment]
Hi @pbranly ,
If I'm not wrong, a new version should be released to get it with the _"latest"_ tag.
At this moment, you can test it with the _"github-develop"_ tag.
