### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by jrichet** [jc21/nginx-proxy-manager#97]
trying to point at other dockers' exposed port only gives me

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by jc21** [comment]
Which exposed port? Is that port definitely serving HTTPS?

Usually you'd only see this error when you are using HTTPS with a url that points to Nginx Proxy Manager and the host in that url is not set up as a HTTPS enabled host in Nginx Proxy Manager.

Make sure your host is created and has SSL. If you still have problems, make sure you can hit your other docker service directly in a browser.

**Comment by jrichet** [comment]
you are correct. this was a misconfig on my part.
