### ISSUE TITLE
Add ssl certificate using DNS-01 via ClouDNS

### ISSUE THREAD

**Issue by codeagencybe** [jc21/nginx-proxy-manager#976]
Can ClouDNS be added to the list of compatible DNS providers? 

https://www.cloudns.net/wiki/article/186/

**Comment by ghost-of-cerberus** [comment]
Another vote for ClouDNS. Looks like Inventage created a module for this:

https://github.com/inventage/certbot-dns-cloudns

Even a Python Package was recently created and put up on PyPi:

https://pypi.org/project/certbot-dns-cloudns/

Would definitely love to see this.

**Comment by hwcltjn** [comment]
+1 for this too!

**Comment by hwcltjn** [comment]
I've edited `global/certbot-dns-plugins.js` on my docker host to include ClouDNS, but I'm unable to get it to appear in NPM. I'm assuming I need to rebuild something somewhere? I'd like to test it before creating a PR :)

Snippet:

```
	//####################################################//
	cloudns: {
		display_name:    'ClouDNS',
		package_name:    'certbot-dns-cloudns',
		package_version: '0.4.0',
		dependencies:    '',
		credentials:     `# Target user ID (see https://www.cloudns.net/api-settings/)
dns_cloudns_auth_id=1234
# Alternatively, one of the following two options can be set:
# dns_cloudns_sub_auth_id=1234
# dns_cloudns_sub_auth_user=foobar

# API password
dns_cloudns_auth_password=password1`,
		full_plugin_name: 'certbot-dns-cloudns:dns-cloudns',
	},
```

**Comment by ghost-of-cerberus** [comment]
@hwcltjn  - Did you install the pip package on your instance prior to updating the "global\certbot-dns-plugins.js" file? Also, I believe the `full_plugin_name` value should just be `'dns-cloudns'`. The argument examples provided on the plugin page do not indicate `certbot-dns-cloudns:dns-cloudns` as any argument and referencing other configs in the "global\certbot-dns-plugins.js" would confirm that.

Try installing the pip in your instance and then updating the "global\certbot-dns-plugins.js" file with the following and see if that changes anything:
 
```
	//####################################################//
	cloudns: {
		display_name:    'ClouDNS',
		package_name:    'certbot-dns-cloudns',
		package_version: '0.4.0',
		dependencies:    '',
		credentials:     `# Target user ID (see https://www.cloudns.net/api-settings/)
dns_cloudns_auth_id=1234
# Alternatively, one of the following two options can be set:
# dns_cloudns_sub_auth_id=1234
# dns_cloudns_sub_auth_user=foobar

# API password
dns_cloudns_auth_password=password1`,
		full_plugin_name: 'dns-cloudns',
	},
```

I'll give it a go this weekend when I have some time to dig in further.

**Comment by hwcltjn** [comment]
@ghost-of-cerberus thanks for the input. I had realised my `full-plugin` was wrong and actually had it match yours.
Installed the pip in the container, but still cannot get the front-end to reflect the new option. 

Removing or renaming `certbot-dns-plugins.js` has no effect on NPM, so I'm assuming I'm missing a step  😅

**Comment by ghost-of-cerberus** [comment]
@hwcltjn I gave it a few shots as well and am encountering the same. I feel that we're really close. Thanks for the heads up on the removal/renaming of `certbot-dns-plugins.js` not affecting NPM. Did you happen to test renaming/removing `certbort-dns-plugins.js` and restarting services or the whole container?
I'm going to keep digging but we may need to look at the actual container build process if we don't find anything.

**Comment by hwcltjn** [comment]
@ghost-of-cerberus glad to hear you gave it a go!

> Did you happen to test renaming/removing `certbort-dns-plugins.js` and restarting services or the whole container?

Yes, I did, but it didn't change anything.

> I'm going to keep digging but we may need to look at the actual container build process if we don't find anything.

If we really get stuck, maybe we can @ some other people that have successfully integrated other DNS methods 😅

**Comment by codeagencybe** [comment]
Been trying the same without success :(

I wonder if there is some kind of dependency in the core app that makes the providers visible? 
If the original creator could give some feedback and integrate this based on our tries, that would be the easiest way I think to get a clean working solution

**Comment by ghost-of-cerberus** [comment]
@codeagencybe and @hwcltjn at least we're all not crazy. I was thinking I was missing something obvious but it does appear that there is something in the build process that updates the available provider list. Hopefully, this will be seen and can be implemented in the build, if we don't figure it out first.

**Comment by hwcltjn** [comment]
@lebrou34 and @hepelayo apologies for tagging you directly on something you're not involved in - but I noticed from other closed PR's and issues that you were both able to integrate custom certbot-dns providers. 

Could you possibly help steer us in the right direction? 
Thank you!

**Comment by ghost-of-cerberus** [comment]
@chaptergy I saw that you have been involved with other components and PRs for NPM and offered to look at the Porkbun certbot addition. I was curious if you could help us on this one for ClouDNS. We think we're close but not quite sure what we're missing. Any assistance would be greatly appreciated. Thank you!

**Comment by chaptergy** [comment]
> ```
> cloudns: {
> 	display_name:    'ClouDNS',
> 	package_name:    'certbot-dns-cloudns',
> 	package_version: '0.4.0',
> 	dependencies:    '',
> 	credentials:     `# Target user ID (see https://www.cloudns.net/api-settings/)
> dns_cloudns_auth_id=1234
> # Alternatively, one of the following two options can be set:
> # dns_cloudns_sub_auth_id=1234
> # dns_cloudns_sub_auth_user=foobar 
> 
> # API password
> dns_cloudns_auth_password=password1`,
> 	full_plugin_name: 'dns-cloudns',
> },
> ```

You're doing it exactly right. When I paste your code snippet into `certbot-dns-plugins.js` it shows up as expected as a DNS challenge provider. Does not not show up for you?  

![image](https://user-images.githubusercontent.com/26956711/117571710-3fc43f00-b0bf-11eb-8d80-2a7dbb4c3f8b.png)

Once the provider is used for an SSL certificate it will automatically install the DNS plugin via `pip`.

**Comment by chaptergy** [comment]
I am now also adding the porkbun dns provider, should I just include your code snippets in this PR? Or do you want to create your own PR?

**Comment by hwcltjn** [comment]
@chaptergy thanks for getting involved!

I cannot get it to appear at all! What version are you running? I'm still on v2.8.1

Did you just add it to the JS file on the docker host and click refresh?

**Comment by chaptergy** [comment]
Ah, I was working on a development container, not on a production container. Unfortunately the frontend cant be changed to include this new entry in a normal docker container. The frontend is compiled / packaged with webpack, and only this packaged data is included in the docker container. To reflect the changes in the `certbot-dns-plugins.js` file, the frontend would have to be rebuilt, which is not possible with just the data inside the docker container.

You can just create a PR with these changes, and a bot will then build a docker container based on these changes, which you can then use in your docker-compose file. Otherwise you can run a dev container locally by

-  cloning the repo
- installing `docker`
- installing `docker-compose` 
- adding the changes
- running `docker-compose -f docker/docker-compose.dev.yml up` in the cloned folder

**Comment by ghost-of-cerberus** [comment]
> I am now also adding the porkbun dns provider, should I just include your code snippets in this PR? Or do you want to create your own PR?

If you could combine into the Porkbun PR that would be great! Thanks a million, @chaptergy!

Also, thanks for the info on the dev container vs production container. I assumed this was it but wasn't quite sure! Again, thanks for all of your help!

**Comment by codeagencybe** [comment]
@chaptergy 

Also thanks from my end. 
I had a hunch that it would be something involved with a build somewhere. Thanks for confirming this also. 

Lets hope this update gets through fast so we can all enjoy ClouDNS with proxy manager soon :)

**Comment by chaptergy** [comment]
The PR is done. You can already test to see if it works before the next release if you use the docker image `jc21/nginx-proxy-manager:github-pr-1083` (in your docker compose) instead of `jc21/nginx-proxy-manager:latest`

**Comment by hwcltjn** [comment]
@chaptergy thank you!
