### ISSUE TITLE
[question] related to planka

### ISSUE THREAD

**Issue by ikwtif** [jc21/nginx-proxy-manager#984]
Not really a bug, but since I can't get into the reddit community thought I'd ask here.

I'm trying to run planka but there are some issues with loading the webpage after logging in. I'm getting this error

```
websocket.js:124 WebSocket connection to 'wss://planka.mydomain.be/socket.io/?__sails_io_sdk_version=1.2.1&__sails_io_sdk_platform=node&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: 
```
I found the issue referenced on planka github. Is it possible to input this somewhere in the manager? I tried putting it in the advanced tab but that did not work 
how should I put something like this for the config in advanced? 

[planka issue link](https://github.com/plankanban/planka/issues/21)
```
server {
    server_name planka.url;

    listen 443 ssl;                                                         
    listen [::]:443 ssl;

    location / {
        proxy_pass      http://127.0.0.1:1337;
        include         proxy_params;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by ikwtif** [comment]
Apparently I'm blind and there is a toggle for websocket support. Anyway, thanks for this manager! Makes it super easy to set everything up.

**Comment by Drstrubbel** [comment]
How did you configure it?
I cannot login, even with activated WebSocket

**Comment by ghost007** [comment]
same here. not working with Websocket enabled.
