### ISSUE TITLE
No Relevant User Found

### ISSUE THREAD

**Issue by RyanOver9000** [jc21/nginx-proxy-manager#990]
**Are you in the right place?**
Yes, My issue is with the initial setup of NPM

**Describe the bug**
I have a new install of NPM. After logging in as admin@example.com / changeme, I set my new login information.  If I logout at any point I am unable to log back in with my credentials I have just created. 

**To Reproduce**
1. Install fresh NPM
2. Login with admin@example.com / changeme
3. Change login information
4. Logout
5. Try to log back in with newly changed information
6. Fail

**Expected behavior**
Log back in to system

**Operating System**
UnRaid 6.9.1

**Comment by RyanOver9000** [comment]
Wrong place

**Comment by BananaHead-ui** [comment]
Hy, i have the same issue. What did you mean by wrong  place?
