### ISSUE TITLE
remove call to https://fonts.googleapis.com/

### ISSUE THREAD

**Issue by krswin** [jc21/nginx-proxy-manager#998]
**Is your feature request related to a problem? Please describe.**
* For privacy reasons its important to get css,fonts from code itself
* nginx-proxy-manager gets CSS from internet API to get CSS
* https://fonts.googleapis.com/css

**Describe the solution you'd like**
* Please include CSS in the code so no need to connect to internet for requests. 

Thank you for your help.

**Comment by chaptergy** [comment]
Closed via https://github.com/jc21/nginx-proxy-manager/pull/1096
