### ISSUE TITLE
Unable to renew cert because of outdated certbot?

### ISSUE THREAD

**Issue by ikomhoog** [jc21/nginx-proxy-manager#999]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? yes
- Are you sure you're not using someone else's docker image? yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? yes

**Describe the bug**
- A clear and concise description of what the bug is.
My certs expired and npm cannot renew them because of an error, there is a timeout when trying it manually.
My certs are cloudflare DNS challenges for "*.mydomain.com" and "mydomain.com" in 1 cert
```
[4/4/2021] [9:36:57 PM] [SSL ] › ✖ error Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation

Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA. You may need to use an authenticator plugin that can do challenges over DNS.
Attempting to renew cert (npm-1) from /etc/letsencrypt/renewal/npm-1.conf produced an unexpected error: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA. You may need to use an authenticator plugin that can do challenges over DNS.. Skipping.

All renewal attempts failed. The following certs could not be renewed:

/etc/letsencrypt/live/npm-1/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)

at ChildProcess.exithandler (child_process.js:308:12)
at ChildProcess.emit (events.js:314:20)
at maybeClose (internal/child_process.js:1051:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

- What version of Nginx Proxy Manager is reported on the login page? 2.8.1

**To Reproduce**
1. have an expired cloudflare dns cert
2. try to renew them

**Expected behavior**
I expected the certs to be renewed

**Operating System**
- Please specify if using a Rpi, Mac, orchestration tool or any other setups that might affect the reproduction of this error.
UnRaid Docker

**Additional context**
UnRaid 6.9.1

**Comment by akanealw** [comment]
Did you ever fix this? I'm having the same issue.

**Comment by jc21** [comment]
@akanealw what version of Nginx Proxy Manager is shown in the UI?

**Comment by akanealw** [comment]
2.9.0. I'm running jc21/nginx-proxy-manager:latest and I repulled it just in case there was a new version but no change.

**Comment by akanealw** [comment]
I must have left this comment on the wrong issue. I'm trying to generate a certificate for a new domain. My error is different but still something about an outdated certbot version.

```Error: Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-11" --agree-tos --email "akanealw@gmail.com" --domains "mydomain.com" --authenticator dns-cloudflare --dns-cloudflare-credentials "/etc/letsencrypt/credentials/credentials-11"
An unexpected error occurred:
pkg_resources.VersionConflict: (certbot 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('certbot>=1.1.0'))
Please see the logfile '/tmp/tmpe23xh9ls' for more details.

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**Comment by jc21** [comment]
right so the previous certbot version in 2.8.1 (alpine) is 1.4.0, the one in 2.9.0 (debian) is 0.31.0. I'll look at pulling from a more up to date source.

**Comment by akanealw** [comment]
Ok, cool. I'm just a bit confused that I'm on 2.9.0 but still somehow 2.8.1? Should I pull jc21/nginx-proxy-manager:2.9.0 instead?

**Comment by jc21** [comment]
>but still somehow 2.8.1 
? how do you know you're on an old version, if the UI reports the newest version?

**Comment by akanealw** [comment]
oh nvm, I was misreading the version mismatch.

**Comment by ikomhoog** [comment]
Sorry for the late reply, I didn't fix this, I closed it because it was a duplicate and only discovered it after I made this one.
The other issue thread is: #967
Should have commented that when closing.
